flutter/cocoon

- auto_submit/lib/request_handling/pubsub.dart
- auto_submit/lib/requests/check_pull_request.dart
- auto_submit/lib/requests/github_webhook.dart
- auto_submit/test/requests/check_pull_request_test.dart
- auto_submit/test/requests/github_webhook_test.dart
- auto_submit/test/requests/github_webhook_test_data.dart
- auto_submit/test/src/request_handling/fake_pubsub.dart
This PR intends to set up the pubsub pull logic, solving the issue: https://github.com/flutter/flutter/issues/98705.
Therefore, we can pull the message from the subscription to get the pull request stored in pub sub to process here. After we got the message, we will acknowledge the pub sub.
Make the pull based subscription running on a cron to pull the message from the pub sub every minute. https://github.com/flutter/flutter/issues/100399
> [autosubmit] Add pubsub pull logic

- app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
- app_dart/lib/src/request_handlers/check_for_waiting_pull_requests_queries.dart
- app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
Graphql queries were timing out because the query by labels is
extremelly expensive. Changing the query to filter by open PRs and then
filtering by the label is more efficient and reduces the query exection
time to 1/3. …
> Update graphql query to remove a redundant query to labels and prevent the query from timing out.

- Dockerfile
- app_dart/Dockerfile
- auto_submit/Dockerfile
- licenses/check_licenses.dart
Some dockerfiles do not include the license header but the licenses
checks have been happy. This change will make the licenses header check
fail for docker files missing the header.
Bug: https://github.com/flutter/flutter/issues/100181 …
> Update licenses script to include Dockerfiles.

- device_doctor/lib/src/ios_device.dart
- device_doctor/lib/src/utils.dart
- device_doctor/test/src/fake_ios_device.dart
- device_doctor/test/src/ios_device_test.dart
This is a follow up of https://github.com/flutter/cocoon/pull/1660, fixing the case of `idevice_id`.
https://github.com/flutter/flutter/issues/99490#issuecomment-1076889601
> [device doctor] Fix `idevice_id` binary path for M1 bots

- app_dart/bin/generate_jspb.dart
The extra dependencies make it fail in environments where you can't import `dart:mirrors`
> [app_dart] Remove extra dependencies in generate_jspb

- app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
- app_dart/lib/src/request_handlers/refresh_cirrus_status.dart
- app_dart/lib/src/request_handlers/refresh_cirrus_status_queries.dart
- app_dart/lib/src/service/config.dart
- app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
Recently the "waiting for tree to go green" bot has been failing to land
the PR even when they meet all the requisites. This is because empty
Cirrus build results generate silent errors that completely stop the
iteration for a given repository.
Bug: https://github.com/flutter/flutter/issues/100878 …
> Fix the cirrus query validation.

- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/service/luci_build_service_test.dart
TODO: Add test
Underlying technical debt issue is tracked in https://github.com/flutter/flutter/issues/97687. Since there's so much duplicated logic in this one service, it's hard to ensure new features roll out everywhere in the scheduler.
> [scheduler] Pass dimensions on post-submit

- auto_submit/lib/requests/check_pull_request.dart
- auto_submit/test/requests/check_pull_request_test.dart
To control the number of PR to be merged to each repo per cycle, here we set a maximum threshold. Here I set it to be 2 initially, and we can change this threshold later according to the test result.
> [autosubmit] Control numbers of PR to be merged per cycle

- dashboard/lib/build_dashboard_page.dart
- dashboard/linux/flutter/CMakeLists.txt
- dashboard/pubspec.lock
- dashboard/test/build_dashboard_page_test.dart
Reverts flutter/cocoon#1696
There appears to be a bug in this that causes the text to not always be updated (missing key in tooltip?)
Fixes https://github.com/flutter/flutter/issues/101311
> Revert "[app_flutter] wrap AppBar.title in a Tooltip"

- auto_submit/lib/requests/check_pull_request.dart
- auto_submit/lib/service/github_service.dart
- auto_submit/test/src/service/fake_github_service.dart
This PR fixed the issue https://github.com/flutter/flutter/issues/101008 encountered when creating the comment to the PR. 
Instead of directly creating a review comment in the pull request diff, we here use the API that adds a regular comment to an issue timeline.
> [autosubmit] Fix create comment

- auto_submit/lib/requests/check_pull_request.dart
- auto_submit/lib/requests/check_pull_request_queries.dart
- auto_submit/lib/requests/exceptions.dart
- auto_submit/lib/service/config.dart
- auto_submit/lib/service/github_service.dart
- auto_submit/test/requests/check_pull_request_test.dart
- auto_submit/test/requests/github_webhook_test_data.dart
- auto_submit/test/service/github_service_test.dart
- auto_submit/test/src/service/fake_config.dart
- auto_submit/test/src/service/fake_github_service.dart
- auto_submit/test/src/service/fake_graphql_client.dart
- auto_submit/test/utilities/mocks.dart
- auto_submit/test/utilities/mocks.mocks.dart
To solve the issue https://github.com/flutter/flutter/issues/101012 to get the real author association, this PR changed the rest api to graphQL to query reviews and statuses. 
For checks, since we can use Rest Api to get all checks and graphQL query has a limitation on the numbers of checks we can get, we will keep using Rest Api for checks.
> [autosubmit] Use graphQL to get actual authorAssociation

- app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
- app_dart/lib/src/request_handlers/check_for_waiting_pull_requests_queries.dart
Existing logic returns top 5 labels for any PR, but PRs may have more than that, e.g. https://github.com/flutter/flutter/pull/101345.
When this happens, it will cause API failure and stop merging PRs.
This PR increases the limit to 10 from 5. The issue may still happen if a PR has more than 10 labels, but this will not be a problem when we move to `auto-submit` bot later this quarter.
This PR also adds logs to make the error message more clear.
Fixes https://github.com/flutter/flutter/issues/101539
> Increase label node request limit when graphql quering waiting PRs

- auto_submit/lib/requests/check_pull_request.dart
- auto_submit/lib/service/config.dart
- auto_submit/test/service/config_test.dart
- auto_submit/test/src/service/fake_config.dart
For the installation Id used to generate github token, we should pick the one belongs to flutter to get the write permission.
This PR also solves the issue: https://github.com/flutter/flutter/issues/100808. So now we can track the installation Id by repo to ensure every repo's quota is independent.
> [autosubmit] Get correct installation id

- app_dart/dev/branches.txt
- app_dart/lib/src/service/config.dart
- app_dart/test/service/config_test.dart
This is necessary as next engine beta will use the Cocoon scheduler. As a hack, you can add the branch manually in the URL encode, this is to make it easier to surface these results to the rest of the team.
This is temporary until https://github.com/flutter/flutter/issues/100491 is implemented
> [app_dart] Add flutter-2.13-candidate.0 to release branches

- app_dart/lib/src/request_handlers/github_webhook.dart
- app_dart/test/request_handlers/github_webhook_test.dart
More visibility for tool code during iOS PR triage.
> Add platform-ios to iOS tool code

- cloud_build/deploy_app_dart.sh
- cloud_build/deploy_cron_jobs.sh
- cloudbuild_cron.yaml
- cron.yaml
https://github.com/flutter/cocoon/pull/1717 enforced authentication of APIs to cronjob only.
Considering gcloud project supports only one cron.yaml, this PR generalize existing cron job deployment to include both app_dart and auto_submit.
> Refactor cronjob deploy to include auto-submit bot

- auto_submit/lib/requests/check_pull_request.dart
Add a log after _processMegre() to help triage the mergePR error.
> [autosubmit] Add after merge log

- auto_submit/lib/requests/check_pull_request.dart
- auto_submit/lib/service/github_service.dart
- auto_submit/test/requests/check_pull_request_test.dart
- auto_submit/test/requests/github_webhook_test_data.dart
- auto_submit/test/src/service/fake_github_service.dart
Previously we have already added and merged the codes that call Rest API to merge the pull request ( #1719). 
However, even though we are granted the merge permission to the flutter/cocoon repo, we still cannot successfully merge the pull request and continue to get the error `Can not merge the pull request 1723. Merge commits are not allowed on this repository..`.
To implement a valid way to merge the pull request, we found another Rest API here (https://docs.github.com/en/rest/reference/branches#merge-a-branch). Though this API is typically used for merging branch, we can use commit sha as head to merge commit as well.
Since the github dart package doesn't contain an existing API for this, I referred to https://github.com/SpinlockLabs/github.dart/blob/master/lib/src/common/issues_service …
> [autosubmit] Add valid merge PR

- auto_submit/lib/requests/check_pull_request.dart
- auto_submit/lib/service/github_service.dart
- auto_submit/test/requests/check_pull_request_test.dart
- auto_submit/test/requests/github_webhook_test_data.dart
- auto_submit/test/src/service/fake_github_service.dart
To implement auto merge branch, I first referred to github graphQL doc (https://docs.github.com/en/graphql/reference/input-objects#mergebranchinput) and wrote the correct codes by using graphQL mutation in #1727. 
However, I continued to receive `GraphQLError(message: Resource not accessible by integration)` error when I tested the code, even though flutter/cocoon has given the write permission to content. 
This is because the repositoryId parameter we used to merge branch is the Node ID of the Repository containing the base branch, that is, Kristin/cocoon, instead of flutter/cocoon. And for the Kristin/cocoon repo, I didn't install the app into my github, let alone changed the settings to give the write permission to allow merging branch.
One possible way to solve this issue is to …
> [autosubmit] Auto update pull request branch

- app_dart/lib/src/model/ci_yaml/target.dart
- app_dart/test/model/ci_yaml/target_test.dart
Instead of using `mac_model`, it is recommended to use `cpu`+`os`. This PR adds `cpu` dimension support defined in .ci.yaml config, which will help validate changes in pre-submit.
Related: https://flutter-review.googlesource.com/c/infra/+/29061
context: https://github.com/flutter/flutter/pull/101871, https://github.com/flutter/flutter/issues/101861
> Add cpu dimension support when parsing ci yaml

- auto_submit/lib/requests/check_pull_request.dart
- auto_submit/lib/requests/check_pull_request_queries.dart
- auto_submit/lib/service/github_service.dart
- auto_submit/test/requests/check_pull_request_test.dart
This PR continues to solve the issue https://github.com/flutter/flutter/issues/101803.
In our autosubmit bot, after we processed to check a pull request should be merged, we want to add a method autoMergePR() that can help us auto merge this pull request to our main branch.
I first used the Rest API [#merge-a-pull-request](https://docs.github.com/en/rest/reference/pulls#merge-a-pull-request)  in the github official doc, (you can check this part of codes in https://github.com/flutter/flutter/issues/1719). However, I continued to get the error `Can not merge the pull request 1723. Merge commits are not allowed on this repository..` even we granted the write permission.
Then I used the Rest API [#merge-a-branch](https://docs.github.com/en/rest/reference/branches#merge-a-branch) to merge the …
> [autosubmit] GraphQL merge PR

- cron.yaml
I've been using the bot. It would be nice if it was every 2 minutes, which roughly matches the existing logic.
This would allow 2 PRs to be submitted every 4 minutes versus the 2 PRs every 5 minutes today.
> [cron] Increase autosubmit frequency to 2 minutes

- dashboard/lib/logic/task_grid_filter.dart
- dashboard/lib/widgets/filter_property_sheet.dart
- dashboard/test/logic/task_grid_filter_test.dart
This is regarding https://github.com/flutter/flutter/issues/102000
Added private attribute _caseSensitive to RegExpFilterProperty, defaulted it to true, so that it doesn't affect anything else, and made it for for task name filter.
> issue #102000, making cocoon dashboard task name filter case insensitive

- app_dart/lib/src/model/ci_yaml/ci_yaml.dart
Sometimes the ci.yaml validation fails as PRs aren't up to date with tip of tree. This gives an actionable message to users to rebase their PRs with the master to get unblocked.
> [app_dart] Add remedy for ci.yaml validation failures by rebasing PR

- app_dart/lib/src/model/ci_yaml/target.dart
Related https://flutter-review.googlesource.com/c/infra/+/29261
Issue: https://github.com/flutter/flutter/issues/87508
> Support platform `mac_arm64_ios` when injecting devicelab xcode property

- test_utilities/bin/prepare_environment.sh
This is to fix the Cocoon post-submit failures in go/cocoon-build
> [test_utilities] Migrate pub to use dart pub

- auto_submit/lib/requests/check_pull_request.dart
- auto_submit/lib/requests/github_webhook.dart
- auto_submit/lib/service/approver_service.dart
- auto_submit/lib/service/config.dart
- auto_submit/test/service/approver_service_test.dart
- auto_submit/test/src/service/fake_config.dart
- auto_submit/test/utilities/mocks.dart
- auto_submit/test/utilities/mocks.mocks.dart
Auto-submit authenticates as a github application preventing it from
approving PRs or from landing autogenerated PRs.
This PR allows to approve autogenerated PRs using the fluttergithubbot
account and limits the actions that trigger pub/sub messages to
labeled|unlabeled.
Bug: https://github.com/flutter/flutter/issues/102418 …
> Fixes for auto-submit.

- auto_submit/lib/requests/check_pull_request.dart
- auto_submit/test/requests/check_pull_request_test.dart
- auto_submit/test/requests/github_webhook_test_data.dart
A new message is published to the topic everytime a new label is added
to a PR. If the first message is used to land the PR or somebody
manually merge the PR the bot will keep trying to merge the PR and
failing.
Bug: https://github.com/flutter/flutter/issues/102944 …
> Adds logic to deal with duplicated messages and closed PRs.

- app_dart/lib/src/service/config.dart
- app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
- app_dart/test/request_handlers/vacuum_github_commits_test.dart
Impeller was merged into engine so removing impeller repos everywhere from cocoon
Bug: flutter/flutter#103016
> Impeller was merged into engine so removing impeller repos

- app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
- app_dart/test/src/utilities/push_message.dart
This was temporarily added to recover from an outage. Removing as it seems to be causing some bugs in the release builds on go/engine-build
Fixes https://github.com/flutter/flutter/issues/102998
> Revert "[scheduler] Process build messages with null task key (#1698)"

- dashboard/lib/logic/task_grid_filter.dart
- dashboard/test/logic/task_grid_filter_test.dart
Adding a checkbox to menu for staging tasks (tasks whose names
are prefixed with 'Staging_build_').
By default staging tasks are not displayed.
Should have no other visible changes/functionality of the dashboard.
Bug:103081 …
> Adding a filter for staging tasks

- app_dart/README.md
- app_dart/dev/branches.txt
This is no longer used as we're storing them in datastore
> [app_dart] Remove branches.txt

- dashboard/lib/widgets/filter_property_sheet.dart
- dashboard/test/logic/task_grid_filter_test.dart
Fixes https://github.com/flutter/flutter/issues/103372
the BoolPropertyFilter was considered as having true as default all the time, so everything was hardcoded as true.
Changed that.
> removing hardcode true in BoolFilterProperty.

- app_dart/lib/src/request_handlers/scheduler/request_subscription.dart
- app_dart/test/request_handlers/scheduler/request_subscription_test.dart
Fix: https://github.com/flutter/flutter/issues/103168
This PR catches exception when retry limit is hit to batch schedule builds.
> Catch exception to ack pub/sub message

- .github/dependabot.yml
This seems to be mostly automated, and we can move manual intervention to the weekly triage meeting.
> [dependabot] Remove human reviewers

- auto_submit/lib/requests/check_pull_request.dart
- auto_submit/lib/requests/github_webhook.dart
- auto_submit/lib/service/approver_service.dart
- auto_submit/test/requests/check_pull_request_test.dart
- auto_submit/test/utilities/mocks.dart
- auto_submit/test/utilities/mocks.mocks.dart
This was happening because the webhook was getting multiple parallel
requests with the same PR. Moving the approval logic to the message
processing allows us to avoid the multiple approvals caused by the race
condition.
Bug: https://github.com/flutter/flutter/issues/102712 …
> Prevent multiple approvals.

- app_dart/dev/deploy.dart
- app_dart/pubspec.lock
- app_dart/pubspec.yaml
No longer needed as `unawaited` is in `dart:async` now
> [app_dart] Remove package:pedantic

- dashboard/lib/build_dashboard_page.dart
- dashboard/test/build_dashboard_page_test.dart
Closes flutter/flutter#101311
@christopherfujino I am reusing your code, the only difference is that I am calling `_getStatusTitle` inside the animation builder, I guess that's why it was being stuck on Loading...
> wrapping AppBar.title in a Tooltip

- app_dart/lib/src/service/branch_service.dart
context: https://github.com/flutter/flutter/issues/103996.
This commit adds more catch blocks to potentially catch previously foreseeable exceptions, and prints more logging information in appengine for better analysis.
Tried to fix the issue and investigated appengine logs multiple times with different queries but the logs are all legit. Also created different tests for different json webhook responses and tested locally, and the tests all passed. Couldn't dig out valuable information from current setup. Decided to add more catch blocks and loggings to help diagnose the issue.
> [app_dart] branch creation: catch exceptions and provide better logging

- device_doctor/lib/src/android_device.dart
- device_doctor/lib/src/health.dart
- device_doctor/lib/src/ios_device.dart
- device_doctor/lib/src/utils.dart
- device_doctor/pubspec.lock
- device_doctor/pubspec.yaml
this was not actually logging anywhere anyway, so remove the package. some of the logs were redundant to what was printed to stderr, I simply deleted these. Some seemed useful diagnostics to show, I ported these to `stdout.writeln()`. And printing the executed command seemed unimportant so I simply deleted (I can port it to stdout.writeln() if it would be useful).
No tests were affected by this change.
> remove package logging

- app_dart/lib/src/request_handlers/github_webhook.dart
- app_dart/test/request_handlers/github_webhook_test.dart
- app_dart/test/src/service/fake_buildbucket.dart
We already test when drafts are opened, so we don't need to re-trigger when marked ready for review.
> do not re-trigger builds when marking ready for review

- cron.yaml
There are three cron jobs running for flake bot, and they are at the same time. This caused github issue when calling APIs too frequently.
This is a mitigation to differentiate their time.
Issue: https://github.com/flutter/flutter/issues/105277
> Differentiate flake bot cron jobs time

- dashboard/test/utils/golden.dart
Flutter upstream https://github.com/flutter/flutter/pull/105648 caused cocoon builder breakage: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/flutter-try-builder_chops-service-accounts.iam.gserviceaccount.com/4080afd105c86723c951472336133b98c312107c022060d4761ea8d4cf7b9c94/+/build.proto?server=chromium-swarm.appspot.com
This PR fixes forward.
> Remove unused import to fix cocoon

- app_dart/lib/src/request_handlers/github_webhook.dart
- app_dart/test/request_handlers/github_webhook_test.dart
Dependabot and auto-roller account PRs are exempt from `needs tests` label and the "It looks like this pull request may not have tests." comments.  
Fix https://github.com/flutter/flutter/issues/105180 …
> Auto-roller accounts do not get labeled/commented with needs tests

- app_dart/lib/src/service/buildbucket.dart
- dashboard/lib/widgets/sign_in_button.dart
Fixes: https://github.com/flutter/flutter/issues/106429
Context: https://github.com/flutter/cocoon/pull/1917 used incorrect `builder` url for `builds` related requests, and caused buildbucket RPC failures.
> Fix urls in buildbucket RPCs

- auto_submit/lib/service/validation_service.dart
- auto_submit/lib/validations/ci_successful.dart
- auto_submit/test/validations/ci_successful_test.dart
Potential fix for: https://github.com/flutter/flutter/issues/106684
This PR does:
1) adds more logging to help triage
2) make use non-empty message when posting github comments
3) `await` message ack
> Guarantee non-empty message when posting github comment

- app_dart/lib/src/service/scheduler.dart
- app_dart/pubspec.lock
- app_dart/pubspec.yaml
- auto_submit/lib/model/auto_submit_query_result.dart
- auto_submit/lib/validations/ci_successful.dart
- auto_submit/pubspec.lock
- auto_submit/pubspec.yaml
- auto_submit/test/requests/github_webhook_test_data.dart
- auto_submit/test/validations/ci_successful_test.dart
- dashboard/pubspec.lock
This isn't a fix but it does add more logging so we can see what information is coming into the CiSuccessful Validator so we can determine why it is causing the autosubmit label to be removed in certain circumstances.
https://github.com/flutter/flutter/issues/106916
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutt …
> Autosubmit bot logs for #106914

- dashboard/pubspec.lock
- dashboard/pubspec.yaml
dependabot had downgraded some of the dependencies included here with the upgrad to build_runner and url_launcher dependencies.
https://github.com/flutter/cocoon/pull/1973
https://github.com/flutter/cocoon/pull/1983 …
> Upgraded url_launcher and build_runner dependencies manually.

- auto_submit/lib/requests/check_pull_request.dart
- auto_submit/lib/service/validation_service.dart
Follow up of https://github.com/flutter/cocoon/pull/1987
> Log pull request for autosubmit triage

- cron.yaml
Now everything is on cocoon scheduler (https://github.com/flutter/cocoon/pull/1998), and API `/api/refresh-chromebot-status` is not used anymore.
This PR removes cronjobs replying on this API.
> Remove cronjob relying on `/api/refresh-chromebot-status`

- app_dart/lib/src/service/config.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/scheduler_test.dart
- app_dart/test/src/datastore/fake_config.dart
With cocoon scheduling, a single schedule request of all builds will be created. This causes unpredicted builds schedule failure.
This PR use batch requests instead of a single request of ~300 builds: each batch is with default 5 builds.
Validation: a test version of cocoon wit this change has been running since yesterday.
Related: https://github.com/flutter/flutter/issues/103443, https://github.com/flutter/flutter/issues/92300
> Send batch requests when scheduling new commit builds

- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/service/luci_build_service_test.dart
Part of https://github.com/flutter/flutter/issues/108183.
We have the logic to prepare high priority, but fail to inject it to `ScheduleBuildRequest`. This PR fixes it.
> Rerun failed build with a higher priority

- app_dart/lib/src/model/ci_yaml/target.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/lib/src/service/scheduler/policy.dart
- app_dart/test/model/ci_yaml/target_test.dart
- app_dart/test/service/scheduler_test.dart
Release branches are currently blocked as they will use batch scheduling for the engine on mac, which isn't expected.
I assume this is similar logic we also want for the engine repo.
> [scheduler] Run guranteed policy on release branches and engine PRs

- app_dart/lib/src/service/branch_service.dart
- app_dart/pubspec.lock
- app_dart/pubspec.yaml
- app_dart/test/service/branch_service_test.dart
When GitHub has a newly created branches, the commit list hasn't finished replicating for the new branch. This adds a retry around it.
Additionally, explicitly add `package:retry` to the pubspec dependencies.
https://github.com/flutter/flutter/issues/102325
> [app_dart] Add retries to GitHub.listCommits

- app_dart/lib/src/service/gerrit_service.dart
https://github.com/flutter/flutter/issues/102325
The Gerrit documentation was out of date, and this should only be the string of the sha.
Next issue is dealing with the 403's coming from Gerrit
> [app_dart] Fix Gerrit CreateBranch request body

- app_dart/cloudbuild_app_dart.yaml
- flutter_image_build.yaml
In order to generate provenance and increase SLSA level, images are being routed to Artifact Registry instead of Container Registry. The transition has been tested for both autosubmit and app-dart. It is also necessary for the flutter image build prerequisite to be pushed to Artifact Registry.
As part of this, the build configurations for app-dart and flutter image build need to be updated to point to the correct Artifact Registry location. …
> Change Image Name to Use Artifact Registry

- dashboard/pubspec.lock
- dashboard/pubspec.yaml
- dashboard/test/utils/fake_google_account.dart
Manually land: https://github.com/flutter/cocoon/pull/2042 with fixes.
> Manually bump `google_sign_in` from 5.2.3 to 5.4.1 in /dashboard

- codesign/lib/src/file_codesign_visitor.dart
- codesign/lib/src/utils.dart
- codesign/test/file_codesign_visitor_test.dart
- codesign/test/file_codesing_visitor_test.dart
context: this is the fourth split (a smaller split) of https://github.com/flutter/cocoon/pull/1861.
prior splits (merged, excluding abandoned) : https://github.com/flutter/cocoon/pull/1972, https://github.com/flutter/cocoon/pull/1899, https://github.com/flutter/cocoon/pull/2003.
This split adds in logic to visit a binary file, and code sign it with or without entitlement, based on the configuration file.
-------
Thanks for reviewing! Incorporated feedbacks from Christopher
> [codesign] Logic to visit a binary file

- app_dart/cloudbuild_app_dart.yaml
- app_dart/cloudbuild_app_dart_deploy.yaml
- app_dart/cloudbuild_app_dart_docker.yaml
- auto_submit/cloudbuild_auto_submit.yaml
- auto_submit/cloudbuild_auto_submit_deploy.yaml
- auto_submit/cloudbuild_auto_submit_docker.yaml
- cloud_build/deploy_app_dart.sh
- cloud_build/deploy_auto_submit.sh
Bug: b/242225018
Creates build provenance for the following docker images:
* Docker image utilized by the flutter dashboard
* Flutter dashboard
* Flutter autosubmit
This required a couple of significant changes:
* Docker images are now deployed to artifact registry instead of container registry.
* This change was necessary because provenance is able to be generated in artifact registry easily, but not in container registry.
* Originally,`gcloud app deploy` automatically generated the docker image and uploaded it.
* In order to generate provenance, we needed to create the images ourselves. Therefore, the build and deploy have been split into different cloud builds, with a main cloud build configuration executing the build and deploy cloudbuild configs in order.
If you need help, consider …
> Establish Docker Image build provenance and move to artifact registry

- app_dart/lib/src/service/branch_service.dart
- app_dart/lib/src/service/gerrit_service.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/service/gerrit_service_test.dart
- app_dart/test/src/service/fake_gerrit_service.dart
There was an assumption that release branches all started with flutter-
which is only partially true as fuchsia* should be also considered
release branches.
Bug: https://github.com/flutter/flutter/issues/107761
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-brea …
> Support fuchsia release branches.

- codesign/lib/src/file_codesign_visitor.dart
- codesign/test/file_codesign_visitor_test.dart
This the fifth split (and a shorter split) of https://github.com/flutter/cocoon/pull/1861.
This PR adds function to parse and store entitlement files that were generated through GN.
prior splits: https://github.com/flutter/cocoon/pull/1972, https://github.com/flutter/cocoon/pull/1899, https://github.com/flutter/cocoon/pull/2003, https://github.com/flutter/cocoon/pull/2044.
> [codesign] add function to parse entitlement configs

- app_dart/lib/src/request_handlers/github_webhook.dart
- app_dart/test/request_handlers/github_webhook_test.dart
iOS and macOS native unit and integration tests should count as a PR having tests.
Fixes https://github.com/flutter/flutter/issues/109788
> Objective-C integration and unit tests do not need tests

- dashboard/pubspec.lock
- dashboard/pubspec.yaml
- dashboard/test/build_dashboard_page_test.dart
- dashboard/test/state/build_test.dart
- dashboard/test/utils/fake_flutter_app_icons.dart
- dashboard/test/widgets/commit_box_test.dart
- dashboard/test/widgets/task_grid_test.dart
* Uprev flutter_app_icons to 0.0.8
* Fix tests failing as there was no fake plugin created for it as it was originally a no-op
> [dashboard] Create fake for FlutterAppIcon in tests

- auto_submit/lib/service/validation_service.dart
Fixed two issues preventing merge of approved revert request.
1. added async to wait for approval before proceeding.
2. Fixed Repository Slug to create issue in flutter/flutter and not target slug. …
> Fixed two minor issues for revert functionality not merging issue

- auto_submit/lib/service/approver_service.dart
- auto_submit/lib/service/github_service.dart
- auto_submit/lib/service/revert_review_template.dart
- auto_submit/lib/service/validation_service.dart
- auto_submit/test/requests/check_pull_request_test.dart
- auto_submit/test/requests/github_webhook_test_data.dart
- auto_submit/test/service/approver_service_test.dart
- auto_submit/test/service/validation_service_test.dart
- auto_submit/test/src/service/fake_approver_service.dart
- auto_submit/test/src/service/fake_github_service.dart
- auto_submit/test/src/validations/fake_revert.dart
- auto_submit/test/utilities/mocks.mocks.dart
If merging has failed the autosubmit cannot remove the label in an exceptional case.
See https://github.com/flutter/flutter/issues/109754.
When an exception occurs we return from the call to the API caller with an error code and are unable to remove the label allowing this failure loop to continue.
fixes https://github.com/flutter/flutter/issues/109754
[test-exempt]: …
> Remove autosubmit on fail

- dashboard/lib/widgets/commit_author_avatar.dart
- dashboard/lib/widgets/commit_box.dart
- dashboard/lib/widgets/error_brook_watcher.dart
- dashboard/lib/widgets/task_grid.dart
Dependencies have been updated in the dashboard and we were using deprecated members of certain classes. This pr updates to the correct usage.
[CLA]: …
> Fix use of deprecated members in cocoon dashboard

- auto_submit/lib/service/revert_review_template.dart
Remove the step for adding the 'revert_review' label as it is causing confusion. The autosubmit bot does not currently respond to it so we will add it back at that time.
[CLA]: …
> Temporarily remove the step about the revert_review label when creating follow up review on revert pull requests

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
Adds flutter/package custom package test driver scripts to the list of files that don't need tests.
Fixes https://github.com/flutter/flutter/issues/103452
> Exempt package test runners from test bot

- CI_YAML.md
We are lacking doc example for devicelab targets.
This will help reduce tractions when team members add such targets: https://github.com/flutter/flutter/pull/111658
> Add devicelab example to CI_YAML doc

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
`dev/benchmarks` only contains integration test apps used for benchmarks:
```
complex_layout
macrobenchmarks
microbenchmarks
multiple_flutters
platform_channels_benchmarks
platform_views_layout
platform_views_layout_hybrid_composition
test_apps
```
Count these files as tests in the framework.
Seen in https://github.com/flutter/flutter/pull/112502 …
> Add dev/benchmarks example apps to test patterns

- dashboard/lib/build_dashboard_page.dart
- dashboard/pubspec.lock
- dashboard/pubspec.yaml
- dashboard/test/build_dashboard_page_test.dart
- dashboard/test/utils/fake_build.dart
This trims branches to not be as long in the build dashboard. It makes the max length able to show full release candidate branches, but any longer is trimmed.
Adds `package:truncate` to `dashboard`. This is already used in `app_dart`
> [dashboard] Truncate branch names

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
Analysis options are inherently tested by steps that run analysis, so don't need tests.
Extracts the common set of test-exempt files from the flutter/flutter and flutter/plugins+packages checks to minimize duplicate code. (Switching flutter/engine to sharing the same set of exemptions is out of scope for this refactor, as it would change behavior.) …
> Exempt analysis_options.yaml from test requirement

- auto_submit/lib/service/validation_service.dart
- dashboard/pubspec.lock
A retry-able error was encountered during a revert request due to a required check being scheduled and a revert needing to be merged.
This fix will address issues like the following where we failed to merge and kicked back out to the user when we could have just retried since the user added the label back immediately and the merge was successful.
https://github.com/flutter/flutter/pull/112905 …
> Remove strictness of graphql error check in retry.

- app_dart/lib/src/request_handlers/check_flaky_builders.dart
- app_dart/lib/src/service/config.dart
- app_dart/test/src/datastore/fake_config.dart
When multiple github requests are called in a short period, it hits 
```
You have exceeded a secondary rate limit 
```
This PR adds a 1s delay between calls following: https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits
More context: https://github.com/flutter/flutter/issues/102402
> Add delay between deflake github requests

- app_dart/lib/src/foundation/utils.dart
- app_dart/lib/src/model/ci_yaml/target.dart
- app_dart/lib/src/request_handlers/check_flaky_builders.dart
- app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart
- app_dart/lib/src/request_handlers/flaky_handler_utils.dart
- app_dart/lib/src/request_handlers/update_existing_flaky_issues.dart
- app_dart/test/model/ci_yaml/target_test.dart
- app_dart/test/request_handlers/update_existing_flaky_issues_test.dart
- app_dart/test/request_handlers/update_existing_flaky_issues_test_data.dart
- app_dart/test/src/utilities/entity_generators.dart
- dashboard/pubspec.lock
Update to flaky issues handler code so that we use the protobuf and wrappers instead of using the ciYaml directly. This will avoid issues with deprecated features as we will only receive changes via the protobuf definitions.
https://github.com/flutter/flutter/issues/87529 …
> Using protobuf instead of ciyaml directly.

- app_dart/lib/src/model/ci_yaml/target.dart
- app_dart/test/model/ci_yaml/target_test.dart
The scheduler is overriding the osx_properties passed from infra configs. This PR adds support for cleanup_xcode_cache.
Bug: https://github.com/flutter/flutter/issues/113539
[Discord]: …
> Allow cache cleanup in osx_properties.

- app_dart/README.md
The `dev/branches.txt` has been removed and this PR removes obsolete doc.
> Remove obsolete branch doc

- app_dart/bin/server.dart
- app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
- app_dart/lib/src/service/config.dart
- app_dart/lib/src/service/github_checks_service.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
- app_dart/test/service/luci_build_service_test.dart
- app_dart/test/src/datastore/fake_config.dart
Fixes: https://github.com/flutter/flutter/issues/106902
This PR enables checkrun support for plugins and packages:
1) create checkrun when commit lands
2) update checkrun when builds finish
This PR has been validated with cocoon repo:
/cc @stuartmorgan
> Support postsubmit checkruns for plugins/packages

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
Enables the same logic to exempt (some) comment-only changes from the test bot that is currently used in flutter/{flutter,plugins,packages}.
> Enable comment-only test exclusion for engine

- codesign/bin/codesign.dart
dryrun mode means code signed artifacts aren't uploaded back to gcs buckets.
dryrun mode should be selected by default. User need to supply a `--no-dryrun` flag to opt out of dry run mode.
> [codesign] set the default value of dryrun flag to true

- auto_submit/pubspec.lock
- auto_submit/pubspec.yaml
Reverts flutter/cocoon#2263
https://github.com/grpc/grpc-dart/pull/565/files implemented `onConnectionStateChanged`, which doesn't seem addressed in appengine 0.13.3.
> Revert "Bump appengine from 0.13.2 to 0.13.3 in /auto_submit"

- app_dart/lib/src/service/branch_service.dart
- app_dart/lib/src/service/gerrit_service.dart
An attempted fix at getting the pubsub retries to kick in by reducing max runtime to less than 60 seconds.
https://github.com/flutter/flutter/issues/112036
> [app_dart] Reduce create branch delays

- app_dart/pubspec.lock
- app_dart/pubspec.yaml
- auto_submit/pubspec.lock
- auto_submit/pubspec.yaml
With upstream fix (https://github.com/dart-lang/appengine/pull/155) from appengine, a new version has been pushed to pub.dev.
This PR bumps appengine version to latest 0.13.4.
Fixes: https://github.com/flutter/flutter/issues/114270
Related early workaround PR: https://github.com/flutter/cocoon/pull/2275
> Bump appengine version to latest version

- codesign/bin/codesign.dart
- codesign/lib/src/file_codesign_visitor.dart
- codesign/lib/src/utils.dart
- codesign/test/file_codesign_visitor_test.dart
Currently we assume the codesign credentials are stored in a file located at '/tmp/passwords.txt' (we can change this file path location). And code sign standalone app will read the credentials from this file, as opposed from reading from user input or environment variables. Also capped the naming of credentials and parameters per request.
> [codesign + recipe ] read passwords from a file

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
dev/devicelab/lib/versions/gallery.dart contains the flutter/gallery repo SHA to be synced during the gallery transitions test. Semantically, it's similar to the engine's DEPS file or a pubspec.yaml in that updates to it are version bumps.
This marks this file test exempt in our GitHub web hook.
Uncovered during fixing: https://github.com/flutter/flutter/issues/114025
[CLA]: …
> Make gallery dependency file test-exempt

- dashboard/pubspec.lock
- dashboard/web/index.html
This PR updates the dashboard's `web/index.html` to:
* Use `flutter.js` to embed flutter ([as described here](https://docs.flutter.dev/development/platform-integration/web/initialization)).
* Use the `canvasKitBaseUrl` config option to load the locally distributed canvaskit, rather than the version from the external CDN.
Once [this `flutter/engine` PR](https://github.com/flutter/engine/pull/37187) lands, the dashboard will start to warn (in development) about `flutterConfiguration` being deprecated. The fix is to pass the configuration object to the `initializeEngine` call, like so (feel free to reach out to me for any assistance!):
```javascript
engineInitializer.initializeEngine({
canvasKitBaseUrl: "/canvaskit/",
}).then(function (appRunner) {
appRunner.runApp();
});
```
(This also …
> [dashboard] Use flutter.js and local canvaskit.

- app_dart/lib/src/model/ci_yaml/target.dart
This is to make the behavior consistent for json lists and dictionaries.
Bug: https://github.com/flutter/flutter/issues/114656
> Pass process json dicts in ci.yaml.

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
Count `.sh` shell scripts as tests in the engine.
Now matches on `run_ios_tests.sh`.
Seen in https://github.com/flutter/engine/pull/37435
> Add shell scripts to engine test pattern

- cron.yaml
It seems as though the cocoon-cron-job has been failing due to a missing /
https://pantheon.corp.google.com/cloud-build/builds;region=global?query=trigger_id%3D%228e6790d7-1a7b-46e7-998b-f481964be9ff%22&project=flutter-dashboard …
> Update revert url to start with /

- app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
This will give us visibility of the message format required to report results from builders from dart-internal.
Bug: https://github.com/flutter/flutter/issues/115730
[Discord]: …
> Temporarily add logging of results messages.

- app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
This PR is moving the logging to the step before parsing the message. This will allow us to see the json that is causing parsing errors.
Bug: https://github.com/flutter/flutter/issues/115490 …
> Change logging order.

- codesign/lib/src/file_codesign_visitor.dart
- codesign/test/file_codesign_visitor_test.dart
Change system codesign to use absolute path.
For our mac bots, system codesign are located at /usr/bin/codesign. Based on discussion in https://github.com/flutter/cocoon/pull/2316 , we would like to use the absolute path to identify the different callable `codesign`s. Without specifying an absolute path, the name resolution would fail during the led recipe run.
> [codesign] absolute path for system codesign

- auto_submit/lib/service/validation_service.dart
- auto_submit/pubspec.lock
- codesign/pubspec.lock
- dashboard/pubspec.lock
We are getting rare permissions based errors when attempting to merge a pull request. It can happen that we are using a somewhat stale client and when we hit retries we are using the same client over and over. I have made a change to fetch a new client each time we need to attempt a new merge.
fixes https://github.com/flutter/flutter/issues/116304 …
> Updated autosubmit so that we get a new client when merging a pull request

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
The `pigeon` package in flutter/packages has a very unusual test structure, with several plugins and a common shared library that are all just tests for generated Pigeon code. This causes a lot of false positives with the test bot, so this adds the `platform_tests` directory to the list of known tests. …
> Teach test bot about Pigeon tests

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
Embedder API tests in the engine are implemented as C++ unit tests and test infrastructure such as embedder_test_context_metal.{h,cc} (located under the shell/platform/embedder/tests directory), which execute and test Dart functions (and associated test assets) stored in the shell/platform/embedder/fixtures directory.
Uncovered while sending https://github.com/flutter/engine/pull/38133.
Issue: https://github.com/flutter/flutter/issues/116381 …
> Add test exemption for embedder tests and fixtures

- test_utilities/bin/dart_test_runner.sh
The error causing this workaround has been fixed and the instruction is not needed anymore.
> Remove the global tuneup instruction.

- codesign/bin/codesign.dart
Gives codesign app the ability to write info to stdout.
This helps user to monitor and triage led runs and luci builds. As pointed out by Christopher, stdout.writeln is the way to go
> [codesign] write codesign info to stdout via stdout writeln

- app_dart/lib/src/service/luci_build_service.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/luci_build_service_test.dart
- app_dart/test/src/utilities/mocks.mocks.dart
`rescheduleBuild` and `rescheduleUsingCheckRunEvent` now return `Build` objects instead of `true`.
Addresses https://github.com/flutter/flutter/issues/83945
> Change some LuciBuildService methods to return Build objects

- device_doctor/lib/src/ios_device.dart
On mac, there can be multiple provisioning profiles files. Currently, device_doctor assumes only one, and errors if it finds multiple files.
Update device doctor to look through all files and if any of them contain a valid profile.
Bug:https://github.com/flutter/flutter/issues/117400 …
> Update device_doctor to look through all provisioning profile files.

- codesign/lib/src/file_codesign_visitor.dart
- codesign/test/file_codesign_visitor_test.dart
open to suggestions, we have two options here:
1. enforce every artifact to have both `entitlements.txt` and `without_entitlements.txt` as metadata, and throw exception when any of the metadata is missing.
2. allow artifact to have a single or no metadata file, to imply that the artifact does not have any binary files to be codesigned (with/without entitlements). In this case we will convert exception to warning.
> [codesign + open to suggestions] log warning instead of exception when metadata isn't present

- cron.yaml
Reduce outage latency.
With the removal of the release branch logic from this handler, there should be spare quota to running this more often.
> [cron] Increase vacuum frequency to 10 minutes

- auto_submit/pubspec.lock
- auto_submit/pubspec.yaml
> Revert "Bump graphql from 5.1.2-beta.6 to 5.1.2 in /auto_submit"

- device_doctor/tool/infra-dialog/infra-dialogUITests/infra_dialogUITests.swift
iOS-16 has a new dialog that is not being dismissed with the existing options in the dismiss dialog app.
Bug:https://github.com/flutter/flutter/issues/118411
- [] I updated/added relevant documentation (doc comments with `///`).
- [] I added new tests to check the change I am making, or this PR is [test-exempt]. …
> Add new button text to dismiss dialog app.

- app_dart/cloudbuild_app_dart_docker.yaml
- auto_submit/cloudbuild_auto_submit_docker.yaml
Issue: https://github.com/flutter/flutter/issues/117928
Adding this will require the autosubmit bot and cocoon to have provenance in order to be deployed. If there is no provenance for any reason, it will not deploy the image.
Additional info on this change can be found here: https://cloud.google.com/build/docs/securing-builds/view-build-provenance#req-metadata
[CLA]: …
> Add verification of build provenance

- app_dart/lib/src/service/NoBuildFoundException.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/luci_build_service_test.dart
Cleanup the logs so we can better isolate and debug errors from the infra services. This fix addresses the issue when we attempt to reschedule builds then access the empty build list. Instead we will now catch an exception and log a warning. 
Fixes https://github.com/flutter/flutter/issues/118631
[test-exempt]: …
> Eliminate unnecessary errors in the logs and fail gracefully if we cannot find build to reschedule.

- dashboard/test/utils/fake_google_account.dart
Make operator == override parameters non-nullable. See dart-lang/linter#3441
Work towards dart-lang/sdk#51038.
> == override parameters are non-nullable

- auto_submit/pubspec.lock
- auto_submit/pubspec.yaml
The web_socket_channel dependency has been locked to 2.2.0 in the newest graphql package. We do not need to override it here. 
Fixes https://github.com/flutter/flutter/issues/118352 …
> Updated to remove dependency override for web_socket_channel

- codesign/bin/verify.dart
- codesign/lib/verify.dart
- codesign/pubspec.lock
- codesign/test/verify_test.dart
Usage is:
```
$ dart bin/verify.dart --input-file /Users/fujino/Downloads/darwin_ruby_x64/bin/ruby
Authority:      Developer ID Application: FLUTTER.IO LLC (S8QB4VV633)
Time stamp:     Jan 9, 2023 at 9:39:07 AM
Format:         Mach-O thin (x86_64)
Signature size: 8979
Notarization:   true
```
If the file is codesigned but not notarized, the output will be:
```
$ dart bin/verify.dart --input-file /Users/fujino/git/flutter/bin/cache/dart-sdk/bin/dart
Authority:      Developer ID Application: FLUTTER.IO LLC (S8QB4VV633)
Time stamp:     Jan 11, 2023 at 3:45:00 PM
Format:         Mach-O thin (x86_64)
Signature size: 8978
Notarization:   false
```
And if the file is neither codesigned nor notarized, the output will be:
```
$ dart bin/verify.dart --input-file …
```
> add codesignature verification tool

- app_dart/lib/src/foundation/github_checks_util.dart
- app_dart/lib/src/model/luci/push_message.dart
- app_dart/lib/src/model/luci/push_message.g.dart
- app_dart/lib/src/request_handling/subscription_handler.dart
- app_dart/lib/src/service/github_checks_service.dart
- app_dart/lib/src/service/github_service.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/github_service_test.dart
- app_dart/test/service/scheduler_test.dart
- app_dart/test/src/service/fake_github_service.dart
- app_dart/test/src/utilities/entity_generators.dart
- app_dart/test/src/utilities/mocks.dart
- app_dart/test/src/utilities/mocks.mocks.dart
According to https://github.com/flutter/flutter/issues/100081, this should fix ci.yaml validation errors.
> Use search API to find matching PR for ci.yaml validation reruns

- app_dart/lib/src/service/scheduler.dart
- app_dart/pubspec.lock
- app_dart/pubspec.yaml
- app_dart/test/service/scheduler_test.dart
- app_dart/test/src/utilities/entity_generators.dart
Replaces a hack that was used to substitute the git branch in the checkrun event handler until this got merged and released: https://github.com/SpinlockLabs/github.dart/pull/347
Addresses https://github.com/flutter/flutter/issues/119171
> Use headBranch from checkRunEvent instead of default branch

- dashboard/test/widgets/commit_box_test.dart
> SystemChannels.platform.setMockMethodCallHandler is deprecated

- app_dart/lib/src/request_handlers/scheduler/vacuum_stale_tasks.dart
- app_dart/test/request_handlers/scheduler/vacuum_stale_tasks_test.dart
Follow up to https://github.com/flutter/cocoon/pull/2471
This column can't be set to null.
```
Error while encoding entity (Bad state: Property validation failed for property createTimestamp while trying to serialize entity of kind Task. , #0 
```
> [app_dart] Fix stale tasks timestamp encoding

- analyze/pubspec.lock
- app_dart/pubspec.lock
- auto_submit/lib/validations/revert.dart
- auto_submit/pubspec.lock
- auto_submit/test/service/validation_service_test.dart
- auto_submit/test/validations/revert_test.dart
- codesign/pubspec.lock
- dashboard/pubspec.lock
- device_doctor/pubspec.lock
- licenses/pubspec.lock
- test_utilities/pubspec.lock
When processing a revert the logic to determine mergeability was incorrect. When a pull request has mergeable value of null it means that github is still calculating the mergeability to determine if there are conflicts. I have fixed this in the code to detect that condition. 
Fixes https://github.com/flutter/flutter/issues/120795
[test-exempt]: …
> Get updated pull request info for mergeable state check in revert requests

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
Matches framework repo:
https://github.com/flutter/cocoon/blob/68e36df5bf668d67ae52c036bd427518e0a38929/app_dart/lib/src/request_handlers/github/webhook_subscription.dart#L241-L249
and packages repos:
https://github.com/flutter/cocoon/blob/68e36df5bf668d67ae52c036bd427518e0a38929/app_dart/lib/src/request_handlers/github/webhook_subscription.dart#L463-L468
Would have avoided requesting tests for https://github.com/flutter/engine/pull/39682 …
> Do not request tests for engine deletion-only PRs

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
`integration_test` PRs are not currently triaged on their own as one of the ["classification labels"](https://github.com/flutter/flutter/wiki/Triage#triaging-prs) that indicate a particular team will look at it.  Add the `framework` label so they are included in the framework team's triage.
https://github.com/flutter/flutter/pull/117977 would have been triaged sooner.
[CLA]: …
> Add framework label to integration_test PRs

- auto_submit/lib/service/validation_service.dart
- auto_submit/test/requests/github_webhook_test_data.dart
- auto_submit/test/service/validation_service_test.dart
* If a PR title does "Revert "Revert", it was likely auto-generated by GitHub, and should be corrected to "Reland ..." to follow best practices
* Fix generatePullRequest to be null safe
* Make generatePullRequest parameters null safe
* Remove unused queryResult parameter
> [autosubmit] Fix commit messages to use "Reland"

- dashboard/lib/main.dart
Calling `setSemanticsEnabled` is error-prone as the platform can override this and turn semantics on/off willy-nilly and we are in the process of removing this API. Calling `ensureSemantics` ensures that semantics stay turned on no matter what the platform says.
> Call proper semantics API

- app_dart/lib/src/foundation/utils.dart
- app_dart/test/foundation/utils_test.dart
The recursive glob was matching a single character.
Bug: https://github.com/flutter/flutter/issues/121160
> Implement correct glob behavior in run_if.

- analyze/analyze.dart
- app_dart/cloudbuild_app_dart_deploy.yaml
- app_dart/test/service/luci_build_service_test.dart
- auto_submit/cloudbuild_auto_submit_deploy.yaml
- cloud_build/get_docker_image_provenance.sh
- cloud_build/verify_provenance.sh
Addresses https://github.com/flutter/flutter/issues/121559
* Move obtaining provenance to a separate shell script
* Add retry logic to the script in case the provenance isn't obtained on the first try.
* Added parameters to the provenance verification, in order to make it more reusable
* Fixed a unit test that was failing based on the order of the unit test
Occasionally the provenance fails to be obtained, so adding a retry in order to obtain more information …
> Retry provenance

- app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
- app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
- app_dart/test/src/service/fake_scheduler.dart
This is a follow up of https://github.com/flutter/cocoon/pull/2516, which disabled postsubmit `checkrun` creation on other repos. This PR disables postsumbmit `checkrun` update on other repos.
Fixes: https://github.com/flutter/flutter/issues/122314
> Limit postsubmit checkrun update logic to `postsubmitSupportedRepos` only

- app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
Batch backfiller API now bundles all suitable back filling targets in a Future list, and exits with error whenever an error happens in any Future (with `eagerError: true`). This has caused hanging yellow boxes without builds scheduled (https://github.com/flutter/flutter/issues/122117).
This PR disables `eagerError`, this way all other Futures will continue even there is any error occurring.
> Wait all futures complete before return when there are errors in `batch backfiller`

- app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
- app_dart/lib/src/service/config.dart
- app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart
- app_dart/test/src/datastore/fake_config.dart
- app_dart/test/src/service/fake_scheduler.dart
This is an attempt to fix issue https://github.com/flutter/flutter/issues/122117 by limiting the number of back filler targets, which limits the number of pub/sub requests in each API.
> Enforce `backfillerTargetLimit` when backfilling

- dashboard/test/build_dashboard_page_test.dart
- dashboard/test/dashboard_navigation_drawer_test.dart
In preparation for https://github.com/flutter/flutter/pull/122824.
> Migrate away from deprecated TestWindow API

- app_dart/lib/src/service/config.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
Some PRs from roller `dependabot` are with `user.login` as `dependabot[bot]` in webhook payload. This PR covers it to skip tests check for repos (packages, engine, framework).
Fixes: https://github.com/flutter/flutter/issues/108129
> Skip tests check for `dependabot[bot]`

- device_doctor/lib/src/ios_debug_symbol_doctor.dart
- device_doctor/test/src/ios_debug_symbol_doctor_test.dart
Related to https://github.com/flutter/flutter/issues/123257
Treat messages that look like:
`! Error: iPhone 11 is busy: Preparing iPhone 11 for development. Xcode will continue when iPhone 11 is finished. (code -10)`
As debug symbol errors that should be recovered by opening Xcode.
> add new error message pattern to ios_debug_symbol_doctor

- cloud_build/verify_provenance.sh
* Addresses https://github.com/flutter/flutter/issues/123657
* Cloud Builds are sometimes adding `git+` to the source uri. This will eventually be generated for all builds, but until then, check for the source-uri with `git+` and without so that our builds don't randomly fail.
[breaking change …
> Update verify_provenance.sh to check two different source uris

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
Like CODEOWNERS, a change just to TESTOWNERS should not require tests.
See https://github.com/flutter/flutter/pull/124263
> Exempt TESTOWNERS files from test requirements and scold

- app_dart/bin/server.dart
- app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
- app_dart/lib/src/request_handling/pubsub.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart
- app_dart/test/service/luci_build_service_test.dart
- app_dart/test/service/scheduler_test.dart
- app_dart/test/src/request_handling/fake_pubsub.dart
- app_dart/test/src/service/fake_luci_build_service.dart
- app_dart/test/src/utilities/mocks.mocks.dart
This PR is to mitigate https://github.com/flutter/flutter/issues/124018
Changes include:
1) Cache builder list when calling the buildbucket API. This should help with 
- Failed to update tasks when backfilling: BuildBucketException: [502]
- Failed to update tasks when backfilling: BuildBucketException: [504]: Request deadline exceeded
- Failed to update tasks when backfilling: Connection closed before full header was received
2) Retry when pub/sub error happens. This should help with the `DetailedApiRequestError`.
> Use cache + retry when batch backfilling to mitigate server errors

- app_dart/lib/src/foundation/utils.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/foundation/utils_test.dart
- codesign/pubspec.lock
- dashboard/pubspec.lock
The glob regex was not working correctly with localization files as they have digits in the file names. The regex was modified to collect these and was improved to allow trailing * for and file in a dir.
Also added more logging to aid with debugging.
Fixes https://github.com/flutter/flutter/issues/124140
[test-exempt]: …
> Modify the glob regex replacement for the runIf clause for target collection

- cron.yaml
The current configurations run on Wed at 9:00 PST which opens several PRs consuming all the available capacity during MTV working hours.
Bug: https://github.com/flutter/flutter/issues/124272 …
> Update flake cron jobs to run at 2AM PST.

- app_dart/lib/src/service/branch_service.dart
https://github.com/flutter/flutter/issues/124763
For customers outside Flutter that manage their own release branches, they usually don't maintain their own flutter/flutter branch. Fuchsia is failing on this step as it relies on flutter/flutter.
This is moreso the correct behavior as well. Recipes doesn't change much for flutter/flutter, where it changes often for flutter/engine. Basing this off the flutter/engine commits will give a more likely to be green recipe branch.
> [app_dart] Change create recipe branch to use engine repo

- app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
- app_dart/lib/src/service/luci_build_service.dart
One more instance happened yesterday (https://github.com/flutter/flutter/issues/124018), and this PR adds logs to help triage.
> Add logs to batch backfiller to help triage

- codesign/lib/src/file_codesign_visitor.dart
- codesign/lib/src/utils.dart
- codesign/test/file_codesign_visitor_test.dart
context: fixes https://github.com/flutter/flutter/issues/124656 , where symlink is followed and an exception was thrown.
Instead, if a file is a symlink that is pointing to another file, we will skip code signing this file.
> [codesign] skip symlink files

- device_doctor/lib/src/ios_debug_symbol_doctor.dart
- device_doctor/test/src/ios_debug_symbol_doctor_test.dart
Fixes https://github.com/flutter/flutter/issues/124749
Before this change, if the subprocess `xcrun xcodebuild -runFirstLaunch` exits non-zero, we'd log about it and then continue going, wasting CI time.
> [device_doctor] ios_debug_symbol_doctor recover exit early if subprocess fails

- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/service/branch_service_test.dart
- app_dart/test/service/luci_build_service_test.dart
Initially to fix the cancel builds I made the mistake of cancelling by sha which does not work since if you use the head sha the builds are tied to that so it will find no builds each time to cancel.
I have validated the query by running the following on a previous pull request:
```
{
"predicate": {
"builder": {
"project": "flutter",
"bucket": "try",
"builder": null
},
"tags": [
{
"key": "buildset",
"value": "pr/git/2616"
},
{
"key": "github_link",
"value": "https://github.com/flutter/cocoon/pull/2616"
}
]
}
}
```
This returns the 4 builds that we need:
```
{
"builds": [
{
"id": "8783897293298038209",
"builder": {
"project": "flutter",
"bucket": "try",
"builder": "Linux ci_yaml roller"
},
"number": 3349,
"createdBy": "user:flutter-dashboard@appspot.gserviceaccount.com",
"createTime": …
```
> Cancel builds by pull request not sha

- app_dart/lib/src/request_handlers/get_branches.dart
- app_dart/test/request_handlers/get_branches_test.dart
Filter out branches that are not relevant from development or release workflows.
Bug: https://github.com/flutter/flutter/issues/124843
> Filter out branches.

- codesign/bin/codesign.dart
- codesign/lib/src/file_codesign_visitor.dart
- codesign/test/file_codesign_visitor_test.dart
Fix (hopefully) an inexplicable bug when codesign tool is used on chromium bots. Specify 'build.keychain' as the keychain to look for flutter identity.
Context: on luci runs, the flutter identity is correctly imported under 'build.keychain', and is listed as both 'matching identity' and 'valid identity' for codesign, and 'build.keychain' is set and verified to be the default keychain. However, when signing on chromium bots, there is this inexplicable flake (~30 percent of time) where the bots keep looking for flutter cert under 'login.keychain'. 
Open to suggestion:  if this works, we could supply '--keychain' as a parameter instead of hard coding it to be 'build.keychain'. And we can supply 'build.keychain' as a parameter on the recipe side.
I have tested the correctness of '--keychain' …
> [codesign] look for cert in designated keychain

- app_dart/lib/src/request_handlers/get_branches.dart
- app_dart/test/request_handlers/get_branches_test.dart
The regexes were applied from anywhere in the string causing unexpected results.
Bug: https://github.com/flutter/flutter/issues/125086
> Apply branch filter regex from start of string.

- analysis_options.yaml
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/pubspec.lock
- auto_submit/pubspec.lock
- codesign/pubspec.lock
- dashboard/pubspec.lock
- dashboard/test/widgets/task_grid_test.dart
- device_doctor/pubspec.lock
- device_doctor/tool/build.bat
- device_doctor/tool/build.sh
- licenses/pubspec.lock
- test_utilities/bin/global_test_runner.dart
A change was made to collect the try tasks and cancel them for a pull request when it is updated, closed, or merged. The function that gets the tasks was missing the 'async' keyword which caused us not to wait for the results of the task collection. It would only work rarely but it should be collecting all of the targets for the pull request each time unless nothing was truly scheduled or run yet.
Fixes [125278](https://github.com/flutter/flutter/issues/125278) …
> Missing async keyword not allowing cocoon to wait for build collection

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
- Ignore dev/integration_tests file changes in flutter/flutter since they are tests already
- Add test
https://github.com/flutter/flutter/issues/125244
Previous pr was removed because it contained sensitive data.
> i125244 exempt dev integration from test required tag

- app_dart/cloudbuild_app_dart_deploy.yaml
- auto_submit/cloudbuild_auto_submit_deploy.yaml
- cloud_build/verify_provenance.sh
https://github.com/flutter/flutter/issues/125423
Fixes a couple of issues:
* `golang:stretch` seemed to not be able to successfully run `apt update` anymore. I'm not exactly sure why, but to be safe we switched to `golang:latest`
* The pinned version of `jq` no longer exists, switched to the latest version of that as well.
* Tested the build and it passed successfully
[CLA]: …
> Switch to latest image and default to latest jq

- dashboard/lib/build_dashboard_page.dart
- dashboard/lib/service/google_authentication.dart
- dashboard/lib/state/build.dart
- dashboard/lib/widgets/task_overlay.dart
- dashboard/pubspec.lock
- dashboard/test/build_dashboard_page_test.dart
- dashboard/test/service/google_authentication_test.dart
- dashboard/test/state/build_test.dart
- dashboard/test/utils/mocks.mocks.dart
- dashboard/test/utils/wrapper.dart
- dashboard/test/widgets/task_overlay_test.dart
- dashboard/test/widgets/user_sign_in_test.dart
This PR updates the Build Dashboard to make sure its UI reflects the authentication state of the user more directly. The UI refreshes as "logged out" when calls to the backend that require a valid authentication fail.
Before this, it was not entirely clear why some actions failed (failing operations only raised a small snackbar at the bottom of the page, and there was no way to renew the user session other than full-page reloading). The app could be in an inconsistent state where it *seemed* to be logged-in, but the user authorization would have expired.
After this PR, the app will seemingly "kick the user out" when they attempt something that they don't have permission to do, so they can interactively re-authenticate. It will also disable the problematic buttons so they cannot be spammed …
> [cocoon] Remove user authentication when backend calls fail.

- auto_submit/lib/validations/approval.dart
- auto_submit/test/validations/approval_test.dart
- auto_submit/test/validations/approval_test_data.dart
It was found that a review author can request changes be made then later approve the pull request. However Autosubmit was not honoring the chronological order of the reviews and was incorrectly blocking reviews that succeeded the original changes requested review. We now are traversing the reviews in reverse chronological order.
Also added a check so the pr author cannot review his own pull request.
Fixes https://github.com/flutter/flutter/issues/125280 …
> Fix review approval check ordering

- codesign/tool/build.sh
update dart path for codesign build.
the path of dart cipd package has been updated. Now mac, linux, and windows share the same path.
> update dart path

- auto_submit/lib/configuration/repository_configuration.dart
- auto_submit/lib/configuration/repository_configuration_manager.dart
- auto_submit/lib/exception/configuration_exception.dart
- auto_submit/lib/service/config.dart
- auto_submit/lib/service/github_service.dart
- auto_submit/lib/service/secrets.dart
- auto_submit/pubspec.lock
- auto_submit/pubspec.yaml
- auto_submit/test/configuration/repository_configuration_data.dart
- auto_submit/test/configuration/repository_configuration_manager_test.dart
- auto_submit/test/configuration/repository_configuration_test.dart
- auto_submit/test/src/configuration/fake_repository_configuration_manager.dart
- auto_submit/test/src/service/fake_config.dart
- auto_submit/test/src/service/fake_github_service.dart
Adding code to allow for autosubmit to collect it's configuration based on the Organization and Repository. 
This code is the basis of the remaining changes and is not currently active so it should be safe to merge.
While this is not the fix for this feature this pr addresses the following:
Fixes https://github.com/flutter/flutter/issues/125685 …
> Add code to collect the repository configuration for Configurable Autosubmit - Part 1

- app_dart/test/src/request_handling/fake_http.dart
All the current rolls are failing due to this class not having the correct implementation or being abstract. Class is now made abstract to avoid the error.
[CLA]: …
> Make fake_http.dart abstract so it does not fail analysis

- app_dart/lib/src/model/ci_yaml/target.dart
- app_dart/test/model/ci_yaml/target_test.dart
This is a joint PR with https://flutter-review.googlesource.com/c/infra/+/43921, appending `osx_sdk` property to devicelab targets. This is to prepare osx_sdk and devicelab_osx_sdk recipe modules consolidation.
Part of https://github.com/flutter/flutter/issues/117541
> Append osx_sdk property to devicelab tasks

- .github/dependabot.yml
- tooling/go.mod
- tooling/go.sum
https://github.com/flutter/flutter/issues/126343
The reason the builds were failing is because indirect dependencies were getting updated when they should not have been, causing the packages needed by `slsa-verifier` to be out of sync. The following changes should prevent this going forward:
* Add a restriction in dependabot to only update `slsa-verifier`
* Recreate the tooling so that it is correctly in sync with the current version of `slsa-verifier` …
> Only allow direct slsa-verifier updates

- app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart
https://github.com/flutter/cocoon/pull/2201 added a 1s delay between PR creations for `check_flaky_builders` API. It doesn't seem to hit the secondary rate limit issue.
This PR adds the 1s delay to file_flaky_issue_and_pr.
Potentially helps with https://github.com/flutter/flutter/issues/126604
> Add 1s delay between issue/pr creation

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
https://github.com/flutter/flutter/issues/126825
- Add gradle and groovy to the extensions understood by the comment excluder for test exempt then add tests for all languages
> Teach comment analysis about gradle/groovy comments

- app_dart/lib/src/model/ci_yaml/target.dart
- app_dart/test/model/ci_yaml/target_test.dart
This is not needed as the logic has been switched to osx_sdk: https://flutter-review.googlesource.com/c/recipes/+/43980
> Cleanup devicelab_osx_sdk property

- codesign/lib/src/file_codesign_visitor.dart
Remove codesign metadata after parsing them.
Context: fix https://github.com/flutter/flutter/issues/126705 by removing codesign metadata after parsing them. When https://github.com/flutter/flutter/pull/126875 becomes ready, we could add back codesign metadata inside engine zips?
Sorry for the delay, was busy landing different cps during the day
> [codesign] remove metadata files for now

- dashboard/lib/main.dart
- dashboard/pubspec.yaml
As part of https://flutter.dev/go/multiple-views we are deprecating `RendererBinding.pipelineOwner`. This PR migrates the dashboard away from it.
Also includes a bump of `package:collection` to work with the latest master version of Flutter.
> Migrate away from pipelineOwner

- app_dart/lib/src/request_handling/static_file_handler.dart
- app_dart/test/request_handling/static_file_handler_test.dart
Changes were made to switch the file extension for AssetManifest.bin to smcbin which is not a normal file extension and therefore has no associated mimetype. This change can be found here: https://github.com/flutter/flutter/pull/126077
Without this change the dashboard fails to display all icons in the top column above the builds.
With the added mimetype the icons are present.
https://github.com/flutter/flutter/issues/127038 …
> Add the mimetype for smcbin file extension

- auto_submit/lib/validations/ci_successful.dart
- auto_submit/test/requests/github_webhook_test_data.dart
- auto_submit/test/service/validation_service_test.dart
- auto_submit/test/utilities/mocks.mocks.dart
- auto_submit/test/validations/ci_successful_test.dart
Add support for release/non-default base branches. Autosubmit can now merge pull requests into non-default base branches by ignoring the tree status check. It will still process all other checks as it would if merging into the base branch.
Example merge into base release candidate branch:
Fixes https://github.com/flutter/flutter/issues/126282 …
> Support release branches with Autosubmit

- dashboard/web/index.html
Statically serving the canvaskit.wasm file compressed results in a 1.5 MB download instead of 5 MB download when serving from  https://flutter-dashboard.appspot.com/
[CLA]: …
> Statically serve the canvaskit.wasm compressed for faster download

- device_doctor/lib/src/ios_debug_symbol_doctor.dart
- device_doctor/test/src/ios_debug_symbol_doctor_test.dart
Adding to help debug https://github.com/flutter/flutter/issues/120808.
Currently it does not do anything other than print out the status. In the future, we may want to try a) changing the status or b) opening Xcode based off the status. First, we just want to observe what the status is when tests run.
It's currently piggybacking on the `ios_debug_symbol_doctor.dart diagnose` command. If this is something we want to keep and use, we should rename `ios_debug_symbol_doctor` or make this its own command.
I filed https://github.com/flutter/flutter/issues/127517 to make sure we follow up. …
> Add check for DevToolsSecurity

- cron.yaml
This is a follow up of https://github.com/flutter/cocoon/pull/2725, which scheduled the cronjob as 
```
schedule: every wednesday 9:00,9:30,10:00,10:30,11:00
```
However, we can either schedule using `Sub-daily intervals`:
```
schedule: every 30 minutes from 9:00 to 11:00
```
or schedule using `Custom interval` at a specific time:
```
schedule: every wednesday 9:00
```
Unfortunately we can not schedule mixing these two to run on multiple times within an interval on a specific day. This PR splits the schedule to multiple entries based on the custom internal.
Context: https://cloud.google.com/appengine/docs/legacy/standard/python/config/cronref#defining_the_cron_job_schedule
> Split `file_flaky_issue_and_pr` to multiple cron jobs

- app_dart/lib/src/request_handlers/get_branches.dart
- app_dart/test/request_handlers/get_branches_test.dart
In general master, main branches are really old and filtered out by the current query(filtering out branches older with no activity in the last 60 days).
Bug: https://github.com/flutter/flutter/issues/127452
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breakin …
> Do not filter main or master independently of age.

- app_dart/lib/src/model/ci_yaml/target.dart
- app_dart/test/model/ci_yaml/target_test.dart
Now we are relying solely on `$flutter/osx_sdk` property for xcode related logics. The PR removes logics based on `xcode` or `runtime` properties.
Part of https://github.com/flutter/flutter/issues/127534
> Clean up logics related to xcode/runtime properties

- app_dart/lib/src/model/ci_yaml/ci_yaml.dart
- app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart
- app_dart/test/service/scheduler_test.dart
Sometimes targets are explicitly enabled on release candidate branches and not in main. This PR updates the filtering logic to avoid filtering targets that are not enabled in main.
Bug: https://github.com/flutter/flutter/issues/127496 …
> Do not filter out targets enabled only on release candidate branches.

- device_doctor/pubspec.yaml
- device_doctor/test/src/utils.dart
This is https://github.com/flutter/cocoon/pull/2790 with CI fix.
> Implement `onLevelChanged` to unblock logging version bump

- device_doctor/lib/src/ios_debug_symbol_doctor.dart
- device_doctor/test/src/ios_debug_symbol_doctor_test.dart
This reverts commit 8c093a0194222d421c3c7f928f8b21ec6b923245.
We added a check for `DevToolsSecurity` as sources recommended enabling it could resolve issues like https://github.com/flutter/flutter/issues/120808. However,  after observing the output, it shows `DevToolsSecurity` is already enabled. I observed multiple tests, including ones that errored with before mentioned issue.
Example: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20hot_mode_dev_cycle_ios__benchmark/5298/overview
Fixes https://github.com/flutter/flutter/issues/127517. …
> Revert "Add check for DevToolsSecurity (#2801)"

- app_dart/cloudbuild_app_dart.yaml
- app_dart/cloudbuild_app_dart_deploy.yaml
- auto_submit/cloudbuild_auto_submit.yaml
- auto_submit/cloudbuild_auto_submit_deploy.yaml
- cloud_build/deploy_app_dart.sh
- cloud_build/deploy_auto_submit.sh
* Remove the _GAE_PROMOTE variable, since we don't ever want to promote since we already promote on the line following the deployment
* Brings cocoon closer toward a SLSA 4 requirement of reproducible builds by simplifying the build process and removing a variable that can be changed during the deployment. …
> Remove _GAE_PROMOTE variable in lieu of directly specifying --no-promote

- device_doctor/lib/src/ios_debug_symbol_doctor.dart
- device_doctor/test/src/ios_debug_symbol_doctor_test.dart
- device_doctor/test/src/utils.dart
When a mac CI test times out, delete the device symbols and then open Xcode to allow Xcode to regenerate them.
Part of solution for https://github.com/flutter/flutter/issues/126412#issuecomment-1574304265.
In the long term, should move this logic to https://github.com/flutter/flutter/issues/128123 as explained in https://github.com/flutter/flutter/issues/126412#issuecomment-1574329205. …
> Delete symbols on ios_debug_symbol_doctor recover

- app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
- app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
- app_dart/test/src/utilities/push_message.dart
https://github.com/flutter/flutter/issues/128469
* Retries builds that are cancelled
* Adds a unit test to check for retrying a task on an infra failure
[Discord]: …
> Add retries to builds that are cancelled

- dashboard/lib/main.dart
- dashboard/test/build_dashboard_page_test.dart
Prepare for the change to the default value of `ThemeData.useMaterial3` coming in https://github.com/flutter/flutter/issues/127064. Currently the dashboard's tests depend on the UI being configured for Material2. While we're undergoing this transition, changed the dashboard's MaterialApp and its tests to specify `useMaterial3: false`.
> Updated dashboard: wired down Material2 dependency

- dashboard/lib/widgets/lattice.dart
This removes the _FakeViewport from the build dashboard implementation. It was added in https://github.com/flutter/cocoon/pull/741, and we think it's sole purpose was the preserve the 1D expectations of widgets in the framework like scrollbars and overscroll indicators. Since adding support for 2D in the framework, the framework has been updated so that the fake viewport should no longer be necessary.
All of the tests pass, so I think this is safe to remove now that the framework is 2D compatible.
This came up as a test failure in https://github.com/flutter/flutter/pull/128812, where the function signature of getOffsetToReveal is being changed. …
> Remove fake viewport from dashboard

- app_dart/lib/src/model/ci_yaml/ci_yaml.dart
- app_dart/test/model/ci_yaml/ci_yaml_test.dart
Targets with the release_build property are producing release artifacts and when running from release candidate branches it should run exclusively from dart_internal.
Bug: https://github.com/flutter/flutter/issues/128847 …
> Do not run release_build targets using cocoon scheduler.

- dashboard/test/widgets/commit_box_test.dart
- dashboard/test/widgets/task_grid_test.dart
- dashboard/test/widgets/task_overlay_test.dart
- dashboard/test/widgets/user_sign_in_test.dart
Updated all of the golden image file tests in dashboard/test/widgets to specify `useMaterial3: false` to ensure that the images continue to match when the default for useMaterial3 is changed to true.
> Updated dashboard/test/widgets tests to handle useMaterial3:true by default

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
When requests are made to the webhook_subscription there is one method that when called is disposing of the github client. In the _checkForTests methods it calls dispose on the github client which closes the connection while it is still in scope. This is the only part of the code that does this. This was killing the client for any pull request event for edited, opened, and reopened but not synchronized. 
The fix will be investigated further but this prevents .ci.yaml checks and other issues blocking checkRuns from starting.
Fixes: https://github.com/flutter/flutter/issues/129134 …
> Do not dispose of the client in test check

- auto_submit/lib/validations/unknown_mergeable.dart
Updating our unknown mergeable check to use the mergeable field instead of mergeable_state as the mergeable state enum is only partially documented in the Graphql API.
https://docs.github.com/en/github-ae@latest/graphql/reference/enums#mergeablestate
Remove ambiguity with the check.
Fixes: https://github.com/flutter/flutter/issues/129636 …
> Update to use mergeable as mergeable_state is only partially documented

- app_dart/lib/src/request_handlers/push_build_status_to_github.dart
- auto_submit/lib/validations/ci_successful.dart
- auto_submit/test/requests/github_webhook_test_data.dart
- auto_submit/test/utilities/utils.dart
- auto_submit/test/validations/approval_test_data.dart
- auto_submit/test/validations/ci_successful_test_data.dart
Part of https://github.com/flutter/flutter/issues/92931
Follow up is to clean up old `luci-flutter`/`luci-engine` names from auto-submit.
> Replacing luci-flutter with tree-status as context name in GitHub presubmit

- packages/buildbucket-dart/CHANGELOG.md
- packages/buildbucket-dart/lib/buildbucket_pb.dart
- packages/buildbucket-dart/pubspec.yaml
Exposing more of the status enums from the protos so we can more easily translate the statuses to github statuses for check runs. …
> Expose buildbucket status enums for easier translation to Github statuses.

- auto_submit/lib/validations/ci_successful.dart
This is a follow up of https://github.com/flutter/cocoon/pull/2875, and fixes: https://github.com/flutter/flutter/issues/92931
The new tree status has been populated:
> Remove legacy tree statuses from auto-submit

- app_dart/lib/src/request_handlers/flaky_handler_utils.dart
- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/check_flaky_builders_test_data.dart
- app_dart/test/request_handlers/file_flaky_issue_and_pr_test_data.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
- auto_submit/test/validations/ci_successful_test.dart
`team: flakes`, `severe: flake` -> `c: flake`
`needs tests` -> removed
`tech debt` -> `c: tech debt`
> Update cocoon code for new label conventions

- auto_submit/lib/requests/check_pull_request.dart
- auto_submit/lib/requests/check_request.dart
- auto_submit/lib/requests/check_revert_request.dart
- auto_submit/lib/requests/github_webhook.dart
- auto_submit/lib/service/config.dart
- auto_submit/test/requests/check_pull_request_test.dart
The goal of this refactor is to made the coming work of separating the revert class much easier. This refactor will allow us to separate the checks for pull requests and revert pull requests to separate endpoints within autosubmit before ultimately separating them to individual services.
Add the revert queue topic and subscription and make several of the static pubsub variables in the Config class non static as getters because these fields are not inheritable.
Part of https://github.com/flutter/flutter/issues/113867
If you need help, consider asking for advice on the #hackers-new …
> Refactor the Autosubmit PullRequestCheck class so it can support multiple methods

- app_dart/lib/src/model/luci/push_message.dart
- app_dart/lib/src/request_handlers/dart_internal_subscription.dart
- app_dart/lib/src/service/config.dart
- app_dart/test/request_handlers/dart_internal_subscription_test.dart
* Now that buildbucket is publishing the results instead of within the recipes, this PR updates how we handle buildbucket results based on the updated publishing format
* Remove the retry on the buildbucket client now that we can correctly handle builds that are in progress
* Add new tests
[breaking …
> Update dart-internal-build-results-sub to different pubsub message format

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
The label is actually called `c: flake`.
> `c: flakes` was a typo

- app_dart/pubspec.yaml
- app_dart/test/service/datastore_test.dart
bump grpc 3.2.2 -> 3.2.3 manually
Fixes issue encountered in roller: https://github.com/flutter/cocoon/pull/2931 …
> Bump GRPC and use const in test

- app_dart/lib/src/model/appengine/task.dart
In the Task object when we are converting statuses LUCI has a 'scheduled' status that we do not check for and as a result when we go to process the result is it null which throws a 400 error and causes to not acknowledge or update the build status. We report this as a warning but it returns a 400 BadRequest error.
Part of https://github.com/flutter/flutter/issues/131192 …
> Encountering scheduled tasks causes 400 error

- app_dart/lib/src/model/appengine/task.dart
- app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
- app_dart/test/model/task_test.dart
- app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
- app_dart/test/src/utilities/entity_generators.dart
Fixes: https://github.com/flutter/flutter/issues/131419
1) Does not change task status when build hasn't started
2) Updates datastore only when task status changes
3) Adds tests
> Skip post-submit task status update when build hasn't started

- app_dart/lib/src/service/datastore.dart
- dashboard/pubspec.yaml
See https://github.com/flutter/flutter/issues/131310 for a detailed explanation of the problem this fix addresses. The main culprit was a change made to the Appengine dependency we use that added retries in the background.
Fixes https://github.com/flutter/flutter/issues/131192
[test-exempt]: …
> Remove retries datastore from our Datastore service wrapper

- app_dart/lib/src/service/datastore.dart
- app_dart/test/request_handlers/push_gold_status_to_github_test.dart
- app_dart/test/service/datastore_test.dart
Clean up from https://github.com/flutter/cocoon/pull/2954 to remove the function as it's no longer used.
> [app_dart] Remove DatastoreService.runTransactionsWithRetries

- app_dart/lib/src/model/appengine/task.dart
- app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
- app_dart/test/model/task_test.dart
- app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
This PR fixes a couple of things:
1) skips task updates for build `scheduled` case
a) All tasks will be marked as `in progress` whenever scheduled. This skips the 400 errors: `Failed to process Instance of 'PushMessage'. (400) null is unknown`
b) This skips datastore updates when a `scheduled` message comes after a `completed` message. Our pub/sub subscriber was created with `Message ordering: Disabled`, and we need to make sure [`idempotency`](https://en.wikipedia.org/wiki/Idempotence#Computer_science_meaning) from our consumer side.
2) skips task updates for task which has already finished
3) Removes the buggy logic to reset task status as `New`. 
4) Adds explicit task status in log before and after the update.
Helps: https://github.com/flutter/flutter/issues/131192
> Fix datastore task update for post-submit builds

- app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
- app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
Follow up of https://github.com/flutter/cocoon/pull/2964, which exit early also for the failed case. It causes auto-retry skipped.
This PR reorg the logics and restores the rerun logic back for the failed case.
> Restore auto rerun on failures

- app_dart/lib/src/model/ci_yaml/ci_yaml.dart
- app_dart/test/model/ci_yaml/ci_yaml_test.dart
As flutter-3.13-candidate.0 is promoted to stable the exemption is not needed anymore.
Bug: https://github.com/flutter/flutter/issues/128844
> Remove flutter-3.10-candidate.1 exemption.

- auto_submit/lib/service/revert_request_validation_service.dart
Fix the subscription name when ack'ing a message that we should not process in the revert path. …
> Fix the pubsub subscription in the revert path which can cause ack error

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
- app_dart/test/src/utilities/webhook_generators.dart
I should also note that when I originally wrote the test, my test reported a false positive. This is because the `generateGithubWebhookMessage` utility was using the `master` branch as the default base branch for all repositories, even though some are actually `main` and some are `master`. This fixes that as well, so that the default value for the base branch in the generated webhook messages matches the actual default base branch for the specified repository.
> Treat files of type `*test.py` as test files in the engine repo.

- app_dart/lib/src/request_handlers/github/branch_subscription.dart
- app_dart/lib/src/service/commit_service.dart
Since all github events are passed to this endpoint, but we only care about branch events, add some logging so that we can find information about a specific branch in the log explorer easier. …
> Add some more logging to make it easier to find branches

- cloud_build/get_docker_image_provenance.sh
Cloud build provenance in plain text is not consistent with the base64 payload. This change makes it consistent to pass the validation.
Bug: https://github.com/flutter/flutter/issues/133376 …
> Add work around for provenance generation.

- cloud_build/get_docker_image_provenance.sh
- cloud_build/verify_provenance.sh
The get_provenance script now requires jq but it was not installed until later.
> Move jq installation before the step to get provenance.

- cloud_build/verify_provenance.sh
Somewhat related to https://github.com/flutter/flutter/issues/133376
It seems that occasionally the builds are failing because they are being built on a different version of Cloud Build. This is not actually providing any sort of security since we aren't explicitly specifying the version of cloud build when we trigger it, so instead we can just check that the artifact is built on cloud build at all.
Additionally, remove the hard pinned version of slsa-verifier, as it is already specified and updated by dependabot in the `tooling` folder
[test-exempt]: …
> Remove the hardcoded builder_id version

- app_dart/lib/src/service/commit_service.dart
- app_dart/test/service/commit_service_test.dart
We are getting alert for 500 errors from the /api/github/webhook-branch-subscription endpoint when attempting to insert a commit for a release branch. The issue is with the timestamp presumably being null when we attempt to insert it into the database since it not a field in the return RepositoryCommit in the github lib.
```
"Failed to process Instance of 'PushMessage'. (500) Invalid argument(s): Error while encoding entity (Bad state: Property validation failed for property timestamp while trying to serialize entity of kind Commit. , #0      _ModelDescription._encodeProperty (package:gcloud/src/db/model_db_impl.dart:449:7)
#1      _ModelDescription.encodeModel.<anonymous closure> (package:gcloud/src/db/model_db_impl.dart:429:7)
#2      _LinkedHashMapMixin.forEach …
```
> Update the timestamp field to use the current data in the commit_service class

- app_dart/bin/server.dart
- app_dart/lib/src/request_handlers/presubmit_luci_subscription.dart
- app_dart/lib/src/service/github_checks_service.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/request_handlers/presubmit_luci_subscription_test.dart
- app_dart/test/service/github_checks_service_test.dart
- app_dart/test/service/luci_build_service_test.dart
- app_dart/test/src/service/fake_scheduler.dart
- app_dart/test/src/utilities/mocks.mocks.dart
Fixes: https://github.com/flutter/flutter/issues/126556
This PR does:
1) retry failures only once
2) retry failures only when that happen under roller accounts
3) inject `user_login` to `user_data` to help identify the user
4) inject `retry: true` to a build's tags when this is a retry to avoid unlimited rerunning
/cc @zanderso
> Auto retry presubmit failures from rollers

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/lib/src/service/config.dart
- app_dart/test/src/datastore/fake_config.dart
We consistently get 500 errors when checking for commits on GoB. This is most likely due to some latency so adding a retry for up to a second should help in reducing the number of 500 errors we see from this.
Fixes https://github.com/flutter/flutter/issues/134146
[Flutter …
> Add a retry for checking for the GoB commit after PR merged

- CI_YAML.md
- app_dart/bin/server.dart
- app_dart/lib/src/request_handlers/presubmit_luci_subscription.dart
- app_dart/lib/src/service/github_checks_service.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/request_handlers/presubmit_luci_subscription_test.dart
- app_dart/test/service/github_checks_service_test.dart
- app_dart/test/service/luci_build_service_test.dart
- app_dart/test/src/service/fake_scheduler.dart
- app_dart/test/src/utilities/mocks.mocks.dart
Reland of https://github.com/flutter/cocoon/pull/3018.
The only difference is documentation about the property: `presubmit_max_attempts`.
The blocking bug is fixed: https://github.com/flutter/flutter/issues/134438
> Auto rerun presubmit

- app_dart/pubspec.yaml
- app_dart/test/service/datastore_test.dart
The dependabot update was blocked by an analyzer fix.
> Update grpc dependency.

- dashboard/lib/build_dashboard_page.dart
New link copied from "The CI infrastructure used by Flutter has a problem" on https://github.com/flutter/flutter/issues/new/choose.
> Fix link to file bugs

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/lib/src/service/commit_service.dart
- app_dart/test/service/commit_service_test.dart
- app_dart/test/src/utilities/mocks.mocks.dart
- app_dart/test/src/utilities/webhook_generators.dart
https://github.com/flutter/flutter/issues/134746
* The github `Push` event has discrepancies to other similar objects sent and returned by Github, which was causing the automatic conversion from json to fail. Instead of adding more bloat to the github package through adding extensions of objects, use a map since there are only a few values we need from the webhook.
[CLA]: …
> Fix push handling by removing the PushEvent in favor of Map

- dashboard/lib/build_dashboard_page.dart
- dashboard/lib/logic/qualified_task.dart
- dashboard/lib/service/dev_cocoon.dart
Fixes https://github.com/flutter/flutter/issues/133622
Release branches are generic to the repos. Remove the legacy check for the specific repo, which is no longer returned.
Updated the fake data to properly reflect the expected state.
> [dashboard] Show release branches regardless of repo

- auto_submit/lib/model/auto_submit_query_result.dart
- auto_submit/lib/model/auto_submit_query_result.g.dart
- auto_submit/test/src/validations/fake_approval.dart
- auto_submit/test/src/validations/fake_mergeable.dart
- auto_submit/test/src/validations/fake_required_check_runs.dart
- auto_submit/test/src/validations/fake_validation_filter.dart
Add supporting fake classes for testing and a new field for the autosubmit query result.
Part of https://github.com/flutter/flutter/issues/113867
[CLA]: …
> Automatic Revert (Part 3): Add supporting test files for the automatic revert feature

- app_dart/bin/server.dart
- app_dart/lib/src/request_handlers/github_webhook.dart
- app_dart/lib/src/service/config.dart
- app_dart/test/request_handlers/github_webhook_test.dart
- app_dart/test/src/datastore/fake_config.dart
b/238326337 - Google Testing isn't receiving related "rerequested" check run events.
Adding this here, and we'll create dedicated FROB pubsubs for that application instead of reusing the flutter-dashboard events.
> [app_dart] Add FRoB Webhook endpoint

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/lib/src/service/config.dart
- app_dart/test/src/datastore/fake_config.dart
Reverts flutter/cocoon#3042
Fixes https://github.com/flutter/flutter/issues/135518
This was preventing messages from being processed as if copybara is latent we can get in a loop of retrying for the commit while blocking reprocessing from pubsub. This will result in unacked messages and will cause them to be retried on exponential backoff.
Removing the retry we can see that the unacked messages are being retried now as we are not passing the ack deadline.
> Revert "Add a retry for checking for the GoB commit after PR merged"

- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/scheduler_test.dart
Fixes: https://github.com/flutter/flutter/issues/131501, https://github.com/flutter/flutter/issues/127138
When a new target is created, it should not be scheduled before its configs rolled to LUCI (via ciyaml_roller). Currently these new targets are treated same way as any other existing targets, and will just hang forever.
This PR skips scheduling all `bringup: true` targets from `webhook` side. This way:
1) newly created targets will not be scheduled before configs ready (avoid hanging forever)
2) existing `bringup: true` targets will be covered by backfiller scheduling.
> Skip scheduling `bringup: true` from webhook

- auto_submit/lib/configuration/repository_configuration.dart
- auto_submit/lib/configuration/repository_configuration_manager.dart
- auto_submit/lib/git/git_repository_manager.dart
- auto_submit/test/configuration/repository_configuration_manager_test.dart
This is a fix to the way the default branch is collected. The code was wrongly checking for if the default branch was empty after the config was collected. It was never empty because a default value of main was assigned so that was used each time.
This changes the default branch to have a default value of 'default' and then we check against that value to get true default branch from the repo.
Example pull request of the fix: https://github.com/flutter/flutter/pull/135692
Fixes https://github.com/flutter/flutter/issues/135670
If you need help, consider asking for advice on the …
> Revert not correctly collecting default branch

- app_dart/lib/src/request_handlers/presubmit_luci_subscription.dart
- app_dart/test/request_handlers/presubmit_luci_subscription_test.dart
Occasionally we hit an issue where we cannot get an element from the ciYaml and then cannot update an existing task in presubmit. This implies that we found none or more than one task. This log message will let us know which it is if hit again.
Related to https://github.com/flutter/flutter/issues/135640
[test-exempt]: …
> Adding a log for builders found vs build name in presubmit subscription

- app_dart/lib/src/service/github_checks_service.dart
- app_dart/test/service/github_checks_service_test.dart
Part of https://github.com/flutter/flutter/issues/132616.
This PR updates checkrun based on the one generated via check_run_id from build.user_data, instead of gets all detailed checkrun by calling the API.
The motivation is reduce API quota use.
> Skip get check run API call when updating check runs

- app_dart/lib/src/service/github_checks_service.dart
This fixes the issue with https://github.com/flutter/flutter/issues/132616#issuecomment-1761973681.
Checkrun's start time is the build created time.
> Use build createdTimestamp for checkrun start time

- cipd_packages/device_doctor/lib/src/utils.dart
- cipd_packages/device_doctor/test/src/utils_test.dart
This is to fix a problem with brew binaries being installed in different locations with new versions of brew.
Bug: https://github.com/flutter/flutter/issues/136587
[Discord]: …
> Support multiple different locations for binary paths.

- cipd_packages/device_doctor/lib/src/android_device.dart
Adding an additional wait, since we experienced a package manager not ready error.
Bug:flutter/flutter#135035 …
> Adding a wait for device ready before deleting packages.

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
Issue: https://github.com/flutter/flutter/issues/135991
This is pulling the logic over from https://github.com/flutter/cocoon/pull/3005 that got accidentally removed, and adding it into the webhook_subscription class instead. …
> Create a new commit in the datastore on branch creation for candidate branches

- app_dart/lib/src/service/scheduler.dart
- app_dart/lib/src/service/scheduler/policy.dart
- app_dart/test/service/scheduler/policy_test.dart
- app_dart/test/service/scheduler_test.dart
Fixes: https://github.com/flutter/flutter/issues/136487
Context:
https://github.com/flutter/cocoon/pull/3108 skipped scheduling bringup: true targets from webook for all repos
https://github.com/flutter/cocoon/pull/3139 restores scheduling bringup:true targets for guranteed policy repos (engine/pacakges)
With above two PR patches, we still hit https://github.com/flutter/flutter/issues/136487
This PR proposes a more concise way to solve via priority control.
1) restores the above two PRs
2) returns `null` priority when existing number of tasks < `kBatchSize`.
> Fix scheduling issue via priority control for new targets

- cipd_packages/device_doctor/lib/src/android_device.dart
The filters were incorrect and given that we are alredy getting only the list of third_party apps we are removing the unnecessary filter.
Bug: https://github.com/flutter/flutter/issues/135035 …
> Remove all third_party apps in recovery mode.

- dashboard/android/app/src/main/kotlin/com/example/dashboard/MainActivity.kt
This keeps the screen saver from coming on when you leave the dashboard running on a TV
> Keep screen awake on Android

- app_dart/lib/src/request_handlers/github_rate_limit_status.dart
Part of https://github.com/flutter/flutter/issues/132616.
This is to help triage and prepare for alert setup in GCP.
> Add log warning when GitHub API usage exceeds half of the limit

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
* `impeller/fixtures` contains only test fixtures.
* `impeller/golden_tests` contains a test harness for goldens.
* `impeller/playground` contains a test harness that spawns Impeller backends. Also used for capturing goldens.
Patch where this was noticed: https://github.com/flutter/engine/pull/47781 …
> Make Impeller test harnesses + fixtures test exempt in the engine repo.

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
The current engine rules are the reverse of the framework and packages repos; those assume that any file that has not been explicitly exempted needs tests, whereas the engine only requires tests for a specific set of files. This is prone to false negatives (e.g., if/when we start adding Swift files, someone would have had to remember to come update this rule, which probably wouldn't have happened).
This flips the engine to be consistent with the other repositories. This will almost certainly cause a lot of false positives in the short term while the set of files that should be exempted is worked out.
Also fixes a bug where the removal-only case was only being applied to Dart files, not other languages. …
> Default engine to requiring tests

- app_dart/lib/src/foundation/utils.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/scheduler_test.dart
Closes https://github.com/flutter/flutter/issues/138430 and I believe https://github.com/flutter/flutter/issues/111418.
As @CaseyHillers mentions in https://github.com/flutter/flutter/issues/138430, this would _not_ be sufficient to understand the addition of a label (only if the PR is _first created_ with a label, or a commit is pushed after the label is added), but it might be worth merging as-is (assuming I got all of the assumptions correct).
> Add a feature that allows treating `presubmit: false`  as `true`, conditionally.

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
Everything in `/ci/licenses_golden/` in the engine repo should be test-exempt.
> Add license goldens to the engine test exclusion list

- auto_submit/lib/service/config.dart
- auto_submit/lib/validations/approval.dart
- auto_submit/test/validations/approval_test.dart
Example of the current bot comment:
>auto label is removed for flutter/flutter/138973, due to This PR has not met approval requirements for merging. You are not a member of flutter-hackers and need 1 more review(s) in order to merge this PR.
>
>Merge guidelines: You need at least one approved review if you are already part of flutter-hackers or two member reviews if you are not a flutter-hacker before re-applying the autosubmit label. Reviewers: If you left a comment approving, please use the "approve" review action instead.
This message is confusing when the person adding the "autosubmit" label is not the author of the PR (which is common in the case that the author is not a regular contributor), because the use of 'you' can be interpreted as 'the person who added the label'.
Context …
> Change autosubmit comment from 'You' to 'The PR author'

- app_dart/lib/src/service/branch_service.dart
- app_dart/test/service/branch_service_test.dart
- app_dart/test/src/service/fake_github_service.dart
temporary fix before the next beta is pushed.
when branch version file such as https://github.com/flutter/flutter/blob/beta/bin/internal/release-candidate-branch.version isn't available, show error in the branch selection drop down of flutter dashboard, instead of popping up snackbar errors.
context: https://github.com/flutter/flutter/issues/138755, https://github.com/flutter/flutter/issues/138738, https://github.com/flutter/flutter/issues/138747
> [dashboard] show error in dropdown and suppress snackbar error when branch file 404

- dashboard/pubspec.yaml
For future ease of issue resolution, this change pins google_sign_in_web to the latest version rather than using `any`. Dependabot will be able to bump versions moving forward 
Related to: https://github.com/flutter/flutter/issues/139382
[CLA]: …
> Pin google_sign_in_web

- dashboard/pubspec.yaml
These pins otherwise prevent us from rolling the pins in the Flutter SDK because this is a a presubmit test for that repo.
- also, cleanup boilerplate comments
- also, add breadcrumbs for the next person who wonders how these dependencies roll
- also, alphabetize the dependencies
> Unpin dependencies that are pinned by the Flutter SDK

- cipd_packages/codesign/lib/src/file_codesign_visitor.dart
- cipd_packages/codesign/test/file_codesign_visitor_test.dart
context: b/311427184
replace codesign credentials in logs with placeholders. 
The log will now look like `this command failed: blah blah ... --apple-id <appleID> --password <appSpecificPassword> --team-id <teamID> ... blah blah` instead of printing the literal passwords.
refactored test to be more stable and reliable.
> [codesign] hide codesign credentials from logs

- auto_submit/lib/validations/ci_successful.dart
- auto_submit/test/validations/ci_successful_test.dart
Following up of https://github.com/flutter/cocoon/pull/3332/files#r1423217355
This PR does:
1) supports engine to framework roller
2) change stale logic to focus on `queued` status. There are cases where GitHub check runs have finished a while ago, and we do not want to trigger alerts for them.
> Flag stale PRs for engine to framework roller

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
Treat [engine `scenario_app`](https://github.com/flutter/engine/tree/main/testing/scenario_app) as a test and do not add needs-test comment.  Example:  https://github.com/flutter/engine/pull/49066#issuecomment-1857181226
Refactor tests, put all the code/test combo checks into one test to reduce boilerplate, otherwise I would have needed to add a new test for the `scenario_app` check.
[CLA]: …
> Engine scenario_app as a test, avoid needs-tests comment

- app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
- app_dart/lib/src/request_handlers/scheduler/vacuum_stale_tasks.dart
- app_dart/test/request_handlers/scheduler/vacuum_stale_tasks_test.dart
- cron.yaml
We should enable the task vaccum process before https://github.com/flutter/flutter/issues/122117 is fixed, especially when there is limited gardener support.
This PR:
1) updates the vacuum logic to be based on `task.status` is `in progress` and `builder` is null, instead of being based on `created time` which caused https://github.com/flutter/flutter/issues/121989.
2) enables as a daily cronjob running 12:00 PST
> Update and reenable periodic task vacuum

- cipd_packages/codesign/lib/src/file_codesign_visitor.dart
- cipd_packages/codesign/pubspec.yaml
- cipd_packages/codesign/test/file_codesign_visitor_test.dart
Fixes https://github.com/flutter/flutter/issues/138636
* Migrate to package:retry instead of hand writing the retry logic
* Enables easily adding exponential backoff
* Minor cleanup
> [codesign] Add additional retries on notarytool commands with exponential backoff

- app_dart/lib/src/request_handlers/update_existing_flaky_issues.dart
- app_dart/test/request_handlers/update_existing_flaky_issues_test.dart
Fixes: https://github.com/flutter/flutter/issues/140886
> Skip priority bump for already bringup true target in Flake Bot

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
For example for PRs like https://github.com/flutter/engine/pull/49776
> Make engine build configs test exempt

- cipd_packages/codesign/lib/src/file_codesign_visitor.dart
- cipd_packages/codesign/test/file_codesign_visitor_test.dart
**context:** 
https://github.com/flutter/flutter/issues/140934
**what I learnt:**
1. out of our current [release bundles downloaded from gcs](https://pantheon.corp.google.com/storage/browser/flutter_infra_release/flutter/4f18bb4dcb99d7e0d94aeff2ffa74e6ddef301cd;tab=objects?authuser=0&project=flutter-infra&prefix=&forceOnObjectsSortingFiltering=false), only Flutter.xcframework is not codesigned. Both FlutterMacOS.framework and Flutter.xcframework/*/Flutter.framework are already codesigned. I will explain in more details on why this happens in bullet point 5 below. <br />
The existing bundles are verified using `codesign --verify --verbose --display <path to codesign bundle>`. 
2. According to Eskimo's reply in [this post](https://developer.apple.com/forums/thread/661852) and [this other …
> [codesign] codesign framework bundle

- dashboard/lib/widgets/sign_in_button/sign_in_button_web.dart
- dashboard/pubspec.yaml
Cocoon's dependabot seems to be ignoring "patch" (`+z`) releases in packages with version < `1.0.0`.
That's caused them to miss [a fix in how the Google Sign In button renders into the app](https://github.com/flutter/packages/pull/5660) that was released as a "patch" version (`0.12.3+1`).
This PR updates the cocoon dependency to the fixed version of the package, so the Google Sign In button renders normally again.
(It also uses a new API introduced in 0.12.3 to access `web_only` components much more easily than before, which allows to remove an intermediate dependency).
* Fixes https://github.com/flutter/flutter/issues/142195 …
> [dashboard] Fix Log-In button not showing up.

- app_dart/lib/src/service/access_client_provider.dart
- app_dart/lib/src/service/config.dart
- app_dart/lib/src/service/firestore.dart
The very first step to support Firestore. Part of https://github.com/flutter/flutter/issues/142951
This PR:
1) Creates a client support with customized header support
2) Adds a basic FirestoreService based on the client
> Initialize Firestore client and service

- app_dart/lib/src/service/firestore.dart
- app_dart/test/service/firestore_test.dart
Follow up of https://github.com/flutter/cocoon/pull/3473.
It turns out that Firestore doesn't accept null/empty values for `integerValue`.
This PR removes the field when adding new tasks. The `builderNumber` field will be added when updating task statuses, where the real build number will be available until then.
Fixes: https://github.com/flutter/flutter/issues/143187
More context: https://github.com/flutter/flutter/issues/142951
> Remove `builderNumber` when adding new tasks

- auto_submit/lib/service/revert_issue_body_formatter.dart
- auto_submit/test/service/revert_issue_body_formatter_test.dart
* Consistent with how GitHub generates revert PRs
* Google testing relies on this to know when a PR was reverted upstream
For Googlers, see b/324342695 which was generated as the PR didn't include the original info.
I'm open to suggestions on a better way of figuring out the original PR from a revert.
> Add original PR number in revert PR title

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
By repo convention, plugins using the shared darwin source structure put unit tests in darwin/Tests/
> Add darwin/Tests/ to packages test pattern

- app_dart/lib/src/model/firestore/task.dart
- app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
- app_dart/lib/src/service/firestore.dart
- app_dart/test/model/firestore/task_test.dart
- app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
- app_dart/test/src/utilities/entity_generators.dart
- app_dart/test/src/utilities/mocks.mocks.dart
This PR
1) creates a Firestore task model
2) adds getDocument and batchWriteDocuments to firestore service
3) starts updating documents in Firestore
4) no op to existing production workflow.
> Start updating post-submit tasks in Firestore

- app_dart/lib/src/model/firestore/task.dart
- app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
- app_dart/lib/src/request_handlers/presubmit_luci_subscription.dart
- app_dart/lib/src/service/github_checks_service.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/model/firestore/task_test.dart
- app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
- app_dart/test/service/luci_build_service_test.dart
- app_dart/test/src/utilities/entity_generators.dart
- app_dart/test/src/utilities/mocks.mocks.dart
- cloud_build/verify_provenance.sh
This PR adds support to save multiple entries for a task retry. Old logic overrides task statuses on a single task, which fails to track statuses.
This PR:
1) makes it customizable to collect `attempts` info
2) adds `current_attempt` tag to make it easy to track `attempts` info.
3) handles `attempt` increase when retry is triggered.
> Support multiple records for retries on a same task

- cloud_build/verify_provenance.sh
Mistakenly merged in https://github.com/flutter/cocoon/pull/3494. This PR restores the URL.
> Restore deploy repo url

- auto_submit/lib/validations/ci_successful.dart
- auto_submit/test/validations/ci_successful_test.dart
Closes https://github.com/flutter/flutter/issues/143352.
In practice this reverts the functionality in https://github.com/flutter/flutter/issues/123979 (https://github.com/flutter/cocoon/pull/2585). Sorry for the back-and-forth, we tried this model but ended up with (currently) [~170 untriaged failures](https://flutter-engine-gold.skia.org/), so we want to go back to treating these as failures and improve our tools/process if needed instead.
/cc @jonahwilliams and @Piinks
> Treat `flutter-gold` failures in `flutter/engine` as failures.

- app_dart/lib/src/model/firestore/task.dart
- app_dart/lib/src/request_handlers/update_task_status.dart
- app_dart/lib/src/service/firestore.dart
- app_dart/test/request_handlers/update_task_status_test.dart
- app_dart/test/service/firestore_test.dart
- app_dart/test/src/utilities/mocks.mocks.dart
This is a follow up of https://github.com/flutter/cocoon/pull/3495.
This PR:
1) updates the latest task status correctly when multiple records exist
2) uses const variables to avoid potential typos
> Update Firestore task when mulitple reruns exist

- app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
- app_dart/lib/src/service/firestore.dart
- app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart
- app_dart/test/service/firestore_test.dart
This PR starts updating task documents in Firestore when batch back filling tasks.
> Update Firestore task documents when back filling

- app_dart/lib/src/request_handlers/reset_prod_task.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/request_handlers/reset_prod_task_test.dart
- app_dart/test/service/luci_build_service_test.dart
This PR:
1) inserts new task document to Firestore when retried manually
2) fixes `trigger_type` tag: instead of overriding manual case as `trigger_type: auto`, we now distinguish them with
2.1) `trigger_type: manual_retry` for manual retry
2.2) `trigger_type: auto_retry` for auto retry
> Update Firestore when reseting a prod task

- app_dart/lib/src/model/firestore/github_build_status.dart
- app_dart/lib/src/model/firestore/github_gold_status.dart
- app_dart/lib/src/request_handlers/push_build_status_to_github.dart
- app_dart/test/model/firestore/github_build_status_test.dart
- app_dart/test/request_handlers/push_build_status_to_github_test.dart
- app_dart/test/src/utilities/entity_generators.dart
This PR:
- starts updating Github Build Status to Firestore
- updates status in a try block to avoid breaking prod workflow
- creates a corresponding Firestore model
> Write github build status to Firestore

- cipd_packages/ktlint/tools/build.sh
In https://github.com/flutter/cocoon/pull/3522 I landed a `build.sh` which uses `curl` with the output
```
-o $DIR/../build/ktlint/
```
I didn't know `-o` is intended to target the output file, not directory (both the file and the directory in this case are named ktlint). Hence the warning:
```
Warning: Failed to create the file 
Warning: /b/s/w/ir/x/w/cocoon/cipd_packages/ktlint/tools/../build/ktlint: Is a 
Warning: directory
```
Changes to `-o $DIR/../build/ktlint/ktlint` …
> Fix the outpit directory for ktlint

- app_dart/lib/src/model/firestore/commit.dart
- app_dart/lib/src/model/firestore/github_gold_status.dart
- app_dart/lib/src/model/firestore/task.dart
- app_dart/lib/src/request_handlers/dart_internal_subscription.dart
- app_dart/lib/src/request_handlers/reset_prod_task.dart
- app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
- app_dart/lib/src/request_handlers/scheduler/vacuum_stale_tasks.dart
- app_dart/lib/src/service/commit_service.dart
- app_dart/lib/src/service/firestore.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/model/firestore/commit_test.dart
- app_dart/test/model/firestore/github_gold_status_test.dart
- app_dart/test/model/firestore/task_test.dart
- app_dart/test/request_handlers/reset_prod_task_test.dart
- app_dart/test/service/commit_service_test.dart
- app_dart/test/service/firestore_test.dart
- app_dart/test/src/utilities/entity_generators.dart
This PR doesn't add new functionalities, but refactor logics to closer to data models.
1) moves task `variables` and `functions` from `firestore.dart` to `firestore/task.dart`.
2) moves commit `variables` and `functions` from `firestore.dart` to `firestore/commit.dart`.
3) moves github gold status `variables` and `functions` from `firestore.dart` to `firestore/github_gold_status.dart`.
4) updates related reference points from other places.
> Refactor to move logics closer to data models

- app_dart/lib/src/model/firestore/github_gold_status.dart
- app_dart/test/model/firestore/github_gold_status_test.dart
This is to make it consistent with old datastore logic: for each pr of a repo, we keep a single record.
Namely, this PR replaces the following entries into a single one.
> Use repository and prNumber as goldstatusstatus document name

- app_dart/lib/src/model/firestore/github_gold_status.dart
- app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
- app_dart/lib/src/service/firestore.dart
- app_dart/test/request_handlers/push_gold_status_to_github_test.dart
- app_dart/test/src/utilities/entity_generators.dart
- app_dart/test/src/utilities/mocks.mocks.dart
The github gold status API has been querying and writing updates to Datastore.
https://github.com/flutter/cocoon/pull/3513 started writing updates to Firestore.
This PR:
1) starts querying from Firestore
2) supports both datastore/Firestore queries and writes
3) updates all unit tests to cover Firestore logics
> Switch github gold status API toFirestore

- app_dart/lib/src/service/firestore.dart
- app_dart/test/service/firestore_test.dart
- app_dart/test/src/utilities/mocks.mocks.dart
This is to prepare switching get-build-status queries to firestore.
This PR:
1) add function queryRecentCommits
2) add query option: `orders` and `limit`.
> Query recent commits from firestore

- app_dart/lib/src/request_handlers/get_build_status.dart
- app_dart/lib/src/request_handlers/get_green_commits.dart
- app_dart/lib/src/request_handlers/get_status.dart
- app_dart/lib/src/request_handlers/push_build_status_to_github.dart
- app_dart/lib/src/service/build_status_provider.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/request_handlers/get_green_commits_test.dart
- app_dart/test/request_handlers/get_status_test.dart
- app_dart/test/request_handlers/push_build_status_to_github_test.dart
- app_dart/test/service/build_status_provider_test.dart
- app_dart/test/service/scheduler_test.dart
- app_dart/test/src/service/fake_build_status_provider.dart
This is to prepare query logics switch to Firestore. 
This PR is a no op for existing workflow, but just inject the firestore service to prepare for future logic updates.
> Support Firestore in build status service

- app_dart/lib/src/service/build_status_provider.dart
- app_dart/lib/src/service/firestore.dart
- app_dart/test/service/build_status_provider_test.dart
- app_dart/test/src/service/fake_build_status_provider.dart
This PR:
1) keeps existing function `retrieveCommitStatus` and creates a new `retrieveCommitStatusFirestore` for `get_build_status` API. This is to avoid affecting other APIs.
2) keeps existing class `CommitStatus` and creates a new `CommitTasksStatus` to support firestore case, preparing to deprecate the `stage` field from the old Task status.
3) maps to the firestore commit/task fields from old Datastore models and updates all related tests.
> Calculate tree build status based on Firestore task statuses

- app_dart/lib/src/model/firestore/github_build_status.dart
- app_dart/lib/src/request_handlers/push_build_status_to_github.dart
- app_dart/lib/src/service/firestore.dart
- app_dart/test/request_handlers/push_build_status_to_github_test.dart
- app_dart/test/src/utilities/entity_generators.dart
- app_dart/test/src/utilities/mocks.mocks.dart
The github build status API has been querying and writing updates to Datastore.
This PR:
- starts querying from Firestore
- supports both datastore/Firestore queries and writes
- updates all unit tests to cover Firestore logics
> Push build status based on Firestore

- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/service/luci_build_service_test.dart
To migrate postsubmit build API fully to firestore, we need to support user data servicing firestore data models. This PR adds corresponding document names.
> Support Firestore user data for postsubmit build

- app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
- app_dart/test/service/luci_build_service_test.dart
Following https://github.com/flutter/cocoon/pull/3583, this PR:
1) switches logics to use firestore task
2) keeps querying/writing task status for both Datastore and Firestore, in case fallback happens
3) updates all unit tests
4) removes the condition when `taskKey` doesn't exist (seems all builds are enforced with the `userData`, and confirmed no call for the past week)
> Switch to use firestore task for postsubmit_luci_subscription API

- app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
Follow up of https://github.com/flutter/cocoon/pull/3584 to fix the query document name.
> Fix document name when querying Firestore tasks

- app_dart/lib/src/model/appengine/task.dart
- app_dart/lib/src/model/firestore/task.dart
- app_dart/lib/src/request_handlers/reset_prod_task.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
- app_dart/test/request_handlers/reset_prod_task_test.dart
- app_dart/test/service/luci_build_service_test.dart
This PR:
1) supports `taskDocumentName` arg for reset-prod-task API. This is to prepare frontend logic switched to Firestore
2) uses Firestore data when checking rerun, instead of Datastore data
3) moves `taskFailStatusSet` to Task models
4) moves Firestore logics out of try/catch block to break API if failing
> Use Firestore data when reseting prod task and rerunning a build

- app_dart/lib/src/service/scheduler.dart
This is to resolve issues:
1) data mismatch between datastore and firestore when LUCI schedule fails
2) postsubmit-luci-scheduler failures if LUCI schedules a task before the data is saved to firestore
> Save commit/tasks to firestore first before scheduling LUCI builds

- app_dart/lib/src/service/github_checks_service.dart
This is to identify where the summary output is getting garbled.
Bug: https://github.com/flutter/flutter/issues/143162
> Add logging for the checks update output.

- app_dart/lib/src/service/github_checks_service.dart
The logs showed that once the output is sent to the checkrun update is already garbled. We need to see the state of the data from LUCI and also after the summary.
Bug: https://github.com/flutter/flutter/issues/143162 …
> Add more logs to identify where summary gets garbled.

- app_dart/lib/src/service/buildbucket.dart
- app_dart/test/service/buildbucket_test.dart
Dart uses latin1 encoding by default instead of utf-8 causing garbled output in summary markdown. This change send the proper headers to get utf-8 from server and decode utf from bytes before passing it to the json decoder.
Bug: https://github.com/flutter/flutter/issues/143162
[breaking change …
> Use utf-8 encoding on getbuild requests.

- dashboard/lib/model/commit_firestore.pb.dart
- dashboard/lib/model/commit_firestore.pbenum.dart
- dashboard/lib/model/commit_firestore.pbjson.dart
- dashboard/lib/model/commit_firestore.pbserver.dart
- dashboard/lib/model/commit_firestore.proto
- dashboard/lib/model/commit_tasks_status.pb.dart
- dashboard/lib/model/commit_tasks_status.pbenum.dart
- dashboard/lib/model/commit_tasks_status.pbjson.dart
- dashboard/lib/model/commit_tasks_status.pbserver.dart
- dashboard/lib/model/commit_tasks_status.proto
- dashboard/lib/model/task_firestore.pb.dart
- dashboard/lib/model/task_firestore.pbenum.dart
- dashboard/lib/model/task_firestore.pbjson.dart
- dashboard/lib/model/task_firestore.pbserver.dart
- dashboard/lib/model/task_firestore.proto
This is to prepare frontend firestore migration for Cocoon dashboard.
One can view https://github.com/flutter/cocoon/pull/3619 for a quick reference how we are gonna to use these protos.
This PR adds:
- commit_firestore.proto, a replacement of commit.proto for Datastore case
- task_firestore.proto, a replacement of task.proto for Datastore case
- commit_tasks_status.proto, a replacement of commit_status.proto for Datastore case
Note: *.pb.dart, *.pbenum.dart, *.pbjson.dart, *.pbserver.dart are auto generated based on the proto.
> Add firestore data model protos

- dashboard/lib/service/appengine_cocoon.dart
- dashboard/lib/service/cocoon.dart
- dashboard/lib/service/dev_cocoon.dart
- dashboard/test/service/appengine_cocoon_test.dart
- dashboard/test/utils/appengine_cocoon_test_data.dart
This is part of https://github.com/flutter/flutter/issues/142951
This PR adds logics to fetch commit tasks status from Firestore based on newly added Firestore data model protos. After this lands, next step is to switch the build logic to reference this PR's changes from Datastore.
This PR is a no-op change by this point.
> Add logics to fetch commit status from Firestore

- app_dart/lib/cocoon_service.dart
- app_dart/lib/server.dart
- app_dart/lib/src/model/firestore/commit.dart
- app_dart/lib/src/model/firestore/commit_tasks_status.dart
- app_dart/lib/src/model/firestore/task.dart
- app_dart/lib/src/request_handlers/get_status_firestore.dart
- app_dart/lib/src/service/build_status_provider.dart
- app_dart/test/model/firestore/commit_tasks_status_test.dart
- app_dart/test/model/firestore/commit_test.dart
- app_dart/test/model/firestore/task_test.dart
- app_dart/test/request_handlers/get_status_firestore_test.dart
- app_dart/test/src/service/fake_build_status_provider.dart
- app_dart/test/src/utilities/entity_generators.dart
- dashboard/lib/service/appengine_cocoon.dart
This PR adds api entry point for `api/public/get-status-firestore`. This is prepare frontend migration to Firestore.
This change is a no-op, as the frontend is still calling `api/public/get-status`.
> Add API `api/public/get-status-firestore`

- app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
- app_dart/lib/src/service/config.dart
- app_dart/pubspec.yaml
- app_dart/test/request_handlers/push_gold_status_to_github_test.dart
issue: https://github.com/flutter/flutter/issues/146078
This starts running skia gold bot checks on release branches for the engine.  This works for the engine because our infrastructure forks all gold tests when a release branch is created.
See also:
- https://github.com/flutter/engine/tree/main/testing/skia_gold_client#release-testing …
> Adds skia gold to engine release branches.

- app_dart/lib/src/model/firestore/task.dart
- app_dart/test/model/firestore/commit_tasks_status_test.dart
- app_dart/test/model/firestore/task_test.dart
The `CommitSha` field was missed, and this PR adds it.
> Add commit sha to Firestore task facade

- dashboard/lib/main.dart
Closes https://github.com/flutter/flutter/issues/145849.
This was originally added by Casey so he could use some Chrome extension to navigate the dashboard (https://github.com/flutter/cocoon/pull/1729), but it appears to cause serious problems for mouse-users.
I've filed https://github.com/flutter/flutter/issues/147881 for the web team to take a look.
> Remove semantics from the cocoon dashboard.

- auto_submit/lib/service/config.dart
- auto_submit/test/service/config_test.dart
Current autosubmit failures appear to be related to unexpected responses from GitHub, which currently aren't handled. This adds logging when responses don't have the exepcted data, and a specific exception that higher levels could handle (instead of uninitialized `late` variables). …
> Add logging of failed GitHub requests in Config

- auto_submit/lib/service/config.dart
- auto_submit/test/service/config_test.dart
- auto_submit/test/service/config_test_data.dart
Instead of querying all installations and looking for the one owned by a specific user, use the endpoint that allows requesting the installation for a specific user. This avoids issues with pagination, as well as making the logic for processing the result simpler.
Fixes https://github.com/flutter/flutter/issues/148092 …
> Replace installation query with user-specific version

- app_dart/lib/src/request_handlers/presubmit_luci_subscription_v2.dart
- app_dart/test/request_handlers/presubmit_luci_subscription_v2_test.dart
- app_dart/test/src/service/fake_scheduler_v2.dart
Currently the presubmit LUCI pubsub handler has a couple of un-ACK'd messages because the PR has a ci.yaml that references a builder that was recently removed. The current code to determine whether to retry the job is throwing an uncaught exception when validating the config, causing the handler to return a 500.
This catches that error, and forces the job not to retry, so that the message can be processed. Not retrying is the correct behavior, since it would fail again anway. …
> Fix presubmit retry of missing builder

- triage_bot/lib/engine.dart
We are retiring this team. The triage page has already been updated: https://github.com/flutter/flutter/wiki/Triage/_compare/b3c2e735f20bffbe7c8446d64aa5402d01b66aa3...109352c79d1e9b8e837983c55f16f5352e3d4445
> Remove team-google-testing from triage

- app_dart/lib/src/service/config.dart
- app_dart/test/request_handlers/push_gold_status_to_github_test.dart
issue: https://github.com/flutter/flutter/issues/149670
This will fix the part of the issue where the golden tests weren't run on the release branch.  There is still setup that needs to add GOLDCTL for the release bot. …
> Fixed regex for identifying release branches.

- triage_bot/lib/engine.dart
The team-desktop label is being replaced by the team-linux, team-macos, team-windows labels in triage. This provides a more granular breakdown for issues and makes it easier for a combined iOS/macOS team to triage both, without also needing to wade through Windows and Linux issues.
As per instructions:
https://github.com/flutter/flutter/blob/master/docs/triage/README.md#adding-a-new-team …
> Add macos, linux, windows teams

- app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
- app_dart/lib/src/request_handlers/presubmit_luci_subscription.dart
- app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
- app_dart/test/request_handlers/presubmit_luci_subscription_test.dart
- app_dart/test/src/utilities/build_bucket_messages.dart
- triage_bot/lib/bytes.dart
- triage_bot/lib/discord.dart
- triage_bot/lib/engine.dart
- triage_bot/lib/json.dart
https://chromium.googlesource.com/infra/luci/luci-go/+/refs/heads/main/buildbucket/proto/notification.proto says that some parts of the Buildbucket build proto are stored in a separate compressed field.
This must be merged with the rest of the build proto so that consumers of the build will see fields such as build.input.properties
See https://github.com/flutter/flutter/issues/149851
> Decode BuildsV2PubSub.build_large_fields and merge it with the rest of the build data

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
The sky/tools/*.py files are essentially extensions of our *.gn build files.
> exclude sky/tools python scripts from needing tests

- app_dart/lib/src/request_handlers/test_ownership.dart
See https://github.com/flutter/flutter/pull/152194 where I got befuddling error messages:
```txt
Unhandled exception:
Null check operator used on a null value
#0      DeviceLabTestOwner.getTestOwnership (package:cocoon_service/src/request_handlers/test_ownership.dart:60:59)
#1      getTestOwnership (package:cocoon_service/src/request_handlers/flaky_handler_utils.dart:301:20)
#2      validateOwnership (package:cocoon_service/src/foundation/utils.dart:225:27)
#3      remoteCheck (file:///b/s/w/ir/x/w/cocoon/app_dart/bin/validate_task_ownership.dart:31:40)
<asynchronous suspension>
#4      main (file:///b/s/w/ir/x/w/cocoon/app_dart/bin/validate_task_ownership.dart:63:23)
<asynchronous suspension>
```
> Replace an NPE with a human-readable error message.

- app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
Prerequisite for https://github.com/flutter/engine/pull/53571
> Add mac_unopt to the list of engine builders that push gold status

- app_dart/cloudbuild_app_dart_deploy.yaml
Fix https://github.com/flutter/flutter/issues/152394
Because the slsa-verifier transitively depends on at least go sdk version 1.21
> increase the go docker image version

- app_dart/lib/src/service/config.dart
The github-bot-bot part of https://github.com/flutter/flutter/pull/152402.
The major change, once again, is to clarify that the test exemption group is small and volunteer, and their is a responsibility of the reviewer to enforce our rules and _not_ delegate that to the exception group.
> Clarify that test exemption volunteers are a small volunteer group.

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
This tool is used as a test to verify that clangd workds correctly with compile_commands.json.
This is currently run as a test in these shards:
* [ci/builders/linux_unopt_debug_no_rbe.json](https://github.com/flutter/engine/blob/b192a52072812804f88b4dd1cb75dec418f025af/ci/builders/linux_unopt_debug_no_rbe.json#L30-L40)
* [ci/builders/mac_unopt_debug_no_rbe.json](https://github.com/flutter/engine/blob/b192a52072812804f88b4dd1cb75dec418f025af/ci/builders/mac_unopt_debug_no_rbe.json#L41-L51) …
> Add tools/clangd_check to test exempt paths

- app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
I [added this task a few weeks ago](https://github.com/flutter/flutter/blob/309ae21448521b18a4cc90e3db435089a6dbc3cb/.ci.yaml#L1346-L1356) but forgot to update this allow list.
> Signal `flutter-gold` when `flutter_driver_android_test` runs.

- cipd_packages/codesign/lib/src/file_codesign_visitor.dart
- cipd_packages/codesign/test/file_codesign_visitor_test.dart
This patch:
* Fixes incorrect logging of the without_entitlements.txt content.
* extracts an enum of code-signing types rather than passing as a boolean, which will allow us to add `CodesignType.unsigned` in a followup patch.
* Renames some identifiers to focus on code-signing rather than entitlements, for readability.
* Improves doc comments.
Issue: https://github.com/flutter/flutter/issues/154571 …
> iOS,macOS: Refactor code-signing code, fix logging

- test_utilities/bin/dart_test_runner.sh
Currently on a failed run due to unformatted dart code, the output looks like:
######### dart format #########
Formatted lib/src/file_codesign_visitor.dart
Formatted 10 files (1 changed) in 0.65 seconds.
In the face of this output, my natural inclination would be to run
dart format path/to/file
but that would be incorrect. What would be correct would be to locate our CI test script, read the code, and discover that we format to a width of 120 characters, then format with those args. 
Instead, we now inform the user of the args directly in the test output to save them some digging.
Also checks to see the user actually supplied an argument to the script and if not, emits an error message and usage info then fails, rather than silently running  `pushd ""`, resulting in no change to PWD, then …
> dart_test_runner: output expected dart format args

- cipd_packages/codesign/lib/src/file_codesign_visitor.dart
- cipd_packages/codesign/test/file_codesign_visitor_test.dart
This updates the code-signing workflow to account for iOS and macOS binaries in the artifact cache that are _expected_ to not be codesigned.
In https://github.com/flutter/engine/pull/54414 we started bundling dSYM (debugging symbols) within Flutter.xcframework, a requirement for App Store verification using Xcode 16.
We did the same for macOS in https://github.com/flutter/engine/pull/54696.
Unlike the framework dylib, dSYM contents are not directly codesigned (though the xcframework containing them is). This skips code-signing for files found in `unsigned_binaries.txt`, which will be added in a followup patch to the framework artifact archive creation scripts in engine:
* `sky/tools/create_ios_framework.py`
* `sky/tools/create_macos_framework.py`
Issue: …
> iOS,macOS: Skip codesigning files in unsigned_binaries.txt

- cipd_packages/codesign/lib/src/file_codesign_visitor.dart
- cipd_packages/codesign/test/file_codesign_visitor_test.dart
Also cleans up a few more hard-coded filenames and adds more tests.
Also clarified `entitlementsPlist` rather than `entitlementsFile` since we have several things that could legitimately be called entitlements files.
Issue: https://github.com/flutter/flutter/issues/154571
[CLA]: …
> iOS,macOS: Clean up unsigned_binaries.txt

- dashboard/lib/logic/task_grid_filter.dart
- dashboard/lib/main.dart
- dashboard/lib/widgets/task_icon.dart
- dashboard/test/logic/task_grid_filter_test.dart
- dashboard/test/widgets/task_grid_test.dart
- dashboard/test/widgets/task_icon_test.dart
Update the dashboard so "mokey" and "pixel_7pro"  tasks are filtered/iconed as Android.  https://github.com/flutter/flutter/issues/148085
For example, `Linux_mokey old_gallery__transition_perf` should show up in the dashboard as an Android test, but its icon and filtering counts it as a Linux test:
Also fix two unrelated warnings. …
> Filtered Android tasks should include mokey and pixel 7 pro in dashboard

- dashboard/lib/build_dashboard_page.dart
- dashboard/test/build_dashboard_page_test.dart
- dashboard/test/logic/task_grid_filter_test.dart
Related https://github.com/flutter/flutter/pull/155072
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#handling-breaking-changes …
> Remove `ThemeData.dialogBackgroundColor` usage

- dashboard/test/logic/task_grid_filter_test.dart
This fixes a failure in flutter/tests when running `dart fix apply` + `dart format . --line-length=120`
Found in https://github.com/flutter/tests/pull/413 …
> Fix format and dart fix results

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
The templates are tested in https://github.com/flutter/flutter/blob/main/packages/flutter_tools/test/commands.shard/permeable/create_test.dart by creating and analyzing them, so any issue with changed dependencies or pubspec format would be caught.
> Mark `flutter create` pubspec templates as test exempt

- app_dart/lib/src/service/scheduler.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
Because the MQ only waits for "required" checks to pass before merging PRs and merge groups, at least one required check is needed that stays in pending state while all other (non-required) checks pass. Required checks cannot be added dynamically. They are pre-configured in the repositories settings. The "CI tasks" check is that one pre-configured required check whose status is used as a proxy for "the status of all other checks".
> add a required "CI tasks" check that locks the merge queue

- auto_submit/lib/model/auto_submit_query_result.g.dart
- auto_submit/lib/model/big_query_pull_request_record.g.dart
- auto_submit/lib/requests/graphql_queries.dart
- auto_submit/lib/service/pull_request_validation_service.dart
- auto_submit/lib/service/revert_request_validation_service.dart
- auto_submit/lib/service/validation_service.dart
- auto_submit/test/service/pull_request_validation_service_test.dart
- auto_submit/test/service/revert_request_validation_service_test.dart
- auto_submit/test/utilities/mocks.mocks.dart
Use https://docs.github.com/en/graphql/reference/mutations#enqueuepullrequest to land PRs in MQ-enabled repos.
> Implement enqueuing of pull requests for MQ-enabled repos

- auto_submit/lib/requests/graphql_queries.dart
`enqueuePullRequest` does not return a pull request. Remove it from the return schema.
> remove output queries unsupported by enqueuePullRequest

- app_dart/.vscode/settings.json
- app_dart/bin/gae_server.dart
- app_dart/bin/local_server.dart
- app_dart/bin/validate_scheduler_config.dart
- app_dart/integration_test/validate_all_ci_configs_test.dart
- app_dart/lib/server.dart
- app_dart/lib/src/foundation/utils.dart
- app_dart/lib/src/model/ci_yaml/ci_yaml.dart
- app_dart/lib/src/model/proto/internal/scheduler.proto
- app_dart/lib/src/request_handlers/check_flaky_builders.dart
- app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart
- app_dart/lib/src/request_handlers/flaky_handler_utils.dart
- app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
- app_dart/lib/src/request_handlers/presubmit_luci_subscription.dart
- app_dart/lib/src/request_handlers/reset_prod_task.dart
- app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
- app_dart/lib/src/request_handlers/update_existing_flaky_issues.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/model/ci_yaml/ci_yaml_test.dart
- app_dart/test/request_handlers/check_flaky_builders_test.dart
- app_dart/test/request_handlers/file_flaky_issue_and_pr_test.dart
- app_dart/test/request_handlers/update_existing_flaky_issues_test_data.dart
- app_dart/test/server_test.dart
- app_dart/test/service/scheduler/graph_test.dart
- app_dart/test/service/scheduler_test.dart
- app_dart/test/src/service/fake_scheduler.dart
- app_dart/test/src/utilities/entity_generators.dart
CiYaml now tracks one or more ci.yaml files in a fusion tree
CiYamlInner is the old CiYaml. Instead of merging or updating protobufs to know which target are engine targets and which are framework targets; keep them apart. We'll have to use this information later when scheduling engine builds first and waiting before we can schedule the test runs.
The fusion-engine-ciyaml will need to be updated to include paths; that needs to be added to the merge script.
- Downloading a ci.yaml path should respect the path requested
- Only adding the ability to find targets; scheduling to follow this PR.
The `settings.json` file has only the dart line length specified; which should be a shared setting between all developers as it is enforced by CI.
> Scheduler ci yaml merge

- auto_submit/lib/requests/graphql_queries.dart
- auto_submit/lib/service/validation_service.dart
- auto_submit/test/service/pull_request_validation_service_test.dart
This is a speculative fix for `enqueuePullRequest` internal error:
```
OperationException(linkException: null, graphqlErrors: [GraphQLError(message: Could not resolve to a node with the global id of '2157301061', locations: [ErrorLocation(line: 2, column: 3)], path: [enqueuePullRequest], extensions: null)])"
```
It's unclear what "global id of '2157301061'" is and where it comes from (we're not passing it). The hypothesis in this PR is that perhaps Github is failing to lookup the `expectedHeadOid` or something in the return value, and so reducing the argument list to just the essential one and not requesting anything to be returned might fix the issue.
> use minimal number of arguments to enqueue PRs

- auto_submit/lib/requests/graphql_queries.dart
It looks like Github doesn't like it when the return payload is completely empty:
```
auto_submit: OperationException(linkException: null, graphqlErrors: [GraphQLError(message: Field must have selections (field 'enqueuePullRequest' returns EnqueuePullRequestPayload but has no selections. Did you mean 'enqueuePullRequest { ... }'?), locations: [ErrorLocation(line: 2, column: 3)], path: [mutation EnqueueFlutterPullRequest, enqueuePullRequest], extensions: {code: selectionMismatch, nodeName: field 'enqueuePullRequest', typeName: EnqueuePullRequestPayload}), GraphQLError(message: Variable $pullRequestId is declared by EnqueueFlutterPullRequest but not used, locations: [ErrorLocation(line: 1, column: 1)], path: [mutation EnqueueFlutterPullRequest], extensions: {code: variableNotUsed, …
```
> [mq] add a return payload

- auto_submit/lib/service/validation_service.dart
- auto_submit/test/service/pull_request_validation_service_test.dart
Turns out REST IDs are incompatible with GraphQL IDs, so we need to look up the GraphQL ID and use that in the `enqueuePullRequest` GraphQL mutation.
> [mq] use the graphql ID for graphql mutations

- app_dart/lib/src/service/scheduler.dart
- auto_submit/lib/model/auto_submit_query_result.dart
- auto_submit/lib/model/auto_submit_query_result.g.dart
- auto_submit/lib/requests/check_pull_request.dart
- auto_submit/lib/requests/graphql_queries.dart
- auto_submit/lib/service/graphql_service.dart
- auto_submit/lib/service/pull_request_validation_service.dart
- auto_submit/lib/service/validation_service.dart
- auto_submit/test/service/pull_request_validation_service_test.dart
- auto_submit/test/utilities/utils.dart
A PR stays open while it's in the merge queue because the MQ can eject it back if it doesn't pass tests, so `PullRequestValidationService` can receive pings that would look like a request to validate and merge the PR (it will be all green, reviewed, and have an `autosubmit` label). However, if a PR is already in the merge queue, there's nothing to do. So short-circuit the validation process, do nothing other than print a log message that it happened.
> [mq] do not enqueue already enqueued PRs

- app_dart/lib/src/service/scheduler.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
New name: "Merge Queue Guard"
New description: "This is only here to block the merge queue; nothing to see here in PRs"
> rename "CI Tasks" to "Merge Queue Guard"

- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/scheduler_test.dart
Enables the "Merge Queue Guard" check in all repos. No impact on contribution process is expected. This check should simply pass or fail in tandem with the "ci.yaml validation" check.
> [mq] enable merge queue guard check in all repos

- app_dart/docs/fusion_schduler.md
> Document the scheduler changes for monorepo in cocoon

- auto_submit/lib/service/pull_request_validation_service.dart
- auto_submit/lib/service/validation_service.dart
- auto_submit/test/requests/check_pull_request_test.dart
- auto_submit/test/src/service/fake_graphql_client.dart
Add flutter/flutter to the list of MQ-enabled repos.
> [!IMPORTANT]  
> Deploying this change to production will cause Cocoon to start merging PRs using the merge queue. Therefore, this change needs to be deployed shortly after merge queue is enabled in flutter/flutter "Settings" tab.
> [mq] flutter/flutter will autosubmit using MQ

- app_dart/lib/src/model/firestore/ci_staging.dart
- app_dart/test/model/firestore/ci_staging_test.dart
This is specifically handling the ability of users to re-run tests (e.g. in case of flake or infra failure). We want to make it easier for folks to make progress on a PR by continue to build the engine assets and then running the framework / engine tests.
> Update CiStaging to handle flip-flop of test conclusions

- app_dart/lib/src/service/luci_build_service.dart
The `_createPresubmitScheduleBuild` method does not perform any async work, so it just unnecessarily creates an async gap, and also confuses things by making it look like it does some network/database stuff when it doesn't.
> remove unnecessary async/await

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
The top-level `testing/` directory contains unit test support files. Most of these are test-specific OpenGL/Metal/Vulkan/Software context/surface code. …
> Add test exemption for engine code under testing/*

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
In `GithubWebhookSubscription._isTestExempt` we exempt a collection of directories (in both the framework and the engine) from tests by checking if the filename starts with the directory path. This adds a trailing slash to any such checks.
Since `git` only stores files (not directories), all such paths will include a trailing slash. This avoids accidentally exempting directories such as `impeller/fixtures_that_actually_ship` when we only intended to exempt `impeller/fixtures`. Alright, bad example, but perhaps someday someone would have added something more ambiguous. …
> Add trailing slash to test exemption dir paths

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/lib/src/service/config.dart
- app_dart/lib/src/service/github_service.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
- app_dart/test/src/service/fake_github_service.dart
- app_dart/test/src/utilities/webhook_generators.dart
- auto_submit/lib/service/config.dart
- auto_submit/lib/service/pull_request_validation_service.dart
- auto_submit/test/service/pull_request_validation_service_test.dart
Only remove the autosubmit label if the PR is dequeued.
This is a speculative fix for https://github.com/flutter/flutter/issues/159139
> [mq] remove autosubmit label on dequeue only

- app_dart/lib/src/model/firestore/pr_check_runs.dart
- app_dart/test/model/firestore/pr_check_runs_test.dart
- app_dart/test/src/utilities/entity_generators.dart
Problem: we're hitting some quota on github, typically around check_runs Future problem: merging repos and having engine staging requires more check_runs mapping to PRs, which is a query, check suite look up, and comparison.
This PR setups a solution where were record a new document in firestore that can be queried at each check_run update when we need access to the pull request field.
```
/projects/flutter-dashboard/databases/cocoon/prCheckRuns/
document: <firebase unique id>
pullRequest: json string
slug: json string
sha: string
[*fields]: <string check_run id>: empty string
```
> Query GitHub Less: pull request / check_run map in Firestore

- app_dart/lib/src/model/firestore/pr_check_runs.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/model/firestore/pr_check_runs_test.dart
- app_dart/test/service/luci_build_service_test.dart
- app_dart/test/service/scheduler_test.dart
- app_dart/test/src/utilities/mocks.dart
- app_dart/test/src/utilities/mocks.mocks.dart
Reduces the need to search for PRs by check suite / check runs in a monorepo
> Record & Query PrCheckRuns in luci when scheduling

- app_dart/bin/gae_server.dart
- app_dart/bin/local_server.dart
- app_dart/lib/src/model/firestore/ci_staging.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/model/firestore/ci_staging_test.dart
- app_dart/test/service/luci_build_service_test.dart
- app_dart/test/src/service/fake_luci_build_service.dart
1. Don't ask for masked fields - our tests names have spaces and potentially other "regex escaped fields" - instead just get the whole document.
2. Set the 'is_fusion' build property when re/scheduling presubmits
> Tweaks to get Fusion working:

- app_dart/cloudbuild_app_dart.yaml
- auto_submit/cloudbuild_auto_submit.yaml
Even with `-f file`, `.` is still required. Podman didn't have a problem with this.
> Docker fix #2: Docker build requries '.'

- app_dart/lib/src/model/firestore/ci_staging.dart
- app_dart/test/model/firestore/ci_staging_test.dart
Tests didn't catch this because they started with a failure recorded.  Changing the test triggers the failure and then removing the bad code turns it green again.
> CiStaging: record first failure

- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/service/luci_build_service_test.dart
LUCI recipes should set an environment variable to this property if it exists; the Flutter Tool should set the `engine.realm` file as appropriate.
> Fusion presubmits should specify a realm property

- app_dart/lib/src/foundation/utils.dart
- app_dart/lib/src/model/ci_yaml/ci_yaml.dart
- app_dart/test/foundation/utils_test.dart
- app_dart/test/model/ci_yaml/ci_yaml_test.dart
The merge queue uses branches like:
gh-readonly-queue/master/pr-160481-1398dc7eecb696d302e4edb19ad79901e615ed56
This parses the branch and returns the <branch name> expected to match enabled branches.
> Parse github merge queue branches for CI targets

- app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
- app_dart/test/request_handlers/push_gold_status_to_github_test.dart
The flutter-gold check prevents PRs from landing in flutter/flutter or flutter/engine if there are new images that need triage.
It currently does this by having awareness of what checks run golden file tests in these repos. In monorepo world, flutter-gold needs to now cover engine checks in flutter/flutter.
Added a spot for newly added integration test coverage as well. …
> Update checks flutter-gold guards for in monorepo land

- app_dart/lib/src/service/scheduler.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
It was there for testing MQ functionality. We don't need it anymore.
> [tech debt] remove the MQ simulation

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
Upgrade some low noise high signal messages from `fine` level to `info` level, mostly in the merge group area. `log.fine` doesn't show up in GCP logs.
> upgrade some merge group logs from fine to info

- app_dart/bin/generate_jspb.dart
- app_dart/test/generate_jspb_test.dart
This is to support .ci.yaml roller in the monorepo. This is to prepare for this recipe change: https://flutter-review.googlesource.com/c/recipes/+/61680
> Add an optional third argument for a relative path from the root directory.

- app_dart/lib/src/model/github/checks.dart
- app_dart/lib/src/model/github/checks.g.dart
- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
- app_dart/test/src/service/fake_build_bucket_client.dart
- app_dart/test/src/utilities/mocks.mocks.dart
- app_dart/test/src/utilities/webhook_generators.dart
When a PR gets kicked out of the queue, Cocoon will cancel any remaining LUCI builds to free up resources.
> [monorepo] cancel builds after merge group is destroyed

- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
It's totally OK that when we attempt to cancel merge group builds, there aren't any. Some merge groups may still be waiting to be scheduled when the "destroy" message comes in, and there's nothing wrong with that. Warnings would make it seem like something is wrong. So I'm downgrading this to info.
> shout less and explain better empty build list

- app_dart/lib/src/request_handlers/presubmit_luci_subscription.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/service/luci_build_service_test.dart
See flutter/flutter#160704 - Merge Queue builds are postsubmit, they are missing the git_ref but have the gitiles passed along with them. Since MQ uses the presubmit callback for Luci, this wasn't passed along on retries, leading to incorred checkouts and corrupt builds.
Changed logging levels since `fine` doesn't show up.
Added test that failed before and now shows the gitiles passed through.
Extra commas for the dart analyzer.
> Rescheduled merge queue builds must include gitiles

- app_dart/lib/src/model/ci_yaml/ci_yaml.dart
- app_dart/test/model/ci_yaml/ci_yaml_test.dart
- app_dart/test/service/scheduler_test.dart
- cloud_build/dashboard_build.sh
Closes https://github.com/flutter/flutter/issues/160707.
Fixes a bug where `DEPS` was accidentally (or purposefully, there were no tests to verify) not checked for framework builds, and then expands on the validation by adding a check for `engine/**` for framework builds, adding a check nobody uses `runIfNot`, which is extremely broken and should not be used, and then lastly refactors the code and adds tests for the next shmuck to want to change this.
> Fix `.ci.yaml` validation for Fusion (the monorepo)

- app_dart/lib/src/foundation/utils.dart
- app_dart/test/foundation/utils_test.dart
The SHA in the branch name could be accidentally used, and this logic's presence already confused me while I was investigating https://github.com/flutter/flutter/issues/160704. The branch name is not meant to be the source of truth for the actual head SHA that's being tested (that should be the `headSha` of the `merge_group` request). In the spirit of "better safe than sorry", let's remove it for now.
> remove dangerously unused SHA from parsed MQ branch

- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
The old logic was using the presubmit LUCI tags. Prod tags look like this:
We also don't want to grep non-Cocoon jobs, as that would include jobs started manually.
Fixes https://github.com/flutter/flutter/issues/160887
> [monorepo] fix prod job look-up

- dashboard/lib/build_dashboard_page.dart
- dashboard/lib/logic/task_grid_filter.dart
- dashboard/test/logic/task_grid_filter_test.dart
Closes https://github.com/flutter/flutter/issues/160926.
The test explains things better than I can in the PR description.
> Remove filter query parameters that are now default values.

- dev/provision_salt.sh
Part of https://github.com/flutter/flutter/issues/157963
For context: https://saltproject.io/blog/salt-project-package-repo-migration-and-guidance/
> Bump SALT packages to 3006.9 in provision_salt.sh

- app_dart/lib/src/model/firestore/ci_staging.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/model/firestore/ci_staging_test.dart
- app_dart/test/service/scheduler_test.dart
- When `fusionEngineBuild` completes, create a firestore document for the `fusionTests` CI stage tasks.
- When receiving a status update for a test check run, update the respective document.
This PR does not yet alter the MQ guard behavior. I'd like to debug the document behavior first.
Progress towards https://github.com/flutter/flutter/issues/159898
> [monorepo] add CI stage document for tests

- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/scheduler_test.dart
Today if a test check run fails (i.e. one of the post engine build check runs), Cocoon also fails the merge queue guard. This is wrong according to the current semantics of the guard, which is only meant to watch engine build check runs.
Fixes: flutter/flutter#161779
> [monorepo] do not fail merge queue guard on failed fusionTests stage

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
Makes `Test.kt` files count as tests for the purpose of calculating if a PR has tests.
Context: https://github.com/flutter/flutter/pull/161835 …
> Make `Test.kt` files count as tests for the purpose of calculating if a PR has tests

- app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
Shard was renamed in https://github.com/flutter/flutter/pull/162020.
> Add new gold shard names to Flutter Gold.

- app_dart/lib/src/model/firestore/ci_staging.dart
- app_dart/lib/src/service/config.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/model/firestore/ci_staging_test.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
- app_dart/test/service/scheduler_test.dart
- app_dart/test/src/datastore/fake_config.dart
- auto_submit/lib/requests/check_pull_request.dart
- auto_submit/lib/service/config.dart
- auto_submit/lib/service/github_service.dart
- auto_submit/lib/service/process_method.dart
- auto_submit/lib/service/pull_request_validation_service.dart
- auto_submit/lib/service/revert_request_validation_service.dart
- auto_submit/lib/service/validation_service.dart
- auto_submit/lib/validations/ci_successful.dart
- auto_submit/lib/validations/validation_filter.dart
- auto_submit/test/requests/check_pull_request_test.dart
- auto_submit/test/service/pull_request_validation_service_test.dart
- auto_submit/test/service/revert_request_validation_service_test.dart
- auto_submit/test/src/service/fake_config.dart
- auto_submit/test/src/service/fake_github_service.dart
- auto_submit/test/validations/ci_successful_test.dart
Implement the new break glass behavior for the monorepo world.
Fixes https://github.com/flutter/flutter/issues/159898
Fixes https://github.com/flutter/flutter/issues/132811
Below is an updated copy of https://github.com/flutter/flutter/issues/159898#issuecomment-2597209435:
The guard can only be in two states:
- **Pending** (yellow): this is the initial state, and the guard stays in this state for as long as the pull request is not allowed to enter the merge queue.
- **Success** (green): the guard enters this state when the infra decides that the PR is allowed to enter the merge queue.
The state can only go from pending to success. There are no other state transitions.
Going from pending to green is the only transition we need to worry about. This is how we decide it:
- **Normal case**: …
> Break glass v2

- app_dart/lib/src/service/config.dart
Even with 4 PRs in the merge queue (the max); we have several idle
machines. Lets test by using more for the dashboard.
> Increase backfill limit to 100

- app_dart/lib/src/model/firestore/ci_staging.dart
- app_dart/lib/src/service/config.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/model/firestore/ci_staging_test.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
- app_dart/test/service/scheduler_test.dart
- app_dart/test/src/datastore/fake_config.dart
- auto_submit/lib/requests/check_pull_request.dart
- auto_submit/lib/service/config.dart
- auto_submit/lib/service/github_service.dart
- auto_submit/lib/service/process_method.dart
- auto_submit/lib/service/pull_request_validation_service.dart
- auto_submit/lib/service/revert_request_validation_service.dart
- auto_submit/lib/service/validation_service.dart
- auto_submit/lib/validations/ci_successful.dart
- auto_submit/lib/validations/validation_filter.dart
- auto_submit/test/requests/check_pull_request_test.dart
- auto_submit/test/service/pull_request_validation_service_test.dart
- auto_submit/test/service/revert_request_validation_service_test.dart
- auto_submit/test/src/service/fake_config.dart
- auto_submit/test/src/service/fake_github_service.dart
- auto_submit/test/validations/ci_successful_test.dart
This relands commit b9bd02b1370bb10704ecd904a78a82cd229d0904.
The previous attempt was reverted in https://github.com/flutter/cocoon/pull/4175 because of the suspicion that it was landing PRs with failed checks. However, that suspicion seems to have been wrong. This is what actually happened:
* 12:25PM: @polina-c creates the [PR](https://github.com/flutter/flutter/pull/162106); Cocoon starts testing it and unlocks the Merge Queue Guard after all engine builds are done (old behavior).
* 1:02PM: I deploy the new Cocoon with the new behavior.
* 1:10PM: @polina-c hits the "Merge When Ready" button, and GitHub allows the PR to enter the queue.
GitHub allowed that last action because the guard was already unlocked by the old behavior. It wasn't the new code misbehaving. In fact, this is exactly …
> Break glass v2 (attempt 2)

- app_dart/lib/src/service/scheduler.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
- app_dart/test/service/scheduler_test.dart
1. Remove the fake "Merge queue check" that was used for testing flutter/flaux.
2. Fail the "Merge Queue Guard" when failing to schedule LUCI builds for the merge group (instead of failing the fake).
> fail merge queue guard when failing to schedule merge group

- app_dart/bin/gae_server.dart
- app_dart/bin/local_server.dart
- app_dart/lib/src/foundation/utils.dart
- app_dart/lib/src/service/get_files_changed.dart
- app_dart/lib/src/service/github_service.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/foundation/utils_test.dart
- app_dart/test/service/github_checks_service_test.dart
- app_dart/test/service/scheduler_test.dart
- app_dart/test/src/service/fake_get_files_changed.dart
- app_dart/test/src/service/fake_github_service.dart
- app_dart/test/src/service/fake_scheduler.dart
- app_dart/test/src/utilities/mocks.mocks.dart
Towards https://github.com/flutter/flutter/issues/161462, towards https://github.com/flutter/flutter/issues/162201.
This PR does a few things:
1. Introduces an abstraction, `GetFilesChanged`
2. Codifies "we aren't confident" as `InconclusiveFilesChanged`
3. Refactors the existing implementation into `GithubApiGetFilesChanged`
The intention is no user-facing behavioral changes, but this PR enables:
1. Swapping out the implementation (i.e. to `CheckRunArtifactsGetFilesChanged`)
2. Reusing the logic, including inconclusive-ness, for https://github.com/flutter/flutter/issues/162201 (framework-only PRs).
> Inject a `GetFilesChanged` shim instead of using `GithubService` directly.

- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/service/luci_build_service_test.dart
> `flutter_realm` is cleared when  `app_dart/bin/codefu.dart` is set

- app_dart/bin/gae_server.dart
- app_dart/bin/local_server.dart
- app_dart/lib/src/service/get_files_changed.dart
Currently hitting free quota; which fails and falls back to "build everything"
There wasn't any tests for `GithubApiGetFilesChanged`, but we'd only verify one api was called over another.
> Use the authenticated client when requested PR files

- app_dart/lib/src/service/config.dart
Without an explanation it's not clear why we pass 8 minutes right after mentioning 10 minutes in the comment.
> explain Github token TTL value

- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/scheduler_test.dart
Unblocks presubmits such as https://github.com/flutter/flutter/pull/162383 without hacks required.
I want to fix this logic properly, but will do that in a follow-up.
> Test for master branch when applying optimization.

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
Log the `labeled` action for `pull_request` event. Know this works will help us determine if the `emergency` logic can be implemented in the `app_dart` rather than `auto_submit`.
> log pull_request/labeled events in app_dart

- app_dart/lib/src/model/appengine/github_build_status_update.dart
- app_dart/lib/src/model/firestore/github_build_status.dart
- app_dart/lib/src/request_handlers/push_build_status_to_github.dart
- app_dart/lib/src/service/build_status_provider.dart
- app_dart/lib/src/service/config.dart
- app_dart/test/request_handlers/push_build_status_to_github_test.dart
- app_dart/test/src/datastore/fake_config.dart
Part of flutter/flutter#162715
Check for PR labels before labeling the "tree status" check.
> Let tree-status be "neutral" for emergency labels

- auto_submit/lib/requests/check_pull_request.dart
Just a readability clean-up:
* Shorter loops
* Break up into methods
* Better log messages
* Better variable names
* Better comments
> clean up check_pull_request.dart

- dev/provision_salt.sh
Resolves https://github.com/flutter/flutter/issues/162630.
Resolves https://github.com/flutter/flutter/issues/157963.
Fixes the provision script for Ubuntu bots.
Diff succeeds on linux-74.
> Fix Ubuntu branch in Device Lab provision script

- auto_submit/lib/helpers.dart
- auto_submit/test/helpers_test.dart
Wrap all handlers in a `LoggingHandler` at the server bootstrap level, so that we catch and log as many uncaught errors as possible.
> [auto_submit] catch and log errors at the root level

- dev/provision_salt.sh
Part of https://github.com/flutter/flutter/issues/157963.
Follow-up patch to fix compilation errors while building the m2crypto wheel on fresh linux hosts:
```
error: subprocess-exited-with-error
× python setup.py bdist_wheel did not run successfully.
│ exit code: 1
╰─> [57 lines of output]
INFO:run_command:running bdist_wheel
INFO:run_command:running build
INFO:run_command:running build_py
INFO:copy_file:copying src/M2Crypto/X509.py -> build/lib.linux-x86_64-cpython-310/M2Crypto
INFO:copy_file:copying src/M2Crypto/m2xmlrpclib.py -> build/lib.linux-x86_64-cpython-310/M2Crypto
INFO:copy_file:copying src/M2Crypto/EC.py -> build/lib.linux-x86_64-cpython-310/M2Crypto
INFO:copy_file:copying src/M2Crypto/RSA.py -> build/lib.linux-x86_64-cpython-310/M2Crypto
INFO:copy_file:copying …
```
> Install m2crypto wheel dependencies in provision script

- app_dart/lib/src/request_handlers/scheduler/scheduler_request_subscription.dart
- app_dart/test/request_handlers/scheduler/scheduler_request_subscription_test.dart
When LUCI complains there isn't a builder, instead of leaving dangling check runs - fail them.
Fixes flutter/flutter#163869
> Fail unscheduled CheckRuns

- app_dart/lib/src/service/config.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/scheduler_test.dart
- app_dart/test/src/datastore/fake_config.dart
- app_dart/test/src/utilities/entity_generators.dart
No need to use up quota when the PR already says it has changed 30 or more files.
Also took the opportunity to code the check in as a config file if we ever want to tweak it.
> Avoid a REST API call to github when the `PR.changedFilesCount` >= 30.

- app_dart/lib/src/service/scheduler.dart
- app_dart/test/model/firestore/pr_check_runs_test.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
- app_dart/test/request_handlers/push_build_status_to_github_test.dart
- app_dart/test/service/scheduler_test.dart
- app_dart/test/src/utilities/entity_generators.dart
This reverts commit fc543f1837abaeb8bfb8aa68be95bc5c731e8b8e.
This is causing errors when presubmit CI jobs try to download the Dart SDK from a URL that is missing the "flutter_archives_v2" realm.
> Revert "Always set `FLUTTER_PREBUILT_ENGINE_VERSION` for framework-stage PRs. (#4254)"

- app_dart/lib/src/service/luci_build_service/build_tags.dart
- app_dart/test/service/build_tags_test.dart
Towards https://github.com/flutter/flutter/issues/164242.
After this PR merges, I'll do a follow-up that changes `luci_build_service.dart`, but didn't want to stomp on your changes.
> Deobsfucate what a `BuildTag` is by using concrete types (part 1).

- app_dart/lib/src/request_handlers/reset_prod_task.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/lib/src/service/luci_build_service/build_tags.dart
- app_dart/test/service/build_tags_test.dart
- app_dart/test/src/utilities/mocks.mocks.dart
Towards https://github.com/flutter/flutter/issues/164242.
It's also obvious the previous logic was flawed for `checkRerunBuilder`, regardless of (initially) putting `manual_retry`, it always got immediately replaced with `auto_retry`. I'm not sure which one is correct, please LMK.
> Update `checkRerunBuilder` to use `BuildTagSet`.

- app_dart/lib/src/model/github/checks.dart
- app_dart/test/model/github/hooks_tostring_test.dart
Addresses this wonderful log:
```txt
Failed to process Instance of 'PushMessage'. (500) Failed to process check_run event. checkRunEvent: Instance of 'CheckRunEvent'
```
> Add meaningful `toString` to some objects we log.

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
We now search for a previous comment; so we'll be limited to 1 on the PR. To keep things consistent, leave a comment even if the MQG was already unlocked
> Leave comment, even if the MQG is already completed

- cipd_packages/ktlint/ktlint_metadata.txt
Required for flutter/flutter/issues/164408. 
Discovered when trying to use ktlint in https://github.com/flutter/flutter/pull/164409
current code is a text file with "not found" https://chrome-infra-packages.appspot.com/p/flutter/ktlint/linux-amd64/+/PGscrVjJsPjl_CqtUV6kKH-JBNvGVlIKY9BnHpko6SIC 
can be verified by running `curl -L https://github.com/pinterest/ktlint/releases/download/1.5.0/ktlint  -o ktlint` vs `curl -L https://github.com/pinterest/ktlint/releases/download/1.5/ktlint  -o ktlint`
> Update ktlint_metadata.txt to use 1.5.0 since 1.5 returns "not found"

- app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/lib/src/service/luci_build_service/pending_task.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/luci_build_service_test.dart
- app_dart/test/service/scheduler_test.dart
- app_dart/test/src/utilities/mocks.mocks.dart
No behavioral changes, but `pending.target` is much nicer to read and write than `pending.first` and nasty generics.
> Refactor `Tuple<Target, Task, int>` as `PendingTask`.

- app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
- app_dart/lib/src/request_handlers/presubmit_luci_subscription.dart
- app_dart/lib/src/service/github_checks_service.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
- app_dart/test/request_handlers/presubmit_luci_subscription_test.dart
- app_dart/test/service/github_checks_service_test.dart
- app_dart/test/service/luci_build_service_test.dart
- app_dart/test/src/utilities/mocks.mocks.dart
Before:
> Be me
> Pass a `Map<String, Object?>` around
> Check a key, and just `return false` with a log message if it wouldn't work, even though it was documented as required
After:
- Pass around exactly what is needed from `userData`
- Don't silently fail if we require data
- Update the tests that were "benefiting" from this by omitting required data
I don't _imagine_ this is a breaking change, but I'll monitor error logs tomorrow I guess?
> Be more explicit about required parameters, `userData`, and correct tests.

- app_dart/lib/src/service/luci_build_service.dart
I.e. often before triggering new builds
This reduces warning+ level spam, such as [here](https://pantheon.corp.google.com/logs/query;cursorTimestamp=2025-03-05T01:31:50.869Z;duration=PT30H;query=resource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22default%22%0Aseverity%3E%3DWARNING%0Atimestamp%3D%222025-03-05T01:31:52.349Z%22%0AinsertId%3D%22kmk1sf5kqd0p%22?project=flutter-dashboard).
> Do not treat `no builds were found` as a warning case, we cancel builds aggressively

- app_dart/lib/src/service/luci_build_service.dart
- app_dart/lib/src/service/luci_build_service/user_data.dart
- app_dart/lib/src/service/luci_build_service/user_data.g.dart
- app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
- app_dart/test/service/luci_build_service/user_data_test.dart
- app_dart/test/service/luci_build_service_test.dart
Towards https://github.com/flutter/flutter/issues/164568.
The only potentially user-visible change is removing `firestore_commit_document_name` which appears unused outside of tests. 
These new `UserData` classes will replace `Map<String, Object?>` in a future PR.
> Refactor `UserData`->`Presubmit.*`+`Postsubmit.*`, remove unused key.

- app_dart/lib/src/service/branch_service.dart
- app_dart/test/service/branch_service_test.dart
- dashboard/lib/build_dashboard_page.dart
- dashboard/lib/service/dev_cocoon.dart
- dashboard/test/service/appengine_cocoon_test.dart
- dashboard/test/utils/appengine_cocoon_test_data.dart
Closes https://github.com/flutter/flutter/issues/164726.
It turns out `HEAD`, as defined, did nothing, and was really just ignored (by both the UI and backend), so trying to make it do something broke stuff. I thought about adding a UI regression test, but there isn't (really) a way to know it would work (or not), so settled for a note in a backend regression test.
> Use `master` as both the channel and branch name.

- app_dart/lib/src/service/luci_build_service.dart
Closes https://github.com/flutter/flutter/issues/164593.
> Verified we still want to check for `fuchsia.*` branches.

- app_dart/lib/src/service/config.dart
Currently, this message is often the first thing new contributors (who are not familiar with our processes) see, telling them to ask for a test exemption in Discord. This results in a lot of people asking for exemptions on PRs that are clearly not exempt, and that any reviewer would tell them to add tests for, putting an unnecessary burden on the small number of exemption reviewers.
This moves the section about requesting an exemption to the paragraph targeted for reviewers, to try to encourage the desired outcome of having exemption requests happen only once reviewers have agreed that it should be exempt.
> Reword the missing test bot comment

- app_dart/lib/src/service/luci_build_service.dart
There is no reason to log a warning.
> Move from warning to info for max retries.

- app_dart/lib/src/request_handlers/scheduler/vacuum_stale_tasks.dart
- app_dart/lib/src/service/firestore.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
- app_dart/test/request_handlers/scheduler/vacuum_stale_tasks_test.dart
- app_dart/test/request_handlers/vacuum_github_commits_test.dart
- app_dart/test/service/scheduler_test.dart
- app_dart/test/src/utilities/mocks.mocks.dart
Closes https://github.com/flutter/flutter/issues/144733.
Also rewrote the test suite to be understandable by humans.
> Migrate vacuum stale tasks from datastore to firestore.

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/lib/src/service/scheduler/process_check_run_result.dart
- app_dart/test/service/scheduler_test.dart
Closes https://github.com/flutter/flutter/issues/165018.
This splits the possible result states of `processCheckRuns` into:
- Success (previously: `true`)
- User error (previously: `false`), where we don't log an exception/error but return a `400` to the user
- Internal error (previously: `false`), where we log an exception/stack trace and return a `500` to the user
> Don't treat `.ci.yaml` validation errors as an `InternalServerError`

- app_dart/lib/src/request_handlers/scheduler/vacuum_stale_tasks.dart
- app_dart/lib/src/service/firestore.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
- app_dart/test/request_handlers/scheduler/vacuum_stale_tasks_test.dart
- app_dart/test/request_handlers/vacuum_github_commits_test.dart
- app_dart/test/service/scheduler_test.dart
- app_dart/test/src/utilities/mocks.mocks.dart
Reverts flutter/cocoon#4323.
This was not a safe change, I updated both the read _and_ writes of `vacuum-stale-tasks`, meaning that datastore is no longer having task status updated. We can only change the write layer after _all_ (applicable) read layers have been updated to exclusively use Firestore, which in many cases, will just mean "update all read layers first to avoid accidentally missing something".
Mitigates https://github.com/flutter/flutter/issues/165282.
> Revert "Migrate vacuum stale tasks from datastore to firestore."

- app_dart/lib/src/service/scheduler/ci_yaml_fetcher.dart
- app_dart/test/service/scheduler/ci_yaml_fetcher_test.dart
Closes https://github.com/flutter/flutter/issues/165433.
I believe this restores the [logic we had before](https://github.com/flutter/cocoon/pull/4333/files#diff-44d26c271d034096ac3f0506b7400724ed6dd135aaff3b443ef628880a21457e) that I accidentally broke.
> Use `Config.defaultBranch` for tip-of-tree `.ci.yaml`.

- app_dart/lib/src/model/appengine/task.dart
- app_dart/lib/src/request_handlers/rerun_prod_task.dart
- app_dart/test/request_handlers/rerun_prod_task_test.dart
- dashboard/lib/build_dashboard_page.dart
- dashboard/lib/service/appengine_cocoon.dart
- dashboard/lib/service/cocoon.dart
- dashboard/lib/service/dev_cocoon.dart
- dashboard/test/build_dashboard_page_test.dart
- dashboard/test/service/appengine_cocoon_test.dart
- dashboard/test/utils/mocks.mocks.dart
Closes https://github.com/flutter/flutter/issues/165572.
This allows re-running tasks that otherwise would not be re-run, but behind a flag (argument) that otherwise is not set.
Included validation/tests on both the frontend and backend.
> Include skipped tasks in `rerun-prod-task`.

- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/scheduler_test.dart
- dashboard/tool/update_goldens_from_luci.dart
Closes https://github.com/flutter/flutter/issues/165662.
The check run was cute but it now means we need to filter out re-run attempts on it.
Given we'll probably move away from check runs (and use a dashboard), this seems fine?
> Leave a comment instead of check run.

- app_dart/lib/src/service/config.dart
- app_dart/lib/src/service/get_files_changed.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/scheduler_test.dart
Closes https://github.com/flutter/flutter/issues/161462.
It turns out @jtmcdole  had _accidentally_ fixes fixed by using our `GithubService` wrapper while refactoring, meaning `PaginationHelper` has been used this _entire_ time, and we have been getting the full list of files (since https://github.com/flutter/cocoon/pull/4191 at least), so this can actually be lifted.
In addition, we can just gate the optimization on a specific release branch (to speed up beta/new stables).
> Raise limit to `1000` framework-only files and modern release branches.

- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/scheduler_test.dart
Closes https://github.com/flutter/flutter/issues/165810.
> Pass `PREBUILT_ENGINE` to `release-candidate-branches`.

- app_dart/lib/src/model/firestore/commit_tasks_status.dart
- app_dart/test/model/firestore/commit_tasks_status_test.dart
Closes https://github.com/flutter/flutter/issues/165828.
I assumed `CommitTasksStatus.collateTasks()` worked, but it never did 😢 .
Fixed it, and added some trivial tests to catch the obvious null-check bugs that were crashing.
> Collate tasks correctly for `/api/get-status`.

- app_dart/lib/src/model/firestore/commit_tasks_status.dart
- app_dart/lib/src/model/firestore/task.dart
- app_dart/lib/src/request_handlers/dart_internal_subscription.dart
- app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
- app_dart/lib/src/request_handlers/scheduler/vacuum_stale_tasks.dart
- app_dart/lib/src/service/firestore.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/model/firestore/task_test.dart
- app_dart/test/request_handlers/dart_internal_subscription_test.dart
- app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
- app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart
- app_dart/test/request_handlers/scheduler/vacuum_stale_tasks_test.dart
- app_dart/test/src/utilities/entity_generators.dart
Reverts (fixing-forward) https://github.com/flutter/cocoon/pull/4399.
This time we use `fieldName` instead of `fieldBringup`.
> Attempt 2 - Stop using the (external) field names of Task outside of the Task class 

- app_dart/lib/src/service/scheduler.dart
The goal is not to "block the merge queue". The goal is to test PRs before merging. Updating the description accordingly.
> more useful merge queue guard description

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
- app_dart/test/src/service/fake_github_service.dart
- app_dart/test/src/utilities/webhook_generators.dart
Closes https://github.com/flutter/flutter/issues/166078.
Part 2 of https://github.com/flutter/cocoon/pull/4393.
Before we were returning `5xx` class errors to Cloud PubSub, which means "retry". After this PR, for PRs that are >= 15 minutes old, we check and see "was the corresponding branch deleted", and if it was, we return a `4xx` class error, which will discard the Cloud PubSub message instead.
This reduces the amount of indefinite hops that happens from Cocoon <> Cloud PubSub.
> Avoid retrying deleted branches in the Merge Queue handler

- app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
- app_dart/test/request_handlers/push_gold_status_to_github_test.dart
- dashboard/test/widgets/task_grid_test.dart
- dashboard/test/widgets/task_overlay_test.dart
Gold can return multiple patchsets for the same commit. We need to sum the untriaged images of all of them, otherwise based on the exact ordering we can miss golden diffs.
> Handle duplicate gold patchsets.

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/lib/src/request_handling/request_handler.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/lib/src/service/scheduler/process_check_run_result.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
- app_dart/test/request_handlers/scheduler/process_check_run_result_test.dart
Closes https://github.com/flutter/flutter/issues/166272.
Closes https://github.com/flutter/flutter/issues/166285.
Two major changes:
- Use a 503 (service unavailable) to denote GoB has not synced yet (expected to happen)
- Don't silently overwrite all `response.statusCode` to `HttpStatus.ok`...
> Fix Cloud PubSub never getting a non-200 status code.

- app_dart/lib/src/model/firestore/ci_staging.dart
- app_dart/lib/src/model/firestore/commit.dart
- app_dart/lib/src/model/firestore/github_build_status.dart
- app_dart/lib/src/model/firestore/github_gold_status.dart
- app_dart/lib/src/model/firestore/task.dart
- app_dart/lib/src/request_handlers/get_green_commits.dart
- app_dart/lib/src/request_handlers/get_status.dart
- app_dart/lib/src/service/build_status_provider.dart
- app_dart/lib/src/service/build_status_provider/commit_tasks_status.dart
- app_dart/test/request_handlers/get_green_commits_test.dart
- app_dart/test/request_handlers/get_status_test.dart
- app_dart/test/service/commit_tasks_status_test.dart
- app_dart/test/src/service/fake_build_status_provider.dart
Towards https://github.com/flutter/flutter/issues/166229.
This makes it easier to remember where these models are stored in a NoSQL path than looking it up each time on Firebase. Also moved a "model" that was not actually serialized and stored in Firestore out of the `model` directory.
> Move `commit_tasks_status`, explain `documentId` path Firestore models

- app_dart/bin/gae_server.dart
Closes https://github.com/flutter/flutter/issues/166345.
Without this change, the server fails to startup.
> Set `hierarchicalLoggingEnabled` to disable `neat_cache` logs properly.

- app_dart/lib/src/service/luci_build_service.dart
- packages/cocoon_server/lib/firestore.dart
- packages/cocoon_server/test/firestore_test.dart
Fixes a regression due to https://github.com/flutter/cocoon/pull/4398, which is over a week ago and does not revert cleanly.
The underlying issue is https://github.com/flutter/flutter/issues/166229, where we are trying to derive fields from `document.name` (such as `<Task>.attempts`), which in turn causes contortions for insertion logic (we want to _start_ with an existing Task, and then edit the attempt number, and then insert the new task).
> Ignore `<Document>.name` when inserting a new document.

- dashboard/lib/service/appengine_cocoon.dart
- dashboard/lib/service/dev_cocoon.dart
- dashboard/test/service/appengine_cocoon_test.dart
- dashboard/test/utils/generate_commit_for_tests.dart
- dashboard/test/widgets/commit_box_test.dart
- dashboard/test/widgets/task_grid_test.dart
- dashboard/test/widgets/task_overlay_test.dart
Towards https://github.com/flutter/flutter/issues/165025.
When we remove `commit.proto`, it will be a nightmare to change all mutable properties to a constructor call.
Nearly all of these happen in tests, so let's just change them now.
> Remove usages of Commit().. across dashboard.

- app_dart/lib/src/model/firestore/ci_staging.dart
- app_dart/lib/src/model/firestore/task.dart
- app_dart/lib/src/request_handlers/get_green_commits.dart
- app_dart/lib/src/request_handlers/get_status.dart
- app_dart/lib/src/service/build_status_provider.dart
- app_dart/lib/src/service/build_status_provider/commit_tasks_status.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/model/firestore/ci_staging_test.dart
- app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
- app_dart/test/service/commit_tasks_status_test.dart
- app_dart/test/service/luci_build_service_test.dart
- app_dart/test/service/scheduler/policy_test.dart
- app_dart/test/service/scheduler_test.dart
- app_dart/test/src/utilities/mocks.dart
- app_dart/test/src/utilities/mocks.mocks.dart
Towards https://github.com/flutter/flutter/issues/166229.
After this PR, _new_ documents inserted store each field explicitly, instead of relying on the hack-y "store the field delimited by `_` in `name` and parse it".  This allows us to do queries, both for administrative purposes, and for business logic, and, once we backfill, simplify some of our logic (for example, we won't need special keys, and can use the default Firestore unique keys).
(We should probably do the backfill on like, the weekend)
> Add synthetic fields that are missing from Firestore.

- app_dart/lib/src/model/firestore/task.dart
- app_dart/test/model/firestore/task_test.dart
Closes https://github.com/flutter/flutter/issues/166581.
> Revert `TaskId.parse` usage causing errors, add a warning log.

- app_dart/lib/src/request_handlers/dart_internal_subscription.dart
See https://github.com/flutter/flutter/issues/166535#issuecomment-2779593051.
> Log `message.data` for `dart-internal-build-results-sub`.

- app_dart/lib/src/model/firestore/base.dart
- app_dart/lib/src/model/firestore/ci_staging.dart
- app_dart/lib/src/model/firestore/commit.dart
- app_dart/lib/src/model/firestore/github_build_status.dart
- app_dart/lib/src/model/firestore/github_gold_status.dart
- app_dart/lib/src/model/firestore/pr_check_runs.dart
- app_dart/lib/src/model/firestore/task.dart
- app_dart/lib/src/request_handlers/push_build_status_to_github.dart
- app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
- app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
This mostly removes a several dozen `fields!` across the codebase.
Also update unnecessary `\w+\?\s+get` getters.
> Simplify `src/model/firestore`, `AppDocument` is-a `Document`.

- app_dart/lib/src/service/firestore.dart
- app_dart/test/service/firestore_test.dart
- app_dart/test/src/service/fake_firestore_service.dart
- app_dart/test/src/service/fake_firestore_service_test.dart
Closes https://github.com/flutter/flutter/issues/165931.
A basic in-memory implementation of Firestore in-so-far it supports `FirestoreService`.
For more advanced use-cases, i.e. `documentsResource().any.possible.api()`, mocking is still required, but for much of our API surface, it now _really_ reads, writes, and updates to an in-memory database that supports queries, filtering, ordering, and a (very basic) transaction.
We can move more code from `.documentsResource()` to `service.something()`, and ensure those are supported by the fake. In a follow-up PR we can start using this in our own tests where appropriate.
No production code changes.
> Implement fakes of `FirestoreService` except `documentsResource()`

- app_dart/lib/src/model/appengine/task.dart
- app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
- app_dart/lib/src/service/datastore.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart
- app_dart/test/service/luci_build_service_test.dart
- app_dart/test/src/utilities/mocks.mocks.dart
... or, make it explicit (`ds.*`) where the change would be too disruptive in a single PR.
> Reduce dependency on type signatures of `ds.Commit` or `ds.Task`

- app_dart/lib/src/service/commit_service.dart
- app_dart/test/service/commit_service_test.dart
Now converting and saving to both stores are distinct operations.
> Split Firestore from Datastore in `CommitService`

- app_dart/lib/src/request_handlers/update_discord_status.dart
- app_dart/test/src/service/fake_firestore_service.dart
The regex for firestore is:
> Unquoted property paths must match regex ([a-zA-Z_][a-zA-Z_0-9]*), and quoted property paths must match regex (`(?:[^`\\]|(?:\\.))+`)
We appear to only have unquoted property paths.
> Remove `\t` from query - update FakeFirstoreService

- app_dart/bin/gae_server.dart
- app_dart/lib/src/service/gerrit_service.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/service/gerrit_service_test.dart
- app_dart/test/service/luci_build_service/cancel_builds_test.dart
- app_dart/test/service/luci_build_service/check_rerun_builder_test.dart
- app_dart/test/service/luci_build_service/find_or_get_builds_test.dart
- app_dart/test/service/luci_build_service/schedule_prod_builds_test.dart
- app_dart/test/src/service/fake_gerrit_service.dart
- app_dart/tool/local_server.dart
- dev/cocoon_code_health/lib/src/checks/do_not_submit_fixme.dart
This PR removes a FIXME, lints for FIXMEs in the future, and fixes the test.
The original test did nothing, because if you write:
```dart
try {
doSomethingThatNeverThrows();
} catch (e) {
expect(e, 'You can literally write anything here');
}
```
The test will always pass. It turns out `GerritService` never retried (or threw) on `.get()` requests.
Fixing this and using a retry-client will also reduce the amount of pub-sub messages we use just to check Gerrit when waiting a few seconds in thread would have been sufficient. In addition did some TLC to `GerritService` and `FakeGerritService` across the repo.
> Refactor `GerritService`, use retries for `GET`s, fix FIXME

- app_dart/lib/src/request_handling/cache_request_handler.dart
- app_dart/pubspec.yaml
- app_dart/test/request_handling/cache_request_handler_test.dart
- app_dart/test/src/request_handling/fake_request_handler.dart
Closes https://github.com/flutter/flutter/issues/166930.
> Store `statusCode` and `reasonPhrase` in `CacheRequestHandler`.

- dashboard/lib/main.dart
- dashboard/lib/src/pages/v2_landing_page.dart
Imagine the following:
```sh
open https://flutter-dashboard.appspot.com/flutter/flutter/1234/presubmit
```
Ok this doesn't do that yet, but it does create a placeholder widget for it at `v2/<owner>/<repo>`.
Also disables Firebase Crashlytics in debug mode, it doesn't work and spams the console.
> Start a `/v2/...` dashboard for an improved Cocoon UI

- app_dart/lib/src/service/gerrit_service.dart
- app_dart/test/service/gerrit_service_test.dart
This API was supposed to be special cased to return `null` instead of throwing.
> Fix a regression in `GerritService.getCommit`.

- app_dart/lib/src/model/firestore/build_status_snapshot.dart
- app_dart/lib/src/request_handlers/update_discord_status.dart
- app_dart/lib/src/service/discord_service.dart
- app_dart/test/request_handlers/update_discord_status_test.dart
- app_dart/test/src/model/_build_status_snapshot.dart
- app_dart/test/src/model/firestore_matcher.dart
- app_dart/test/src/utilities/mocks.mocks.dart
**Give ourselves a model** (I know, I know, but like, I'd prefer to know what's in the database - at some point someone will want to change something or something will break and purely for consistency it's nice to have all of the documents in a single place) and **make the Discord message include more details** (and diff between that and the previous status).
In addition:
1. Stores the failing tasks instead of the raw Discord message, in Firestore.
1. Reset the collection name so that the schemas are not incompatible (can delete the old one after).
Links would be nice, but I'd prefer to just building out a `/v2/flutter/flutter` page that is nice to look at instead.
> Tweak `UpdateDiscordStatus` a bit

- app_dart/lib/src/request_handlers/dart_internal_subscription.dart
- app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
- app_dart/lib/src/request_handlers/scheduler/vacuum_stale_tasks.dart
- app_dart/lib/src/service/commit_service.dart
- app_dart/test/request_handlers/dart_internal_subscription_test.dart
- app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
- app_dart/test/request_handlers/scheduler/vacuum_stale_tasks_test.dart
All of these classes already can just self-wrap `config.db` if needed.
This reduces the amount of work required to rip out Datastore entirely when the time (soon) comes.
> Remove `DatastoreServceProvider` where not needed in services.

- app_dart/lib/src/model/firestore/build_status_snapshot.dart
- app_dart/lib/src/request_handlers/update_discord_status.dart
- app_dart/test/request_handlers/update_discord_status_test.dart
That middle update would be better if it repeated what was still failing.
> Add `still failing: ...` to the Discord tree status update

- app_dart/test/request_handlers/get_green_commits_test.dart
> Remove unused test dependencies from `get_green_commits_test`.

- dev/cocoon_code_health/bin/check.dart
- dev/cocoon_code_health/lib/src/checks.dart
- dev/cocoon_code_health/lib/src/checks/do_not_submit_fixme.dart
- dev/cocoon_code_health/lib/src/checks/use_test_logging.dart
It was accidentally not enabled before (https://github.com/flutter/cocoon/pull/4499), it is now.
> Fix the `FIXME check`, use `git ls-files`.

- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/service/luci_build_service/schedule_try_builds_test.dart
This is effectively an unreachable error case, and does not appear in our logs.
Closes https://github.com/flutter/flutter/issues/166795.
> Makes 'unexpected engineArtifacts' an error.

- auto_submit/pubspec.yaml
- cipd_packages/device_doctor/pubspec.yaml
- dashboard/pubspec.yaml
Closes https://github.com/flutter/flutter/issues/167322.
There is no (good) reason to pin this package, it's an indirect dependency used by Mockito only.
> Remove pinned `package:analyzer`.

- app_dart/lib/src/service/firebase_jwt_validator.dart
- app_dart/pubspec.yaml
- app_dart/test/service/firebase_jwt_validator_test.dart
- app_dart/test/src/service/fake_firebase_jwt_validator.dart
Towards flutter/flutter#167006
Moving to firebase_auth on the dashboard requires the backend to accept the JWT coming from Firebase now. Firebase Admin SDK has support for "validateToken" - but the SDK is not available to dart. This solves that.
FirebaseJwtValdiator does:
1. Signature checking with jose / firebase public keys
2. validate all claims mentioned https://firebase.google.com/docs/auth/admin/verify-id-tokens#verify_id_tokens_using_a_third-party_jwt_library
> Add firebase jwt validator

- app_dart/lib/src/service/scheduler.dart
Mitigates `Could not reschedule checkRun ... not found in list of presubmit targets` running over and over.
> Do not echo/retry "could not reschedule checkRun".

- app_dart/bin/gae_server.dart
- app_dart/lib/src/request_handling/dashboard_authentication.dart
- app_dart/test/request_handling/dashboard_authentication_test.dart
- app_dart/test/src/request_handling/fake_dashboard_authentication.dart
- app_dart/tool/local_server.dart
Towards flutter/flutter#167006
1. Break up DashboardAuthentcationProvider in to specific providers.
2. Extend that list to [cron, googlesignin, firebase]
> Hook in FirebaseJwt to dashboard authentication

- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/service/luci_build_service/schedule_prod_builds_test.dart
At the moment, the ability to re-run prod tasks does not work (work gated on finishing the Firestore migration), and as such, we need the ability for `engine.version` files to work in post-submit so that there is a reliable way to test, otherwise it is not reasonably feasible (without hacking on the backend).
See https://flutter-dashboard.appspot.com/#/build?repo=flutter&branch=flutter-3.32-candidate.0.
Filed https://github.com/flutter/flutter/issues/167383 to track re-enabling this.
/cc @reidbaker
> Disable passing `FPEV=...` for release candidates for now.

- app_dart/lib/src/service/scheduler.dart
- app_dart/lib/src/service/scheduler/policy.dart
Oops!
This is a mistype that queries by the full document name instead of the name of the task!
> Fix `policy.triggerPriority`

- app_dart/lib/src/service/scheduler.dart
Still crashes on commit without these (otherwise unused) fields.
> Add another inert schema field.

- app_dart/lib/src/request_handlers/rerun_prod_task.dart
- app_dart/lib/src/service/firestore.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/request_handlers/rerun_prod_task_test.dart
- app_dart/test/src/service/fake_firestore_service.dart
Closes https://github.com/flutter/flutter/issues/165816.
Since we have several hundred tasks, scheduling them all in an RPC is not viable. This PR repurposes `rerun-prod-task?task=all` (the RPC powering the button labeled below) to mark all tasks as `New`, so that the _backfiller_ picks them up. We can change priorities (i.e. have the backfiller fill release candidates with priority) in a future PR if desired.
Also changes the branch to run the query/updates in a transaction.
- Towards https://github.com/flutter/flutter/issues/163896.
- Unblocks https://github.com/flutter/flutter/issues/165078.
- Unblocks https://github.com/flutter/flutter/issues/167383.
> Treat `rerun-prod-task?task=all` as marking all statuses as new.

- app_dart/lib/src/request_handlers/rerun_prod_task.dart
- app_dart/lib/src/service/firestore/commit_and_tasks.dart
- app_dart/test/request_handlers/rerun_prod_task_test.dart
- app_dart/test/service/firestore_test.dart
- app_dart/test/src/service/fake_firestore_service.dart
Closes https://github.com/flutter/flutter/issues/167600.
Prior to this PR, there were multiple bugs:
- Most "recent" task was computed incorrectly (regression test added)
- It wasn't clear how we handled `flutter_release_builder` (made explicit ignore/error cases now)
> Fix `rerun-all` logic with cases involving `flutter_release_builder`.

- app_dart/lib/server.dart
- app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
- app_dart/lib/src/service/firestore.dart
- app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart
Closes https://github.com/flutter/flutter/issues/167675.
I think using `githubFileContent` (the same technique used by `CiYamlFetcher`) is the best way to reduce the GitHub API cost of this added operation, but I could be talked into either just letting it stand, or going for another option (caching, batch updates, etc).
> Backfill release candidates commits (otherwise are ignored)

- app_dart/lib/src/service/luci_build_service/user_data.dart
- app_dart/test/service/luci_build_service/user_data_test.dart
It's been 3 days since we replaced it with `task_id`.
Closes https://github.com/flutter/flutter/issues/167464.
> Remove legacy key `firestore_task_document_name` from UserData.

- app_dart/lib/server.dart
- app_dart/lib/src/request_handlers/scheduler/vacuum_stale_tasks.dart
- app_dart/test/request_handlers/scheduler/vacuum_stale_tasks_test.dart
Closes https://github.com/flutter/flutter/issues/167774.
Arguably we should have _always_ have done this, but it's even more important now.
> Consider release candidate branches for vacuum-stale-tasks.

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
Makes the file test exempt. We could alternately count it as a test, but I think it is rare (and not a great practice) for someone to test the changes in their PR exclusively by modifying an element of the customer tests.
Motivated by https://github.com/flutter/flutter/pull/167754 …
> Make `dev/customer_testing/tests.version` test exempt

- app_dart/lib/src/request_handlers/get_green_commits.dart
- app_dart/test/request_handlers/get_green_commits_test.dart
Closes https://github.com/flutter/flutter/issues/167750.
There is always at least one failing task, which is bringup, so as a result we never returned any green commits.
> Fix `get-green-commits`, use `bringup` instead of `flaky`.

- .ci.yaml
Towards https://github.com/flutter/flutter/issues/167755.
Cocoon supports both formats at the moment, so this a NOP.
> Move `backfill: "false"` out of properties, make it a boolean.

- app_dart/lib/src/service/scheduler.dart
- app_dart/lib/src/service/scheduler/files_changed_optimization.dart
- app_dart/test/service/scheduler_test.dart
See https://github.com/flutter/flutter/issues/167821.
Closes https://github.com/flutter/flutter/issues/165078.
Closes https://github.com/flutter/flutter/issues/163896.
This marks the end of the "make release branches have delayed post-submits" arc of work.
/cc @reidbaker
> Specifically mark 3.29 a legacy branch, opt-in other RC branches.

- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/service/luci_build_service/schedule_prod_builds_test.dart
Closes https://github.com/flutter/flutter/issues/167383.
Still has a carveout for 3.29 (https://github.com/flutter/flutter/issues/167821).
> Enable use of `PBEV` on release candidate postsubmits.

- app_dart/lib/src/service/scheduler/policy.dart
- app_dart/test/service/scheduler/policy_test.dart
The previous code would only schedule `backfill: false` properties if `kBatchSize` tasks were `New`.
Also consider `Skipped`, as otherwise https://github.com/flutter/flutter/issues/167810 is not yet fixed.
> Schedule tasks immediately if previous tasks skipped.

- .github/workflows/app_dart_tests.yaml
- app_dart/lib/src/service/scheduler.dart
Experiment with running some cocoon tests on actions.
- app_dart tests
- dart format checks (could get moved to its own action*)
- dart analyze checks (*)
- license checks (*)
(*): it would be slower and spin up more actions. I only saw a 5 second add on for format,analyze, and license checking.
This makes no change to the luci recipes.
> Github action to run tests

- app_dart/lib/src/model/firestore/base.dart
- app_dart/lib/src/model/firestore/content_aware_hash_builds.dart
- app_dart/lib/src/service/content_aware_hash_service.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/content_aware_hash_service_test.dart
- app_dart/test/src/service/fake_content_aware_hash_service.dart
- app_dart/test/src/service/fake_firestore_service.dart
> [!NOTE]  
> This does not currently complete any check runs, its only to record the data.
Towards flutter/flutter#167778
Add the ability to mark the content aware documents as completed from the scheduler.  This flows from:
```mermaid
sequenceDiagram
participant S as Scheduler
participant CAHS as ContentAwareHashService
S->>S: processCheckRunCompletion(checkRunEvent)
activate S
alt Staging Conclusion is Error AND Is Merge Group
S->>S: failGuardForMergeGroup(...)
S->>CAHS: completeArtifacts(commitSha: sha, failed)
activate CAHS
CAHS-->>S: List<String> completedShas
deactivate CAHS
S-->>GitHub: complete_check_runs(failure)
else Staging Conclusion is Success AND Is Merge Group
S->>S: _closeSuccessfulEngineBuildStage(...)
S->>CAHS: completeArtifacts(commitSha: sha, success)
activate CAHS …
```
> Add a hook to complete artifacts in the CAH service

- app_dart/lib/src/request_handlers/scheduler/backfill_strategy.dart
- app_dart/test/request_handlers/scheduler/backfill_strategy_test.dart
Closes https://github.com/flutter/flutter/issues/165683.
A few changes:
- Release candidates are now kDefault, so that reruns still take priority
- Reruns check for tree-redness cause, not just last kBatchSize tasks
- Tip-of-tree runs at kDefaultPriority
> Fix a TODO and slightly optimize backfill strategy.

- app_dart/lib/src/request_handlers/dart_internal_subscription.dart
- app_dart/lib/src/request_handlers/rerun_prod_task.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/request_handlers/dart_internal_subscription_test.dart
- app_dart/test/request_handlers/rerun_prod_task_test.dart
- app_dart/test/service/luci_build_service/rerun_dart_internal_test.dart
- app_dart/test/src/utilities/mocks.mocks.dart
Closes https://github.com/flutter/flutter/issues/168090.
Also some improvements: 
- Mark the task as in progress 
- Don't create unnecessary tasks as a result of initially marking the task as in progress
> Test `rerunDartInternalReleaseBuilder` workflow.

- app_dart/lib/src/model/firestore/task.dart
- packages/cocoon_common/lib/rpc_model.dart
- packages/cocoon_common/lib/task_status.dart
- packages/cocoon_common/test/task_status_test.dart
Towards https://github.com/flutter/flutter/issues/167284.
This change is non-breaking, because `extension type implements String` _is_ a `String`, and will be represented using the same exact (backing) implementation. The next step(s) would be to remove all manual string references (i.e. to `'New'`), and start using the getters on `TaskStatus` instead of things like `failedStatusSet.contains(...)` across the codebase.
> Start a shared `TaskStatus` enum-_lite_.

- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/scheduler_test.dart
Copypasta was completing these documents with "succeed". 
Added a test that was missing for ensuring the merge group was failed.
> fix: scheduler should complete artifacts with failure

- app_dart/lib/src/model/bbv2_extension.dart
- app_dart/lib/src/model/commit_ref.dart
- app_dart/lib/src/model/firestore/task.dart
- app_dart/lib/src/model/task_ref.dart
- app_dart/lib/src/request_handlers/dart_internal_subscription.dart
- app_dart/lib/src/request_handlers/rerun_prod_task.dart
- app_dart/test/model/bbv2_extension_test.dart
- app_dart/test/model/firestore/task_test.dart
- app_dart/test/model/ref_test.dart
- app_dart/test/src/delegate_matcher.dart
- app_dart/test/src/model/ref_matcher.dart
Towards https://github.com/flutter/flutter/issues/167284.
Removes (and tests) a subset of the original functionality, which is now migrated over.
> More adoption of `TaskStatus`

- app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
- app_dart/lib/src/request_handlers/rerun_prod_task.dart
- app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
- app_dart/lib/src/request_handlers/scheduler/vacuum_stale_tasks.dart
- app_dart/lib/src/service/firestore.dart
- app_dart/lib/src/service/firestore/commit_and_tasks.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/lib/src/service/scheduler/ci_yaml_fetcher.dart
- app_dart/lib/src/service/scheduler/files_changed_optimization.dart
- app_dart/test/service/firestore_test.dart
- app_dart/test/service/scheduler/ci_yaml_fetcher_test.dart
- app_dart/test/src/service/fake_ci_yaml_fetcher.dart
... also cleans up `CiYamlFetcher`-messiness due to supporting Firestore+Datastore.
> Adopt `CommitRef` even more, reducing dependencies on Firestore model.

- app_dart/lib/src/service/commit_service.dart
- app_dart/test/service/commit_service_test.dart
Closes https://github.com/flutter/flutter/issues/168684.
> Do not add/update a commit if the SHA already exists.

- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/scheduler_test.dart
Helps unblock https://github.com/flutter/flutter/issues/168738.
> Use more defined scope for post-submit task scheduling.

- app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
- app_dart/lib/src/request_handlers/scheduler/vacuum_stale_tasks.dart
- app_dart/lib/src/service/config.dart
- app_dart/lib/src/service/config.g.dart
- app_dart/lib/src/service/flags/content_aware_hashing_flags.dart
- app_dart/lib/src/service/flags/content_aware_hashing_flags.g.dart
- app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart
- app_dart/test/service/dynamic_config_updater_test.dart
- app_dart/test/src/fake_config.dart
- app_dart/test/src/utilities/mocks.mocks.dart
- stops making top-level flags in config (no one wants 100 flags to sort through)
- creates a new group for content-aware-hashing
- updated the current flag to show it working
> feat: breakout dynamic into flags/*

- app_dart/lib/src/request_handlers/scheduler/backfill_grid.dart
- app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
- app_dart/test/request_handlers/scheduler/backfill_grid_test.dart
- app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart
Towards https://github.com/flutter/flutter/issues/168738.
This enables backfill support for `ios-experimental`. More work is required to make this work e2e.
/cc @vashworth
> Experimental backfill for `ios-experimental` branch.

- app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
- app_dart/lib/src/service/config.dart
- app_dart/test/service/dynamic_config_updater_test.dart
Side effect: don't set them if they aren't changing... shouldn't really be a side effect since we're single threaded.
> feat: diff the configs and output them

- app_dart/lib/src/service/luci_build_service.dart
- app_dart/lib/src/service/luci_build_service/cipd_version.dart
- app_dart/test/service/luci_build_service/schedule_prod_builds_test.dart
Towards https://github.com/flutter/flutter/issues/168738.
I believe this is the last PR, we can do some validation testing after it (and it's friends) merge.
/cc @vashworth
> Support post-submit builds for experimental branches.

- dashboard/lib/widgets/task_overlay.dart
- dashboard/test/widgets/task_overlay_test.dart
> Use the word `bringup` not `flaky` to describe `bringup: true`.

- dashboard/test/utils/golden.dart
Closes https://github.com/flutter/flutter/issues/168859.
> Use `GITHUB_ACTIONS` to determine a CI run.

- dashboard/lib/widgets/task_grid.dart
Closes https://github.com/flutter/flutter/issues/168851.
> Do not show a loading indicator when we are not loading.

- app_dart/lib/src/request_handlers/vacuum_github_commits.dart
- app_dart/test/request_handlers/vacuum_github_commits_test.dart
- dashboard/lib/service/appengine_cocoon.dart
- dashboard/lib/service/cocoon.dart
- dashboard/lib/service/dev_cocoon.dart
- dashboard/lib/state/build.dart
- dashboard/test/service/appengine_cocoon_test.dart
- dashboard/test/state/build_test.dart
- dashboard/test/utils/mocks.mocks.dart
Closes https://github.com/flutter/flutter/issues/168833.
Better supports branches such as https://github.com/flutter/flutter/issues/168738.
> Allow vacuuming a specific repository and branch.

- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/scheduler_test.dart
Closes https://github.com/flutter/flutter/issues/168867.
> Conditionally lock MQG on `flutter/flutter`+`master` only.

- auto_submit/lib/action/git_cli_revert_method.dart
- auto_submit/test/action/git_cli_revert_method_test.dart
- auto_submit/test/requests/github_webhook_test_data.dart
Closes https://github.com/flutter/flutter/issues/168926.
> When using revert-bot, it applies the right `base-ref`/`branch-name`.

- app_dart/lib/src/request_handlers/github/webhook_subscription.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/request_handlers/github/webhook_subscription_test.dart
- app_dart/test/service/scheduler/ci_yaml_strings.dart
- app_dart/test/service/scheduler/create_check_run.dart
- app_dart/test/service/scheduler/hash_workflow_test.dart
- app_dart/test/service/scheduler_test.dart
- app_dart/test/src/service/fake_content_aware_hash_service.dart
This ONLY waits on the content hash before triggering all builds.
- renames `triggerMergeGroupTargets` -> `handleMergeGroupEvent`. We want to be able to trigger targets in the merge group later from synthetic data. See `triggerTargetsForMergeGroup`.
- Moves some test strings out to ci_yaml_test_strings
- Moves some test check run methods to new file.
- Tests really need to be broken out; follow up PR
> Handle flag`waitOnContentHash`

- app_dart/lib/src/request_handlers/rerun_prod_task.dart
Towards https://github.com/flutter/flutter/issues/168905.
Haven't had the chance to dig further yet, but should help for next time.
> Add a log statement when a `dart-internal` re-run occurs but won't succeed.

- app_dart/integration_test/data/cocoon_config.json
- app_dart/lib/src/model/ci_yaml/target.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/lib/src/service/scheduler/files_changed_optimization.dart
- app_dart/test/model/ci_yaml/target_test.dart
- app_dart/test/service/scheduler_test.dart
We will not make any future 3.29 updates.
Closes https://github.com/flutter/flutter/issues/167821.
Closes https://github.com/flutter/flutter/issues/167755.
> Remove legacy branch logic for `3.29`.

- app_dart/lib/src/service/config.dart
- app_dart/test/service/config_test.dart
Required since `YamlMap.cast()` does not deeply cast.
Work around till: https://github.com/dart-lang/tools/issues/2094
> Fix dynamic parsing

- app_dart/config.yaml
Enable `waitOnContentHash` for the merge queue.
If something goes wrong; revert this PR and wait ~2 minutes.
> chore: turn on `waitOnContentHash` flag

- app_dart/lib/src/model/ci_yaml/target.dart
Note that in `getProperties()` there is a pre-step that already converts the string `"true"` to the boolean `true`, which is confusing, but go figure.
> Simplify `Target.isReleaseBuild`, with otherwise the same output.

- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/service/luci_build_service/schedule_prod_builds_test.dart
Towards https://github.com/flutter/flutter/issues/169088.
> Use `FPEV=...` similar to release branches for experimental branches.

- app_dart/lib/src/model/ci_yaml/ci_yaml.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/scheduler/ci_yaml_strings.dart
- app_dart/test/service/scheduler_test.dart
Closes https://github.com/flutter/flutter/issues/169088.
> Build engine binaries in post-submit on experimental branches.

- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/scheduler/hash_workflow_test.dart
Prior to flipping completely over; we need to trigger tests for all shas, even if the content hash was generated.
> fix: `waitOnContentHash` should also trigger on completed hash

- app_dart/lib/src/request_handlers/get_status.dart
- app_dart/lib/src/service/build_status_service.dart
- app_dart/lib/src/service/firestore.dart
- app_dart/test/request_handlers/get_status_test.dart
- app_dart/test/src/service/fake_build_status_service.dart
- packages/cocoon_common/lib/core_extensions.dart
- packages/cocoon_common/lib/src/time_range.dart
- packages/cocoon_common/test/time_range_test.dart
I started to work on https://github.com/flutter/flutter/issues/169234 and realized the current way timestamp filtering is done with Firebase is inflexible (and personally, confusing). This adds a small-ish `TimeRange` class in `cocoon_commons` and uses it instead of `int? timestamp` to determine which commits to find.
(Even if we want a different approach than https://github.com/flutter/flutter/issues/169234, this seems worth it?)
> Add and use a `TimeRange` class to represent before/after timestamp.

- app_dart/lib/server.dart
- app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
- app_dart/lib/src/service/firestore.dart
- app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart
- cron.yaml
Closes https://github.com/flutter/flutter/issues/169234.
This could be made a (dynamic) flag if needed in the future, but I don't see the need for now.
> Use any branch with commits in the last week as a backfill signal.

- app_dart/lib/src/request_handlers/scheduler/backfill_grid.dart
- app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
- app_dart/test/request_handlers/scheduler/backfill_grid_test.dart
- app_dart/test/request_handlers/scheduler/backfill_strategy_test.dart
- app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart
- app_dart/test/src/service/fake_ci_yaml_fetcher.dart
Closes https://github.com/flutter/flutter/issues/169405.
- Properly downloads (and compares) both the _current_ commit `.ci.yaml` _and_ the ToT `.ci.yaml`
- A missing target is not an error, it just implicitly disables (skips) the target at the current commit
- Adds tests for both skipping tasks properly _and_ for the right `properties: ...` to be used as a system result
/cc @gmackall
> Fix backfill execution based on ToT target comparison.

- app_dart/bin/gae_server.dart
- app_dart/lib/src/service/config.dart
- app_dart/lib/src/service/flags/content_aware_hashing_flags.dart
- app_dart/lib/src/service/flags/content_aware_hashing_flags.g.dart
- app_dart/lib/src/service/flags/dynamic_config.dart
- app_dart/lib/src/service/flags/dynamic_config.g.dart
- app_dart/lib/src/service/flags/dynamic_config_updater.dart
- app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart
- app_dart/test/service/config_test.dart
- app_dart/test/service/dynamic_config_updater_test.dart
- app_dart/test/service/scheduler/hash_workflow_test.dart
- app_dart/test/service/scheduler_test.dart
- app_dart/test/src/fake_config.dart
- app_dart/test/src/utilities/mocks.mocks.dart
- app_dart/tool/local_server.dart
Doing as pre-work before requested changes on https://github.com/flutter/cocoon/pull/4731.
I ran into a number of cases where changes were needed, and figured a separate PR was cleaner:
- Moved all of the bits out of `config.dart` and into `flags/_*.dart` files to reduce file size
- We have command-line tools in `app_dart/bin` that are _not_ a server (i.e. `verify_test_ownership.dart`) that create `CiYaml` objects, and also need `CiYamlFlags`. Instead of hacking something together, I added `DynamicConfig.fromRemoteLatest` and `DynamicConfig.fromLocalRepo` to use, respectively, in these command-line tools (which are used in CI production, not unused tools).
- I made all of the objects `const`-able, and made it easy to create defaults, even if they are not `const` themselves, by using the …
> Refactor and split up `DynamicConfig*`, prepare for more flag groups.

- Dockerfile.app_dart
- Dockerfile.auto_submit
... instead of manual revs.
We can always pin to an older version if that ends up being needed, but this will be in line with how most of us do development (using the latest version of `dart` that ships with the master channel of `flutter`).
> Update Docker SDK images to latest `stable`.

- dashboard/lib/service/appengine_cocoon.dart
Oopsie! This API requires authentication both ways.
> Update API for `*TreeStatus`, to remove `public`.

- app_dart/config.yaml
- dashboard/lib/logic/links.dart
The "secret" (but auth required) https://flutter-dashboard.appspot.com/#/status page allows turning a tree red manually.
I'll submit this PR when I'm back Tuesday.
> Allow manually closing the tree.

- app_dart/lib/src/request_handlers/get_tree_status_changes.dart
- app_dart/test/request_handlers/get_tree_status_test.dart
Closes https://github.com/flutter/flutter/issues/170366.
... the `GET` part of https://github.com/flutter/cocoon/pull/4775.
> Fix `get-tree-status` call as well.

- app_dart/lib/src/request_handlers/flaky_handler_utils.dart
- app_dart/lib/src/request_handlers/update_existing_flaky_issues.dart
- app_dart/test/request_handlers/update_existing_flaky_issues_test_data.dart
Comments on flakiness issues are leading to an empty dashboard page (e.g. https://github.com/flutter/flutter/issues/169574#issuecomment-2961845607). That's because `bringup` tasks are hidden by default.
This PRs adds the `&showBringup=true` query param for bringup tasks to make sure the Dashboard link works as expected.
> Include `showBringup=true` in Dashboard links

- dashboard/lib/views/build_dashboard_page.dart
TIL the "Settings" popup (triggered by clicking the gear button) has buttons at the bottom but they are hidden by the fixed height. Unfortunately on MacOS the scroll bars are hidden by default so I never knew they were there.
With this change the height can now expand enough to fix the contents.
There are some overflow issues on very small screen sizes so if there are preferable ways to achieve this please let me know. 
Ideally it should resize to fit the contents if the screen size allows, otherwise be scrollable.
> Update "Settings" popup to grow in size vertically

- app_dart/lib/src/request_handlers/push_build_status_to_github.dart
Avoid enumerating multiple pages of PRs over a period of time in which the list can be mutated by outside factors.
potentially fixes #171179
> fix: update tree-status should fetch the entire PR list

- app_dart/lib/src/service/content_aware_hash_service.dart
- app_dart/lib/src/service/luci_build_service.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart
- app_dart/test/service/content_aware_hash_service_test.dart
- app_dart/test/service/luci_build_service/schedule_prod_builds_test.dart
- app_dart/test/service/scheduler_test.dart
- app_dart/test/src/service/fake_content_aware_hash_service.dart
- app_dart/test/src/utilities/mocks.mocks.dart
This change plumbs the content-aware hash from the scheduler to the LUCI build service for post-submit builds. This will allow LUCI/recipes to use the content hash in post-submit builds (windows arm, ddm, etc).
The following changes are included:
- The `ContentAwareHashService` is updated to include a `getHashByCommitSha` method.
- The `Scheduler` now retrieves the content hash on addCommit() and passes it to `LuciBuildService`.
- `LuciBuildService` plumbs the `contentHash` through to buildbucket properties.
- Tests have been added to verify that the content hash is correctly passed to the `LuciBuildService`.
Extension of flutter/flutter#167779
> feat: Plumbs content hash to post-submit LUCI builds

- dashboard/lib/widgets/sign_in_button/sign_in_button_web.dart
Removes calling the plugin directly. Uses the `authenticationEvents` stream, and the web-only exposed render button.
fixes flutter/flutter#171479
> fix: signin api breakage

- app_dart/lib/src/model/common/firestore_extensions.dart
- app_dart/lib/src/model/firestore/content_aware_hash_builds.dart
- app_dart/lib/src/service/content_aware_hash_service.dart
- app_dart/lib/src/service/scheduler.dart
- app_dart/test/service/content_aware_hash_service_test.dart
- app_dart/test/service/scheduler/hash_workflow_test.dart
- app_dart/test/src/model/_content_aware_hash_builds.dart
- app_dart/test/src/service/fake_firestore_service.dart
fixes: flutter/flutter#172694
When a merge group is destroyed (for dequeued or invalided reasons), the corresponding content-aware hash build is now explicitly marked as failed. This short-curcuits waiting for LUCI jobs to be canceled.
When a content-aware hash build fails, it can now be taken over by a subsequent build for the same content hash. This happens when a PR is removed from the merge queue and an "engine" PR is added back - the previous failure will be restarted and "content_hash" passed to LUCI recipes.
The `ContentAwareHashBuilds` model now includes a list of `failedCommitShas` to track the history of failed attempts for a given content hash. When a new build takes over a failed one, the old commit SHA is added to this list.
> feat(content-aware-hashing): Allow builds to take over failed hashes

- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/service/luci_build_service/rerun_dart_internal_test.dart
This fixes a bug that @camsim99 noticed where if a non-engine build (i.e. docs generation) step failed.
It would be better to _not_ do this, and instead only re-run the docs test, but this avoids an NPE:
```txt
Null check operator used on a null value
package:cocoon_service/src/service/luci_build_service.dart 1201:60   LuciBuildService._filterFailedEngineBuilds.<fn>
dart:core                                                            new List.of
package:cocoon_service/src/service/luci_build_service.dart 1142:32   LuciBuildService.rerunDartInternalReleaseBuilder
===== asynchronous gap ===========================
test/service/luci_build_service/rerun_dart_internal_test.dart 442:5  main.<fn>
Log buffer: BufferedLogger [
{
"message": "rerunDartInternalReleaseBuilder(buildNumber=123 for Commit …
```
> Avoid assuming all failed release builders have a `config_name` property

- app_dart/config.yaml
Turned on closeMqGuardAfterPresubmit feature
Issue: [166466](https://github.com/flutter/flutter/issues/166466)
> Turned on closeMqGuardAfterPresubmit feature

- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/service/luci_build_service/schedule_try_builds_test.dart
https://github.com/flutter/cocoon/pull/4844 was partially correct.
However, PRs such as https://github.com/flutter/flutter/pull/174310 are still blocked because they touch the engine, and try-bots (as of currently) only upload engines to a git SHA, not a content hash. This PR relaxes the try-bot logic to continue to provide the current SHA as "this is the engine" if the engine is being built from source.
Implicitly, it will no longer provide `FLUTTER_PREBUILT_ENGINE_VERSION=` for the `master` branch, if and only if the engine is not being touched. That means `flutter <any command>` will start to download the engine using the content hash, which should be fine.
> Always provide a git SHA of an engine to use if the try-bots built the engine for the commit

- app_dart/lib/src/service/luci_build_service.dart
- app_dart/test/service/luci_build_service/schedule_merge_group_builds_test.dart
- app_dart/test/service/luci_build_service/schedule_prod_builds_test.dart
- app_dart/test/service/luci_build_service/schedule_try_builds_test.dart
These are no longer processed by LUCI recipes, including those branched for 3.35 and 3.36.
> Remove now unused `is_fusion` builder properties

- auto_submit/lib/validations/base_commit_date_allowed.dart
Change PR validation to verify that PR base is no more than X days old, not the head
Issue: [170476](https://github.com/flutter/flutter/issues/170476)
> Change PR validation to verify PR base expiration

- dashboard/lib/widgets/sign_in_button/sign_in_button.dart
Flutter has already migrated from dart:js_util to dart:js_interop (which is unsupported by dart2wasm). This migrates a remaining reference to js_util which will be broken when dart2wasm drops the library entirely.
> Remove references to js_util
