flutter/cocoon

app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/request_handlers/github_webhook_test.dart
Fixes https://github.com/flutter/flutter/issues/110487
This is somewhat difficult to test as the issue in the differences between the prod pubsub and the fake pubsub.
=> [app_dart] Fix encoding GithubWebhookMessage for pubsub

app_dart/lib/src/request_handlers/github_webhook.dart
Fixes https://github.com/flutter/flutter/issues/110487
=> [app_dart] Fix publish topic name for github webhooks

auto_submit/test/utilities/test.txt
=> test file added for revert

auto_submit/test/utilities/test.txt
=> Revert "test file added for revert"

codesign/lib/src/file_codesign_visitor.dart, codesign/test/file_codesign_visitor_test.dart
Context: Boost codesign priority and add more commits before the Christopher meeting next Tuesday.
This commit adds the function and tests to check notarization status of an uploaded zip artifact.
prior prs: https://github.com/flutter/cocoon/pull/1972, https://github.com/flutter/cocoon/pull/1899, https://github.com/flutter/cocoon/pull/2003, https://github.com/flutter/cocoon/pull/2044, https://github.com/flutter/cocoon/pull/1861, https://github.com/flutter/cocoon/pull/2059
=> [codesign] add function to check notarization status

auto_submit/lib/exception/retryable_merge_exception.dart, auto_submit/lib/service/config.dart, auto_submit/lib/service/validation_service.dart, auto_submit/pubspec.lock, auto_submit/pubspec.yaml, auto_submit/test/service/validation_service_test.dart, auto_submit/test/src/service/fake_graphql_client.dart
Added exponential backoff to retryable error when Github is unable to merge pull request. When attempting a merge too close to another merge github occassionally will not be able to merge the pull right away until it processes the changes and revalidates conditions for merging the new request.
https://github.com/orgs/community/discussions/24462
The current setting for us to retry the merge error is 2^n * 50 milliseconds 5 times or up to a total of 3 seconds in order to re-attmept the merge request.
fixes https://github.com/flutter/flutter/issues/110889
[Contributor …
=> Added exponential backoff to retryable merge error.

codesign/lib/src/file_codesign_visitor.dart, codesign/test/file_codesign_visitor_test.dart
Context: Add more commits before the Christopher meeting next Tuesday.
This commit adds the function and tests to upload artifact to notary server.
prior prs: https://github.com/flutter/cocoon/pull/1972, https://github.com/flutter/cocoon/pull/1899, https://github.com/flutter/cocoon/pull/2003, https://github.com/flutter/cocoon/pull/2044, https://github.com/flutter/cocoon/pull/1861, https://github.com/flutter/cocoon/pull/2059, https://github.com/flutter/cocoon/pull/2107
=> [codesign] function to Upload to notary server

README.md
Adding the SLSA badge for cocoon repository.
=> Add SLSA L2 Badge

auto_submit/test.txt
Testing the full revert path with database access added for metrics and revert request tracking. …
=> Adding a file to test full revert with db access path.

auto_submit/test.txt
=> Revert "Adding a file to test full revert with db access path."

auto_submit/test.data
=> Adding a file to test revert

auto_submit/test.data
=> Revert "Adding a file to test revert"

app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart, app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart, app_dart/test/src/datastore/fake_datastore.dart
Fixes: https://github.com/flutter/flutter/issues/111899
=> Schedule builds after db updates in batch-backfiller

app_dart/lib/src/service/config.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart, dashboard/lib/widgets/commit_author_avatar.dart, dashboard/lib/widgets/commit_box.dart, dashboard/lib/widgets/error_brook_watcher.dart, dashboard/lib/widgets/task_grid.dart
Previously builds in the framework were not generating any artifacts but after we started uploading docs the framework builds started failing on retries because the zip files alread exist.
Bug: https://github.com/flutter/flutter/issues/111921 …
=> Add force_upload property to flutter/flutter retries.

app_dart/lib/src/foundation/utils.dart, app_dart/lib/src/model/ci_yaml/target.dart, app_dart/lib/src/request_handlers/check_flaky_builders.dart, app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart, app_dart/lib/src/request_handlers/flaky_handler_utils.dart, app_dart/lib/src/request_handlers/update_existing_flaky_issues.dart, app_dart/test/model/ci_yaml/target_test.dart, app_dart/test/request_handlers/update_existing_flaky_issues_test.dart, app_dart/test/request_handlers/update_existing_flaky_issues_test_data.dart, app_dart/test/src/utilities/entity_generators.dart, dashboard/pubspec.lock
Reverts flutter/cocoon#2206
This is causing tree breakage: https://github.com/flutter/flutter/issues/113473
=> Revert "Using protobuf instead of ciyaml directly."

auto_submit/test/validations/revert_test.dart
Adding a comment for revert testing. …
=> Adding a comment for revert validate.

auto_submit/test/validations/revert_test.dart
Reverts flutter/cocoon#2234 this is a test with added context.
The bot should still pick out the reverts link and perform the compare and merge.
=> Revert "Adding a comment for revert validate."

auto_submit/lib/service/github_service.dart, auto_submit/lib/validations/revert.dart, auto_submit/test/src/service/fake_github_service.dart, auto_submit/test/validations/revert_test.dart, auto_submit/test/validations/revert_test_data.dart, dashboard/pubspec.lock
Modified the revert link extraction code so that we can find the revert link when it is surrounded by text. This fixes an issue where when developers want to add context the previous code could not deal with finding the reverts link. This change allows that to be found as well as detecting only one ```reverts owner/repo#id``` in order to block multiple links.
A second change is to compare the file names as well as the changes made to each file and that the number of additions,  deletions and total changes is equal to the reverted files number of deletions or additions and total changes respectively.
We are detecting that the changes seek to undo the original changes but not parsing the changes. This is considerably more work to do to parse the change sets.
Validated that the bot will now …
=> Update revert regex to be more flexible with surrounding text and other quality changes

app_dart/lib/src/request_handlers/check_flaky_builders.dart, app_dart/test/request_handlers/check_flaky_builders_test.dart
Fixes: https://github.com/flutter/flutter/issues/107563
=> Skip bug creation for already `bringup: true` targets

.github/workflows/scorecards-analysis.yml, app_dart/pubspec.lock, app_dart/pubspec.yaml
New versions of the action are signing the generated file and they require a id-token.
=> Fix scorecards analysis.

app_dart/lib/src/request_handlers/push_build_status_to_github.dart
Fixes: https://github.com/flutter/flutter/issues/113617
=> Update tree status link from GitHub PRs

auto_submit/alternate_merge_test.txt
Adding a test file to validate an alternate method of merging pull request. This file will be reverted. …
=> Adding a file to test an alternate http merge method

auto_submit/alternate_merge_test.txt
=> Revert "Adding a file to test an alternate http merge method"

app_dart/lib/src/model/luci/buildbucket.g.dart, app_dart/lib/src/model/luci/push_message.g.dart, app_dart/pubspec.lock, app_dart/pubspec.yaml, app_dart/test/src/utilities/mocks.mocks.dart, auto_submit/pubspec.lock, auto_submit/pubspec.yaml, codesign/pubspec.lock, device_doctor/pubspec.lock, licenses/pubspec.lock
This dependency was failing tests.
=> Use grpc < 3.1.0.

app_dart/lib/src/foundation/github_checks_util.dart
This is to help triage: https://github.com/flutter/flutter/issues/114633
=> Retry on any exception when creating .ci.yaml check run

app_dart/lib/src/model/proto/internal/scheduler.proto
Adds an additional `SchedulerSystem` option for the SchedulerConfig that will be used to trigger packaging builds in dart_internal
=> Add 'release' SchedulerSystem

codesign/test/file_codesign_visitor_test.dart
fixes https://github.com/flutter/flutter/issues/115117.
Ensure the password files are cleaned up after runs.
=> [codesign] remove password files after runs

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/src/utilities/entity_generators.dart
Fixes: https://github.com/flutter/flutter/issues/115397
=> Skip bringup true targets for post-submit checkruns in GitHub

dashboard/lib/build_dashboard_page.dart, dashboard/lib/dashboard_navigation_drawer.dart, dashboard/lib/index_page.dart, dashboard/lib/logic/links.dart, dashboard/test/dashboard_navigation_drawer_test.dart
issue:https://github.com/flutter/flutter/issues/115476
- [] I added new tests to check the change I am making, or this PR is [test-exempt].
=> Rename NavigationDrawer to DashboardNavigationDrawer because NavigationDrawer will be a material widget

packages/buildbucket-dart/example/buildbucket_pb_example.dart, packages/buildbucket-dart/lib/buildbucket_pb.dart, packages/buildbucket-dart/pubspec.yaml, packages/buildbucket-dart/test/buildbucket_pb_test.dart
There were some errors with the version and the package name.
Bug: https://github.com/flutter/flutter/issues/115490
=> Fix buildbucket publishing errors.

app_dart/bin/server.dart, app_dart/lib/cocoon_service.dart, app_dart/lib/src/request_handlers/create_branch.dart, app_dart/test/request_handlers/create_branch_test.dart
https://github.com/flutter/flutter/issues/112036
=> [app_dart] Add CreateBranch handler

device_doctor/tool/build.sh, device_doctor/tool/ensure_file, device_doctor/tool/ensure_file_windows
This is to unblock recipe changes impacting device_doctor builders.
=> Use dev dart in device_doctor.

analysis_options.yaml
This diagnostic is deprecated and will soon no longer be produced.
*List which issues are fixed by this PR. You must list at least one issue.* Fixes https://github.com/flutter/flutter/issues/117184 …
=> Remove implicit-dynamic-parameter from analysis_options.yaml

app_dart/pubspec.lock
Pubspec file was outdated causing multiple test issues.
=> Fix CyclicInitializationError in app_dart tests.

device_doctor/lib/src/ios_debug_symbol_doctor.dart, device_doctor/test/src/ios_debug_symbol_doctor_test.dart
Fixes https://github.com/flutter/flutter/issues/119197
Fixes https://github.com/flutter/flutter/issues/119151
Fixes https://github.com/flutter/flutter/issues/119147
=> make pattern more general

app_dart/pubspec.lock, app_dart/test/src/utilities/entity_generators.dart, device_doctor/lib/src/ios_debug_symbol_doctor.dart, device_doctor/test/src/ios_debug_symbol_doctor_test.dart
Speculatively may help with https://github.com/flutter/flutter/issues/118924.
=> Add -runFirstLaunch command before opening Xcode during iOS symbol recovery

codesign/pubspec.lock
This is to fix errors with codesign tests.
=> Update codesign dependencies.

app_dart/lib/src/service/scheduler.dart
Occasionally we fail during roller PRs to get the ci.yaml file from github. With some investigation it was found that we are only attempting 3 times with a retry factor of 200 ms which means we attempt three tries during a span of 1 second. I don't believe this is near long enough since this does not fail each time.
Also this means we will wait 4 + 8 + 16 seconds for a total of 28 seconds in the worst case which is acceptable since there are other far longer running tests.
We also error out when attempting to get from GoB since the commit is not there it makes no sense to run that check. Possibly remove that now or later.
[Engine roller blocked on ci.yaml validation …
=> Change RetryOptions for getCiYaml call

dev/provision_salt.sh
Bug:https://github.com/flutter/flutter/issues/120211 …
=> Point to the flutter salt master server.

dev/provision_salt.sh
Bug:https://github.com/flutter/flutter/issues/120255 …
=> Update provision script settings for salt key autoaccept.

app_dart/lib/src/model/luci/push_message.dart, app_dart/lib/src/model/luci/push_message.g.dart, app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart, app_dart/lib/src/request_handlers/presubmit_luci_subscription.dart, app_dart/lib/src/service/github_checks_service.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart, app_dart/test/src/utilities/mocks.mocks.dart
* Moves the logic in the PubSub handlers to the model class
* I plan to reuse this in some new pubsubs, and there's no point in copying it around further
* Part of https://github.com/flutter/cocoon/pull/2391
=> [app_dart] Add BuildPushMessage.fromPushMessage

app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/src/service/fake_scheduler.dart
https://github.com/flutter/flutter/issues/120331
=> [scheduler] Do not update postsubmit bringup targets in check runs

app_dart/bin/server.dart, app_dart/lib/cocoon_service.dart, app_dart/lib/src/request_handlers/get_status.dart, app_dart/lib/src/request_handlers/scheduler/vacuum_stale_tasks.dart, app_dart/test/request_handlers/scheduler/vacuum_stale_tasks_test.dart, app_dart/test/src/utilities/entity_generators.dart, cron.yaml
The build dashboard is getting stuck with stale tasks. Add a vacuum handler to get them to eventually run.
=> [scheduler] Add vacuum stale tasks

app_dart/pubspec.lock, app_dart/pubspec.yaml
https://github.com/flutter/flutter/issues/121292
This should prevent GitHub API requests from being randomly rejected.
=> Bump github.dart version to pass User-Agent header

analyze/pubspec.lock, app_dart/lib/src/request_handlers/github/webhook_subscription.dart, app_dart/test/request_handlers/github/webhook_subscription_test.dart, app_dart/test/src/service/fake_scheduler.dart, app_dart/test/src/utilities/mocks.mocks.dart, auto_submit/pubspec.lock, codesign/pubspec.lock, dashboard/pubspec.lock, device_doctor/pubspec.lock, licenses/pubspec.lock, test_utilities/pubspec.lock
When a pull request is forcefully merged the pending presubmit tasks need to be cancelled.
Fixes https://github.com/flutter/flutter/issues/101064
[CLA]: …
=> Cancel running presubmit tasks on force merge

app_dart/lib/src/model/appengine/task.dart, app_dart/lib/src/request_handlers/flaky_handler_utils.dart, app_dart/lib/src/service/github_checks_service.dart, app_dart/test/src/utilities/mocks.mocks.dart, auto_submit/lib/server/request_handler.dart, cron.yaml, device_doctor/lib/src/device.dart
Part of https://github.com/flutter/flutter/issues/121989. 
See comment: https://github.com/flutter/flutter/issues/121989#issuecomment-1457104096
=> Disable vaccum task job

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/src/utilities/mocks.mocks.dart
Fixes: https://github.com/flutter/flutter/issues/122116
=> Limit postsubmit checkruns to packages only

app_dart/lib/src/service/luci_build_service.dart
To help triage: https://github.com/flutter/flutter/issues/122117
=> Add more logs to help triage hanging yellow tasks

README.md
Cocoon has achieved SLSA L3, this PR is updating the badge in the readme file.
=> Update SLSA badge to L3

CI_YAML.md
Following https://github.com/flutter/flutter/pull/120912#discussion_r1128793254 to make doc clear.
=> Update CI_YAML.MD regarding taget updates

auto_submit/lib/service/config.dart, auto_submit/lib/validations/approval.dart, auto_submit/test/utilities/mocks.mocks.dart, auto_submit/test/validations/approval_test.dart, auto_submit/test/validations/approval_test_data.dart, dashboard/pubspec.lock
This change adds a clarifying message to let the author of a pull request know how many remaining reviews are required for them to merge their pull request.
We will print the authors authorAssociation along with the remaining number of required reviews. See below for examples.
If a pr author is a MEMBER/OWNER then they will require at least 1 review from another MEMBER. 
```
This PR has not met approval requirements for merging. You have project association MEMBER and need 1 more review(s) in order to merge this PR.
- Merge guidelines: You need at least one approved review if you are already a MEMBER or two member reviews if you are not a MEMBER before re-applying the autosubmit label. __Reviewers__: If you left a comment approving, please use the "approve" review action instead.
```
If a …
=> Clarify the number of remaining reviews needed to merge a pull request

app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
Addresses comment: https://github.com/flutter/flutter/issues/122117#issuecomment-1468673964
=> Shuffle tasks to be back filled

app_dart/pubspec.lock, app_dart/test/src/utilities/mocks.mocks.dart
Fixes https://github.com/flutter/flutter/issues/122838
=> Sync github mocks from upstream

app_dart/lib/src/request_handlers/github/webhook_subscription.dart, app_dart/test/request_handlers/github/webhook_subscription_test.dart
Fixes https://github.com/flutter/flutter/issues/122924
For an example, see the PR https://github.com/flutter/flutter/pull/122856/files, which updated packages/flutter_tools/test/integration.shard/test_utils.dart
=> [app_dart] consider all files under flutter_tools/test to be tests

analyze/analyze.dart, app_dart/lib/src/model/appengine/key_helper.proto, app_dart/lib/src/model/proto/internal/build_status_response.proto, app_dart/lib/src/model/proto/internal/github_webhook.proto, app_dart/lib/src/model/proto/internal/key.proto, dashboard/lib/model/branch.proto, dashboard/lib/model/build_status_response.proto, dashboard/lib/model/commit.proto, dashboard/lib/model/commit_status.proto, dashboard/lib/model/key.proto, dashboard/lib/model/task.proto
This is to support getting Cocoon into Google for the Flutter-Roll-on-Borg. This fixes a lint in the ongoing third_party roll
=> Namespace Cocoon protos

.github/autosubmit.yml
Adding a file pointer here for the autosubmit config in order to "hide" it a little more and to avoid changes directly to this file. …
=> Adding config pointer file.

app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart, app_dart/lib/src/service/config.dart, app_dart/test/src/datastore/fake_config.dart
Fixes: https://github.com/flutter/flutter/issues/123405
=> Bump batch backfiller commit row limit

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/src/utilities/mocks.mocks.dart
=> Revert "Cancel builds was not cancelling all builds"

dev/githubanalysis/bin/githubanalysis.dart
Missed this file in https://github.com/flutter/cocoon/pull/2578, oops.
=> Add a missing file from the githubanalysis tool.

cron.yaml
Part of https://github.com/flutter/flutter/issues/124603.
=> Extend cronjob to vacuum github commits to every 6 hours

README.md, app_dart/README.md, app_dart/bin/server.dart, app_dart/lib/cocoon_service.dart, app_dart/lib/src/request_handlers/dart_internal_subscription.dart, app_dart/lib/src/request_handlers/github/webhook_subscription.dart, app_dart/lib/src/request_handlers/scheduler/request_subscription.dart, app_dart/test/request_handlers/dart_internal_subscription_test.dart
https://github.com/flutter/flutter/issues/124628
* Basic setup for the dart-internal endpoint, to make future PRs with the logic less busy
* Connects endpoint to pub/sub
* Ensures the message is consumed and logs it for now
* Adds a test setup …
=> Initial creation of dart-internal endpoint

auto_submit/lib/requests/check_pull_request_queries.dart, auto_submit/lib/service/validation_service.dart, auto_submit/test/service/validation_service_test.dart
Issues:
* Fixes: https://github.com/flutter/flutter/issues/124742
* Related: https://github.com/flutter/flutter/issues/124554
https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#merge-a-pull-request
=> [autosubmit] add PR body to commit message when auto-submitting

app_dart/bin/server.dart, app_dart/lib/src/model/gerrit/commit.dart, app_dart/lib/src/model/gerrit/commit.g.dart, app_dart/lib/src/request_handlers/github/webhook_subscription.dart, app_dart/lib/src/service/branch_service.dart, app_dart/lib/src/service/gerrit_service.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/test/request_handlers/github/webhook_subscription_test.dart, app_dart/test/request_handlers/update_branches_test.dart, app_dart/test/service/gerrit_service_test.dart, app_dart/test/src/datastore/fake_config.dart, app_dart/test/src/service/fake_gerrit_service.dart, app_dart/test/src/utilities/entity_generators.dart, app_dart/test/src/utilities/webhook_generators.dart
This is a rebase of https://github.com/flutter/cocoon/pull/2411 to TOT, and some cleanup.
Fixes: https://github.com/flutter/flutter/issues/62375, https://github.com/flutter/flutter/issues/100911
=> Check GoB for mirrored commit before scheduling postsubmit tasks

CI_YAML.md
Related https://github.com/flutter/flutter/issues/125492
=> Add doc for updating target platform in .ci.yaml

auto_submit/lib/validations/revert.dart
Need to merge this to test configurable autosubmit. …
=> Add a comment for testing revert.

auto_submit/lib/validations/revert.dart
=> Revert "Add a comment for testing revert."

auto_submit/lib/service/validation_service.dart, auto_submit/test/requests/github_webhook_test_data.dart, auto_submit/test/service/validation_service_test.dart
Validate that a pull request is mergeable before attempting to merge it into the default branch.
Fixes https://github.com/flutter/flutter/issues/112018
[CLA]: …
=> Verify if a pull request is mergeable before attempting to merge it

auto_submit/lib/request_handling/pubsub.dart, auto_submit/pubspec.lock
Replace constants in the pubsub.dart class. …
=> [Configurable Autosubmit] Add changes to use config values - Part 2

auto_submit/lib/requests/github_webhook.dart, auto_submit/pubspec.lock
Add a logging message and new config values to github webhook. …
=> [Configurable Autosubmit] Update github_webhook to use config values - Part 4

auto_submit/lib/requests/check_pull_request.dart, auto_submit/pubspec.lock
Check pull requests api uses new config values as well as added logging.
[breaking change …
=> [Configurable Autosubmit] Updated check pull requests class to use new config values - Part 3

auto_submit/lib/validations/required_check_runs.dart, auto_submit/lib/validations/revert.dart, auto_submit/pubspec.lock, auto_submit/test/service/validation_service_test.dart, auto_submit/test/src/service/fake_github_service.dart, auto_submit/test/validations/revert_test.dart, auto_submit/test/validations/revert_test_data.dart
Update the revert validation to use the new repository configuration values when validating a revert request. …
=> [Configurable Autosubmit] Update revert validation to use configurable autosubmit configuration - Part 5

CI_YAML.md
Added details about `timeout` versus `test_timeout_secs`
Provides info to help with issue: https://github.com/flutter/flutter/issues/126451
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling …
=> Update CI_YAML.md to include specific timeout details

app_dart/lib/src/request_handlers/vacuum_github_commits.dart, app_dart/lib/src/service/branch_service.dart, app_dart/lib/src/service/github_service.dart, app_dart/pubspec.lock, app_dart/test/service/branch_service_test.dart, app_dart/test/service/github_service_test.dart, app_dart/test/src/service/fake_github_service.dart, app_dart/test/src/utilities/mocks.mocks.dart
* Rename githubservice.listCommits to listBranchedCommits
* More accurately reflect what it is doing
* Change branch service to use repositories.listCommits
The current implementation fails with the pagination helper getting an empty stream.
Fixes https://github.com/flutter/flutter/issues/112036
=> [app_dart] Fix recipes branching to look at all commits

app_dart/lib/src/service/luci_build_service.dart
Follow up to https://github.com/flutter/cocoon/pull/2699
=> [app_dart] Auto-retry cancelled builds

app_dart/lib/src/model/proto/internal/scheduler.pb.dart, app_dart/lib/src/model/proto/internal/scheduler.pbenum.dart, app_dart/lib/src/model/proto/internal/scheduler.pbjson.dart, app_dart/lib/src/service/branch_service.dart, app_dart/test/service/branch_service_test.dart
https://github.com/flutter/flutter/pull/127087#issuecomment-1553318242
=> [app_dart] Handle possible null values in CreateBranch

app_dart/lib/src/model/ci_yaml/ci_yaml.dart, app_dart/lib/src/service/scheduler.dart, app_dart/pubspec.yaml, app_dart/test/model/ci_yaml/ci_yaml_test.dart, app_dart/test/service/scheduler/graph_test.dart, app_dart/test/service/scheduler_test.dart, app_dart/test/src/service/fake_scheduler.dart, dashboard/pubspec.yaml
Filter out builds removed from main when running for a different branch.
Bug: https://github.com/flutter/flutter/issues/122235
Bug: https://github.com/flutter/flutter/issues/122204
[Discord]: …
=> Filter out builds removed from main.

app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart, app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart, app_dart/test/src/service/fake_scheduler.dart
Fixes: https://github.com/flutter/flutter/issues/127208
=> Skips tasks missed in TOT when backfilling

app_dart/lib/src/request_handlers/github/webhook_subscription.dart, app_dart/test/request_handlers/github/webhook_subscription_test.dart
See for example this change that only touches comments and whitespace: https://github.com/flutter/flutter/pull/127227
=> do not require tests for whitespace only changes

app_dart/lib/src/request_handlers/reset_prod_task.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/test/request_handlers/reset_prod_task_test.dart
* Allow the release team to easily get green commits after infra failures
* Can be used by infra oncall to recover from infra outages
=> [app_dart] Add rerun all support to ResetProdTask

CI_YAML.md
Part of https://github.com/flutter/flutter/issues/127534
=> Update xcode config in CI_YAML doc

app_dart/lib/src/request_handlers/github/webhook_subscription.dart, app_dart/test/request_handlers/github/webhook_subscription_test.dart
Fixes https://github.com/flutter/flutter/issues/126002
=> [app_dart] Remove labeling logic

app_dart/lib/src/model/common/json_converters.dart, app_dart/lib/src/model/gerrit/commit.dart, app_dart/lib/src/model/gerrit/commit.g.dart, app_dart/lib/src/service/branch_service.dart, app_dart/test/model/gerrit/commit_test.dart, app_dart/test/service/branch_service_test.dart, app_dart/test/service/gerrit_service_test.dart, app_dart/test/src/utilities/entity_generators.dart
Fixes https://github.com/flutter/flutter/issues/114626
=> [app_dart] Fix gerrit commit time parsing

auto_submit/README.md
=> Testing revert

app_dart/lib/src/request_handlers/github/webhook_subscription.dart, app_dart/test/request_handlers/github/webhook_subscription_test.dart
Fixes https://github.com/flutter/flutter/issues/127808
=> [app_dart] Skip needs tests on branches

app_dart/lib/src/request_handlers/push_gold_status_to_github.dart, app_dart/test/request_handlers/push_gold_status_to_github_test.dart
Fixes https://github.com/flutter/flutter/issues/129389
=> Add misc shard for gold check

analysis_options.yaml, app_dart/integration_test/validate_all_ci_configs_test.dart, app_dart/lib/src/request_handlers/github/webhook_subscription.dart, app_dart/lib/src/service/config.dart, app_dart/test/request_handlers/vacuum_github_commits_test.dart, app_dart/test/src/datastore/fake_config.dart, auto_submit/lib/validations/ci_successful.dart, dashboard/lib/service/cocoon.dart, dashboard/lib/service/dev_cocoon.dart, dev/githubanalysis/lib/main.dart, oneoff/cirrus_stats/README.md, oneoff/cirrus_stats/model/repository.go
Part of https://github.com/flutter/flutter/issues/122334
=> Clean up legacy codes related to plugins

app_dart/lib/src/request_handlers/github/webhook_subscription.dart, packages/buildbucket-dart/lib/src/generated/go.chromium.org/luci/buildbucket/proto/notification.pb.dart, packages/buildbucket-dart/lib/src/generated/go.chromium.org/luci/buildbucket/proto/notification.pbenum.dart, packages/buildbucket-dart/lib/src/generated/go.chromium.org/luci/buildbucket/proto/notification.pbjson.dart, packages/buildbucket-dart/tool/regenerate.sh
Add the buildbucket v2 notification proto to the infra proto package.
Part of https://b.corp.google.com/issues/268253534 …
=> Add notification to build bucket protos package

packages/buildbucket-dart/lib/buildbucket_pb.dart, packages/buildbucket-dart/pubspec.yaml
Forgot to expose the required objects in the newly created protos.
=> Forgot to expose the notification object and BuildV2 pubsub.

packages/buildbucket-dart/lib/buildbucket_pb.dart, packages/buildbucket-dart/pubspec.yaml
PubsubCallBack is the equivalent to PushMessageEnvelope.
=> Add pubsub callback, the enclosing object

analyze/pubspec.yaml, app_dart/pubspec.yaml, auto_submit/pubspec.yaml, codesign/pubspec.yaml, dashboard/pubspec.yaml, device_doctor/.gitignore, device_doctor/pubspec.yaml, licenses/pubspec.yaml, test_utilities/pubspec.yaml
Fixes: https://github.com/flutter/flutter/issues/110272
=> Pin fixed dependency versions for all apps

app_dart/lib/src/request_handlers/flaky_handler_utils.dart, app_dart/test/request_handlers/check_flaky_builders_test_data.dart, app_dart/test/request_handlers/file_flaky_issue_and_pr_test_data.dart, app_dart/test/request_handlers/update_existing_flaky_issues_test.dart, dev/githubanalysis/lib/issue.dart, dev/githubanalysis/lib/main.dart
We recently changed the priority labels. This updates code in cocoon accordingly.
=> Adjust to new priority schemes

app_dart/lib/src/model/ci_yaml/ci_yaml.dart, app_dart/test/model/ci_yaml/ci_yaml_test.dart
Fixes: https://github.com/flutter/flutter/issues/129736
=> Fix presubmit targets filtering

app_dart/lib/src/request_handlers/flaky_handler_utils.dart, app_dart/lib/src/service/bigquery.dart, app_dart/test/request_handlers/update_existing_flaky_issues_test_data.dart, app_dart/test/service/bigquery_test.dart
Fixes: https://github.com/flutter/flutter/issues/115403
=> Add date range for flaky statistics when updating flake bugs

app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart, app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart
Fixes: https://github.com/flutter/flutter/issues/81702
=> Fix priority issue when backfilling

dashboard/lib/build_dashboard_page.dart, dashboard/lib/logic/task_grid_filter.dart, dashboard/lib/widgets/task_grid.dart, dashboard/test/service/appengine_cocoon_test.dart, dashboard/test/state/build_test.dart, dashboard/test/widgets/task_grid_test.dart
Simple fix to make the searches case insensitive in the dashboard.
Fixes https://github.com/flutter/flutter/issues/102755
Without case: …
=> Make filters insensitive

app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart, app_dart/lib/src/request_handlers/flaky_handler_utils.dart, app_dart/lib/src/service/github_service.dart, app_dart/test/request_handlers/file_flaky_issue_and_pr_test.dart, app_dart/test/src/service/fake_github_service.dart
Fixes: https://github.com/flutter/flutter/issues/112891
=> Add team label to flaky pull requests

.github/autosubmit.yml
Remove autosubmit config files that are no longer being used. This was from a previous design and not longer used.
List which issues are fixed by this PR. You must list at least one issue.
Part of https://github.com/flutter/flutter/issues/130182
[CLA]: …
=> Remove unused autosubmit configuration file

app_dart/pubspec.yaml, app_dart/test/request_handlers/github_webhook_test.dart, app_dart/test/request_handlers/query_github_graphql_test.dart, app_dart/test/src/request_handling/fake_http.dart, auto_submit/test/requests/github_webhook_test.dart
=> Remove unneccessary casts.

app_dart/lib/src/service/scheduler/policy.dart, app_dart/test/service/scheduler/policy_test.dart
Fixes: https://github.com/flutter/flutter/issues/110716
=> Skip scheduling recent failed tasks if an earlier task is already InProgress

auto_submit/lib/requests/github_webhook.dart
Add revert requests to a separate topic in pubsub.
List which issues are fixed by this PR. You must list at least one issue.
Part of https://github.com/flutter/flutter/issues/113867 …
=> Update Autosubmit github-webhook to publish to separate topics for pull requests

app_dart/lib/src/request_handlers/vacuum_github_commits.dart
* Unblock current release by allowing oncalls to vacuum the release branch
=> [app_dart] Support vacuuming release branch commits

dashboard/web/index.html
Hopefully this reduces the number of manual interventions to fix the TV version of the dashboard.
=> Refresh dashboard hourly

app_dart/lib/src/model/appengine/task.dart, app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart, app_dart/test/model/task_test.dart, app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart, app_dart/test/src/utilities/entity_generators.dart
=> Revert "Skip post-submit task status update when build hasn't started"

app_dart/lib/src/model/appengine/task.dart
=> Revert "Encountering scheduled tasks causes 400 error"

app_dart/lib/src/service/datastore.dart, app_dart/pubspec.yaml, app_dart/test/request_handlers/push_gold_status_to_github_test.dart, app_dart/test/service/datastore_test.dart, dashboard/pubspec.yaml
This effectively resets our datastore code to before the changes made while debugging this issue: https://github.com/flutter/flutter/issues/131192. 
The problem was isolated to the dependencies that were updated right before these changes were made. An issue will be opened against gcloud implementation for the Datastore with retries changes: https://github.com/dart-lang/gcloud/pull/168/files. Backing out these changes greatly reduces the number of transaction aborted errors to virtually none. …
=> Put our Datastore impl back to original design with downgrades to grpc, appengine, gcloud packages

auto_submit/lib/service/approver_service.dart, auto_submit/lib/service/pull_request_validation_service.dart, auto_submit/lib/service/revert_request_validation_service.dart, auto_submit/lib/service/validation_service.dart, auto_submit/lib/validations/approval.dart, auto_submit/lib/validations/ci_successful.dart, auto_submit/lib/validations/empty_checks.dart, auto_submit/lib/validations/mergeable.dart, auto_submit/lib/validations/required_check_runs.dart, auto_submit/lib/validations/revert.dart, auto_submit/lib/validations/validation.dart, auto_submit/test/validations/ci_successful_test.dart
Currently there are some intermittent rare issues where autosubmit fails to act on a PR and the log does not help with debugging because there are either no log messages or they are not related to any one pull request.
This PR adds the following:
1. Messages are tied to pull requests with owner/repo/pr_number in the message.
2. Add names to validations so we can log the ones that fail per pull request.
3. Identify checks that cause temporary ignore on a pr or that fail outright.
Part of https://github.com/flutter/flutter/issues/131876
If you need help, consider asking for advice …
=> Autosubmit logging improvements, pr identifiers to log messages for easier debugging

app_dart/lib/src/model/ci_yaml/ci_yaml.dart, app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart, app_dart/test/model/ci_yaml/ci_yaml_test.dart, app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart, app_dart/test/src/service/fake_scheduler.dart
Filter out the ci_yaml rollers from the backfiller.
Fixes https://github.com/flutter/flutter/issues/127063 …
=> Filter out ci_yaml auto roller targets from backfiller

app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart, app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
Fixes: https://github.com/flutter/flutter/issues/132065
=> Fix postsubmit task status update failure due to outdated targets

dev/githubanalysis/analysis_options.yaml, dev/githubanalysis/lib/main.dart, dev/githubanalysis/lib/team.dart
- output had a missing comma
- Duration.toString does not work well with Google Sheets
- PR output didn't include username
- members.txt file parsing was not resilient to empty lines
=> githubanalysis improvements (commas, Durations, PR usernames, etc)

app_dart/bin/server.dart
Related to https://github.com/flutter/flutter/issues/132066
Will need this endpoint actively running in order to add additional logic
=> Add back the create subscription

.cirrus.yml
Cocoon is not running tests on cirrus anymore.
=> Remove cirrus yml file.

app_dart/bin/server.dart, app_dart/lib/src/request_handlers/github/branch_subscription.dart, app_dart/lib/src/service/commit_service.dart, app_dart/test/request_handlers/github/branch_subscription_test.dart, app_dart/test/service/commit_service_test.dart, app_dart/test/src/utilities/mocks.dart, app_dart/test/src/utilities/mocks.mocks.dart
Issue: https://github.com/flutter/flutter/issues/132066
This is based on comments from https://github.com/flutter/cocoon/pull/2991, but the code was significantly different so it made more sense to create a new branch.
When a branch is created, get the associated commit and push it to the datastore with the new branch. This will allow dart-internal builders, which run on a new candidate branch creation, to have a commit to save their task results to. …
=> Insert a new commit on branch creation

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/service/scheduler_test.dart, app_dart/test/src/utilities/entity_generators.dart
Bug:https://github.com/flutter/flutter/issues/130076 …
=> Pass through specific github label to presumit builds

app_dart/bin/server.dart, app_dart/lib/src/request_handlers/presubmit_luci_subscription.dart, app_dart/lib/src/service/github_checks_service.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/test/request_handlers/presubmit_luci_subscription_test.dart, app_dart/test/service/github_checks_service_test.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/src/service/fake_scheduler.dart, app_dart/test/src/utilities/mocks.mocks.dart
Reverts flutter/cocoon#3018
We still need some protobuf plumbing for this. We can reland when Keyong is back.
cc/ @yusuf-goog since you are on call.
=> Revert "Auto retry presubmit failures from rollers"

app_dart/lib/src/service/branch_service.dart, app_dart/test/service/branch_service_test.dart, dashboard/lib/build_dashboard_page.dart, dashboard/lib/service/appengine_cocoon.dart, dashboard/test/service/appengine_cocoon_test.dart, dashboard/test/utils/appengine_cocoon_test_data.dart
* The previous way can show the past 60 days worth of branches
* Instead, only show HEAD, stable, beta, dev
=> Show release channels in build dashboard

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/src/utilities/entity_generators.dart
Fixes: https://github.com/flutter/flutter/issues/134438
=> Populate commit related user data for presubmit rerun

CI_YAML.md
Follow up of https://github.com/flutter/cocoon/pull/3059
=> Add an example for `presubmit_max_attempts` property

auto_submit/README.md
Auto revert has specific conditions to revert a change and there are currently no changes that I can test with that will not cause disruption to the services.
Adding a test comment to the readme. …
=> Add a test comment to readme for automated revert

app_dart/bin/server.dart, app_dart/lib/src/request_handlers/dart_internal_subscription.dart, app_dart/lib/src/request_handlers/github/webhook_subscription.dart, app_dart/lib/src/service/commit_service.dart, app_dart/pubspec.yaml, app_dart/test/request_handlers/github/webhook_subscription_test.dart, app_dart/test/service/commit_service_test.dart, app_dart/test/src/utilities/mocks.mocks.dart, app_dart/test/src/utilities/webhook_generators.dart
* https://github.com/flutter/flutter/issues/133690
* Under the dart-internal build results, add the packaging build to the list of valid builds
* Add handling of `PushEvent` so that when a push to beta/stable is made, the associated commit is added to the datastore
* Manual upgrade of `github` package to utilize `PushEvent` …
=> When packaging builds are run on beta/stable, display on the dashboard

auto_submit/testfile.txt
File to add for revert testing. The revert will work but for some reason double events are getting processed for the same revert PR. This doesn't cause any issues just throws an error that can be ignored but I would rather fix the issue. …
=> Add a file for testing revert

auto_submit/test/testfile.txt
=> Adding a test file.

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/src/utilities/push_message.dart
Fixes: https://github.com/flutter/flutter/issues/134560
=> Fix encode error when auto retry presubmit tasks

.github/dependabot.yml
Several directories were moved to cipd_packages folder but their dependabot references were not updated.
=> Update pubspec locations.

auto_submit/lib/action/git_cli_revert_method.dart, auto_submit/lib/action/revert_method.dart, auto_submit/lib/service/revert_request_validation_service.dart, auto_submit/test/src/action/fake_revert_method.dart
Had some left over test strings that I unfortunately missed when submitting. This has caused some failures in flutter as the default branch there is master.
[CLA]: …
=> Updated to remove hardcoded test strings

cipd_packages/device_doctor/lib/src/android_device.dart, cipd_packages/device_doctor/test/src/android_device_test.dart
Bug:https://github.com/flutter/flutter/issues/135035 …
=> Add deletion of 3p packages to devicedoctor recovery.

CODEOWNERS
This starts tracking ownership of app_dart APIs.
=> Initial ownership for app_dart APIs

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/src/service/fake_buildbucket.dart
Fixes: https://github.com/flutter/flutter/issues/135640
=> Fix github check run rerun branch

cipd_packages/ruby/third_party/ruby_ship/LICENSE.txt, cipd_packages/ruby/third_party/ruby_ship/README, cipd_packages/ruby/third_party/ruby_ship/auto_relink_dylibs.rb, cipd_packages/ruby/third_party/ruby_ship/ruby_ship_build.sh, licenses/check_licenses.dart
This is in preparation to adapt them to flutter use cases.
=> Initial copy of ruby_ship scripts.

app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart
Fixes: https://github.com/flutter/flutter/issues/136361
=> Schedule bringup true targets for guaranteed policy repos

app_dart/lib/src/service/github_checks_service.dart
Fix https://github.com/flutter/flutter/issues/136203.
=> Add a note summary for auto rerun of a presubmit checkrun

cipd_packages/device_doctor/lib/src/android_device.dart
Bug:https://github.com/flutter/flutter/issues/135035 …
=> Making the device_doctor cache cleanup more broad.

dashboard/.metadata, dashboard/android/.gitignore, dashboard/android/app/build.gradle, dashboard/android/app/src/debug/AndroidManifest.xml, dashboard/android/app/src/main/AndroidManifest.xml, dashboard/android/app/src/main/kotlin/com/example/app_flutter/MainActivity.kt, dashboard/android/app/src/main/res/values-night/styles.xml, dashboard/android/app/src/main/res/values/styles.xml, dashboard/android/app/src/profile/AndroidManifest.xml, dashboard/android/build.gradle, dashboard/android/gradle/wrapper/gradle-wrapper.properties, dashboard/android/settings.gradle
```
rm android
flutter create .
```
This fixes `flutter build apk` so we can put the dashboard on the new Android TVs.
=> [dashboard] Fix android build target

cipd_packages/ruby/third_party/ruby_ship/ruby_ship_build.sh, cipd_packages/ruby/tools/build.sh
Some dependencies have additional dependencies that are installed in the systems. This PR ensures all the required dependencies and certs are included in the package.
Bug: https://github.com/flutter/flutter/issues/136377 …
=> Include additional dependencies.

app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart, app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart
Fixes https://github.com/flutter/flutter/issues/136487
Context: https://github.com/flutter/flutter/issues/136487#issuecomment-1778101873
=> Skip backfiller for recently created new targets

cipd_packages/README.md
https://github.com/flutter/flutter/issues/137282
=> Add README for cipd packages

dashboard/lib/main.dart
This enables the TV main activator button to work.
=> Add Shortcuts to handle TV activator button

dashboard/android/app/build.gradle, dashboard/android/app/src/main/AndroidManifest.xml, dashboard/android/app/src/main/kotlin/com/appspot/flutter_dashboard/dashboard/MainActivity.kt, dashboard/lib/build_dashboard_page.dart, dashboard/lib/main.dart, dashboard/lib/service/appengine_cocoon.dart
* Resolve runtime gradle issues
* Fix issue with isolates failing in production mode
* My home Bravia Android TV was able to use arrow up/left/down/right for changing the dashboard, so I hope it works on the ones in the office
=> [dashboard] Fix android TV release mode issues

.github/workflows/no-response_publish.yaml, .github/workflows/no-response_test.yaml
No response workflows only make sense if something changes in the no-response path of the repository.
=> Run only on no-response paths.

.github/workflows/no-response_publish.yaml, .github/workflows/no-response_test.yaml, gh_actions/third_party/no-response/README.md
The paths had a typo preventing the workflows to run.
=> Fix typo in actions workflows.

gh_actions/third_party/no-response/package-lock.json, gh_actions/third_party/no-response/package.json, gh_actions/third_party/no-response/src/no-response.ts
This is to unblock the auto-updates.
=> Manual update of npm deps.

.github/workflows/no-response_test.yaml, gh_actions/third_party/no-response/src/no-response.ts, gh_actions/third_party/no-response/tsconfig.json
Fix build steps to generate the first version.
=> Fix build and add a build step to tests.

cron.yaml
Part of https://github.com/flutter/flutter/issues/128954
=> Enable tree status for packages repository

app_dart/lib/src/service/luci_build_service.dart
Part of https://github.com/flutter/flutter/issues/122117
=> Catch all error exceptions and retry when batch back filling

.github/workflows/no-response_publish.yaml
The release workflow requires additional permissions to post the release.
=> Fix permissions issue.

.github/workflows/no-response_publish.yaml
Tags were harcoded during testing and not returned to their previous state.
=> Remove hardcoded tags.

dashboard/lib/widgets/task_icon.dart
This is so all web tests show using the Chromium icon rather than OS icon.
=> fix web shard icons

dashboard/lib/build_dashboard_page.dart, dashboard/test/build_dashboard_page_test.dart
Fixes: https://github.com/flutter/flutter/issues/138185
=> Add infra ticket queue link to dashboard

cipd_packages/codesign/lib/src/file_codesign_visitor.dart, cipd_packages/codesign/test/file_codesign_visitor_test.dart
=> [codesign] Add verbose flag to notarytool submit

.github/dependabot.yml
This is to autoland NPM dependabot PRs if they pass tests.
=> Add autosubmit label to dependabot npm PRs.

app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart
See https://github.com/flutter/flutter/issues/138559.
The `test: all` label should not skip presubmits, since that sort of defeats the point :)
/cc @gaaclarke @dnfield
=> Change `test: all` labels to also skip `runIf[Not]s`, since the goal is to run all 😎 

CODEOWNERS, triage_bot/.gitignore, triage_bot/Dockerfile, triage_bot/README.md, triage_bot/analysis_options.yaml, triage_bot/app.yaml, triage_bot/bin/triage_bot.dart, triage_bot/cloudbuild_triage_bot.yaml, triage_bot/cloudbuild_triage_bot_deploy.yaml, triage_bot/lib/bytes.dart, triage_bot/lib/discord.dart, triage_bot/lib/engine.dart, triage_bot/lib/json.dart, triage_bot/lib/utils.dart, triage_bot/pubspec.yaml, triage_bot/test/bytes_test.dart, triage_bot/test/discord_test.dart, triage_bot/test/json_test.dart, triage_bot/test/utils_test.dart
This is the code that's been running for a few weeks now. It's time to get it onto Appengine.
=> Triage Bot 1.0

app_dart/lib/src/model/ci_yaml/target.dart, app_dart/test/model/ci_yaml/target_test.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/src/utilities/entity_generators.dart
Fixes https://github.com/flutter/flutter/issues/139313
=> [scheduler] Add recipe property to support releases

app_dart/lib/src/service/config.dart, triage_bot/lib/discord.dart, triage_bot/test/discord_test.dart
More scaleable than listing people's names 1-by-1. Yay!
=> Replace hixie@ with @test-exemption-reviewers.

auto_submit/lib/model/auto_submit_query_result.dart, auto_submit/lib/model/auto_submit_query_result.g.dart, auto_submit/lib/requests/graphql_queries.dart, auto_submit/lib/service/config.dart, auto_submit/lib/validations/ci_successful.dart, auto_submit/lib/validations/validation.dart, auto_submit/test/model/auto_submit_query_result_test.dart, auto_submit/test/validations/ci_successful_test.dart
This PR creates a warning to GCP log when PR hangs. 
A follow up to to setup an alert based on the flagged logs.
First part of https://github.com/flutter/flutter/issues/125451
=> Flag stale PRs when any github check hangs >2 hours

app_dart/lib/src/service/config.dart
=> Fix typo in handle to tag if pr author needs a test exemption

CODEOWNERS, app_dart/bin/server.dart, app_dart/lib/cocoon_service.dart, app_dart/lib/src/request_handlers/get_build_status.dart, app_dart/lib/src/request_handlers/get_build_status_badge.dart, app_dart/test/request_handlers/get_build_status_badge_test.dart
* Enable us to track Flutter CI in the READMEs
https://github.com/flutter/flutter/issues/140460
=> [app_dart] Add BuildStatus badge endpoint

CODEOWNERS
Follow up from https://github.com/flutter/cocoon/pull/3363#pullrequestreview-1793390582
=> Update CODEOWNERS to have me on badge API

app_dart/lib/src/request_handlers/get_build_status_badge.dart
Missed in initial design until I saw it on a README :-)
https://github.com/flutter/flutter/issues/140460
=> Fix right side rounded corners on ci badge

cron.yaml
Fixes: https://github.com/flutter/flutter/issues/140813
=> Correct cronjob format to fix parse errors

cloud_build/get_docker_image_provenance.sh, cron.yaml
* Remove the provenance injection workaround, as provenance should be correctly created now, and slsa-verifier 2.4.1 no longer requires this piece anyway
[Discord]: …
=> Remove slsa-verifier tech debt

.github/dependabot.yml
* Add staggered intervals
* Reduce merge conflicts on Cocoon PRs
* Save some capacity
=> Reduce dependabot updates to weekly in off peak hours

auto_submit/lib/service/approver_service.dart, auto_submit/pubspec.yaml
Same as https://github.com/flutter/cocoon/pull/3386 with a fix.
=> Add null check when bumping github version

analysis_options.yaml
Issue reference: https://github.com/flutter/flutter/issues/141576
=> Remove analysis config for removed `missing_return` diagnostic

app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart, app_dart/test/request_handlers/file_flaky_issue_and_pr_test.dart
Fixes: https://github.com/flutter/flutter/issues/142073
=> Skip flake status check when target no longer exists

CI_YAML.md
=> Add doc about `contexts` property

dev/provision_salt.sh
There is a breaking deprecation in salt-minion 3006.5 and we need to stick to a compatible older version of the minion till we upgrade our code.
Bug:https://github.com/flutter/flutter/issues/142627 …
=> Setting the salt-minion source correctly.

app_dart/lib/src/service/firestore.dart, app_dart/test/service/firestore_test.dart
Fixes: https://github.com/flutter/flutter/issues/143187
=> Use empty string instead of null

app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
Help with https://github.com/flutter/flutter/issues/143497
=> Add logs to help triage Firestore task update failure

app_dart/lib/src/model/firestore/task.dart, app_dart/lib/src/request_handlers/update_task_status.dart, app_dart/test/request_handlers/update_task_status_test.dart, cloud_build/verify_provenance.sh
=> Supports Firestore task update for /api/update-task-status

app_dart/lib/src/request_handlers/push_gold_status_to_github.dart, app_dart/test/request_handlers/push_gold_status_to_github_test.dart, auto_submit/lib/validations/ci_successful.dart, auto_submit/test/validations/ci_successful_test.dart
These checks are out of date:
- It's `web_engine` not `web engine`
- We're missing Impeller, Scenario App goldens for the native engine entirely
/cc @mdebbar as well.
I also filed https://github.com/flutter/flutter/issues/143863 since it's likely we'll drift again in the future.
=> Update status checks for Gold Status -> Github

CI_YAML.md
Part of https://github.com/flutter/flutter/issues/143671
This PR lists/consolidates all supported properties in .ci.yaml.
=> Update CI_YAML doc about properties/dimensions

app_dart/lib/src/model/firestore/commit.dart, app_dart/lib/src/model/firestore/task.dart, app_dart/lib/src/service/firestore.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/model/firestore/commit_test.dart, app_dart/test/service/firestore_test.dart, app_dart/test/src/utilities/entity_generators.dart
Help with https://github.com/flutter/flutter/issues/142951
=> Create firestore commit model and reference it everywhere

app_dart/lib/src/request_handlers/reset_prod_task.dart, app_dart/test/request_handlers/reset_prod_task_test.dart
Fixes: https://github.com/flutter/flutter/issues/144236
=> Fix null sha/task values when resetting prod task

app_dart/lib/src/service/commit_service.dart, app_dart/test/service/commit_service_test.dart
Fixes: https://github.com/flutter/flutter/issues/144260
=> Write branch point commits to firestore

app_dart/lib/src/request_handlers/dart_internal_subscription.dart, app_dart/test/request_handlers/dart_internal_subscription_test.dart
Part of https://github.com/flutter/flutter/issues/142951 for releases branch support.
=> Write dart-internal tasks to Firestore

cipd_packages/README.md
More context: https://github.com/flutter/cocoon/pull/3522#issuecomment-1967383477
=> Update cipd_package doc covering how artifacts are generated and uploaded

analyze/analyze.dart
This is to prevent failures in trying to analyze zip file contents. …
=> Ignoring .zip files in analyze.

gh_actions/third_party/no-response/package-lock.json, gh_actions/third_party/no-response/package.json
Dependabot updates were failing in transitive deps.
=> Manual update of npm dependencies.

app_dart/pubspec.yaml, app_dart/test/request_handlers/check_flaky_builders_test.dart
Dependabot PR was failing and this change manually addresses the roll.
Addresses issue: https://github.com/flutter/flutter/issues/144955
=> Manual Github upgrade

app_dart/lib/src/request_handlers/push_gold_status_to_github.dart, app_dart/lib/src/service/firestore.dart, app_dart/test/request_handlers/push_gold_status_to_github_test.dart, app_dart/test/service/firestore_test.dart
Fixes: https://github.com/flutter/flutter/issues/144856
=> Fix null check error when querying Firestore

cipd_packages/README.md
I noticed this typo while following the steps, figured I would fix it
=> Single typo fix in cipd readme

app_dart/test/service/firestore_test.dart, cipd_packages/README.md
Fixes: https://github.com/flutter/flutter/issues/145038
=> Update cipd write access doc

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart, cloud_build/verify_provenance.sh
Help https://github.com/flutter/flutter/issues/145736
=> Update task status first before rescheduling

cipd_packages/README.md
Add doc how to add a tag to a cipd instance.
Context: https://github.com/flutter/flutter/pull/143478
=> Update cipd package doc how to add a tag

app_dart/lib/src/model/firestore/commit.dart, app_dart/lib/src/model/firestore/commit_tasks_status.dart, app_dart/lib/src/model/firestore/task.dart, app_dart/test/model/firestore/commit_test.dart, app_dart/test/model/firestore/task_test.dart
Fixes: https://github.com/flutter/flutter/issues/146839
=> Skip toJson override in Firestore data models

dev/githubanalysis/README.md, dev/githubanalysis/lib/issue.dart, dev/githubanalysis/lib/main.dart
Adds link to updated spreadsheet.
Adds workaround for https://github.com/SpinlockLabs/github.dart/issues/401
=> Updates to github analysis

dashboard/web/flutter_bootstrap.js, dashboard/web/index.html
This PR updates the web bootstrap to the latest version.
The latest version should load faster, and enable Wasm (when available).
* Part of: https://github.com/flutter/flutter/issues/139170 …
=> [web] Update bootstrap to latest version.

dashboard/lib/model/task_firestore.pb.dart, dashboard/lib/model/task_firestore.pbjson.dart, dashboard/lib/model/task_firestore.proto, dashboard/lib/service/appengine_cocoon.dart, dashboard/test/service/appengine_cocoon_test.dart, dashboard/test/utils/appengine_cocoon_test_data.dart
This is a follow up of https://github.com/flutter/cocoon/pull/3669 to support `buildList` in frontend data model.
=> Add buildList field in Frontend task model

dashboard/lib/model/task_firestore.pb.dart, dashboard/lib/model/task_firestore.pbjson.dart, dashboard/lib/model/task_firestore.proto, dashboard/lib/service/appengine_cocoon.dart, dashboard/test/service/appengine_cocoon_test.dart, dashboard/test/utils/appengine_cocoon_test_data.dart
Follow up of https://github.com/flutter/cocoon/pull/3672 to add the field in frontend.
=> Add commit sha to Frontend task data model

triage_bot/lib/discord.dart, triage_bot/test/discord_test.dart
See https://github.com/flutter/flutter/issues/150869.
=> Point engine docs from flutter/docs/engine to flutter/engine/docs.

app_dart/README.md, app_dart/protofu.yaml
protofu downloads the right version of protoc/plugins and just works.
Also updated instructions for regenerating.
=> Update instructions to use protofu

app_dart/lib/src/model/ci_yaml/ci_yaml.dart, app_dart/lib/src/model/ci_yaml/target.dart, app_dart/lib/src/request_handlers/check_flaky_builders.dart, app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart, app_dart/lib/src/request_handlers/update_existing_flaky_issues.dart, app_dart/test/model/ci_yaml/ci_yaml_test.dart, app_dart/test/model/ci_yaml/target_test.dart, app_dart/test/request_handlers/file_flaky_issue_and_pr_test.dart, app_dart/test/request_handlers/file_flaky_issue_and_pr_test_data.dart, app_dart/test/src/service/fake_scheduler.dart
Targets should be able to define higher or lower threshold limits.
Fixes flutter/flutter#151195
=> Add target property `flakiness_threshold`

app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart
The label will still have to be created, but should now apply to both repos.
=> Allow using the `test: all` label in flutter/flutter.

auto_submit/cloudbuild_auto_submit_deploy.yaml, triage_bot/cloudbuild_triage_bot_deploy.yaml
See https://github.com/flutter/cocoon/pull/3835
=> Use a consistent version of Golang in all cloud build configurations

triage_bot/lib/engine.dart
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: …
=> add accessibility team

cipd_packages/codesign/lib/src/utils.dart
Hopefully address: https://github.com/flutter/flutter/issues/157016
=> //cipd_packages/codesign delete any .DS_Store files in archives

app_dart/lib/src/service/config.dart
Without this, flaux doesn't work on cocoon.
=> Add flaux slug for testing

app_dart/lib/src/foundation/utils.dart, app_dart/lib/src/model/ci_yaml/ci_yaml.dart, app_dart/lib/src/request_handlers/github/webhook_subscription.dart, app_dart/test/foundation/utils_test.dart
Monorepo checks are if a ref or PR is based on a tree with DEPS and engine/src/.gn.
=> Add isFusion checks

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart
"Slug" not used in several places; and I'm getting dinged on trailing commas...
=> Cleanup dead / unused code

app_dart/lib/server.dart, app_dart/lib/src/foundation/utils.dart, app_dart/lib/src/request_handlers/github/webhook_subscription.dart, app_dart/lib/src/request_handling/request_handler.dart, app_dart/test/foundation/utils_test.dart, app_dart/test/request_handlers/github/webhook_subscription_test.dart, app_dart/test/src/service/fake_fusion_tester.dart
* Make FusionTester class for easier faking and testing.
* Fetch file list ahead of time - we don't want to fetch these 2x
* Count type of files changed
=> Fusion: apply engine labels

app_dart/lib/src/foundation/utils.dart, app_dart/test/foundation/utils_test.dart
We want to test flaux as well.
=> Don't forget the flauxSlug for testing fusion

auto_submit/lib/service/validation_service.dart, auto_submit/test/service/pull_request_validation_service_test.dart
Based on local testing, Github prefers the SHA of the head PR as "OID".
=> pass pr.head.sha as expectedHeadOid

app_dart/lib/src/foundation/utils.dart, app_dart/lib/src/request_handlers/github/webhook_subscription.dart, app_dart/test/foundation/utils_test.dart, app_dart/test/src/service/fake_fusion_tester.dart
- remove isFusionBasedPR looking for "base" - lets just check the sha
- cache results (in memory) of slug/sha fusion test
- add a test showing the cache works.
- add a little more logging to help debug
=> Attempt to fix post submit bots slacking off

auto_submit/lib/service/validation_service.dart, auto_submit/test/service/pull_request_validation_service_test.dart
Fixing an oopsie from my previous PR
=> [mq] use PR number, not id

auto_submit/lib/service/pull_request_validation_service.dart, auto_submit/lib/service/revert_request_validation_service.dart, auto_submit/lib/service/validation_service.dart, auto_submit/test/service/pull_request_validation_service_test.dart, auto_submit/test/service/revert_request_validation_service_test.dart
Fixes https://github.com/flutter/flutter/issues/159518
=> fix revert enqueue cycle; ack pubsub

app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart
- library doesn't handle this even though it encodes it.
=> Remove bad json for CheckRuns

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart
This test is apparently hard coded to use flutter.  You can see the results here: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8728908416980782449/+/u/validate_test_ownership/stdout
=> Set the git_repo property for Linux test_ownership

auto_submit/lib/service/validation_service.dart, auto_submit/test/service/pull_request_validation_service_test.dart
Fixes https://github.com/flutter/flutter/issues/159916
=> [mq] merge instead of enqueuing for release branches

app_dart/lib/src/model/ci_yaml/ci_yaml.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/service/scheduler_test.dart
1. Collect post submits from the engine repo if its fusion
2. When scheduling; set the property 'is_fusion'
=> Schedule post submits for fusion engine

auto_submit/lib/requests/github_webhook.dart, auto_submit/test/requests/github_webhook_test.dart, auto_submit/test/requests/github_webhook_test_data.dart
Temporarily disable autosubmit.
Tracking reverting this in https://github.com/flutter/flutter/issues/160451
=> [autosubmit] disable autosubmit for flutter/flutter & flutter/engine

app_dart/lib/src/service/config.dart
The repos have merged. Let's restore the backfill.
=> restore backfill limit

app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart, app_dart/lib/src/request_handlers/presubmit_luci_subscription.dart, app_dart/lib/src/request_handlers/reset_prod_task.dart, app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart, app_dart/lib/src/service/scheduler.dart
CiYaml **sets** already have all the CiYamls in them.
=> Handle dangling fusion tests.

app_dart/lib/src/request_handlers/presubmit_luci_subscription.dart
=> Fix missing target in luci presubmit handler

app_dart/lib/src/model/appengine/task.dart, app_dart/lib/src/model/ci_yaml/ci_yaml.dart, app_dart/lib/src/model/ci_yaml/target.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/model/ci_yaml/ci_yaml_test.dart
Fixes https://github.com/flutter/flutter/issues/160620
=> [monorepo] fix post-submit bringup targets

auto_submit/lib/requests/github_webhook.dart, auto_submit/test/requests/github_webhook_test.dart, auto_submit/test/requests/github_webhook_test_data.dart
Revert "[autosubmit] disable autosubmit for flutter/flutter & flutter/engine (#4098)"
This reverts commit aba8be434c2c42e6f91123068cbab3c899bd090c.
=> Reenable autosubmit

app_dart/lib/src/request_handlers/presubmit_luci_subscription.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart, app_dart/test/request_handlers/presubmit_luci_subscription_test.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/src/utilities/build_bucket_messages.dart
The merge queue is expensive; and all tests must pass. We should retry failed tests if they were flaky.
This was very rough because the tests are very much not well.
=> When scheduling merge queue builds; tag them as such.

cloud_build/dashboard_build.sh
=> Stop gap: build from stable

dashboard/lib/logic/qualified_task.dart, dashboard/lib/logic/task_grid_filter.dart, dashboard/test/build_dashboard_page_test.dart, dashboard/test/logic/task_grid_filter_test.dart, dashboard/test/widgets/task_grid_test.dart, dashboard/test/widgets/task_overlay_test.dart
Closes https://github.com/flutter/flutter/issues/160697.
I did test that it is possible to show bringup builds (and the query parameters works, for example).
---
There are a _lot_ of ways this code[base] could be better, but intentionally tried to limit the amount of changes in this PR.
(I would be happy to try and improve things in Q1 if we decide this is valuable to do)
/cc @jtmcdole
=> Allow showing, and hide `bringup` builds by default.

dashboard/lib/logic/task_grid_filter.dart, dashboard/test/logic/task_grid_filter_test.dart
Closes https://github.com/flutter/flutter/issues/160927.
=> Remove staging filter

app_dart/lib/src/request_handlers/github/webhook_subscription.dart, app_dart/test/request_handlers/github/webhook_subscription_test.dart
test/flutter_test_config.dart is a test configuration file, so should not trigger the testing requirement.
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: …
=> Exempt leak test config files

app_dart/lib/src/foundation/utils.dart, app_dart/lib/src/request_handlers/github/webhook_subscription.dart, app_dart/lib/src/service/config.dart, app_dart/test/foundation/utils_test.dart, app_dart/test/model/firestore/ci_staging_test.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/service/scheduler_test.dart
Flaux has served its purpose. Thanks, Flaux!
=> Remove Flaux

auto_submit/lib/service/validation_service.dart, auto_submit/test/requests/check_pull_request_test.dart, auto_submit/test/service/pull_request_validation_service_test.dart, auto_submit/test/service/revert_request_validation_service_test.dart
Remove remaining mentions of "flaux".
=> [monorepo] remove more of flaux

app_dart/lib/src/service/config.dart
With the engine merged into flutter; there will be more commits to one repository.
=> Increase dashboard backfill limit by 50%

app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart
Partial fix for: https://github.com/flutter/flutter/issues/161319
=> Unlock merge group lock for revertbot

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart
This should fix flutter/flutter#161384
=> If gitiles is empty; don't add it to reschedule

app_dart/lib/src/foundation/utils.dart, app_dart/test/foundation/utils_test.dart
Mitigates https://github.com/flutter/flutter/issues/161462.
=> Be conservative about `runIf` when files changed >= 30.

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/src/utilities/mocks.mocks.dart
see https://github.com/flutter/flutter/issues/162201
=> Pass along flutter_prebuilt_engine_version if so requested

app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart
=> `ref` -> `sha`

app_dart/lib/src/service/scheduler.dart
See https://github.com/flutter/cocoon/pull/4185#pullrequestreview-2576554209.
=> `changes` -> `check for revert request`

app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart
Closes https://github.com/flutter/flutter/issues/162201.
https://github.com/flutter/flutter/pull/162294 needs to merge first 🫡 .
=> Enable framework-only PR optimizations.

app_dart/lib/src/service/luci_build_service.dart
=> Use the correct `flutter_realm` for retries.

auto_submit/lib/service/pull_request_validation_service.dart, auto_submit/test/requests/check_pull_request_test.dart, auto_submit/test/src/service/fake_github_service.dart
Fixes https://github.com/flutter/flutter/issues/162288
=> use head SHA when looking for merge guard

app_dart/lib/src/foundation/github_checks_util.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart, app_dart/test/src/utilities/mocks.mocks.dart
Towards fixing flutter/flutter#162319
=> Tell users about failures.

auto_submit/lib/requests/check_pull_request.dart, auto_submit/lib/service/pull_request_validation_service.dart, auto_submit/test/requests/check_pull_request_test.dart, auto_submit/test/requests/github_webhook_test_data.dart, auto_submit/test/src/service/fake_github_service.dart
Might shed some light on what's happening with the `emergency` label.
=> Catch and log uncaught errors

app_dart/lib/src/service/config.dart
100->75; i can be swayed for the original 50.
=> Reduce backfill pressure while we sort out ToT

app_dart/lib/src/service/scheduler.dart
Closes https://github.com/flutter/flutter/issues/162403.
=> Never run the framework optimization on a release branch.

app_dart/lib/src/request_handlers/push_build_status_to_github.dart, app_dart/lib/src/service/config.dart
Nits that were missed with autosubmit
=> Comments from #4212

app_dart/lib/src/request_handlers/github/webhook_subscription.dart, app_dart/test/request_handlers/github/webhook_subscription_test.dart, app_dart/test/src/service/fake_github_service.dart, app_dart/test/src/utilities/mocks.mocks.dart
=> Leave educational information on `emergency` PRs

tooling/go.mod
=> `go mod tidy`

app_dart/lib/src/request_handlers/github/webhook_subscription.dart, app_dart/lib/src/service/github_service.dart, app_dart/test/request_handlers/github/webhook_subscription_test.dart, app_dart/test/src/service/fake_github_service.dart
Should fix flutter/flutter#163031
=> Only leave one comment for emergency label

app_dart/integration_test/validate_all_ci_configs_test.dart, app_dart/lib/src/request_handlers/create_branch.dart, app_dart/lib/src/request_handlers/github/webhook_subscription.dart, app_dart/lib/src/request_handlers/push_gold_status_to_github.dart, app_dart/lib/src/service/branch_service.dart, app_dart/lib/src/service/config.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/request_handlers/github/webhook_subscription_test.dart, app_dart/test/request_handlers/push_gold_status_to_github_test.dart, app_dart/test/request_handlers/vacuum_github_commits_test.dart, app_dart/test/service/branch_service_test.dart, app_dart/test/service/datastore_test.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/service/scheduler_test.dart, app_dart/test/src/datastore/fake_config.dart, auto_submit/lib/service/config.dart, auto_submit/lib/validations/ci_successful.dart, auto_submit/test/validations/ci_successful_test.dart, dashboard/lib/build_dashboard_page.dart, dashboard/lib/service/cocoon.dart, dashboard/lib/service/dev_cocoon.dart, dashboard/test/build_dashboard_page_test.dart, dashboard/test/service/appengine_cocoon_test.dart, dashboard/test/utils/appengine_cocoon_test_data.dart, dashboard/test/utils/fake_build.dart, dev/githubanalysis/lib/main.dart
We've made two releases with monorepo. The engine is no longer needed and should be archived.
=> Remove the engine slug

app_dart/lib/src/service/scheduler.dart, app_dart/test/model/firestore/pr_check_runs_test.dart, app_dart/test/request_handlers/github/webhook_subscription_test.dart, app_dart/test/request_handlers/push_build_status_to_github_test.dart, app_dart/test/service/scheduler_test.dart, app_dart/test/src/utilities/entity_generators.dart
Closes https://github.com/flutter/flutter/issues/164031.
=> Always set `FLUTTER_PREBUILT_ENGINE_VERSION` for framework-stage PRs.

app_dart/lib/src/service/scheduler.dart
Mitigates https://github.com/flutter/flutter/issues/164342.
=> Mitigate a crash caused by not finding a presubmit target on a checkRun

app_dart/lib/src/request_handlers/presubmit_luci_subscription.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/lib/src/service/luci_build_service/build_tags.dart, app_dart/test/service/build_tags_test.dart, app_dart/test/service/luci_build_service_test.dart
Oops, it's a `List<Tag>` not `Set<Tag>`, my mistake; so fix that, and continue migrating.
I removed `pr/git/PR` since it doesn't even say what repo the PR belongs to and there are other tags associated with that information.
=> Fix missed assumptions in build tag set and continue migration

app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart, app_dart/test/src/utilities/mocks.mocks.dart
Closes https://github.com/flutter/flutter/issues/164345.
That was a doozy. Thanks for the pointers!
=> Support rerunning tests declared in the engine `.ci.yaml`.

cipd_packages/ktlint/ktlint_metadata.txt
Part of #flutter/flutter/issues/164408
=> Update ktlint to 1.5

app_dart/lib/src/request_handlers/presubmit_luci_subscription.dart, app_dart/lib/src/service/config.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/lib/src/service/luci_build_service/build_tags.dart, app_dart/lib/src/service/luci_build_service/cipd_version.dart, app_dart/test/service/build_tags_test.dart, app_dart/test/src/datastore/fake_config.dart, app_dart/test/src/utilities/mocks.mocks.dart
Towards https://github.com/flutter/flutter/issues/164242.
One last set needs to be changed after this, but it can wait until after the weekend.
=> Convert more `bbv2.StringPair()`, and create a `CipdVersion` struct.

app_dart/lib/src/service/luci_build_service.dart, app_dart/lib/src/service/luci_build_service/build_tags.dart, app_dart/test/service/build_tags_test.dart
Closes https://github.com/flutter/flutter/issues/164242.
=> Finish moving the remaining `bbv2.StringPair` literals to `BuildTag`s.

dashboard/test/utils/golden.dart
Closes https://github.com/flutter/flutter/issues/164551.
=> Add a base64 encoded image to save my sanity.

app_dart/lib/src/service/luci_build_service.dart, app_dart/lib/src/service/luci_build_service/cipd_version.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/src/service/fake_gerrit_service.dart
Closes https://github.com/flutter/flutter/issues/164592.
=> Fix a bug in how we fallback to default recipe bundles.

app_dart/lib/src/request_handlers/get_release_branches.dart, app_dart/lib/src/service/branch_service.dart, app_dart/lib/src/service/branch_service.g.dart, app_dart/lib/src/service/config.dart, app_dart/test/server_test.dart, app_dart/test/service/branch_service_test.dart, app_dart/test/service/gerrit_service_test.dart, app_dart/test/src/datastore/fake_config.dart, app_dart/test/src/utilities/mocks.mocks.dart, dashboard/lib/service/appengine_cocoon.dart, dashboard/test/service/appengine_cocoon_test.dart, dashboard/test/utils/appengine_cocoon_test_data.dart
Closes https://github.com/flutter/flutter/issues/164644.
=> Refactor `BranchService`, replace `dev` with `staging`, clean up tests.

Dockerfile.app_dart, Dockerfile.auto_submit
Closes https://github.com/flutter/flutter/issues/164719.
=> Use the latest Dart stable in Dockerfile.

analysis_options.yaml, app_dart/lib/src/request_handlers/dart_internal_subscription.dart, app_dart/lib/src/request_handlers/github/webhook_subscription.dart, app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart, app_dart/lib/src/request_handlers/presubmit_luci_subscription.dart, app_dart/lib/src/service/commit_service.dart, app_dart/test/request_handlers/github_webhook_test.dart, app_dart/test/request_handlers/presubmit_luci_subscription_test.dart, app_dart/test/service/github_checks_service_test.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/service/scheduler_test.dart, auto_submit/lib/configuration/repository_configuration.dart, auto_submit/lib/requests/github_webhook.dart, cipd_packages/device_doctor/bin/main.dart, cipd_packages/device_doctor/lib/src/ios_debug_symbol_doctor.dart, dashboard/lib/logic/task_grid_filter.dart, dashboard/lib/service/appengine_cocoon.dart, triage_bot/lib/engine.dart
This was ignored temporarily during https://github.com/flutter/cocoon/pull/4295.
=> Re-enable `invalid_assignments` by fixing every existing violation.

app_dart/lib/src/service/luci_build_service/user_data.dart
Closes https://github.com/flutter/flutter/issues/164804.
=> Fix `invalid_assignment` breakage.

Dockerfile.app_dart
Closes https://github.com/flutter/flutter/issues/165011.
=> Copy `../packages` so Docker can resolve it for `app_dart`.

analysis_options.yaml, app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart, app_dart/lib/src/service/datastore.dart, app_dart/test/model/ci_yaml/target_test.dart, app_dart/test/model/firestore/commit_tasks_status_test.dart, app_dart/test/request_handlers/get_green_commits_test.dart, app_dart/test/request_handlers/get_status_firestore_test.dart, app_dart/test/request_handlers/get_status_test.dart, app_dart/test/service/scheduler_test.dart, auto_submit/lib/service/validation_service.dart, auto_submit/lib/validations/required_check_runs.dart, auto_submit/test/src/service/fake_graphql_client.dart, cipd_packages/device_doctor/lib/src/ios_debug_symbol_doctor.dart, dashboard/lib/build_dashboard_page.dart, dashboard/lib/widgets/filter_property_sheet.dart, test_utilities/bin/global_test_runner.dart
That's all the egregious ones!
=> Remove more `errors: ignore: ...` in root `analysis_options.yaml`

app_dart/lib/server.dart, app_dart/lib/src/request_handlers/trigger_workflow.dart, licenses/check_licenses.dart
1. This is temporary - its not critical, nor is it mission critical
2. We'll delete this if we choose to do content aware hashing
=> Add temporary API to trigger dispatch enabled workflows

app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart
Towards https://github.com/flutter/flutter/issues/163896.
Let's test in prod!
=> Skip scheduling post-submit tasks for `'flutter-0.42-candidate.0'`

app_dart/lib/src/request_handlers/rerun_prod_task.dart, app_dart/test/request_handlers/rerun_prod_task_test.dart, app_dart/test/src/service/fake_scheduler.dart
Closes https://github.com/flutter/flutter/issues/165522.
=> Add some target protection to `RerunProdTask`.

app_dart/test/service/branch_service_test.dart, app_dart/test/src/utilities/entity_generators.dart
Closes https://github.com/flutter/flutter/issues/165598.
=> Use deterministic dates for fake commits.

dashboard/lib/model/task.pb.dart, dashboard/lib/model/task.pbjson.dart, dashboard/lib/model/task.proto, dashboard/lib/service/appengine_cocoon.dart, dashboard/lib/service/dev_cocoon.dart, dashboard/test/service/appengine_cocoon_test.dart, dashboard/test/widgets/task_overlay_test.dart
Towards https://github.com/flutter/flutter/issues/165025.
This makes it easier to understand what needs to be created in the eventual `task.dart`.
=> Remove fields from `dashboard/task.proto` that are unused.

dashboard/web/index.html
Cribbed from [`flutter_tools/templates/app/web/index.html.tmpl`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app/web/index.html.tmpl).
=> Use updated `index.html`.

app_dart/lib/src/request_handlers/check_flaky_builders.dart
... to try and get some indication of what is causing https://github.com/flutter/flutter/issues/165903.
=> Add some logging to `check_flaky_builders`.

app_dart/lib/src/service/config.dart, app_dart/test/src/datastore/fake_config.dart
=> Remove unused datastore dependency in config.

app_dart/lib/src/model/firestore/commit_tasks_status.dart, app_dart/lib/src/model/firestore/task.dart, app_dart/lib/src/request_handlers/dart_internal_subscription.dart, app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart, app_dart/lib/src/request_handlers/scheduler/vacuum_stale_tasks.dart, app_dart/lib/src/service/firestore.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/model/firestore/task_test.dart, app_dart/test/request_handlers/dart_internal_subscription_test.dart, app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart, app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart, app_dart/test/request_handlers/scheduler/vacuum_stale_tasks_test.dart, app_dart/test/src/utilities/entity_generators.dart
=> Stop using the (external) field names of `Task` outside of the `Task` class

app_dart/lib/src/model/firestore/pr_check_runs.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/test/model/firestore/pr_check_runs_test.dart, app_dart/test/service/luci_build_service_test.dart
Closes https://github.com/flutter/flutter/issues/166014.
Works around https://github.com/flutter/flutter/issues/166022.
=> Fix and add regression tests for `override: ` label handeling

app_dart/lib/src/model/ci_yaml/ci_yaml.dart, app_dart/lib/src/request_handlers/presubmit_luci_subscription.dart
Mitigates https://github.com/flutter/flutter/issues/166274.
=> Guard aginst an invalid .ci.yaml triggering an infinite Cloud PubSub.

app_dart/lib/src/service/firestore.dart
Resolves an issue around task re-runs from the dashboard.
=> Fix a bug where `full/path/to/doc` was used instead of `to/doc`.

app_dart/lib/src/model/firestore/base.dart, app_dart/lib/src/model/firestore/ci_staging.dart, app_dart/lib/src/model/firestore/commit.dart, app_dart/lib/src/model/firestore/github_build_status.dart, app_dart/lib/src/model/firestore/github_gold_status.dart, app_dart/lib/src/model/firestore/pr_check_runs.dart, app_dart/lib/src/model/firestore/task.dart, app_dart/lib/src/request_handlers/rerun_prod_task.dart, app_dart/lib/src/service/commit_service.dart, app_dart/lib/src/service/firestore.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/lib/src/service/luci_build_service/firestore_task_document_name.dart, app_dart/lib/src/service/luci_build_service/user_data.dart, app_dart/lib/src/service/luci_build_service/user_data.g.dart, app_dart/test/model/firestore/task_test.dart, app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart, app_dart/test/request_handlers/push_build_status_to_github_test.dart, app_dart/test/request_handlers/push_gold_status_to_github_test.dart, app_dart/test/service/luci_build_service/user_data_test.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/service/scheduler_test.dart, app_dart/test/src/utilities/entity_generators.dart, app_dart/test/src/utilities/mocks.mocks.dart
This reverts commit 710142b6b16845d4094fd5700e3c572e593b7960.
_Speculative_ fix for https://github.com/flutter/flutter/issues/166463.
=> Revert "Finish adopting `AppDocument<T>` across Firestore models"

app_dart/lib/src/request_handling/subscription_handler.dart, app_dart/test/request_handling/subscription_handler_test.dart
Closes https://github.com/flutter/flutter/issues/166475.
=> Clear the write lock on PubSub messages that are requesting a 5XX retry

app_dart/lib/src/request_handlers/dart_internal_subscription.dart
Towards https://github.com/flutter/flutter/issues/166535.
I'd like to know what the type is instead of guessing, so we'll test it in prod[^1]
[^1]: With log statements
=> Try parsing a `bbv2.BuildV2PubSub` instead of `json[][][]`.

app_dart/lib/server.dart, app_dart/lib/src/request_handlers/get_engine_artifacts_ready.dart, app_dart/test/request_handlers/get_engine_artifacts_ready_test.dart
Closes https://github.com/flutter/flutter/issues/166563.
=> Add `GET /api/public/engine-artifacts-ready?sha=<sha>`

app_dart/lib/src/request_handlers/check_flaky_builders.dart
Towards https://github.com/flutter/flutter/issues/166758.
=> Add more logging to `CheckFlakyBuilders`.

app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart, app_dart/lib/src/request_handlers/rerun_prod_task.dart, app_dart/lib/src/service/config.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/request_handlers/rerun_prod_task_test.dart, app_dart/test/service/luci_build_service/check_rerun_builder_test.dart, app_dart/test/service/luci_build_service/schedule_prod_builds_test.dart, app_dart/test/src/utilities/mocks.mocks.dart
Closes https://github.com/flutter/flutter/issues/166847.
=> Self-create `*Service` instead of receiving as a parameter.

app_dart/lib/src/request_handlers/update_discord_status.dart, app_dart/lib/src/service/discord_service.dart, app_dart/test/request_handlers/update_discord_status_test.dart
Also adds some logging we can remove later.
=> Timevalues required to be in "Z" format

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service/schedule_prod_builds_test.dart, app_dart/test/service/scheduler_test.dart, app_dart/test/src/utilities/mocks.mocks.dart, packages/cocoon_common/lib/src/logging/buffered_logger.dart, packages/cocoon_common/pubspec.yaml
Also do a bit more TLC in `LuciBuildService`.
No changes to behavior.
=> Make `_updateTaskStatusInDatabaseForRetry` Firestore-first.

dashboard/lib/build_dashboard_page.dart, dashboard/lib/main.dart
"/" will be removed from pathSegments.
=> Fix route handling wiht pathSegments

cloud_build/dashboard_build.sh
Closes https://github.com/flutter/flutter/issues/166984.
=> Add source maps for dashboard

app_dart/lib/src/request_handlers/check_flaky_builders.dart, app_dart/test/request_handlers/check_flaky_builders_large_data.yaml, app_dart/test/request_handlers/check_flaky_builders_test.dart
Further work towards debugging why https://github.com/flutter/flutter/issues/166758 occurs in prod.
Locally, with a regression test, it does mark `Windows plugin_test` as non-flaky, but in prod:
```txt
> DEBUG 2025-04-09T09:20:07.673Z Skipping Linux analyzer_benchmark, could not find matching builder line
> DEBUG 2025-04-09T09:20:07.831Z Skipping Linux coverage, could not find matching builder line
> DEBUG 2025-04-09T09:20:07.833Z Skipping Linux_android_emu_unstable android_defines_test, an existing PR is open: https://github.com/flutter/flutter/pull/165961
> DEBUG 2025-04-09T09:20:07.989Z Skipping Linux_pixel_7pro android_semantics_integration_test, could not find matching builder line
> DEBUG 2025-04-09T09:20:08.185Z Skipping Linux_mokey hybrid_android_views_integration_test, could not …
```
=> Flaky test bot: Add more debugging and a large regression test.

dashboard/lib/src/v2/models/github_repository.dart
=> Fix character count RegExp for repo owner.

app_dart/test/model/firestore/commit_test.dart, app_dart/test/model/firestore/github_build_status_test.dart, app_dart/test/model/firestore/github_gold_status_test.dart, app_dart/test/model/firestore/pr_check_runs_test.dart, app_dart/test/model/firestore/task_test.dart, app_dart/test/src/model/_pr_check_run.dart, app_dart/test/src/service/fake_firestore_service.dart
=> Migrate most of the model/firestore directory to `FakeFirestore`.

app_dart/test/request_handlers/get_build_status_test.dart
=> Migrate `get_build_status_test.dart` to FakeFirestore.

app_dart/test/request_handlers/get_engine_artifacts_ready_test.dart
=> Migrate `get_engine_artifacts_ready_test` to `FakeFirestore`.

app_dart/test/service/scheduler/ci_yaml_fetcher_test.dart
=> Migrate `ci_yaml_fetcher_test` to Firestore first.

app_dart/lib/src/model/firestore/github_build_status.dart, app_dart/test/request_handlers/push_build_status_to_github_test.dart, app_dart/test/src/utilities/entity_generators.dart
=> Migrate `push_build_status_to_github_test` to Firestore first.

app_dart/test/request_handlers/vacuum_github_commits_test.dart
=> Migrate `vacuum_github_commits_test.dart` to `FakeFirestore`.

app_dart/test/request_handlers/github/webhook_subscription_test.dart
=> Migrate `webhook_subscription_test` to `FakeFirestore`.

app_dart/test/request_handlers/get_status_test.dart
=> Migrate `get_status_test` to `FakeFirestore`.

app_dart/test/service/commit_service_test.dart
=> Migrate `commit_service_test` to Firestore first.

app_dart/bin/gae_server.dart, app_dart/lib/src/service/content_aware_hash_service.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart, app_dart/test/src/service/fake_content_aware_hash_service.dart, app_dart/test/src/service/fake_scheduler.dart, app_dart/tool/local_server.dart
- should only trigger the workflow
- should not crash anything
- will plumb events in another pr
- no "real" defaults
=> Trigger content aware hash for merge group

app_dart/lib/src/model/firestore/github_gold_status.dart, app_dart/lib/src/request_handlers/push_gold_status_to_github.dart, app_dart/lib/src/service/firestore.dart, app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart, app_dart/test/request_handlers/push_gold_status_to_github_test.dart, app_dart/test/src/utilities/entity_generators.dart
=> Migrate `push_gold_status_to_github_test.dart` to `FakeFirestore`

app_dart/lib/server.dart, app_dart/lib/src/model/ci_yaml/ci_yaml.dart, app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart, app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart, app_dart/lib/src/service/scheduler.dart, app_dart/lib/src/service/scheduler/ci_yaml_fetcher.dart, app_dart/lib/src/service/scheduler/files_changed_optimization.dart, app_dart/test/model/ci_yaml/ci_yaml_test.dart, app_dart/test/request_handlers/check_flaky_builders_test.dart, app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart, app_dart/test/request_handlers/presubmit_luci_subscription_test.dart, app_dart/test/request_handlers/rerun_prod_task_test.dart, app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart, app_dart/test/service/scheduler/files_changed_optimization_test.dart, app_dart/test/src/service/fake_ci_yaml_fetcher.dart, app_dart/test/src/service/fake_scheduler.dart, app_dart/test/src/utilities/entity_generators.dart, dev/cocoon_code_health/bin/check.dart
Towards https://github.com/flutter/flutter/issues/167124.
This has no intended impact to production, only some refactoring to make a future change easier.
In addition, adds a tested (but not used) `FilesChangedOptimizer` to encapsulate code checking files changed.
After this PR merges, I'll work on part 2 (using this in Scheduler).
=> A bit of refactoring, prepare for `files_changed_optimizer`.

app_dart/lib/src/service/scheduler.dart, app_dart/lib/src/service/scheduler/files_changed_optimization.dart, app_dart/test/service/scheduler_test.dart
Closes https://github.com/flutter/flutter/issues/167124.
=> Enable new optimization flow, skip all tests for `CHANGELOG.md`.

app_dart/lib/src/request_handlers/rerun_prod_task.dart
=> Remove outdated docs related to `RerunProdTask`.

app_dart/lib/src/model/firestore/build_status_snapshot.dart, app_dart/lib/src/request_handlers/update_discord_status.dart, app_dart/test/request_handlers/update_discord_status_test.dart
Just a QOL tweak for the current Discord tree message.
=> Change `It has been .. minutes` to `It took .. minutes to become green`

app_dart/lib/src/model/ci_yaml/ci_yaml.dart, app_dart/lib/src/service/scheduler/ci_yaml_fetcher.dart, app_dart/test/model/ci_yaml/ci_yaml_test.dart
Closes https://github.com/flutter/flutter/issues/167288.
=> Fix filtering out targets missing from ToT.

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service/find_or_get_builds_test.dart
=> Remove unused `getTryBuilds`.

app_dart/lib/src/request_handlers/scheduler/backfill_grid.dart, app_dart/lib/src/request_handlers/scheduler/backfill_strategy.dart, app_dart/lib/src/service/luci_build_service/opaque_commit.dart, app_dart/test/request_handlers/scheduler/backfill_grid_test.dart, app_dart/test/request_handlers/scheduler/backfill_matcher.dart, app_dart/test/request_handlers/scheduler/backfill_strategy_test.dart
Towards https://github.com/flutter/flutter/issues/167222.
Adds:
- Replaces `(Super, Awkward, Tuple)` with `BackfillGrid` data structure, and tests.
- Updates `DefaultBackfillStrategy` and adds tests
=> No prod impact: complete (and test) `DefaultBackfillStrategy`

app_dart/lib/src/model/firestore/task.dart, app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart, app_dart/lib/src/service/datastore.dart, app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart, app_dart/test/service/datastore_test.dart, app_dart/test/src/service/fake_firestore_service.dart, app_dart/test/src/utilities/mocks.mocks.dart
Towards https://github.com/flutter/flutter/issues/167222.
This starts using `(Default)BackfillerStrategy`, but is still using Datastore as the source of (read) truth at the moment.
=> Switch over `BatchBackfiller` to use `BackfillStrategy`.

app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
Towards https://github.com/flutter/flutter/issues/167222.
=> Backfiller uses Firestore for primary reads.

app_dart/lib/src/request_handlers/rerun_prod_task.dart, app_dart/lib/src/service/build_status_provider.dart, app_dart/lib/src/service/firestore.dart, app_dart/lib/src/service/scheduler.dart
Just TLC towards the next steps of https://github.com/flutter/flutter/issues/167222.
=> Share code and make some tweaks to `Firestore.queryTasks`.

app_dart/bin/gae_server.dart, app_dart/lib/src/request_handlers/dart_internal_subscription.dart, app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart, app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart, app_dart/lib/src/request_handlers/scheduler/vacuum_stale_tasks.dart, app_dart/lib/src/request_handlers/vacuum_github_commits.dart, app_dart/lib/src/service/commit_service.dart, app_dart/lib/src/service/config.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/request_handlers/vacuum_github_commits_test.dart, app_dart/test/service/commit_service_test.dart, app_dart/test/service/config_test.dart, app_dart/test/src/datastore/fake_config.dart, app_dart/tool/local_server.dart
Towards https://github.com/flutter/flutter/issues/142951.
=> Add a config-guarded flag for Datastore usage.

app_dart/lib/src/service/config.dart
Closes https://github.com/flutter/flutter/issues/167294.
=> Document some obscure `Config` properties.

app_dart/lib/src/request_handlers/scheduler/scheduler_request_subscription.dart, app_dart/lib/src/service/build_bucket_client.dart
Just more [log TLC](https://pantheon.corp.google.com/logs/query;cursorTimestamp=2025-04-21T21:06:10.520Z;duration=PT3H;query=resource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22default%22%0AprotoPayload.resource!%3D%22readiness_check%22%0Aseverity%3E%3DWARNING%0Atimestamp%3D%222025-04-21T21:06:10.520Z%22%0AinsertId%3D%22oggs04f4m0hpc%22?project=flutter-dashboard).
=> Tweak logging for build bucket client calls.

app_dart/lib/src/service/luci_build_service/user_data.dart, app_dart/lib/src/service/luci_build_service/user_data.g.dart, app_dart/test/service/luci_build_service/user_data_test.dart
Towards https://github.com/flutter/flutter/issues/167464.
=> Read `task_id` in addition to `firestore_task_document_name`.

app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart
Towards https://github.com/flutter/flutter/issues/167242.
=> Remove `PrCheckRuns` callback for `initializeDocument`.

app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart
Towards https://github.com/flutter/flutter/issues/167242.
=> Remove unnecessary `initializeCiStagingDocument`.

app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart, app_dart/test/src/utilities/mocks.dart, app_dart/test/src/utilities/mocks.mocks.dart
Closes https://github.com/flutter/flutter/issues/167242.
=> Finish removing scheduler callbacks in favor of (fake) DB reads/writes

app_dart/lib/src/model/firestore/task.dart, app_dart/lib/src/request_handlers/rerun_prod_task.dart, app_dart/test/request_handlers/rerun_prod_task_test.dart
Closes https://github.com/flutter/flutter/issues/167654.
=> Further fix `rerun-prod-task?task=all` with regression tests.

app_dart/lib/src/service/branch_service.dart, app_dart/test/service/branch_service_test.dart
Mitigates the API cost in https://github.com/flutter/cocoon/pull/4580.
=> `BranchService`: Use `githubFileContent` (CDN) instead of `.getFileContents` (API).

app_dart/lib/src/service/config.dart, app_dart/test/src/fake_config.dart
Towards https://github.com/flutter/flutter/issues/164646.
=> Remove unused fields from `[Fake]Config`.

analysis_options.yaml, app_dart/lib/src/service/luci_build_service/user_data.g.dart, app_dart/test/src/utilities/mocks.mocks.dart, test_utilities/bin/dart_test_runner.sh
=> Update generated files, and stop ignoring generated files.

app_dart/lib/src/model/firestore/content_aware_hash_builds.dart, app_dart/test/src/model/_content_aware_hash_builds.dart, app_dart/test/src/model/firestore_matcher.dart
towards flutter/flutter#167778
Add firestore model for content aware hashing.
=> Create `content_aware_hash_builds` firestore document.

dashboard/lib/build_dashboard_page.dart
Closes https://github.com/flutter/flutter/issues/135440.
=> Use a selectable area for the title text.

app_dart/lib/src/request_handlers/scheduler/backfill_grid.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/lib/src/service/luci_build_service/pending_task.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/service/luci_build_service/schedule_prod_builds_test.dart
Closes https://github.com/flutter/flutter/issues/167772.
=> Increment the attempt number when rerunning tasks.

app_dart/lib/src/request_handlers/scheduler/backfill_grid.dart, app_dart/test/request_handlers/scheduler/backfill_grid_test.dart
Closes https://github.com/flutter/flutter/issues/167810.
=> Do not mark non-`new` `backfill: false` tasks skipped.

app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart
Closes https://github.com/flutter/flutter/issues/167842.
=> Fix bug that skips all postsubmit tasks.

app_dart/lib/src/service/firebase_jwt_validator.dart, app_dart/test/service/firebase_jwt_validator_test.dart
the first instance always had the correct keystore, the remaining keystores were empty.
added a test.
=> fix: have all instances create keystore from cache

app_dart/lib/src/request_handlers/get_build_status.dart, app_dart/lib/src/request_handlers/push_build_status_to_github.dart, app_dart/lib/src/service/build_status_provider.dart, app_dart/lib/src/service/build_status_provider/commit_tasks_status.dart, app_dart/test/service/build_status_provider_test.dart, app_dart/test/src/service/fake_build_status_provider.dart
Closes https://github.com/flutter/flutter/issues/167846.
=> Simplify and fix build status provider.

app_dart/lib/src/service/config.dart, app_dart/test/src/fake_config.dart, auto_submit/lib/service/config.dart, packages/cocoon_server/lib/generate_github_jws.dart, packages/cocoon_server/pubspec.yaml, packages/cocoon_server/test/generate_github_jws_test.dart
- Removes `corsac_jwt` dependency (which is using an older jose package).
- Moves nearly identical Json Web Signature code to shared folder + adds tests
- Behind the scenes: update secrets manager with the correctly formatted PEM.
=> Consolidate to one library for JWT / JWS

app_dart/lib/src/request_handlers/rerun_prod_task.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/test/request_handlers/rerun_prod_task_test.dart, app_dart/test/src/utilities/mocks.mocks.dart, dashboard/lib/widgets/task_overlay.dart, packages/buildbucket-dart/lib/buildbucket_pb.dart
Towards https://github.com/flutter/flutter/issues/168090.
I have not added tests, as I (regrettably) need to test this in production before knowing it actually works.
/cc @reidbaker @camsim99 @justinmc
=> Allow rerunning `Linux flutter_release_builder` through Cocoon

app_dart/lib/src/service/luci_build_service.dart
Oops! `buildNumber` != `id`.
Towards https://github.com/flutter/flutter/issues/168090. If this works in production, I'll add tests and finalize it.
=> Resolve a `buildNumber` as a `dart-internal`-owned `id`

app_dart/lib/src/request_handlers/dart_internal_subscription.dart, app_dart/lib/src/service/luci_build_service.dart
Closes https://github.com/flutter/flutter/issues/168239.
After this PR I'll do cleanup. It works!
=> Do not notify `dart-internal` sub, add more logging, add error handling

app_dart/lib/src/request_handling/request_handler.dart, app_dart/test/src/request_handling/request_handler_tester.dart
Towards https://github.com/flutter/flutter/issues/168333.
=> Remove unused `HttpClient`.

analysis_options.yaml, app_dart/lib/src/request_handlers/presubmit_luci_subscription.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/lib/src/service/luci_build_service/user_data.dart, app_dart/lib/src/service/luci_build_service/user_data.g.dart, app_dart/lib/src/service/scheduler/ci_yaml_fetcher.dart, app_dart/test/request_handlers/presubmit_luci_subscription_test.dart, app_dart/test/service/github_checks_service_test.dart, app_dart/test/service/luci_build_service/schedule_merge_group_builds_test.dart, app_dart/test/service/luci_build_service/schedule_try_builds_test.dart, app_dart/test/service/luci_build_service/user_data_test.dart
More work needed to remove/consolidate, but this migrates some code.
=> More wide-spread use of `CommitRef` instead of 3-4 params.

app_dart/lib/src/foundation/utils.dart, app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart, app_dart/lib/src/request_handlers/rerun_prod_task.dart, app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart, app_dart/lib/src/service/scheduler.dart, app_dart/lib/src/service/scheduler/ci_yaml_fetcher.dart, app_dart/test/foundation/utils_test.dart, app_dart/test/service/scheduler/ci_yaml_fetcher_test.dart, app_dart/test/src/service/fake_ci_yaml_fetcher.dart
Closes https://github.com/flutter/flutter/issues/168102. It's not always safe to check GoB.
=> Conditionally fallback to GoB for `CiYamlFetcher`.

app_dart/lib/src/service/content_aware_hash_service.dart, app_dart/test/service/content_aware_hash_service_test.dart, app_dart/test/service/gerrit_service_test.dart, app_dart/test/src/service/fake_content_aware_hash_service.dart
Makes the unit tests take a few seconds less.
=> Do not wait substantial time in retry unit tests.

app_dart/lib/src/foundation/utils.dart, app_dart/lib/src/service/config.dart, app_dart/test/foundation/utils_test.dart, app_dart/test/service/dynamic_config_updater_test.dart
Default values can sometimes be harmful.
=> fix: `githubFileContent` should not have a default ref

app_dart/lib/src/service/scheduler/ci_yaml_fetcher.dart, app_dart/lib/src/service/scheduler/files_changed_optimization.dart, app_dart/test/service/scheduler/ci_yaml_fetcher_test.dart
=> Default to `validate: false` for `postsubmit: true`

app_dart/lib/src/model/gerrit/commit.dart, app_dart/lib/src/model/google/grpc.dart, app_dart/lib/src/model/luci/pubsub_message.dart, app_dart/lib/src/request_handlers/get_build_status_badge.dart, app_dart/lib/src/request_handling/body.dart, app_dart/lib/src/request_handling/request_handler.dart, app_dart/lib/src/request_handling/static_file_handler.dart, app_dart/test/request_handling/request_handler_test.dart
More TLC, also closes https://github.com/flutter/flutter/issues/168315.
=> Add `contentType?` to `Body`, remove `JsonBody`.

.github/workflows/app_dart_tests.yaml, .github/workflows/common_validation.yaml, .github/workflows/dashboard_tests.yaml
- update "paths" for app_dart and dashboard
=> Use flutter-action to complete all tests

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service/rerun_dart_internal_test.dart
Closes https://github.com/flutter/flutter/issues/168608.
=> Fallback to re-running a full release build on missing builds.

app_dart/lib/src/model/proto/internal/scheduler.pb.dart, app_dart/lib/src/model/proto/internal/scheduler.pbjson.dart, app_dart/lib/src/model/proto/internal/scheduler.proto
Towards https://github.com/flutter/flutter/issues/168709.
=> Add `target.schedule_during_release_override`

app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart, app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
Towards https://github.com/flutter/flutter/issues/168738.
This keeps task utilization of `ios-experimental` lower. More work is required to make this work e2e.
/cc @vashworth
=> Do not try to rerun experimental branch task failures.

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service/rerun_dart_internal_test.dart
Closes https://github.com/flutter/flutter/issues/168944.
=> Always re-run release builders from ToT.

app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart, app_dart/lib/src/service/scheduler/ci_yaml_fetcher.dart, app_dart/test/src/service/fake_ci_yaml_fetcher.dart
Closes https://github.com/flutter/flutter/issues/169086.
This was actually a pretty bad bug, it's lucky we caught this (thx experimental branch!)
=> Fix backfiller when fetching ToT when running on a non-default branch.

app_dart/bin/gae_server.dart, app_dart/lib/src/model/ci_yaml/ci_yaml.dart, app_dart/lib/src/service/flags/ci_yaml_flags.dart, app_dart/lib/src/service/flags/ci_yaml_flags.g.dart, app_dart/lib/src/service/flags/dynamic_config.dart, app_dart/lib/src/service/scheduler/ci_yaml_fetcher.dart, app_dart/test/model/ci_yaml/ci_yaml_test.dart, app_dart/test/service/scheduler/ci_yaml_fetcher_test.dart, app_dart/tool/local_server.dart
Closes https://github.com/flutter/cocoon/pull/4731 (well, replaces).
Towards https://github.com/flutter/flutter/issues/169625.
=> Add and use `CiYamlFlags`, but use default values only.

app_dart/config.yaml, app_dart/lib/src/service/flags/dynamic_config.g.dart
Towards https://github.com/flutter/flutter/issues/169625.
=> Set `onlyUseTipOfTreeTargetsExistenceToFilterTargets` to (default) `false`.

packages/buildbucket-dart/pubspec.yaml, packages/cocoon_server/pubspec.yaml, packages/cocoon_server_test/pubspec.yaml, pubspec.yaml
No other changes to keep things small.
=> Add all of `packages/...` to the (root) workspace.

app_dart/lib/server.dart, app_dart/lib/src/model/firestore/tree_status_change.dart, app_dart/lib/src/request_handlers/get_tree_status_changes.dart, app_dart/test/request_handlers/get_tree_status_test.dart, app_dart/test/src/service/fake_firestore_service.dart, dashboard/lib/service/appengine_cocoon.dart, dashboard/lib/service/dev_cocoon.dart, dashboard/lib/views/tree_status_page.dart, packages/cocoon_common/lib/src/rpc_model/tree_status_change.dart, packages/cocoon_common/lib/src/rpc_model/tree_status_change.g.dart
Towards https://github.com/flutter/flutter/issues/74529.
=> Add `GetTreeStatus`, tweak a bit.

app_dart/lib/src/foundation/utils.dart
Closes https://github.com/flutter/flutter/issues/170031.
=> Add some debug information to stdout for task ownership.

app_dart/bin/gae_server.dart, app_dart/lib/src/service/build_status_service.dart, app_dart/lib/src/service/flags/dynamic_config.dart, app_dart/lib/src/service/flags/dynamic_config.g.dart, app_dart/test/request_handlers/get_build_status_badge_test.dart, app_dart/test/request_handlers/get_build_status_test.dart, app_dart/test/request_handlers/update_discord_status_test.dart, app_dart/test/service/build_status_service_test.dart, app_dart/tool/local_server.dart
Towards https://github.com/flutter/flutter/issues/74529.
=> Behind a flag, `allowManualTreeClosures`, allow closing the tree.

app_dart/lib/src/service/scheduler/files_changed_optimization.dart, app_dart/test/service/scheduler/files_changed_optimization_test.dart
See https://github.com/flutter/flutter/pull/170092.
/cc @camsim99
=> Add `release-candidate-version.version` to files-changed optimization.

dashboard/lib/service/appengine_cocoon.dart
=> Use `passing`, not `status`, as the `update-tree-status` body.

app_dart/lib/src/request_handlers/update_tree_status.dart, app_dart/lib/src/service/build_status_service.dart, app_dart/test/request_handlers/update_tree_status_test.dart, app_dart/test/service/build_status_service_test.dart
... oops, it's `flutter` not `flutter/flutter`.
=> Fix how `repo` is passed for manual tree closures

app_dart/lib/src/service/scheduler/files_changed_optimization.dart, app_dart/test/service/scheduler/files_changed_optimization_test.dart
Closes https://github.com/flutter/flutter/issues/170706.
=> Exclude `.github` and `.vscode`.

app_dart/lib/src/request_handlers/get_build_status.dart, app_dart/lib/src/request_handlers/push_build_status_to_github.dart, app_dart/lib/src/service/build_status_service.dart, app_dart/lib/src/service/firestore.dart, app_dart/test/service/build_status_service_test.dart
Closes https://github.com/flutter/flutter/issues/171104.
=> Do not misreport breakages on a non-default branch as a tree status failure

app_dart/lib/src/request_handlers/get_status.dart, app_dart/lib/src/service/build_status_provider/commit_tasks_status.dart, app_dart/test/request_handlers/get_status_test.dart
Closes https://github.com/flutter/flutter/issues/171186.
=> Only mark a task as `IsFlaky` if ran more than once.

app_dart/lib/src/request_handlers/dart_internal_subscription.dart, app_dart/test/request_handlers/dart_internal_subscription_test.dart
Closes https://github.com/flutter/flutter/issues/170370.
=> Fix a bug where multiple release tasks are recorded.

app_dart/lib/src/request_handlers/github/webhook_subscription.dart, app_dart/lib/src/service/config.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/request_handlers/github/webhook_subscription_test.dart
Mitigates https://github.com/flutter/flutter/issues/162656.
Requires https://github.com/flutter/cocoon/pull/4806 to be merged first.
=> Add an explicit comment/warning when a duplicate SHA is detected

app_dart/lib/src/request_handlers/github/webhook_subscription.dart, app_dart/test/request_handlers/github/webhook_subscription_test.dart
See https://github.com/flutter/flutter/pull/172887#issuecomment-3130140772
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#handling- …
=> Add .gemini/ to test exemption list

dashboard/lib/widgets/lattice.dart, dashboard/lib/widgets/user_sign_in.dart, dashboard/test/utils/fake_firebase_user.dart
=> Remove deprecation warnings, unused methods

app_dart/lib/src/service/config.dart
Example: https://github.com/flutter/flutter/pull/174019#issuecomment-3199690699
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#hand …
=> Add missing space
