flutter/cocoon

app_dart/lib/src/request_handlers/luci_status.dart, app_dart/test/request_handlers/get_status_test.dart, app_dart/test/request_handlers/luci_status_test.dart
Append a reload query parameter so that the LUCI UI will refresh the page every 30 seconds for links to in progress builds.
=> Set target_url to reload

app_flutter/lib/commit_box.dart, app_flutter/lib/main.dart, app_flutter/lib/status_grid.dart, app_flutter/test/commit_box_test.dart, app_flutter/test/status_grid_test.dart
Removed displaying the message. This allows commit box to fit easily into the grid with no extra changes.
Added a TODO for work on the overlay that will show more information for a commit.
=> Fit commit widget into status grid

app_flutter/lib/commit_box.dart, app_flutter/lib/status_grid.dart, app_flutter/test/commit_box_test.dart
This is meant to be a way of showing the information regarding a commit. On click, the overlay is shown. On click out, the overlay is closed.
Currently shows basic information, but when the widget is switched to use the commit model it will show more information.
=> Commit overlay

app_flutter/lib/status_grid.dart
While working on improving the scroll, I realized switching the GridView to the builder format improved scrolling (not completely). Before implementing a custom scroll physics so the vertical scroll matches the horizontal scroll on the StatusGrid, I wanted to make this improvement.
Additionally, I made the grid take the rest of the screen space (full screen).
=> StatusGrid using builder

app_dart/lib/src/request_handlers/update_task_status.dart
Existing cocoon fails to populate task endTimestamp accordingly, resulting 0 value for all tasks. Now we are trying to calculate task execution time, and here is the fix.
=> Populate Task endTimestamp

app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/request_handlers/github_webhook_test.dart
With the new setup for LUCI builds, we schedule builds from the recipe itself - which means we can no longer expect the same user agent and created by values in all builds for a tryjob.
This updates the logic so that it will cancel the "drone" builders.
Fixes https://github.com/flutter/cocoon/issues/437
=> Cancel all builds scheduled by a tryjob

app_flutter/lib/service/appengine_cocoon.dart, app_flutter/lib/service/cocoon.dart, app_flutter/lib/service/fake_cocoon.dart, app_flutter/lib/service/mock_cocoon.dart, app_flutter/pubspec.yaml, app_flutter/test/service/appengine_cocoon_test.dart
This service allows the Flutter application to talk to the cocoon backend to get data.
It offers both a production service (talks to AppEngine via HTTP) and a mock service (generate dummy data) based on whether the application was built for production or not.
Most of the code in AppEngineCocoonService will be deleted once protos are being used in the backend.
=> Flutter Cocoon Service

app_flutter/lib/main.dart, app_flutter/lib/state/flutter_build.dart, app_flutter/lib/status_grid.dart, app_flutter/pubspec.yaml, app_flutter/test/service/mock_cocoon.dart, app_flutter/test/state/flutter_build_test.dart, app_flutter/test/status_grid_test.dart
Implemented the Provider package to handle the state management for the new build dashboard. Created a state class for the build dashboard. Once feature parity is reached with the current dashboard, it will contain more variables (e.g. tree build status, agent statuses).
Created a new wrapper widget for the StatusGrid that handles the state management section for now. If we find this creates performance issues, we can refactor it.
This fixes #422 since the feature parity is met. The dashboard loads production data in, and updates it with the latest information on a set interval.
I did a manual test by building the app for release on my phone, and seeing if tasks that were running went to a different state.
=> StatusGrid refreshes to show the latest information

app_flutter/lib/main.dart, app_flutter/lib/service/appengine_cocoon.dart, app_flutter/lib/service/cocoon.dart, app_flutter/lib/service/fake_cocoon.dart, app_flutter/lib/state/flutter_build.dart, app_flutter/test/service/appengine_cocoon_test.dart, app_flutter/test/state/flutter_build_test.dart
- Cocoon service fetches tree build status
- FlutterBuildState stores the tree build status
- AppBar changes color based on the current tree build status
=> Tree Build Status changes the AppBar color

app_flutter/lib/task_box.dart, app_flutter/test/task_box_test.dart
- Added a special case for In Progress tasks to show a loading indicator in the box
- Updated old references of ResultBox to TaskBox
- Added test for this new case
Here's a GIF (the performance issue comes from the GIF, not the app)
=> In Progress Tasks show work is being done

app_flutter/lib/build_dashboard.dart, app_flutter/lib/main.dart, app_flutter/lib/service/fake_cocoon.dart
Fixes #454 
Issue was there was no state for the AppBar. This creates a parent widget for the build dashboard that maintains the state, and wraps its children in a ChangeNotifierProvider.
I updated the fake cocoon service to give a random value for the tree status, and verified that the AppBar switched colors randomly every 10 seconds.
I think a regression test for this bug would involve writing an integration test, and that is out of the scope of this project.
=> Fix tree status updates not reflecting in UI

app_flutter/lib/task_box.dart, app_flutter/test/status_grid_test.dart, app_flutter/test/task_box_test.dart
- If tasks have been attempted, update their status to the correct status (New->Underperformed, Succeeded->SucceededButFlaky, InProgress->UnderpformedInProgress)
- Removed unncessary tester.takeException()s in StatusGrid tests
Fixes #456 , a feature request that asked for tasks that are in progress but have run before to be differentiated from first time running tasks.
=> TaskBox reflects v1 task colors

app_flutter/analysis_options.yaml, app_flutter/android/gradle.properties, app_flutter/lib/build_dashboard.dart, app_flutter/lib/commit_box.dart, app_flutter/lib/service/appengine_cocoon.dart, app_flutter/lib/service/cocoon.dart, app_flutter/lib/service/fake_cocoon.dart, app_flutter/lib/state/flutter_build.dart, app_flutter/lib/status_grid.dart, app_flutter/lib/task_box.dart, app_flutter/test/commit_box_test.dart, app_flutter/test/service/appengine_cocoon_test.dart, app_flutter/test/state/flutter_build_test.dart, app_flutter/test/status_grid_test.dart, app_flutter/test/task_box_test.dart
Mostly formatting stuff.
Removed unnecessary forEach for converting required capabilities json to the proto. Could just be done with a toString() in AppEngineCocoonService.
Fixes #455
=> Update analysis_options to match flutter/flutter for app_flutter

app_flutter/lib/task_box.dart, app_flutter/test/task_box_test.dart
This adds UI that allows users to view more information from a Task. New information shown is the duration of the task (how long it took to complete in seconds) and what agent it ran on. 
Currently, the backend is not  populating the end timestamp, so it defaults to 0. When the backend gets switched over to Dart, the duration will be correct.
*Images are from a phone running a release build. The overlay fits much better on desktop.*
=> Task Overlay UI

agent/lib/src/health.dart
With the linux host migration to new hardware and Debian, ip addresses
are not reported anymore. This is because the network interface name
changed and needs to be updated.
=> [cocoon] Update the net interface we are getting the ip from.

app_flutter/lib/service/fake_cocoon.dart, app_flutter/lib/status_grid.dart, app_flutter/lib/task_box.dart, app_flutter/test/status_grid_test.dart
Fixes #461 
This helps with:
1. Easier ordering of the columns of the StatusGrid (for sorting purposes, like showing most recent failures first)
2. Faster prototyping experimental versions of the StatusGrid to improve the performance of it on Web
This fixes the issue where the StatusGrid was naively using the first CommitStatus as the base for constructing the StatusGrid. However, extra code had to be added to make the TaskIcon row at the top show the correct icons.
=> Task matrix

app_flutter/pubspec.yaml
Tests not run on that PR, and now tests are failing.
/cc @jonahwilliams @tvolkert Do you know why the cirrus tests were not run on #479 ?
=> Revert url launching on web

app_flutter/lib/status_grid.dart
Test: Scrolling through status grid to bottom with fake data, then swiping back up. Using [this stackoverflow on getting average fps from chrome](https://stackoverflow.com/questions/48079661/how-to-get-the-average-fps-in-chrome-devtools).
Current: ~26 average FPS
This fix: ~42 average FPS
Android showed better performance too.
- Experiment with using Skia for rendering on the web
- Experiment with removing use of expanded
- Experiment with List<Row> instead of GridView
=> Improve performance of StatusGrid by not adding repaint boundaries

.cirrus.yml, app_flutter/pubspec.yaml
This should make it so any of the other Flutter for Web plugins can easily be included in the future. It makes Cirrus run on the Flutter dev channel when testing `app_flutter`.
=> Reland #479 url launching for web

app_dart/bin/server.dart
Following #484, this caches the endpoint that returns all the time series history for the different benchmarks. Currently, it takes ~37 seconds to return, and this will bring it to under a second when returning from cache.
- Caching the `get-timeseries-history` endpoint, but we need to move the POST parameter to GET params. `CacheRequestHandler` stores responses by the URI and query parameters, and does not use the POST body.
=> Cache get-benchmarks

app_dart/dev/deploy.dart
Fixes https://github.com/flutter/flutter/issues/43508
When I have been deploying, I notice old versions of the app get deployed. 
It may sound like user error, but my process is always for deployment:
1. `git fetch upstream`
2. `git checkout upstream/master -b <new version>`
3. `dart dev/deploy.dart ...`
For example, I deployed `v307` for the redis caching. However, it cleared the previous commit's status ordering feature. I believe this is because while doing my own test deployments for caching, it had the project built without that latest change. I deployed `v308` with the same branch, but I cleared the `build` folders in `app_dart` and `app_flutter` and that deployment was successful.
```
$ git log v307
commit b5abdc601f98875a01a27ee4433d82244b0dc361 (HEAD -> v307)
Author: Casey …
```
=> deploy script clears old build files

app_dart/lib/src/request_handling/authentication.dart, app_dart/test/request_handling/authentication_test.dart
AppEngine only sets the `X-AppEngine-User-Email` header if a user authenticated through a secured handler:
```
For login:admin or login:required handlers specified in app.yaml, App Engine also provides the following set of headers:
X-AppEngine-User-Email, with example header: "ange@example.com"
```
[Source from AppEngine docs](https://cloud.google.com/appengine/docs/standard/python/reference/request-response-headers#app_engine-specific_headers)
Neither `v228` (the current Go runtime) or the Dart runtimes implement these types of handlers. I believe this code is unused.
=> Remove dead code for handling X-AppEngine-User-Email Authentication

.cirrus.yml, app_flutter/lib/build_dashboard.dart
I was deploying `v310` to AppEngine and ran into this error when building for web. This fixes the issue since it was including two versions of `GoogleSignInService`, one relatively and the other via `package:app_flutter`. `flutter run -d chrome` works and `flutter build aot` works.
To prevent this in the future, I added a build script for `app_flutter` in Cirrus that will build for web as a check.
@jonahwilliams do you think this is a bug that should be filed?
```
$ flutter build web
#0      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:154:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:526:25)
<asynchronous suspension>
#2      _BuildInstance.invokeTarget.<anonymous closure> …
```
=> Web build fix

app_flutter/lib/state/flutter_build.dart, app_flutter/test/state/flutter_build_test.dart
This *fixes* the red screen of death on the TV. The server side issue is documented at https://github.com/flutter/flutter/issues/43762
- Added regression tests to ensure this doesn't break anymore
=> Don't reset FlutterBuildState data when an error comes in

app_flutter/lib/service/appengine_cocoon.dart, app_flutter/lib/service/cocoon.dart, app_flutter/lib/service/fake_cocoon.dart, app_flutter/lib/state/flutter_build.dart, app_flutter/lib/status_grid.dart, app_flutter/lib/task_box.dart, app_flutter/lib/task_helper.dart, app_flutter/pubspec.yaml, app_flutter/test/service/appengine_cocoon_test.dart, app_flutter/test/status_grid_test.dart, app_flutter/test/task_box_test.dart, app_flutter/test/task_helper_test.dart
Waiting on https://github.com/flutter/cocoon/pull/502 for integration testing.
Fixes https://github.com/flutter/flutter/issues/43109 leaving just viewing logs for feature parity with the v1 dashboard.
Added dependency on `flutter_progress_button` for pretty async buttons (MIT license) and added UI for rerunning a `Task` for devicelab tasks in `TaskOverlay`.
Added to `FlutterBuildState` the ability to rerun tasks (forwards to `CocoonService`). `CocoonService` has code for making authenticated requests.
When an error occurs, it will show a `SnackBar` saying an error occurred rerunning the task. Otherwise, it will show a `SnackBar` saying the task is rerunning and it may take a minute to propagate. This is because `/api/public/get-status` cache TTL is 1 minute, and we do not want to mutate …
=> Rerun tasks

app_flutter/lib/task_box.dart, app_flutter/lib/task_helper.dart, app_flutter/test/task_box_test.dart, app_flutter/test/task_helper_test.dart
This fixes https://github.com/flutter/flutter/issues/43106
Ports the logic from the Angular Dart Build Dashboard for viewing logs.
=> View Task Logs

agent/lib/src/commands/ci.dart
We are currently sending the phone to sleep after running a task by
sending a power key press intent. This is making a few tests fail and
some other tests to not give reliable signals. We are forcing the phone
to wake up before running tests.
Bug: 44004
Test: Manual execution of the change locally.
=> Force the phone's screen on before running a test.

app_dart/lib/src/request_handling/authentication.dart, app_dart/test/request_handling/authentication_test.dart, app_dart/test/src/request_handling/fake_authentication.dart
This allows authenticating in the Cocoon backend via a Google Auth access token sent through the `X-Flutter-AccessToken` header.
The `google_sign_in_all` plugin the Flutter app is using for handling Google Auth returns a null id token, but does return a valid access token. Debugging lead to a rabbit hole of where the issue could be occurring, so I decided to just add authenticating via access tokens. The process is very similar to authenticating for id tokens which the backend already does.
- Added unit tests for the different authentication cases (based heavily off the id token's tests)
- Deployed to my test version on the AppEngine project and verified it worked with a working access token. Tested with an expired one too. (via curl)
- Use this authentication method for the Flutter App's …
=> Cocoon authentication accepts access tokens as a method of authentication

app_dart/bin/server.dart, app_dart/dev/deploy.dart, app_dart/pubspec.lock
Updates the Dart project to serve all the web assets out of it.
- Deploy script builds the `app` project assets and uploads them to AppEngine
- `bin/server.dart` instead of falling back to the Go code tries to serve static files
Closes https://github.com/flutter/flutter/issues/43095
Demo available at http://testchillers.flutter-dashboard.appspot.com/
This is waiting on https://github.com/flutter/cocoon/pull/502 before updating AppEngine.
=> Dart project builds `app` project and serves it

app_flutter/lib/build_dashboard.dart
Size needs to be specified, so for now defaulting to 100px.
Before:
After:
=> Fix negative colored Google avatars

app_flutter/pubspec.yaml
`url_launcher` will resolve to a version that does not work on web. This is a temporary fix as I presume this is just from the work being done for federated plugins.
See https://github.com/flutter/flutter/issues/44012#issuecomment-549611173 for more information.
=> Set url launcher to version working on web

app_dart/bin/server.dart, app_dart/dev/deploy.dart, app_dart/pubspec.lock
This reverts commit fc8f82d3ffd48c7fe66a604bb9901b093913dcb4.
Committed this too early. Supposed to stay open until we officially make the switch. Otherwise, any new deploys will make the switch to the new build dashboard.
=> Revert "Dart project builds `app` project and serves it (#513)"

app_flutter/lib/commit_box.dart, app_flutter/lib/service/fake_cocoon.dart, app_flutter/lib/status_grid.dart, app_flutter/lib/task_box.dart, app_flutter/test/status_grid_test.dart, app_flutter/test/task_box_test.dart
Follow up from the experimenting at https://github.com/flutter/cocoon/pull/511. Ideally, we want to use Skia, but the support is not there yet.
- Convert `StatusGrid` to be built with a `ListView` of `ListView`
- Convert Task in progress indicator to a static icon to reduce perceived jank
- Made fake data similar to production size
Should be the same as the previous StatusGrid. Removed last task test because of weirdness with ListView ListView
Demo: https://testchillers-dot-flutter-dashboard.appspot.com/v2/#/
=> Implement StatusGrid performance improvements

app_dart/lib/src/request_handling/authentication.dart, app_dart/test/request_handling/authentication_test.dart, app_dart/test/src/request_handling/fake_authentication.dart
This makes it easier for the Flutter application to authenticate with the Cocoon backend. It takes the current id token authentication method and allows it be run on the header `X-Flutter-IdToken` or the cookie `X-Flutter-IdToken`.
This is follow up from https://github.com/flutter/cocoon/pull/526 since the Google Sign In plugin is in the review phase for web support, and that works with id tokens.
Added checks if the cookie is unauthenticated but the header is (in the case of just using the Flutter application), and if the cookie is authenticated but the header is not (in the case of using the performance dashboard)
=> X-Flutter-IdToken header authentication

agent/lib/src/health.dart
This will use ~1 extra minute for health checks but will prevent test
beds that are not able to sign apps to pick up new tasks.
This solves https://github.com/flutter/flutter/issues/43817 and helps
to mitigate false positives on Mac/iOS test beds.
=> Add iOS signing health check.

app_flutter/lib/build_dashboard.dart, app_flutter/lib/service/appengine_cocoon.dart, app_flutter/lib/service/google_authentication.dart, app_flutter/lib/sign_in_button.dart, app_flutter/lib/state/flutter_build.dart, app_flutter/lib/task_box.dart, app_flutter/pubspec.yaml, app_flutter/test/build_dashboard_test.dart, app_flutter/test/service/google_authentication_test.dart, app_flutter/test/sign_in_button_test.dart, app_flutter/test/state/flutter_build_test.dart, app_flutter/test/task_box_test.dart, app_flutter/test/utils/fake_google_account.dart, app_flutter/web/index.html
The Flutter Google Sign In plugin should be getting official web support very soon. The open source fork the Flutter app was using did not get id tokens which required adding a new authentication method to the backend. This updates all the places in the Flutter app that reference the `GoogleSignInService` to use the new methods (using `GoogleSignInAccount` instead of separate fields).
Right now the web version is in the review stage, so this uses a forked version of it by the @ditman the PR owner.
Added ability to sign out by clicking the user avatar, and then clicking log out in the drop down.
Waiting on ~https://github.com/flutter/plugins/pull/2266~ and preferably https://github.com/flutter/plugins/pull/2280
Demo available at http://testchillers.flutter-dashboard.appspot.com/v2/
=> Switch to federated google sign in plugin

app_flutter/lib/build_dashboard.dart, app_flutter/lib/main.dart, app_flutter/test/build_dashboard_test.dart
Replaces the "Build Dashboard v2" title in `AppBar` to be `Tree is Open` or `Tree is Closed`. Additionally, when the tree is open it is set to match the color of a successful task box (green).
Recommended by @digiter 
Added tests to check the text and color change of the AppBar based on tree status.
Demo: https://testsummary-dot-flutter-dashboard.appspot.com
=> Explicit tree status in AppBar

app_flutter/lib/status_grid.dart, app_flutter/test/status_grid_test.dart
A bug that started in https://github.com/flutter/cocoon/pull/518 where tasks that should be skipped or collated. This lead to skipped tasks not showing correctly and the grid becoming messed up.
The cause was becaused `SizedBox()` was not given a size for skipped tasks. With `GridView` this was okay as everything was constrained, however, this lead to them becoming hidden when switching to the `ListView` implementation.
The only way I could think of regression testing this would be tapping at certain points on the screen and checking the task overlay to be correct. However, I did not know if this would become more so E2E testing of the application which is out of scope of the project.
Demo: https://testskipfix-dot-flutter-dashboard.appspot.com/v2/
=> Fix skipped tasks being collated in ListView's TaskBoxes

app_flutter/pubspec.yaml
No new PRs can go through until this update is made since the forked branch got deleted.
=> Update google sign in web to official version

app_flutter/pubspec.yaml
I noticed this in #535 and @ditman published the web version today.
This is the last plugin in our dependencies that wasn't using a published plugin.
=> Update url launcher web to official plugin

app_flutter/lib/commit_box.dart, app_flutter/lib/state/flutter_build.dart, app_flutter/lib/task_box.dart, app_flutter/test/commit_box_test.dart, app_flutter/test/task_box_test.dart
These changes are to help make the app more explicit and concise. This was feedback given from the team with the v1 dashboard.
Removed the place holder button for rerunning all failed tasks for a commit: Requires a day of work to handle the errors that occur, as right now worst case you will get 10 minutes of error snackbars if the application is not signed in.
Expanded the open in GitHub icon button a button that just says GitHub.
Shortened commit sha in to just show the first 7 characters which is unique enough to lookup a flutter/flutter commit.
Renamed the "Rerun task" button to "Rerun".
Fixed the duration in the task overlay to be in minutes
- Is there a way to make text copyable on web?
Demo: https://testui-dot-flutter-dashboard.appspot.com/v2/
=> Commit Overlay and Task Overlay UI Cleanup

app_flutter/lib/state/flutter_build.dart, app_flutter/lib/status_grid.dart, app_flutter/lib/task_box.dart, app_flutter/lib/task_helper.dart, app_flutter/test/build_dashboard_test.dart, app_flutter/test/task_box_test.dart, app_flutter/test/task_helper_test.dart
Cirrus needs the Commit sha appended to the end of the Cirrus URL to end up on the log specific for that Cirrus task.
Plumbed `Commit` variable to this location to make it easier to expand the `TaskOverlay` with more information regarding the task in a later commit.
Added tests for checking the cirrus log redirects to the sha url when Commit is given instead of master.
Demo: https://testchillers-dot-flutter-dashboard.appspot.com/build.html
=> Pipe Commit through TaskBox for Cirrus logs

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
Fixes https://github.com/flutter/flutter/issues/45357
The API does not return the flag in a useable way for this.  If the PR isn't actually mergeable we'll know when we try to merge it anyway.
=> Do not use the MERGEABLE flag

app_dart/pubspec.lock, app_dart/pubspec.yaml
https://api.dartlang.org/stable/2.6.1/dart-async/Stream/Stream.value.html - Stream.value requires at least 2.5.0.
=> Push version constraint for Stream.value

app_dart/dev/deploy.dart
https://github.com/flutter/cocoon/pull/523 introduced this issue. Somehow everything got deployed correctly, but when I did a wipe on my machine this issue manifested. There's a regression test for this already in the deploy script (delete the build folder that will be uploaded before rerunning the build scripts). However, I don't know how we managed to deploy everything yesterday when switching over the dashboard.
=> Path typo in the deploy script

agent/lib/src/adb.dart, agent/test/src/adb_test.dart
Windows machines keep hanging on "adb devices -l" there is no way to fix
it other than just killing the adb server. Unfortunately for windows
"adb kill-server" does not work as expected and we need to explicitly
kill the process.
This is to fix:
https://github.com/flutter/flutter/issues/43930
=> [agent] Update retry logic to kill adb server in windows.

app_flutter/lib/build_dashboard.dart, app_flutter/lib/state/flutter_build.dart, app_flutter/test/build_dashboard_test.dart, app_flutter/test/utils/fake_flutter_build.dart
Update the tree status to use the null value. This is used on initialization to let users know that we're loading the value. During this state, it shows a grey `AppBar` that says loading.
Originally, we just showed the failed status since that's the worst case. However, it was marginally noticeable as `/api/public/build-status` would return in a few seconds. Lately, it has been averaging at ~7 seconds.
Fixes https://github.com/flutter/flutter/issues/45285
Demo at https://testchillers-dot-flutter-dashboard.appspot.com/build.html
=> Tree status for loading

app/lib/build/status_card.dart, app/lib/build/task_guide.dart, app/lib/build/task_legend.dart, app_dart/dev/deploy.dart
Introduced in https://github.com/flutter/cocoon/pull/404. The deprecation mention messages these can be just removed, but doing that breaks the functionality. Since Cocoon is switching over to Flutter, I am just adding an ignore statement. The ideal approach would be to restructure the state of the Angular apps to work with the Angular state system.
The switch to using just the Dart runtime on AppEngine caused this issue to become evident. We never really redeployed the Go runtime with the latest Angular changes. Now that the latest changes are being served from Dart, users were able to notice some missing functionality.
For example, showing agent status messages was not working since the state was not being called to update.
Fixes https://github.com/flutter/flutter/issues/45549
Manually …
=> Angular Dart state fixes

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
The objects returned by the actual client are not jsonEncode-able, results in errors like:
```
Converting object to an encodable object failed: Instance of 'GraphQLError'
#0      _JsonStringifier.writeObject (dart:convert/json.dart:647:7)
#1      _JsonStringifier.writeList (dart:convert/json.dart:695:7)
#2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:677:7)
#3      _JsonStringifier.writeObject (dart:convert/json.dart:638:9)
#4      _JsonStringStringifier.printOn (dart:convert/json.dart:834:17)
#5      _JsonStringStringifier.stringify (dart:convert/json.dart:819:5)
#6      JsonEncoder.convert (dart:convert/json.dart:255:30)
#7      JsonCodec.encode (dart:convert/json.dart:166:45)
#8      jsonEncode (dart:convert/json.dart:80:10)
#9 …
```
=> Fix error logging

app_flutter/lib/sign_in_button.dart, app_flutter/test/sign_in_button_test.dart
If signed in at https://flutter-dashboard.appspot.com/build.html#/ you'll notice nothing showing you are logged in.
This is left over from switching over to CanvasKit.
=> Show user icon when logged in so CanvasKit shows a logged in state

app_flutter/lib/status_grid.dart, app_flutter/lib/task_box.dart, app_flutter/test/task_box_test.dart
When switching over to CanvasKit, we switched the `StatusGrid` back to an old form that did not include the download log code. Thus, it would not pass a `Commit` into the `TaskBox` so downloading logs would fail immediately.
- Required `Commit` in `TaskBox`
- Updated tests to match this so the issue can be caught via tests
https://testchillers-dot-flutter-dashboard.appspot.com/build.html#/ 
- If signed in, downloading logs should work. However, sign in does not work on this domain as it is not in the permitted domains list, so try the production dashboard.
=> Fix TaskBox null commit regression so logs can be downloaded

app_dart/lib/src/request_handling/cache_request_handler.dart, app_dart/lib/src/service/cache_service.dart
Requests that take advantage of the `CacheRequestHandler` throw 500s when there are several operations going on the cache. To prevent this, we should be waiting for all cache operations to finish (they are fast!).
Fixes https://github.com/flutter/flutter/issues/43762
=> Await cache operations and close cache when done to avoid Stream errors

agent/lib/src/commands/ci.dart
This is a prerequisite for auto-restart agents when they become
unhealthy. Also we will add functionality for nightly reboots of
devicelab host machines to improve testbed stability.
https://github.com/flutter/flutter/issues/43125
=> Unlock keychain before running a task.

app_dart/lib/src/request_handlers/update_task_status.dart, app_dart/pubspec.lock
Currently table Task in BigQuery has ID with two different formats:
<sha>
flutter/flutter/<sha>
This PR to make it consistent with all flutter/flutter/<sha>
=> Change ID in BigQuery to be consistent

.cirrus.yml
The update to Flutter 1.12 made the default version on CI of Dart to 2.5. This creates issues for `app`, and since `app` is being ported away this is just a quick fix to get CI working again.
=> Rollback to previous Dart version

app_dart/lib/src/request_handlers/get_log.dart
These were needed to show the logs in the browser, and now they are downloaded.
=> Remove HTML tags from logs downloaded on Cocoon

test_utilities/bin/dart_test_runner.sh
The `pub upgrade` shouldn't run on each commit.
Assume a dependency is broken at the latest version, in order to continue building Cocoon, we have to use the old stable version until that dependency fixed the problem and release a new version. Command `pub upgrade` would prevent use from doing that.
=> [luci] Remove `pub upgrade` from CI.

app_dart/lib/src/request_handlers/push_build_status_to_github.dart, app_dart/test/request_handlers/push_build_status_to_github_test.dart
This PR inserts tree build status to BigQuery via /api/push-build-status-to-github every 1 minutes.
Ultimate goal is to collect/generate Tree Healthiness metrics for future analysis.
=> Insert build status to BigQuery

app_dart/bin/server.dart, app_dart/cron.yaml, app_dart/lib/cocoon_service.dart, app_dart/lib/src/request_handlers/update_agent_health_history.dart, app_dart/test/request_handlers/udpate_agent_health_history_test.dart
This PR creates an API: /api/update-agent-health-history to update Agent health status history in BigQuery.
The old strategy misses records for cases when Agents hang, or tasks are running. This will make it difficult to tell accurate Agent health status for a certain time period.
This new API will be called via a cronjob every 1 minute, and guarantees continuous records of Agents statuses.
=> Update agent health status history in BigQuery

app_dart/lib/src/request_handlers/update_agent_health.dart, app_dart/lib/src/request_handlers/update_agent_health_history.dart, app_dart/test/request_handlers/update_agent_health_test.dart
A new API: /api/update-agent-health-history has been implemented: https://github.com/flutter/cocoon/pull/580
So, this PR simply removed earlier implementation. The earlier version missed data for certain scenarios, and the above API fixed the issue.
=> Remove bigquery insert from update-agent-health api

app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/request_handlers/github_webhook_test.dart
Both cocoon and engine are ready to start running luci presubmit tests
automatically. This add support for cocoon repo and removes the need for
CQ+1 on engine commits.
https://github.com/flutter/flutter/issues/43348
=> Run presubmit tests for cocoon and engine automatically on luci.

app_dart/lib/src/request_handlers/refresh_chromebot_status.dart, app_dart/test/request_handlers/refresh_chromebot_status_test.dart
Existing logic when refreshing chromebot status is keep updating task status for all executions of the same commit, from the latest to the oldest. This will keep the status on dashboard the same as  the earliest run's status. This is incorrect.
This PR stops updating task status whenever we find the latest status of one commit. This way the status on dashboard is always up-to-date.
=> Update with only the latest commit status when refreshing chromebot status

app_flutter/lib/task_box.dart, app_flutter/test/task_box_test.dart
Add textual information for whether or a Task is flaky. If Material Icons fails to load, we should still be able to tell if a Task is flaky or not by looking in the overlay.
Fixes https://github.com/flutter/flutter/issues/46283
Added test for flaky = true and flaky = false
=> Add isFlaky to Task Overlay

app_dart/bin/server.dart, app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/lib/src/request_handlers/luci_status.dart, app_dart/lib/src/request_handlers/update_task_status.dart, app_dart/lib/src/request_handlers/vacuum-clean.dart, app_dart/lib/src/request_handling/cache_request_handler.dart, app_dart/lib/src/service/cache_service.dart, app_dart/lib/src/service/luci.dart, app_dart/test/request_handling/cache_request_handler_test.dart, app_dart/test/service/cache_service_test.dart, app_dart/test/src/datastore/fake_cocoon_config.dart
Most of Cocoon's requests wait on Datastore operations to get config values that usually never change. This updates `CocoonConfig` to take advantage of caching. To make this simple in `CocoonConfig` I refactored `CacheService` to handle more of the cache logic.
After some discussion, this also moves some of the config values to be hard coded. This helps us better track changes made to the config. Any config values that do not need to be private have been pushed from Datastore into the code.
All Cocoon requests will see a speedup based on how many config variables they used (each variable use was a separate datastore query).
1. ~The current `CacheService` used the Datastore config to get values. To not have a circular dependency on the two resources, I have made the config values hard …
=> Cache CocoonConfig

test_utilities/bin/dart_test_runner.sh
Currently the if a file needs formatting it prints the entire file.
Even when the step fails it is difficult to spot what is failing and
what needs to get done.
=> Make formatting problems easier to spot.

app_dart/lib/src/request_handling/cache_request_handler.dart, app_dart/lib/src/service/cache_service.dart, app_dart/test/request_handling/cache_request_handler_test.dart, app_dart/test/service/cache_service_test.dart
When rolling out the CocoonConfig caching changes from https://github.com/flutter/cocoon/pull/569, there was issues with the cache not being cleared. I discovered it was because the TTLs never got set.
Additionally, memorystore GUI has no way to reset keys that have an indefinite ttl (created from this bug). I added `flushCache=true` to cached requests will reset the cache entry for the accessed response.
- Added regression tests to ensure TTL is passed through to the final set from the different entry points
- Added test to ensure flush cache param in cache request handler works
Broken example: ~https://v336-dot-flutter-dashboard.appspot.com/old_build.html~ - notice that all the agents have timed out
Patched version: https://v338-dot-flutter-dashboard.appspot.com/old_build.html - not all …
=> CacheService pass through ttl regression fix + flush cache

app_flutter/lib/canvaskit_widget.dart, app_flutter/lib/commit_box.dart, app_flutter/lib/sign_in_button.dart, app_flutter/test/canvaskit_widget_test.dart, app_flutter/test/commit_box_test.dart, app_flutter/test/sign_in_button_test.dart, app_flutter/test/status_grid_test.dart
This moves the CanvasKit changes from https://github.com/flutter/cocoon/pull/558 to a toggleable widget. When CanvasKit is currently in use, it will use the workarounds. Otherwise, it will use the previous widgets.
- Any ideas for a better name for `CanvasKitWidget`?
Demo: https://testchillers1-dot-flutter-dashboard.appspot.com/build.html
When running locally on an emulator, it defaults to the previous method (showing images).
=> CanvasKit Widget

app_flutter/lib/task_box.dart, app_flutter/test/task_box_test.dart
Fixes the run time in task summary and adds queue time.
Fixes https://github.com/flutter/flutter/issues/47490
https://testchillers-dot-flutter-dashboard.appspot.com/#/build
=> Task run and queue time in build dashboard

app_dart/lib/src/request_handlers/update_task_status.dart
This is used to easily query task results based on platform.
=> Add agent id for task in bigquery

app_dart/dev/deploy.dart
I did https://github.com/flutter/cocoon/pull/606 on my Mac. When I rebased to master I noticed my desktop could not deploy. Quick fix since it's a difference in how MacOS handles this command.
=> Update deploy script to work on linux

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/lib/src/request_handlers/check_for_waiting_pull_requests_queries.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
We're ignoring checkSuites currently when we check to see if the PR is green, which means we're ignoring the Cirrus check suites (and, presumably, other checks if we ever migrate flutter-build or the LUCI checks to checkSuites).
This makes sure that all statuses AND all check suites are successful before landing a waiting PR.
=> Check checkSuites

app_dart/lib/src/request_handlers/update_agent_health_history.dart, app_dart/test/request_handlers/update_agent_health_history_test.dart, app_dart/test/src/bigquery/fake_tabledata_resource.dart
Existing logic inserts agents health status to BigQuery every 1 min via a cronjob. However, the insertion timestamp is different for different agents.
This PR makes the insertion timestamp the same for all agents whenever the cronjob is called. This is helpful when we collect metric: percentage of time test beds that are over 90% healthiness (daily).
=> make agents timestamp same for bigquery insert

app_flutter/lib/build_dashboard.dart, app_flutter/lib/index_page.dart, app_flutter/lib/main.dart, app_flutter/lib/service/google_authentication.dart, app_flutter/lib/sign_in_button.dart, app_flutter/lib/state/flutter_build.dart, app_flutter/lib/state/index.dart, app_flutter/test/service/google_authentication_test.dart, app_flutter/test/state/flutter_build_test.dart, app_flutter/test/state/index_test.dart
This creates `GoogleSignInService` in `main.dart` and passes it around instead of recreating it on each page.
Updated sign in button to be a progress button to show if the sign in is in progress (good for issues when the plugin is being buggy). However, in CanvasKit this shows a weird color issue with the transparent color.
Mitigates https://github.com/flutter/flutter/issues/47832
- Seems to be an issue with the web implementation of sign in silently where it causes it to hang.
Checked for the states to have `notifyListener()` called when the sign in functions are called.
https://testchillers1-dot-flutter-dashboard.appspot.com
=> Create Google Sign In Service only once

app_flutter/lib/service/google_authentication.dart, app_flutter/test/service/google_authentication_test.dart
The Google Sign In web plugin has an issue where it can occasionally hang calling `signInSilently()`. As a work around, everyone will be required to manually sign in so everyone can sign in.
https://github.com/flutter/flutter/issues/47832
Added a test to check sign in is called in constructor, and skipped it :)
=> Temporarily disable silent sign in

app_dart/lib/src/datastore/cocoon_config.dart
LUCI builders have been running automatically on every PR from LUCI but
mac builders were not enabled because of lack of capacity. We moved half
of the capacity from prod pool to try and now we are ready to start
running LUCI tests by default in presubmit for engine repo.
Bug: https://github.com/flutter/flutter/issues/45562
=> [engine] Enable mac builders on luci try jobs.

app_flutter/lib/service/google_authentication.dart, app_flutter/lib/sign_in_button.dart, app_flutter/pubspec.lock, app_flutter/pubspec.yaml, app_flutter/test/service/google_authentication_test.dart
Thank you @ditman for fixing the Google sign in web bug with silent sign in the dashboard was facing. This just updates the dependencies and re-enables the sign in code with their patch.
Reverts the sign in button back to a basic button so it doesn't have the CanvasKit issue.
Fixes https://github.com/flutter/flutter/issues/47832
https://testchillers1-dot-flutter-dashboard.appspot.com
=> Update to federated plugins and re-enable silent sign in

app_flutter/lib/service/google_authentication.dart, app_flutter/test/service/google_authentication_test.dart
If a user is not signed in, and goes to make an authenticated request in Cocoon they will see an error snackbar prompting them to sign in. This updates it so whenever we attempt to make an authenticated request and the user is not signed in, we start the sign in process.
Fixes https://github.com/flutter/flutter/issues/44854
Since this creates special behavior for id token, I removed some of the basic checks for id token.
=> Prompt sign in process when making authenticated requests if necessary

app_flutter/lib/task_box.dart, app_flutter/test/agent_dashboard_page_test.dart, app_flutter/test/state/agent_test.dart
When deploying, I noticed some offset issues on the task icons. I looked at the skia and engine rolls, and it seems there have been some updates that would have caused this. I presume this is intended, but let me know if I should file a bug.
Also, there are some failing tests this fixes that were introduced with https://github.com/flutter/cocoon/pull/594 and https://github.com/flutter/cocoon/pull/620 being landed right next to each other. The presubmit tests were passing but postsubmit failed.
https://v348-dot-flutter-dashboard.appspot.com/#/build
=> CanvasKit UI tweak for the task matrix icons and test fixes

app_dart/dev/deploy.dart
This is the only dependency on the Flutter side I check for when deploying. It shouldn't be an issue going forward, but it helps document a minimum Flutter version needed for deploying Cocoon.
The reason for Flutter 1.12+ is that the web plugins require it.
=> Check Flutter version to be from the past 3 weeks

app_dart/bin/server.dart, app_dart/lib/src/model/appengine/task.dart, app_dart/lib/src/service/build_status_provider.dart, app_dart/test/service/build_status_provider_test.dart
This updates the build status algorithm to return failed if a task is having to rerun. 
Additionally, it reduces the amount of commits query from 100 to only the latest 20. Additionally, it caches this build status for 15 seconds. These changes are to remove unnecessary Datastore reads.
Fixes https://github.com/flutter/flutter/issues/45735
https://testchillers-dot-flutter-dashboard.appspot.com/#/build
=> Mark tree build status failed when tasks are rerunning

app_dart/lib/src/service/build_status_provider.dart, app_dart/test/src/service/fake_build_status_provider.dart
Introduced in https://github.com/flutter/cocoon/pull/617 where `retrieveCommitStatus` had a hard coded value for the number of commits to store. Instead it needed it to be passed in as a variable.
The reason for 20 commits is that's how many the build status algorithm looks at to validate the current tree state. Before it used to be 100.
https://v350-dot-flutter-dashboard.appspot.com/#/build
=> Fix /api/public/get-status only returning 20 commits

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/model/appengine/commit.g.dart, app_dart/lib/src/request_handlers/get_status.dart, app_dart/lib/src/service/build_status_provider.dart, app_dart/lib/src/service/datastore.dart, app_dart/test/request_handlers/get_status_test.dart, app_dart/test/src/datastore/fake_cocoon_config.dart, app_dart/test/src/request_handling/fake_authentication.dart, app_dart/test/src/service/fake_build_status_provider.dart
This PR reduces the default commit records shown on build dashboard from 100 to 25. 
This is the backend change, and enables `/api/public/get-status` to support input variable: ownerKey (commit). When the input variable is specified, this API will return the next 25 records whose timestamp is smaller than that of the input commit.
This will make it possible to append more records to build page when requested, and effectively reduce datastore queries.
=> Reduce commit rows in dashboard

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/lib/src/request_handlers/check_for_waiting_pull_requests_queries.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
The old logic allows for non-members/owners to approve
It also doesn't handle when someone goes from changes requested to approved.
This does that and adds tests.
=> improve review handling logic

app_dart/lib/src/datastore/cocoon_config.dart
Lack of capacity has been slowing down the develpment workflows because
some builders have been waiting for several hours. We are temporarily
disabling the builders while we add more capacity.
https://github.com/flutter/flutter/issues/49088
=> Temporarily remove engine try jobs.

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/lib/src/request_handlers/check_for_waiting_pull_requests_queries.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
This change makes the bot unlabel PRs that have statsuses or checks that are failing _other than_ luci-engine or flutter-build.
The idea is that if any other check/status is failing, the author needs to take action to actually fix those (as opposed to luci-engine and flutter-build, which get resolved without additional action on the PR).
This is important for autorollers, as they will otherwise not know when to close their PR.
@rmistry
fixes https://github.com/flutter/flutter/issues/49061
=> Unlabel PRs with failing checks

app_flutter/lib/service/appengine_cocoon.dart, app_flutter/lib/service/cookie.dart, app_flutter/lib/service/cookie_interface.dart, app_flutter/lib/service/cookie_web.dart, app_flutter/lib/service/downloader_interface.dart, app_flutter/lib/service/downloader_web.dart, app_flutter/lib/service/google_authentication.dart, app_flutter/test/service/appengine_cocoon_test.dart, app_flutter/test/service/google_authentication_test.dart
The cookie `X-Flutter-IdToken` is used by the Angular Dart dashboards for authenticating with Cocoon. The new Flutter app sends it as a header instead so that authentication in the app works on both mobile and web. When making direct requests to the api and using only the Flutter app, the request will fail when it previously worked on the old dashboards. This is because this cookie isn't being set.
This updates the code to write the auth cookie in the same fashion as the old dashboard so API requests can be made from the browser. That is, when the signed in user changes, write their id token as a cookie.
This removes the arbitrary wait on the cookie being written for downloading logs.
With the main functionality being the html cookie, I was only able to test that the cookie service is …
=> Write X-Flutter-IdToken cookie on sign in changes

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/lib/src/request_handlers/check_for_waiting_pull_requests_queries.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
Right now, the bot is not specifying a sort order when querying for PRs, which can starve older PRs.
Also bumps the number of PRs we merge every 5 minutes to 2 instead of 1.
=> Do 2 PRs per cycle, oldest first (by create date)

app_flutter/lib/service/appengine_cocoon.dart, app_flutter/lib/service/cocoon.dart, app_flutter/lib/service/fake_cocoon.dart, app_flutter/lib/state/flutter_build.dart, app_flutter/lib/status_grid.dart, app_flutter/test/service/appengine_cocoon_test.dart, app_flutter/test/state/flutter_build_test.dart, app_flutter/test/status_grid_test.dart, app_flutter/test/utils/fake_flutter_build.dart
Implement pagination on the build dashboard. This uses the backend query from https://github.com/flutter/cocoon/pull/624 to get the data based on the last commit. Then it appends this data to the end of the statuses. Additionally, the polling for data merges new data into the statuses list. This is done by introducing a loader row at the bottom of `StatusGrid`.
I tried to implement a smoother experience with slivers via a `SliverGrid` and `SliverBox`, where the box was a `CircularLoadingIndicator` that made the call to `fetchMoreCommitStatuses()` on being built. However, the sliver approach did not play nicely since `StatusGrid` needs both horizontal and vertical scrolls.
Closes https://github.com/flutter/flutter/issues/43098
https://github.com/flutter/flutter/issues/44478
See …
=> Add infinite scroll to the build dashboard

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests_queries.dart
GitHub is telling us we're touching too many nodes with this query as it stands - it hits 100 PRs x 100 check suites x 100 jobs per suite, which is 1m nodes.
We only have two check suites.  I'm reducing it to 10, which keeps us under the limits.  A bigger solution would be to actually do paging.
=> reduce nodes touched

app_dart/lib/src/datastore/cocoon_config.dart
First version of web_engine recipes are ready running Linux and Windows
tests. We are enabling their execution and we'll work later on a second
iteration of the recipes to provide more flexibility and scalbility.
https://github.com/flutter/flutter/issues/46782
=> Enable web_engine presubmit.

app_dart/index.yaml
I scanned all of `app_dart` and could not find any `order('reservedForAgentID')` or `filter('reservedForArgentID')` calls. I believe this is safe to remove.
https://github.com/flutter/flutter/issues/48914
=> Remove agent id composite index on task

app_dart/lib/src/request_handling/authentication.dart
This fixes the typo for WhitelistedAccount filed: `Email` to `email`.
=> WhitelistedAccount field name fix - authentication

app_dart/cron.yaml
The vacuum clean handler looks for tasks that are running for more than an hour.
Currently it checks every 10 minutes, which seems excessive with the current usage.
=> Slow vacuum clean cron to run hourly

app/lib/repository/details/roll.dart
Previously the roll dashboard would display green if the last roll failed, but the roller was still running.  That isn't very useful.  I switched it to display red if there was a failure.  This is slightly more useful and consistent with our other reporting.
=> Fixed the roll widget to report when a roll has failed.

agent/lib/src/health.dart
One health check is creating a flutter app and compiling it. If there is
and error with flutter then the agent will quarantine until we manually
checkout a new version of flutter.
https://github.com/flutter/flutter/issues/51085
=> Make health checks resilient to flutter failures.

app_dart/lib/src/datastore/cocoon_config.dart
This PR enables Mac web engine presubmit test.
Related:
https://github.com/flutter/cocoon/pull/645
https://github.com/flutter/flutter/issues/46782
=> Enable Mac Web Engine presubmit.

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/lib/src/request_handlers/refresh_cirrus_status.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
Existing cirrus status logic misses `SKIPPED` status, which causes hang when one task is `SKIPPED`. This will cause PRs not merging forever.
This PR puts `SKIPPED` as a success flag for tasks in cirrus.
=> Consider SKIPPED status for cirrus graphql API

app_dart/analysis_options.yaml
Per comment here: https://github.com/flutter/cocoon/pull/651#discussion_r385561485
The current configuration of the analyzer has a contradiction in it.
dartfmt demands this
```dart
if (this) do that;
```
but the analyzer demands
```dart
if (this)
do that;
```
The **only** way to pass analysis is to include curly braces. 
```dart
if (this) {
do that;
}
```
Adding this to the analyzer will help alleviate confusion and back & forth when this case presents itself. :)
=> Added curly braces to analyzer

app_flutter/lib/task_box.dart
Currently the git commit SHA is a SelectableText, but task name is not.
That said, when tasks fail, developers frequently want to search the
source for the task in question in order to debug.
=> Make task name selectable

app_dart/bin/server.dart, app_dart/cron.yaml, app_dart/lib/cocoon_service.dart, app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/model/appengine/github_gold_status_update.dart, app_dart/lib/src/request_handlers/push_gold_status_to_github.dart, app_dart/lib/src/request_handlers/refresh_cirrus_status.dart, app_dart/lib/src/service/datastore.dart, app_dart/test/request_handlers/push_gold_status_to_github_test.dart
This change will add a Gold status check to all framework PRs that reflects the state of the current tryjobs run through Flutter Gold for the pr and commit.
This was originally attempted in https://github.com/flutter/flutter/pull/49370 as a Cirrus check. That implementation was subject to timeouts from Cirrus, so it will be implemented here instead.
Adding this check will do a couple of things for improved workflow and productivity.
- This will streamline framework changes.
- Currently, framework tests fail when a golden file change is detected. After triaging on the Flutter Gold dashboard, the affected test shards need to be re-executed, which in some cases could take over an hour. A follow-up to this change in the framework would remove the failure case on individual test shards, making …
=> Adding gold status check to framework PRs

app_dart/index.yaml, app_dart/lib/src/model/appengine/commit.dart, app_dart/lib/src/request_handlers/get_status.dart, app_dart/lib/src/service/build_status_provider.dart, app_dart/lib/src/service/datastore.dart, app_dart/pubspec.yaml, app_dart/test/request_handlers/get_status_test.dart, app_dart/test/src/service/fake_build_status_provider.dart
This PR prepares for frontend support to list commits w.r.t. different branches. Default lists are for `master`, otherwise it shows corresponding lists when `branch` parameter is specified.
Related issue: https://github.com/flutter/flutter/issues/51807
=> Support branch parameter for API get-status

app_dart/README.md
This was done in GitHub. A trailing white space was removed on another line :tada:
=> Update app_dart readme with how to run the tests

app_flutter/lib/task_box.dart, app_flutter/test/task_box_test.dart
Update the tests to use `Key` instead of `BoxDecoration` for how they verify `TaskBox` is behaving how it should.
https://github.com/flutter/flutter/issues/52147
=> Fix Flutter app tests that rely on BoxDecoration for color checks

app/pubspec.lock
Without this, the building angular app step will fail in `app_dart/dev/deploy.dart` silently when it just needs a `pub upgrade`.
=> Upgrade app pubspec to fix deploys

app_flutter/lib/commit_box.dart
In case of task failure, these fields are sometimes useful for pasting
to chat or grepping in source.
=> Make author email and cocoon agent selectable

agent/lib/src/health.dart
When devicelab was having signing issues we added a health check that
created and app, build it and sign it. Later on we had some issues
where a problem with flutter sdk cause all the test beds to get
quarantined as soon as it was running test.
App signing has been very stable recently and we don't need this health
check anymore. We are removing it to get a couple of minutes of
execution time back.
Bug:
https://github.com/flutter/flutter/issues/52286
=> Remove signing helloworld app check.

app/pubspec.yaml
New versions of build_web_compilers are failing and we need to lock it
to the latest good known version.
Bug:
https://github.com/flutter/flutter/issues/52362
=> Lock version of build_web_compilers.

app_dart/lib/src/foundation/utils.dart, app_dart/lib/src/request_handlers/push_engine_status_to_github.dart, app_dart/lib/src/request_handlers/refresh_chromebot_status.dart, app_dart/lib/src/request_handlers/reserve_task.dart, app_dart/lib/src/request_handlers/update_task_status.dart, app_dart/test/foundation/utils_test.dart
Most of the 500 errors in the backend are related to failing
transactions. This change adds retries with quadratic backoffs to remove
the flakiness.
Bugs:
https://github.com/flutter/flutter/issues/42524
https://github.com/flutter/flutter/issues/43112
https://github.com/flutter/flutter/issues/49673
https://github.com/flutter/flutter/issues/49672
=> Add transaction retries.

app_flutter/lib/build_dashboard_page.dart, app_flutter/lib/service/appengine_cocoon.dart, app_flutter/lib/service/cocoon.dart, app_flutter/lib/service/fake_cocoon.dart, app_flutter/lib/state/flutter_build.dart, app_flutter/test/service/appengine_cocoon_test.dart, app_flutter/test/state/flutter_build_test.dart, app_flutter/test/utils/fake_flutter_build.dart
This adds the necessary backend in the Flutter app to get the list of branches from Cocoon. It defaults to showing just the `master` branch until data is loaded. The branch list is not refreshed after the initial load of the app.
Tested all possible points of error like the other cocoon service functions are.
Tested that on start of the Flutter build state this `getFlutterBranches()` is called.
https://github.com/flutter/flutter/issues/51807 - Flutter branching for releases
Enable UI in the Flutter app to switch the current branch
=> Cocoon getFlutterBranches()

agent/lib/src/utils.dart
https://github.com/flutter/cocoon/pull/691 and https://github.com/flutter/cocoon/pull/690 (and any new PRs to Cocoon) are blocked due to some lint issue with the agent:
```
error - The type 'Iterable<dynamic>' used in the 'for' loop must implement Iterable with a type argument that can be assigned to 'String' at lib/src/utils.dart:636:31 - (for_in_of_invalid_element_type)
```
I believe this is due to the Dart tests using the latest dev channel, and this issue is now rolled into Cocoon.
=> Fix agent lint issue

app_dart/README.md, app_dart/dev/deploy.dart
There was an issue this past week in deploying where the latest Flutter dev channel broke Cocoon. To prevent these breakages is WIP and being tracked in https://github.com/flutter/flutter/issues/52147
This allows us to pass --force-deploy to ignore Flutter not being a recent version from the past 3 weeks.
Added help dialog to have the deploy script document itself.
=> Add force-deploy and help flags to deploy script

app_dart/lib/src/foundation/utils.dart, app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/lib/src/request_handlers/get_branches.dart, app_dart/lib/src/request_handlers/push_gold_status_to_github.dart, app_dart/lib/src/request_handlers/refresh_cirrus_status.dart, app_dart/lib/src/request_handlers/refresh_cirrus_status_queries.dart, app_dart/lib/src/request_handlers/refresh_github_commits.dart, app_dart/lib/src/service/datastore.dart, app_dart/test/foundation/utils_test.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart, app_dart/test/request_handlers/push_gold_status_to_github_test.dart, app_dart/test/request_handlers/refresh_cirrus_status_test.dart
This is part of https://github.com/flutter/flutter/issues/51807
Instead of assuming only one branch exists for each commit in cirrus, we here consider all branches. When updating cirrus status in cocoon, we consider the branch property as well.
=> Support branching for cirrus status

agent/lib/src/health.dart, agent/test/src/health_test.dart
VMs are failing frequently because the cache folders keep growing over
time. With this change the agent will be deleting the cache folders.
Bug:
https://github.com/flutter/flutter/issues/50482
=> Adds cleanup steps for cache directories.

app_flutter/lib/service/appengine_cocoon.dart, app_flutter/lib/service/cocoon.dart, app_flutter/lib/service/fake_cocoon.dart, app_flutter/lib/state/flutter_build.dart, app_flutter/test/service/appengine_cocoon_test.dart, app_flutter/test/state/flutter_build_test.dart, app_flutter/test/utils/fake_flutter_build.dart
Create `currentBranch` in `FlutterBuildState` and plumbed it through everywhere that uses it.
Refactored some of the test code to remove some of the duplication spread throughout it and fixed some spacing issues.
Added tests for `apiEndpoint` refactor to handle query parameters.
Updated tests to check for defaulting to the `master` branch.
https://github.com/flutter/flutter/issues/51807 - Flutter branching for releases
Create an `updateBranch` method in `FlutterBuildState` to change `currentBranch` to update the UI.
=> Explicitly use the master branch in build dashboard

app_dart/lib/src/request_handlers/reserve_task.dart
As we are implementing support for branching, `reserve-task` API reserves tasks for the default `master` branch only before this PR.
This PR fixes that by reserving tasks regardless of branches. It will reserve tasks for latest commits first, no matter what branch it is.
In the future, we may need to adjust priority to run tasks for different branches.
=> Reserve task regardless of branches

app_dart/lib/src/model/proto/internal/commit_status.pb.dart, app_dart/lib/src/model/proto/internal/commit_status.proto, app_flutter/lib/service/appengine_cocoon.dart, app_flutter/test/service/appengine_cocoon_test.dart
This lets the frontend track data based on branch.
flutter/flutter#51807 - Flutter branching for releases
app_dart tests pass
app_flutter appengine json updated to match latest which includes the branch field
Use this to invalidate previous branch data to show the currently selected branch.
=> Update CommitStatus to have branch field

agent/lib/src/health.dart, agent/test/src/health_test.dart
If we delete .pub-cache the agent execution is affected even if we
immediately run pub get. Pub-cache will need to be cleaned out as part
of the agent update.
https://github.com/flutter/flutter/issues/52957
=> Do not remove .pub-cache as it is required by the agent.

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/foundation/utils.dart, app_dart/lib/src/request_handlers/push_build_status_to_github.dart, app_dart/lib/src/service/github_service.dart, app_dart/test/foundation/utils_test.dart, app_dart/test/request_handlers/get_branches_test.dart, app_dart/test/request_handlers/push_build_status_to_github_test.dart, app_dart/test/request_handlers/refresh_cirrus_status_test.dart, app_dart/test/request_handlers/refresh_github_commits_test.dart, app_dart/test/src/datastore/fake_cocoon_config.dart, app_dart/test/src/datastore/fake_datastore.dart, app_dart/test/src/service/fake_github_service.dart
This is part of https://github.com/flutter/flutter/issues/51807
We will support commits following different branches. Existing logic to push build status to github doesn't recognize branch difference. It will calculate build status based on latest commits of `master` (default), and push the status to all PRs in github.
The change here fixes above issue. It will update PRs of a specific branch based on the build status calculated according to that branch's commits.
=> Support branching for push build status to github

test_utilities/bin/flutter_test_runner.bat, test_utilities/bin/flutter_test_runner.sh
This is causing timeouts on flutter/tests. This was originally added before the web team had tests running in CI on the framework repo. This was to help detect issues before deploying. Now that there is tooling around this, we can remove it from Cocoon's CI.
=> Remove web build test from test runner now that there are flutter web tests in CI

app_flutter/lib/agent_health_details.dart, app_flutter/lib/agent_health_details_bar.dart, app_flutter/lib/agent_list.dart, app_flutter/lib/agent_tile.dart, app_flutter/lib/main.dart, app_flutter/lib/now.dart, app_flutter/test/agent_dashboard_page_test.dart, app_flutter/test/agent_health_details_bar_test.dart, app_flutter/test/agent_health_details_test.dart, app_flutter/test/agent_list_test.dart, app_flutter/test/agent_tile_test.dart, app_flutter/test/utils/wrapper.dart
Having DateTime.now dependencies in logic has two problems:
- It causes the view to become stale over time (because nothing
changes when the time changes, so e.g. "10 minutes ago" stops being
accurate).
- It increases the chance of flakes in tests (because any time you run
the tests, you're running them with new previously untested data,
and because if there's multiple places in the code checking the
current time, they race each other).
Instead this provides the time as an inherited widget.
=> Remove dependencies on DateTime.now

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/lib/src/request_handlers/push_gold_status_to_github.dart, app_dart/lib/src/request_handlers/refresh_cirrus_status.dart
This fixes: https://github.com/flutter/engine/pull/17387#issuecomment-606133019
Per discussions in the above thread, multiple build cirrus results may exist for same SHA and branch. This pr uses the latest result instead, rather than assuming single result.
=> Use latest build result instead for cirrus status check

app_dart/lib/src/service/datastore.dart, app_dart/test/service/datastore_test.dart
This was because we were trying to send too many groups >5 in a single
transaction.
https://github.com/flutter/flutter/issues/54376
=> Fix too many entity groups error.

app_dart/lib/src/datastore/cocoon_config.dart
We have add 10 mac minis that can run these Engine try builds. Let's see if the capacity is enough.
A known issue: Mac iOS Engine is flaky due to https://github.com/flutter/flutter/issues/53455.
Bug: https://github.com/flutter/flutter/issues/49088
=> Re-enable Engine try jobs.

app_dart/lib/src/service/datastore.dart, app_dart/test/request_handlers/push_gold_status_to_github_test.dart, app_dart/test/service/datastore_test.dart
It will modify to a quadratic backoff starting at 200ms and will retry
up to 8 times.
https://github.com/flutter/flutter/issues/54615
=> Update backend retry logic.

app_dart/lib/src/service/datastore.dart
Before this PR, it queries recent history data regardless of branches. 
With this PR, it uses default `master`.
=> Add branch filter when querying TimeseriesValue for benchmark history

app_flutter/lib/service/appengine_cocoon.dart, app_flutter/test/service/appengine_cocoon_test.dart
These API endpoints from the frontend were broken due to a typo.
1. CreateAgent
1. AuthorizeAgent
1. ReserveTask
Also simplified related unit tests.
Bug: https://github.com/flutter/flutter/issues/54677
=> [app_flutter] Fix broken requests

app_dart/lib/src/request_handlers/push_gold_status_to_github.dart, app_dart/test/request_handlers/push_gold_status_to_github_test.dart
This trims the number of requests we are making to Gold for the flutter-gold pull request status. After @kjlubick reported increased traffic, I noticed in the logs that we could eliminated hitting the endpoint if the PR is a 'draft' PR, as well as when other checks are failing since some other action will already need to be taken to resolve those tests before proceeding.
In these two cases, draft and failing PRs, a pending state will be pushed and maintained without checking Gold.
=> Remove unnecessary Gold requests

app_dart/lib/src/request_handlers/push_gold_status_to_github.dart, app_dart/test/request_handlers/push_gold_status_to_github_test.dart
Closing out a TODO I noticed while making another change yesterday.
Now that we are running Luci pre-submit checks, we should include them in determining the Gold status. The flutter-gold check waits on all checks to finish successfully before checking in with the Flutter Gold service for image changes.
=> Add Luci builds to Gold status check

app_dart/lib/src/request_handlers/push_gold_status_to_github.dart, app_dart/test/request_handlers/push_gold_status_to_github_test.dart
This fixes https://github.com/flutter/flutter/issues/56682 which was introduced in https://github.com/flutter/cocoon/pull/762 as we as parsing statuses now looking for Luci builds.
=> [Gold Status] Account for null status descriptions when parsing luci builds 

app_dart/lib/src/request_handlers/refresh_github_commits.dart
Linux bots are experiencing infra failures downloading and installing tiles_ctl dependencies for the fuchsia test.
Temporarily mark as flaky.
=> Mark linux_bot as flaky

app_dart/lib/src/request_handlers/refresh_github_commits.dart
Reverts flutter/cocoon#766
@godofredoc removed the fuchsia tests and will land them on a separate builder.
Fixes https://github.com/flutter/flutter/issues/57042.
=> Revert "Mark linux_bot as flaky"

app/lib/benchmark/benchmark_card.html, app/lib/benchmark/benchmark_grid.html
This PR solves the malformed <!DOCTYPE HTML> issue on flutter benchmark page.
(The above issue happens in both benchmark_grid and benchmark_card).
=> Fix benchmark malformed issue

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/src/datastore/fake_cocoon_config.dart
Previously this list was on webhook but they will need to get shared
with different utilities needed to enable checks apis.
Bug:
flutter/flutter#56422
=> Move configs to detect if a repo supports presubmit to config.

app_dart/lib/src/datastore/cocoon_config.dart
Related to https://github.com/flutter/flutter/issues/58012
=> temporarily comment out Mac Web Engine task, as it is flaky

app_dart/lib/src/datastore/cocoon_config.dart
Reverses https://github.com/flutter/cocoon/pull/782 because the flaking tests have been disabled in the recipe: https://flutter-review.googlesource.com/c/recipes/+/3162 and the builder re-enabled in https://github.com/flutter/infra/pull/130.
Related to https://github.com/flutter/flutter/issues/58012
=> re-enable mac web engine

app_dart/lib/src/request_handlers/refresh_github_commits.dart
This fixes issue: https://github.com/flutter/flutter/issues/52503
Cocoon has been using new key pair <sha, branch> for commits, and the old key <sha> is no longer needed to check.
=> Remove old key check when refreshing github commits

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/request_handlers/luci_status.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/src/datastore/fake_cocoon_config.dart
This is part of the refactoring to add checks api. We are moving generic
functionality used in luci_status and github_webhook.
Bug:
=> Add a luci build service.

README.md, app_dart/bin/server.dart
When `COCOON_USE_IN_MEMORY_CACHE` is set to `true`
we use in memory cache as opposed to the remote redis
instance.
fixes: https://github.com/flutter/flutter/issues/43743
=> Add an env var that supports using inmemory cache

app_dart/README.md, app_dart/dev/branch_regexps.txt
This PR skips unwanted branches scan by changing the general branch regexp to more detailed format.
Related issue:
https://github.com/flutter/flutter/issues/58627
https://github.com/flutter/flutter/issues/55579
=> Avoid unwanted branches scan

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/request_handlers/push_gold_status_to_github.dart, app_dart/test/request_handlers/push_gold_status_to_github_test.dart, app_dart/test/src/datastore/fake_cocoon_config.dart
Related issues: https://github.com/flutter/flutter/issues/58627 https://github.com/flutter/flutter/issues/58814
This removes the gold check from branches that are not staged to land on master (i.e. release branches) We've been hitting Github API rate limits, so this should help cut back on those requests.
=> Removing Gold checks on non-master branches

app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
I merged #800 before seeing @keyonghan's comment to fix the log. 😅  Adds some extra logging as we have changed the skip case to reduce github requests.
=> Updating log info for Gold

app_dart/dev/branch_regexps.txt, app_dart/dev/branches.txt, app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/foundation/utils.dart, app_dart/test/foundation/utils_test.dart
This PR addressed comment: https://github.com/flutter/cocoon/pull/799#discussion_r436174916
Cocoon is using fixed branch name list to iterate wanted branches after PR: https://github.com/flutter/cocoon/pull/799. However it still keeps querying GitHub API to unnecessarily screen through all available branches. This helps nothing but wasting API calls.
This PR removes the above GitHub api call, and uses branches directly.
=> [cocoon] Avoid GitHub API call after changing branch regexps to branches

README.md
This is part of https://github.com/flutter/flutter/issues/58619
=> Update local dev doc to remove requirement of creating a service account in GCP

app_dart/lib/src/request_handlers/update_task_status.dart
Old `task` ID follows format: `/flutter/flutter/<SHA>`, whereas `commit` ID follows: `/flutter/flutter/<branch>/<SHA>`. This make it difficult to join these tables in bigquery.
This PR changes `task` ID to have the same format as `commit`.
=> Update task ID in bigquery to be consistent with commit ID

app_dart/lib/src/datastore/cocoon_config.dart
This builder will be used for subbuilds of mac and is not intended to
run directly.
Bug:
https://github.com/flutter/flutter/issues/59169
=> Remove Mac Engine Drone build.

app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/lib/src/request_handlers/luci_status.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/test/request_handlers/github_webhook_test.dart, app_dart/test/request_handlers/luci_status_test.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/src/utilities/push_message.dart
This is part of the refactoring required to enable checks api on the
cocoon application.
This also fixes a problem when failed builds were not resetting the
build state back to pending for a retry.
Bugs:
https://github.com/flutter/flutter/issues/56421
=> Remove duplicated code from web_hook and luci_status.

app_dart/test/request_handlers/push_build_status_to_github_test.dart
This pr fixes issue with test `update if statuses have changed since last update - multiple branches` for API: `push-build-status-to-github`.
The old test used inappropriate test values.
=> Push build status to github test case fix

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/request_handlers/luci_status.dart
When a builder is deleted there may be still pending or running tasks
that will try to update state. GCP pubsub will try to deliver the
message several times potentially generating several 500 http status.
Bug:
https://github.com/flutter/flutter/issues/59270
=> Discard state pubsub message for builders that were deleted.

app_dart/lib/src/request_handlers/luci_status.dart, app_dart/test/request_handlers/luci_status_test.dart
This is to determine 500s on the backend when calling luci status
handler.
Bug:
https://github.com/flutter/flutter/issues/59270
=> Add more logging to luci status handler.

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/request_handlers/refresh_github_commits.dart, app_dart/lib/src/service/github_service.dart, app_dart/test/request_handlers/refresh_github_commits_test.dart, app_dart/test/src/datastore/fake_cocoon_config.dart, app_dart/test/src/service/fake_github_service.dart
This PR fixes: https://github.com/flutter/flutter/issues/54284
It uses `timestamp` of last commit in datastore as the criteria to query Github api. This makes the query more accurate than the case using a fixed time period.
=> Use timestmap of last commit rather than a fixed time period to query github commits API

app_dart/lib/src/request_handlers/vacuum-clean.dart, app_dart/lib/src/service/datastore.dart, app_dart/test/request_handlers/vacuum_clean_test.dart, app_dart/test/service/datastore_test.dart
Existing `vacuum-clean` api runs on `master` tasks only. This causes unhealthy status for tasks of release branches.
This PR updates `vacuum-clean` api to consider release branches as well.
Related issue: https://github.com/flutter/flutter/issues/60056
=> Apply vacuum clean to branch tasks

app_dart/lib/src/datastore/cocoon_config.dart
LUCI support for packages repository was removed in one of the many
refactorings. This PR is adding it back.
=> Add packages repository.

app_dart/lib/src/model/appengine/task.dart, app_dart/lib/src/model/appengine/task.g.dart, app_dart/lib/src/request_handlers/refresh_chromebot_status.dart, app_dart/lib/src/request_handlers/refresh_github_commits.dart, app_dart/test/request_handlers/refresh_chromebot_status_test.dart
This PR simplifies luci number support for luci reruns.
Existing strategy keeps track of different luci rerun builds by maintaining multiple task records in datastore.
With this PR, only one task record is needed: buildNumberList keeps track of all different builds. This will also make frontend change easiler.
=> Update luci build number list

app_flutter/test/widgets/task_overlay_test.dart, test_utilities/bin/flutter_test_runner.sh
Reopens https://github.com/flutter/flutter/issues/58833 and removes the flakiness to cocoon CQ
Reverts https://github.com/flutter/cocoon/pull/823
=> Disable golden testing on task overlay due to precache flakiness

app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/lib/src/request_handlers/luci_status.dart, app_dart/lib/src/service/github_status_service.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/test/request_handlers/github_webhook_test.dart, app_dart/test/request_handlers/luci_status_test.dart, app_dart/test/service/luci_build_service_test.dart
This is required to add functionality to re-trigger tasks on failure.
Bug:
=> Schedule luci builds using CheckSuite and CheckRun events.

app_dart/bin/server.dart, app_dart/lib/src/request_handlers/luci_status.dart, app_dart/test/request_handlers/luci_status_test.dart, app_dart/test/src/utilities/push_message.dart
The implementation of the checks api will be one repo at a time and we
need to support repos with checks api support and the ones no yet
migrated. This PR checks is the status message comes with all the
expected fields to decide whether to process checks api updates or not.
Bug:
=> Only process check updates if messages come from a supported repo.

app_dart/lib/src/model/appengine/allowed_account.dart, app_dart/lib/src/model/appengine/allowlisted_account.dart, app_dart/lib/src/model/appengine/key_helper.dart, app_dart/lib/src/request_handling/authentication.dart, app_dart/test/request_handling/authentication_test.dart
Switch `WhitelistedAccount` to `AllowedAccount` based off recommended practices. I originally had it as `AllowlistedAccount`, but dropped it as I don't think "listed" gave much value.
Public documentation available at https://developers.google.com/style/inclusive-documentation#features-and-users (googlers see go/avoid-whitelist)
If this looks good, I can duplicate the existing entities over to the new table before submitting. After deployed and verified, I can remove the `WhitelistedAccount` entities.
There's only a few accounts, so this change is relatively low risk.
=> Remove "whitelist" terminology in Cocoon

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/foundation/utils.dart, app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/request_handlers/get_benchmarks_test.dart, app_dart/test/request_handlers/github_webhook_test.dart, app_dart/test/src/datastore/fake_cocoon_config.dart
This PR makes the following bot improvements:
1. Does **not** reset release candidate PRs to target master branch; fixes https://github.com/flutter/flutter/issues/55900
1. Auto-closes PRs that try to merge from {stable,beta,dev} with a comment pointing the user toward "Tree Hygiene" link in wiki; fixes https://github.com/flutter/flutter/issues/60386
1. Replaces a lot of hard-coded uses of the string `'master'` in the codebase to use a constant variable.
=> GitHub Bot Improvements

app_flutter/test/widgets/task_overlay_test.dart
Two of the tests needed a `tester.pump()` after pumping the widget to allow for the precache to populate. When those tests were run first, they were not loading the asset in time.
Fixes https://github.com/flutter/flutter/issues/58833
=> Fix TaskOverlay golden test flakes

app_flutter/test/utils/golden.dart
While working on https://github.com/flutter/cocoon/pull/847, I did not realize that I might be affecting golden files, as I was working on a Mac. 
A skipped test provides output at execution for better awareness than a silent no-op. :)
Now local test output will reflect a test being skipped:
=> Receive local skip feedback for goldens

app_flutter/flake_catcher.sh, app_flutter/lib/service/google_authentication.dart, app_flutter/test/service/google_authentication_test.dart
The app is having google sign in silently crash when executing silent sign in. For now, disabling this should allow for the manual sign in process to work.
By default, a quick window will be opened by google sign in to log the user in. If the user isn't signed in, it will stay open for them to sign in.
Users that are not signed in and that try to perform an authenticated action will be prompted this sign in flow automatically. This is part of the apps built in error handling.
https://github.com/flutter/flutter/issues/59086
https://github.com/flutter/flutter/issues/52338
=> [app_flutter] Disable silent sign in

app_flutter/lib/build_dashboard_page.dart, app_flutter/lib/main.dart, app_flutter/test/build_dashboard_page_test.dart
After recent deployment, noticed the changes from #847 did not match the goldens we checked in.
The tests appear to be using a different Theme than is actually used in the app (default dark and light themes instead of the custom themes in main.dart). 
To avoid updating all of the goldens, I've changed the app to match the tests. Happy to go the other way, will defer to reviewer. :)
Also added a11y tests for the affected conditional app bar color on the build page so it meets text contrast guidelines for light and dark themes for each tree status.
=> Fix app theming and tests

app_dart/lib/src/service/datastore.dart
Vacuum-clean API cleans datastore tasks in bad state every one hour. Existing task query has a limit on the returned number of tasks. With this limit, some tasks that do need to be cleaned up may be skipped.
We need to remove the limit and return all tasks.
\cc @pcsosinski
=> Remove task number limit when vacuum clean tasks in bad state

app_dart/bin/server.dart
A simple QoL change to make it easier to launch the web page from the printout in the terminal.
=> Make the printed URL clickable in command terminals

app/lib/repository/services/sheriff_rotation_service.dart
The rota-ng endpoint we were using to get the engine-oncall is being
deprecated and we are updating it to use the replacement.
=> Update rota-ng endpoint.

app_flutter/lib/service/appengine_cocoon.dart
The handler url was changed but the client code was not updated.
Bug:
https://github.com/flutter/flutter/issues/54873
=> Update the handler url to retry prod bots.

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/foundation/utils.dart, app_dart/lib/src/request_handlers/luci_status.dart, app_dart/lib/src/service/github_status_service.dart, app_dart/test/datastore/cocoon_config_test.dart, app_dart/test/foundation/utils_test.dart, app_dart/test/service/github_status_service_test.dart, app_dart/test/src/datastore/fake_cocoon_config.dart
This PR moves function `repoNameForBuilder` from cocoon_config to utils for below reasons:
- We are changing access of `luciBuilders` from cocoon_config to http request. This change will make testing `repoNameForBuilder` in `cocoon_config_test` challenging. Instead, moving it to `utils` makes it easy for testing in `utils_test`.
- `repoNameForBuilder` will be more general for both `try` and `prod` builders, rather than hard-coded for `try`.
=> Move function 'repoNameForBuilder' to utils from cocoon_config

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
This is required to find out why some rollers are being submitted even
when they have failures.
Bug:
https://github.com/flutter/flutter/issues/62211
=> Add more logging to the autosubmit bot.

app_dart/dev/luci_prod_builders.json, app_dart/dev/luci_try_builders.json
https://github.com/flutter/cocoon/pull/860 mis-switched the contents for `try` and `prod`. This pr updates the files with the correct list.
=> Update with correct builders

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/lib/src/request_handlers/check_for_waiting_pull_requests_queries.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
The checks validation was using the first or last checksuite to collect
all the check runs to validate. The first checksuite contains cirrus
checks and the last one contains the checks from wip app. This caused
several rollers landing changes without validating all the luci
builders.
Bug:
https://github.com/flutter/flutter/issues/62211
=> Pull checks state from flutter-dashboard app.

agent/lib/src/agent.dart, agent/lib/src/commands/ci.dart, agent/lib/src/commands/run.dart, agent/lib/src/runner.dart
Remove 15 minute timeout hard coded into runner (which is used whether
tests are run locally or as part of CI), and add a 1-hour fallback
timeout to the CI runner.
https://github.com/flutter/flutter/issues/62419
=> Fix agent timeouts

agent/lib/src/health.dart, agent/test/src/health_test.dart
If an existing code singing config exists on a test bed, we should use that one in order to build the infra-dialog project.
Bug: flutter/flutter#54792
=> [agent] Overwrites code signing config of infra-dialog

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/request_handlers/github_webhook_test.dart, app_dart/test/src/datastore/fake_cocoon_config.dart
SDK luci try jobs are triggered by labeling `CQ+1`. This PR removes the `CQ+1` label to enable Luci try jobs by default for SDK.
This is part of SDK migration to Luci project.
=> Enable flutter luci try by default

app_dart/lib/src/service/luci_build_service.dart
Github client is now using short lived tokens and in some cases when we
need to validate is builds exist and cancel them the token expired in
the middle of the request. We are moving the github client creation and
authentication to the place it will be used instead of creating at the
beginning of the method.
Bug:
https://github.com/flutter/flutter/issues/62233
=> Move the github client auth closer to where it will be used.

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/service/github_service.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/pubspec.yaml
Github service calls was not using authentication to request the list of
PRs which worked when flutter/flutter was using the webhook but does not
with Github App auth.
Bug:
https://github.com/flutter/flutter/issues/62711
=> Fix auth errors for github service calls.

app_dart/lib/src/request_handlers/refresh_github_commits.dart, app_dart/pubspec.yaml
Commit messages can be longer than 1500 chars however the limit in the
datastore field is 1500 chars. We are truncating commit messages when
they are longer than 1500 chars.
Bug:
https://github.com/flutter/flutter/issues/62789
=> Truncate commit message at 1500 chars.

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/model/appengine/github_gold_status_update.dart, app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/lib/src/request_handlers/push_gold_status_to_github.dart, app_dart/test/request_handlers/github_webhook_test.dart, app_dart/test/request_handlers/push_gold_status_to_github_test.dart, app_dart/test/src/datastore/fake_cocoon_config.dart
This updates and refactors the functionality of the flutter-dashboard bot as it relates to the flutter-gold check.
- Fixes https://github.com/flutter/flutter/issues/62682
- Bot was broken by switch from status to check
- follows the same pattern of `check_for_waiting_pull_requests` to query checkSuites, have not found a way to confirm yet
- updated tests
- Removes gold logic from the `github_webhook`
- This is no longer applicable
- updated tests
- Updates the config to include flutter-gold Strings for status and notifications
- updated fake config and relevant tests
=> Refactor and Update flutter-gold check

app_dart/lib/src/foundation/utils.dart, app_dart/lib/src/request_handlers/push_engine_status_to_github.dart, app_dart/test/foundation/utils_test.dart, app_dart/test/request_handlers/push_engine_status_to_github_test.dart
Framework build status has been collected to monitor the tree status. It would be useful to track the build status of Engine as well.  
By saving status to BigQuery, we can further show its trending chart in datastudio.
\cc @pcsosinski
=> Save engine build status to bigquery

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/foundation/utils.dart, app_dart/test/foundation/utils_test.dart, app_dart/test/src/datastore/fake_cocoon_config.dart
Existing cocoon supports querying luci builders as a whole for all different repos. Now we have moved configs to different repos, this PR provides logic to support querying targeted repo luci builders.
Old existing logic will be removed once we updated corresponding APIs to point to the new changes.
Related: https://github.com/flutter/flutter/issues/62429
=> Add repo support when querying supported luci builders for different repos

app_flutter/lib/index_page.dart, app_flutter/lib/logic/links.dart, app_flutter/lib/navigation_drawer.dart, app_flutter/test/index_page_test.dart, app_flutter/test/navigation_drawer_test.dart
Create a generic list of the links used in Cocoon. This makes it for future additions to only need to be added to one place.
Additionally, add the new skia perfs links.
Closes https://github.com/flutter/flutter/issues/61677
=> Refactor cocoon links to be easier to add

app_dart/lib/src/request_handlers/refresh_github_commits.dart
This is a follow up of https://github.com/flutter/cocoon/pull/904/files, just replacing builder name with taskName. Using builder name blocks refresh-chromebot-status API.
The result is dashboard fails to get updated.
=> Save taskName rather than builderName to datastore when refreshing github commits

app_dart/lib/src/service/luci.dart, app_dart/lib/src/service/luci.g.dart
This PR fixes below two errors:
```
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      BuildBucketClient.batch (package:cocoon_service/src/service/buildbucket.dart:118:28)
<asynchronous suspension>
#2      LuciService.getBuilds (package:cocoon_service/src/service/luci.dart:150:65)
#3      LuciService.getBranchRecentTasks (package:cocoon_service/src/service/luci.dart:61:42)
<asynchronous suspension>
#4      RefreshChromebotStatus.get (package:cocoon_service/src/request_handlers/refresh_chromebot_status.dart:51:93)
#5      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:28)
<asynchronous suspension>
```
``` …
```
=> Update luci builder json keys

app_dart/lib/src/service/luci.dart, app_dart/test/service/luci_test.dart
Cocoon has been using `BranchLuciBuilder` as a map key when refreshing chromebot status. When multiple runs happen for a commit `sha`, the map is expected to update the value of existing key of `branchLuciBuilder`. But it treats the key (which shares same values) as a new key, failing to update with real LUCI statuses.
This PR fixes the above issue by overriding `hashCode` and operator `==`.
=> Enable class BranchLuciBuilder as map key by overriding hashCode & ==

app_dart/lib/src/request_handlers/push_engine_status_to_github.dart, app_dart/test/request_handlers/push_engine_status_to_github_test.dart
The calculation of the engine github status was failing when the first
task succeded and subsequent tasks failed.
Bug:
https://github.com/flutter/flutter/issues/64061
=> Fix calculation of engine github status.

app_dart/lib/src/request_handlers/update_agent_health_history.dart, app_flutter/lib/logic/agent_health_details.dart
The agent dashboard often shows false warnings about agent timeouts, as health checks and test execution has increased the time between two agent pings. This PR will reduce false warnings by increasing the timeout to 30 minutes.
Also update the backend metrics calculation to use this new threshold.
=> Change agent timeout from 10 to 30 minutes

app_dart/lib/src/model/appengine/task.dart, app_dart/test/model/task_test.dart
The `startTimestamp` field was null and caused backend exceptions, this change will ensure the chromebot function returns a valid Task model.
Fix: https://github.com/flutter/flutter/issues/64265
=> [app_dart] Ensure chromebot function returns a valid model

app_dart/lib/src/request_handlers/push_engine_status_to_github.dart, app_dart/lib/src/service/luci.dart, app_dart/test/request_handlers/push_engine_status_to_github_test.dart, app_dart/test/request_handlers/refresh_chromebot_status_test.dart
We are not sure yet what is causing the tree to status to be green when
there are failures. We are reverting the previous logic, using only
builds of master for the calculation and adding logs to identify the
cause of the problem when it happens again.
Bug:
https://github.com/flutter/flutter/issues/64061
=> Reland deleted logic to calculate tree status and add logging.

app_dart/lib/src/service/github_checks_service.dart
When a task times out a task the UI presents it as cancelled and does
not offer a re-run button. Setting cancelled as failed will show the
re-run button.
Bug:
https://github.com/flutter/flutter/issues/64465
=> Set cancelled status as failure to be able to re-run from github.

app_flutter/lib/logic/qualified_task.dart, app_flutter/lib/widgets/task_grid.dart, app_flutter/test/logic/qualified_task_test.dart, app_flutter/test/widgets/task_icon_test.dart
This is to fix: https://github.com/flutter/flutter/issues/64669
=> Update LUCI `DOWNLOAD ALL LOGS` url to correct builder page

app_dart/lib/src/request_handlers/refresh_chromebot_status.dart, app_dart/test/request_handlers/refresh_chromebot_status_test.dart
This is part of https://github.com/flutter/flutter/issues/64090
Existing Cocoon saves only DeviceLab tasks to BigQuery. This PR saves LUCI tasks to BigQuery as well when tasks finish.
=> Save LUCI task to BigQuery for flakiness analysis

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
This is to add `labelId` logging to triage issue: https://github.com/flutter/flutter/issues/65039
=> Add log info for labelId in check-for-waiting-pull-request API

app_dart/lib/src/model/luci/buildbucket.dart, app_dart/lib/src/model/luci/buildbucket.g.dart, app_dart/test/model/buildbucket_test.dart
In order to schedule devicelab builds based on capabilities, we need to add the dimensions field. Also add priority for potential future usage.
Test: I have tested end to end.
Bug: https://github.com/flutter/flutter/issues/65046
=> [app_dart] Add dimensions and priority to ScheduleBuildRequest model

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/foundation/utils.dart, app_dart/lib/src/request_handlers/get_branches.dart
This is to enable `flutter/plugins` repo in cocoon, so that LUCI try builders can be automatically triggered based on commits. `checks` validation is enabled as well.
Related issue: https://github.com/flutter/flutter/issues/56143
=> Enable plugins repo for luci tests in cocoon

app_dart/lib/src/request_handlers/reset_prod_task.dart, app_dart/test/request_handlers/reset_prod_task_test.dart
This is to fix https://github.com/flutter/flutter/issues/64754, when `builderName` is missing in the task record.
=> Using builderName in luci prod config file when retrying Luci prod builder

app_dart/test/src/request_handling/fake_http.dart, app_flutter/lib/widgets/lattice.dart, app_flutter/lib/widgets/task_overlay.dart, test_utilities/bin/dart_test_runner.sh, test_utilities/bin/flutter_test_runner.sh, test_utilities/bin/licenses.sh, test_utilities/bin/prepare_environment.sh
Tip of tree is failing due to Dart 2.10 code landing. There's a missing field in the HttpClientRequest fake.
https://github.com/flutter/flutter/issues/63269 requires updating some of app_flutter render object usage.
Additionally, I enabled on the bash scripts logging the commands run so it's easier to reproduce issues thrown in LUCI.
=> [app_dart] Fix Dart 2.10 issue and log commands run in test_utilities

app_dart/bin/server.dart
In the latest Flutter dev channel, assets can have a versioning tag appended to them (eg `/main.dart.js?v=2752228646`). This causes the cocoon frontend to fail to load.
Fixes https://github.com/flutter/flutter/issues/66041
I deployed this server with the dev channel to:
https://testchillers-dot-flutter-dashboard.appspot.com/
=> [server] Handle query params and anchor tags in url

app_dart/lib/src/request_handlers/update_task_status.dart, app_dart/test/request_handlers/update_task_status_test.dart
Flaky tasks do not block the tree, but we still invest capacity to try and deflake them.
While prototyping the MILO redesign, I noticed this could be an issue with the iOS capacity.
=> Do not automatically deflake flaky tasks

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/request_handlers/push_gold_status_to_github.dart, app_dart/test/request_handlers/push_gold_status_to_github_test.dart, app_dart/test/src/datastore/fake_cocoon_config.dart, app_flutter/lib/widgets/task_overlay.dart
This patches a bug where the flutter-gold check is stuck on old PRs.
Gold no longer caches image results >20 days old, so we need to account for that in the check.
This could also be helpful in cleaning up old PRs that aren't active. :) 
Maybe the bot should just close them if they have not been update in so long? Not sure.
I also added `v1` to the endpoints as part of the new versioning Gold is doing. :)
Fixes https://github.com/flutter/flutter/issues/65979
=> Fix flutter-gold for stale PRs

app_flutter/lib/widgets/commit_author_avatar.dart, app_flutter/test/widgets/commit_author_avatar_test.dart
Download the image bytes directly from GitHub, and push them as `Image.memory`.
- Added checks for GitHub not returning enough bytes, and it returning an image
https://github.com/flutter/flutter/issues/66084
Closes https://github.com/flutter/flutter/issues/49746
https://github.com/flutter/flutter/issues/45955
=> [build_dashboard] Show GitHub avatars on all platforms

app_flutter/lib/state/build.dart
This reverts back to the AngularDart dashboard's timing.
This was set to 10 seconds due to most users being on networks without data caps. With everyone working from home, the app is downloading ~200 KB every 10 seconds.
This should reduce the amount of repainting happening, and reduce the flickering in the GitHub avatars.
=> [build-dashboard] Revert get-status refresh rate back to original timing

app_flutter/lib/widgets/commit_author_avatar.dart, app_flutter/lib/widgets/sign_in_button.dart, app_flutter/lib/widgets/web_image.dart, app_flutter/pubspec.lock, app_flutter/pubspec.yaml, app_flutter/test/widgets/commit_author_avatar_test.dart
CachedNetworkImage is failing to show images in CanvasKit. Initially, we used it as Image.network did not offer any caching strategy but that has been added since.
This reverts the changes in https://github.com/flutter/cocoon/pull/946 and switches the `CachedNetworkImage` to `Image.network`.
This fixes the flickering in the dashboard as whenever the widgets get redrawn, they make an http request for the image.
https://github.com/flutter/flutter/issues/49725
=> [build-dashboard] Use Flutter Image.Network instead of CachedNetworkImage

app_flutter/lib/widgets/web_image.dart
Fixes a small issue where images were being initialized with their default constraints. This caused issues in the commit overlays where the image would push everything off.
=> [build-dashboard] Pass width and height to web image

cloudbuild.yaml
Now with https://github.com/flutter/cocoon/pull/951, we are building cocoon together with the flutter image. The whole process needs longer than 20 minutes, and results in timeout.
This PR extends the timeout to be 30 minuts.
=> Set timeout to 30 min for cloud build of cocoon

app_dart/bin/server.dart, app_dart/lib/cocoon_service.dart, app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/request_handlers/flush_cache.dart, app_dart/lib/src/request_handling/api_request_handler.dart, app_dart/test/request_handlers/flush_cache_test.dart
This is to make it easier to flush the cache. The current process requires getting access to a VM instance in the GCP project, getting access to redis, and then flushing.
Instead, this endpoint can be added to the release playbook to make changes propagate immediately.
Fixes https://github.com/flutter/flutter/issues/66372
Check purge happens, param passed, and cache key exists.
=> [app_dart] Add config cache flush endpoint

agent/lib/src/utils.dart
Investigation for flaky `config` call. https://github.com/flutter/flutter/issues/65413
Add `--verbose` to doctor for good measure (will let us see tethered device OS version).
=> Add verbose flags to flutter config and doctor

app_dart/lib/src/request_handlers/refresh_chromebot_status.dart
There is a bug in existing `refresh-chromebot-status` API: the logic compares with datastore status with the oldest LUCI build's status. This will cause confusion when re-run is triggered.
This PR updates the logic to use latest build's status to do comparison and then update the datastore and dashboard.
=> Fix status update condition in refresh-chromebot-status API

app/build.yaml
Due to recent upgrading `build_web_compilers` to `2.10.0` from `2.7.2`, flutter benchmark dashboard fails to render.
This pr adds option `compiler: dart2js` to make it work. It is validated to work locally.
Related issue: https://github.com/flutter/flutter/issues/67457
=> Add option compiler dart2js to `app` build yaml to recover flutter benchmark dashboard

cloudbuild.yaml, flutter_image_build.yaml
Existing cloud build yaml file includes both flutter image build and cocoon build, which will be auto built daily on workdays.
Potential issues:
- flutter image build is based on `dev` channel, and it is a waste of resources to keep building the same version between two `dev` releases.
- `dev` release happens approximately on a weekly basis, if there is a bug (like: https://github.com/flutter/flutter/issues/67319) in upstream, but gets fixed in `master`, it will take a week before the fix shows up in `dev`.
This PR separates the flutter image build out of cocoon to provide flexibility to build new flutter images, and save resources as well.
Will create a separate trigger based on this new yaml file to build flutter image.
Related issue: https://github.com/flutter/flutter/issues/67457
=> Separate flutter image build configs from existing cocoon build yaml file

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
Temporarily disable the GitHub auto mergebot while the tree is closed from Dart null-safety rolls.
Restoring the bot is tracked in https://github.com/flutter/flutter/issues/68632
=> Temporarily disable mergebot while the tree is closed.

app_flutter/lib/widgets/agent_tile.dart
Make the agent name selectable so it can be copied:
Also raw health details so the IP can be easily copied.
See also #662
=> Selectable raw health details and agent name

test_utilities/bin/dart_test_runner.sh, test_utilities/bin/flutter_test_runner.bat, test_utilities/bin/flutter_test_runner.sh
This will make it easier to view logs from infra on cocoon. For example, https://github.com/flutter/flutter/issues/67681 has logs that get collated into one line which ends up being hard to parse.
=> Add verbose logging to test utilities

app_dart/lib/src/request_handlers/refresh_github_commits.dart
Cocoon refreshes github commits for each branch defined in [`branches.txt`](https://github.com/flutter/cocoon/blob/master/app_dart/dev/branches.txt). This is assuming that branch exists in `flutter/flutter`. 
However when a branch is not defined in `flutter/flutter`, but added in `branches.txt`, cocoon backend API will fail with 
```
GitHub Error: Requested Resource was Not Found
```
This PR is to fix the issue.
Related issue: https://github.com/flutter/flutter/issues/69039
=> Add catch exception logic for missing branch when refreshing github commits

app_flutter/lib/service/appengine_cocoon.dart, app_flutter/lib/service/cocoon.dart, app_flutter/lib/service/dev_cocoon.dart, app_flutter/lib/state/agent.dart, app_flutter/lib/widgets/agent_tile.dart, app_flutter/test/service/appengine_cocoon_test.dart, app_flutter/test/state/agent_test.dart, app_flutter/test/utils/fake_agent_state.dart, app_flutter/test/widgets/agent_tile_test.dart
This tends to be accidentally clicked by users. With the migration to LUCI, we'll remove this to remove a source of issues with the cocoon agents.
Most of this is removing authorize agent code. There is one change where I needed to update the snackbar duration to be the correct variable.
=> [app_flutter] Remove authorized agent UI

app_dart/lib/src/request_handling/static_file_handler.dart, app_dart/test/request_handling/static_file_handler_test.dart
When viewing licenses, there's a 500 error on the endpoint as the `package:mime` functionality fails due to there being no explicit file extension.
Added a regression test for this functionality
https://testchillers-dot-flutter-dashboard.appspot.com/#/
Click the side bar > About Flutter Dashboard > View Licenses
Licenses should show now
In the prod version this endpoint 500s
=> [app_dart] Fix static files with no extension 500ing

app_dart/lib/src/request_handlers/update_task_status.dart, app_dart/test/request_handlers/update_task_status_test.dart
Migrating the DeviceLab to LUCI requires updating Cocoon to work with what LUCI knows. LUCI runs will not know the task key they are running. Instead, they know the git sha, git branch, and task name. This updates the request handler to process those to find corresponding task.
Added a unit test for this use case
=> [app_dart] Task statuses can be updated without task keys

app_dart/lib/src/service/luci_build_service.dart
Sometimes the buildbucket requests are raising exceptions and github
status stays on pending forever.
Bug: https://github.com/flutter/flutter/issues/69589
=> Add retries to buildbucket tries.

.cirrus.yml
Currently, Cirrus will auto-detect the Dockerfile in this repo and build it at every commit. This built docker image is not used. This change will explicitly build the docker image only on dockerfile diffs.
=> add cirrus config to build docker image on dockerfile diffs

app_dart/bin/server.dart, app_dart/lib/cocoon_service.dart, app_dart/lib/src/request_handling/authentication.dart, app_dart/lib/src/request_handling/swarming_authentication.dart, app_dart/test/request_handling/swarming_authentication_test.dart, app_dart/test/src/request_handling/fake_authentication.dart
Add a `SwarmingAuthenticationProvider` that is a child of the existing `AuthenticationProvider`. This provider only authenticates for Cocoon agents and LUCI swarming bot service accounts.
This ensures a given `RequestHandler` can only be updated through these methods (enforcing an ACL). For now, I added this to the `update-task-status`, but we should do a greater security review to audit endpoints that should only be used by automated systems.
Added LUCI swarming authentication which reuses the existing Google authentication.
- Added tests that ensure this child class does not grant the same permissions as the parent
- Added tests for LUCI auth being passed to id token
=> [app_dart] Add swarming authentication provider

app_flutter/lib/widgets/agent_tile.dart, app_flutter/lib/widgets/error_brook_watcher.dart, app_flutter/lib/widgets/task_grid.dart, app_flutter/pubspec.lock, app_flutter/pubspec.yaml
Original:
```
info • 'showSnackBar' is deprecated and shouldn't be used. Use ScaffoldMessenger.showSnackBar. This feature was deprecated after v1.23.0-14.0.pre. • lib/widgets/agent_tile.dart:121:26 • deprecated_member_use
info • 'showSnackBar' is deprecated and shouldn't be used. Use ScaffoldMessenger.showSnackBar. This feature was deprecated after v1.23.0-14.0.pre. • lib/widgets/error_brook_watcher.dart:63:26 • deprecated_member_use
info • 'showSnackBar' is deprecated and shouldn't be used. Use ScaffoldMessenger.showSnackBar. This feature was deprecated after v1.23.0-14.0.pre. • lib/widgets/task_grid.dart:322:59 • deprecated_member_use
info • Sort pub dependencies • pubspec.yaml:29:3 • sort_pub_dependencies
warning • Publishable packages can't have path dependencies • pubspec.yaml:32:5 • …
```
=> [app_flutter] Migrate Flutter deprecations and fix new analyze lints

app_dart/lib/src/foundation/github_checks_util.dart, app_dart/lib/src/service/github_checks_service.dart, app_dart/lib/src/service/luci_build_service.dart
This is to prevent errors when a check run is not created because
github rejects the token.
Bug:
https://github.com/flutter/flutter/issues/69248
=> Add retries with backoff to the github createCheckRun.

app_dart/lib/src/foundation/github_checks_util.dart, app_dart/lib/src/service/github_checks_service.dart
This is because github apis frequently reject the access token and we
need to generate a new one and retry.
Bug:
https://github.com/flutter/flutter/issues/69248
=> Add retries with backoff to the call of updateCheckRun.

app_dart/lib/src/service/luci_build_service.dart
This PR adds the new pubsub topic to use when cocoon reschedules a prod build. This is part of the solution for https://github.com/flutter/flutter/issues/69621. We will need to also specify the notification to happen when the task is initially scheduled by luci.
=> Specify pubsub topic use when rescheduling prod builds.

app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/request_handlers/github_webhook_test.dart
This label has been deleted from the repo, now that draft functionality is more mature.
@Piinks @goderbauer
=> Remove obsolete labeling

app_dart/dev/deploy.dart
Add a `--skip-build` flag that will reuse the existing build files in `app_dart` (will not try to build the Angular or Flutter projects which can add a few minutes). This is useful for backend only changes.
Add `--quiet` to gcloud deploy so user input is not required.
=> [app_dart] Speed up dev deploy script

app_flutter/.gitignore
With the support for MacOS, Linux, and Windows desktops there's a few files that stay in staging due to Cocoon not having an updated gitignore with these platforms.
=> [app_flutter] Update gitignore with latest from flutter/flutter

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/request_handling/authentication.dart, app_dart/lib/src/request_handling/swarming_authentication.dart, app_dart/test/request_handling/swarming_authentication_test.dart, app_dart/test/src/datastore/fake_cocoon_config.dart, app_dart/test/src/request_handling/fake_authentication.dart
Switches `SwarmingAuthenticationProvider` id token authentication to access token.
Make some members in `AuthenticationProvider` public to remove code duplication in `SwarmingAuthenticationProvider`.
Switched tests from id token to access token equivalents.
Check that only the LUCI prod account is authenticated.
=> [app_dart] Add access token authentication for swarming tasks

app_dart/lib/src/request_handling/swarming_authentication.dart
I'm having a hard time to debugging what's going wrong in the devicelab tests trying to upload results on LUCI. Adding logs to see what's happening. Right now the test runner is returning an empty response body, so I want to double check that we even get to authenticating the service account code path.
=> [app_dart] Add logging in swarming auth

app_dart/lib/src/request_handlers/update_task_status.dart
This should match what the DeviceLab test runner uses (or vice versa). [Source](https://cs.opensource.google/flutter/flutter/+/master:dev/devicelab/lib/framework/cocoon.dart;l=85-90)
I think the DeviceLab test runner is more specific so I'll update Cocoon to match.
https://chromium-swarm.appspot.com/task?id=4fd36cbb6d373b10 - Failed on this
This requires a recipe run to validate.
=> [app_dart] Fix update-task-status branch param name

app_dart/lib/src/request_handlers/update_task_status.dart, app_dart/test/src/datastore/fake_datastore.dart
Datastore in production differs slightly from our test service. It cannot have a space at the end of the filter, otherwise an error is thrown.
https://logs.chromium.org/logs/flutter/led/chillers_google.com/226e07e7f862d86628e3b6b73e7b54061ff3caea821ec3915b83c298f8d60937/+/steps/run_web_benchmarks_canvaskit/0/stdout
500 on devicelab luci task due to this filter.
Added assert check to test datastore service to prevent future issues like this.
=> [app_dart] Fix update-task-status query filter with extra space

app_dart/lib/src/request_handlers/refresh_github_commits.dart, app_dart/test/request_handlers/refresh_github_commits_test.dart
This is a follow up of https://github.com/flutter/cocoon/pull/997
=> Stop adding cirrus task to datastore when refreshing new github commits

app_dart/lib/src/request_handlers/update_task_status.dart, app_dart/test/request_handlers/update_task_status_test.dart
Give more informative messages when errors occur.
Only update chromebot tasks when given the LUCI information. This is needed for the DeviceLab migration to LUCI as there will be some period of time where a chromebot and devicelab task both have the same name.
- Added check for Cocoon task exists but not a LUCI one
- Cocoon and LUCI task
- There's an existing one for only a LUCI task
=> [app_dart] update-task-status only updates chromebot tasks when given LUCI information

app_dart/lib/src/request_handlers/update_task_status.dart, app_dart/test/request_handlers/update_task_status_test.dart
LUCI tasks in Cocoon use the builder name for unique look up. This matches that logic.
In the instance of running `web_benchmarks_html` devicelab test, Cocoon stored it as `linux_web_benchmarks_html`. This would cause a 500 issue when retrieving the task to update. Instead, if we search for the task by the builder name, we can uniquely identify it.
Updated tests to use builder name instead of task name.
=> [app_dart] update-task-status uses builder name instead of task name

app_dart/lib/src/model/appengine/task.dart, app_dart/lib/src/request_handlers/refresh_github_commits.dart, app_dart/test/model/task_test.dart
Use `LuciBuilder` to populate the chromebot tasks. The information in `prod_builders.json` is enough to populate some extra values on creation, mainly `builderName`.
Fixes https://github.com/flutter/flutter/issues/69839 - `builderName` was not available on new chromebot tasks
https://github.com/flutter/flutter/issues/66191 - `builderName` is not initially populated on LUCI tasks, and can cause race condition failures depending on when datastore refreshed from luci
Updated chromebot task to expect correct values.
=> [app_dart] Use LuciBuilder when creating chromebot tasks

agent/lib/src/commands/ci.dart, agent/pubspec.lock, app/pubspec.lock, app_dart/pubspec.lock, app_dart/pubspec.yaml, app_flutter/pubspec.lock, repo_dashboard/pubspec.lock, test_utilities/bin/flutter_test_runner.bat, test_utilities/bin/flutter_test_runner.sh, test_utilities/bin/prepare_environment.sh, tests.yaml
This moves Cocoon to test on master to allow us to add the project back to customer_testing to prevent breakages. Deploys will still be based on the beta channel for stability.
With https://github.com/flutter/cocoon/pull/1005, we're able to `pub upgrade` the various repos to be compatible with the master channel.
https://github.com/flutter/flutter/issues/65045
=> Switch Cocoon to test on Flutter master

app_flutter/test/utils/golden.dart
Adding flutter/cocoon back to customer_tests fails because of the windows tests. We should use the path library instead of hardcoding how the path is generated.
https://github.com/flutter/flutter/issues/65045
=> [app_flutter] Fix golden tests on windows

app_dart/lib/src/model/appengine/task.dart, app_dart/lib/src/request_handlers/push_engine_status_to_github.dart, app_dart/lib/src/request_handlers/refresh_chromebot_status.dart, app_dart/lib/src/service/build_status_provider.dart, app_dart/lib/src/service/luci.dart, app_dart/test/service/build_status_provider_test.dart, app_dart/test/service/luci_test.dart, app_flutter/lib/widgets/task_box.dart
LUCI publishes this status, and would be helpful to differentiate infra failures on the dashboard versus test failures. This also allows us to reduce tree closures due to infra causes
This PR takes LUCI builds that were infra failures and keeps the status. Previously, they were marked as failures.
https://github.com/flutter/flutter/issues/70331
Added table test for the app_dart changes
Flutter app already has a similar table test that uses the map to validate expectations
=> Preserve LUCI infra failures in Cocoon

app_dart/lib/src/datastore/cocoon_config.dart
[GitHub dependabot](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically) was turned on in flutter/flutter with https://github.com/flutter/flutter/pull/71602.  PRs will look something like this: https://github.com/flutter/flutter/pull/62379
Currently it's only turned on to update the LUCI docker image macOS Gemfile.
Add the bot to the list of autoroller accounts so it will auto-merge when the tests pass.  Its name really includes those brackets:
https://api.github.com/users/dependabot%5Bbot%5D
=> Add dependabot to roller accounts list

app_flutter/lib/widgets/task_grid.dart
https://github.com/flutter/cocoon/pull/1014 forgot to weight this new status, so they are given a weight of 0. This will show them after failures.
=> [app_flutter] Sort infra failures in grid after failures

app_dart/lib/src/request_handlers/update_task_status.dart
Add more logging to LUCI devicelab upload metrics calls to better understand why it is failing to find the Datastore task.
https://github.com/flutter/flutter/issues/71749
=> [app_dart] Add more logging for upload metrics

dev/provision_salt.sh
This is required for the installation of salt minion packages.
=> Update provisioning script to add debian backports.

device_doctor/.gitignore, device_doctor/bin/main.dart, device_doctor/pubspec.lock, device_doctor/tool/buil.sh, device_doctor/tool/ensure_file, device_doctor/tool/ensure_file_windows, tests.yaml
This creates the build script to build device_doctor. Currently it supports linux, mac, and windows.
Tests will be added from flutter/infra, and recipe side once this is in.
Related issue: https://github.com/flutter/flutter/issues/66193
=> Add build script for device_doctor

app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/request_handlers/github_webhook_test.dart
The former release process advised that branches on a user's mirror should be named the same as the release branch they were going to merge into. The new process advises prefixing their user branch with `cherrypicks-`. Thus, make this test in the github bot more lenient, just requiring both base ref and head ref to match the regex, and not requiring them to be exactly the same.
=> make github bot wrong merge base test more lenient

app_dart/lib/src/request_handlers/update_task_status.dart, app_dart/test/request_handlers/update_task_status_test.dart
This is a brute force solution to unblocking the Devicelab migration to LUCI. Instead of using key lookup, it looks at the most recent commits to find the corresponding parent commit.
https://github.com/flutter/flutter/issues/71749
I generalized some values in the test into variables.
=> [app_dart] Scan for parent commit instead of using key lookup

app_dart/lib/src/service/luci_build_service.dart
Reverts flutter/cocoon#1027
This breaks in prod. flutter/flutter#72007
We need to switch how the recipe pulls the branch (use gitiles instead of the property)
=> Revert "[app_dart] Pass branch when rescheduling prod builds"

device_doctor/tool/build.bat, device_doctor/tool/build.sh
Existing build.sh works for all platforms, but LUCI bot is more comfortable with a `.bat` file for windows.
This PR creates a corresponding `.bat` build file for windows, parallel to the `build.sh` for linux and mac.
=> Create bat script for device_doctor windows build

agent/test/src/adb_test.dart, device_doctor/bin/main.dart, device_doctor/lib/src/android_device.dart, device_doctor/lib/src/device.dart, device_doctor/lib/src/ios_device.dart, device_doctor/pubspec.lock, device_doctor/test/src/android_device_test.dart
As devicelab tasks are being migrated to LUCI, we need to support mac/ios, mac/android, linux/android, and windows/android.
However chromium bot config is not supporting `mac/android` device dimensions query. This PR adds functionality to support that, so that chromium bot can call device_doctor to obtain the device properties and further help pick up builders correctly.
Related issue: https://github.com/flutter/flutter/issues/72760, https://github.com/flutter/flutter/issues/66193, https://github.com/flutter/flutter/issues/72835
=> Add support to device_doctor for device property check

dev/try_builders.json
Pre-submit device_doctor try builders have been configured in https://github.com/flutter/infra/pull/317
This PR follows up to enable them in cocoon repo.
Related issue: https://github.com/flutter/flutter/issues/72835
=> Enable device_doctor try builders for cocoon pre-submit

device_doctor/tool/build.bat, device_doctor/tool/build.sh
This PR copy LICENSE to the build package tool.
Related issue: https://github.com/flutter/flutter/issues/72835
=> Copy device_doctor license to build

device_doctor/bin/main.dart
Device doctor tool is using action `properties` in the logic, but the argument is still based on `propertycheck`. This is to fix that.
=> Update device doctor tool action to `properties`

device_doctor/lib/src/android_device.dart, device_doctor/lib/src/health.dart, device_doctor/pubspec.lock, device_doctor/test/src/ios_device_test.dart
`healthcheck` was conducted but it failed to analyze results and communicate with console for android device. This PR adds it.
This PR also removes unnecessary `throw`.
=> Device_doctor: add healthcheck to android device

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart, app_dart/test/src/datastore/fake_cocoon_config.dart
[GitHub dependabot](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically) was added to the [autorollers list,](https://github.com/flutter/cocoon/pull/1017) but [fluttergithubbot removed the `waiting for tree to go green` label](https://github.com/flutter/flutter/pull/73689#issuecomment-757678283).
Speculating, this may be a problem with the brackets in `dependabot[bot]` username.  Check autoroller IDs instead of usernames.
Fixes https://github.com/flutter/flutter/issues/73723
=> Check autoroller author by ID instead of name

app_dart/bin/server.dart, app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/model/luci/buildbucket.dart, app_dart/lib/src/model/luci/buildbucket.g.dart, app_dart/lib/src/request_handlers/refresh_chromebot_status.dart, app_dart/lib/src/service/luci.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/pubspec.lock, app_dart/test/request_handlers/refresh_chromebot_status_test.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/src/datastore/fake_cocoon_config.dart
This is a workaround for issue https://github.com/flutter/flutter/issues/68322.
An alternative is to filter `-9 recode` via `Build` property `summaryMarkdown`. However `-9 recode` does not show up in parent `summaryMarkdown` for builders with shards, but exists in sub-builders `summaryMarkdown`. This makes it difficult to correctly filter corresponding builders for rerun.
Since most existing `infra failure` Mac builders are related to `-9 recode` issue, and it doesn't hurt to rerun the small portion of other `infra failure` builders, here we are rerunning all Mac builders which fail with `infra failures`. 
This PR focuses only on framework repo. We need to do the same for engine in a separate PR.
=> Auto rerun framework Mac builders with infra failure

app_dart/lib/src/request_handlers/refresh_chromebot_status.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/test/request_handlers/refresh_chromebot_status_test.dart, app_dart/test/service/luci_build_service_test.dart
This PR makes two changes:
1. `task.attempts` includes the first run, so here we minus 1 when making rerun trials check.
2. Add `infra failure` check for rerun. There is a corner case: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_tests/1389/overview, which has same `summaryMarkdown` as the one with shards -9.
=> Follow up of luci auto rerurn

agent/lib/src/utils.dart
Investigation for flaky `flutter config` call. Allow the command to fail to see if we actually get some real logging.  Not sure why there's no [stdout logging](https://github.com/flutter/cocoon/pull/659) for when this fails.  
https://github.com/flutter/flutter/issues/65413
=> Allow 'flutter config --no-analytics' to fail

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/request_handlers/github_webhook_test.dart, app_dart/test/src/datastore/fake_cocoon_config.dart
We were initially skipping try jobs for PRs explicitly marked "unmergeable" by github, but this logic was lost in some refactor. This again skips unmergeable PRs, with an added comment that the author needs to resolve the merge conflict.
=> skip try jobs for unmergeable PRs

app_dart/test/src/datastore/fake_datastore.dart, device_doctor/lib/src/android_device.dart, device_doctor/lib/src/health.dart, device_doctor/lib/src/ios_device.dart, device_doctor/lib/src/utils.dart, device_doctor/test/src/health_test.dart
This is to write query results to a local file, avoiding issues from unexpected stdout/stderr messages.
Part of https://github.com/flutter/flutter/issues/74363
=> Write healthcheck and properties to file instead of using stdout/stderr

device_doctor/lib/src/android_device.dart, device_doctor/lib/src/health.dart, device_doctor/lib/src/ios_device.dart, device_doctor/lib/src/utils.dart, device_doctor/test/src/health_test.dart
This is a follow up of https://github.com/flutter/cocoon/pull/1064
=> Extend device_doctor generated healthcheck results to include both success and failure

app_dart/Dockerfile
This is to fix: https://github.com/flutter/flutter/issues/74430 to unblock Cocoon auto-build.
=> Use Dart dev instead of stable version for cocoon deployment

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart
This is a followup of https://github.com/flutter/cocoon/pull/1054.
The correct summaryMarkdown is `recipe infra failure: Infra Failure: Step('display builds.build(s) failed') (retcode: 1)`, like in build: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20framework_tests/1492/overview
This PR updates the summaryMarkdown.
=> Correct summaryMarkdown for framework LUCI -9 rerun

app_dart/lib/src/service/luci_build_service.dart
Manual retries are usually waiting for ~30 mins as they are added to the
end of the queue of tasks for the current commit. We are changing the
priorities to ensure retried tasks are not waiting for too long in the
queue.
Bug: https://github.com/flutter/flutter/issues/74692
=> Run manual retries with higher priority to open the tree faster.

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/request_handlers/update_task_status.dart, app_dart/pubspec.lock, app_dart/pubspec.yaml, app_dart/test/request_handlers/update_task_status_test.dart, app_dart/test/src/datastore/fake_cocoon_config.dart
This needs https://github.com/flutter/cocoon/pull/1061 and the `metrics_center` change in `pubspec.yaml` from https://github.com/flutter/cocoon/pull/1060.
Once this PR is successfully deployed, we should be able to cut the dependency on Tong's desktop.
=> Let Cocoon write into metrics center

device_doctor/bin/main.dart, device_doctor/lib/src/android_device.dart, device_doctor/lib/src/device.dart, device_doctor/lib/src/ios_device.dart, device_doctor/lib/src/utils.dart, device_doctor/test/src/android_device_test.dart, device_doctor/test/src/fake_ios_device.dart, device_doctor/test/src/ios_device_test.dart
Device doctor is writing results to a hardcoded output file. 
This is to inject the output path as an argument. If not specified, it will use the current dir as the output path.
Related: https://github.com/flutter/flutter/issues/74363
=> Add ouput path as an argument instead of hardcoding

repo_dashboard/lib/services/github_service.dart
This error handler must accept an Object, or it will crash at runtime.
It looks like the Error type was not necessary; the error object is only being Stringified.
The Dart analyzer at HEAD starting today reports such functions with a non-Object parameter, as part of https://github.com/dart-lang/sdk/issues/35825.
=> Correct type in Future.catchError error handler.

app_dart/bin/server.dart, app_dart/lib/src/request_handlers/push_engine_status_to_github.dart, app_dart/lib/src/service/luci.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/test/request_handlers/push_engine_status_to_github_test.dart, app_dart/test/service/luci_build_service_test.dart, repo_dashboard/lib/services/github_service.dart
This is a workaround for issue flutter/flutter#68322: auto rerun Mac builders failing with -9 retcode.
This is for post-submit builders only.
=> Auto rerun engine Mac builders with infra failure

app_flutter/lib/widgets/lattice.dart, app_flutter/lib/widgets/task_grid.dart
I found it difficult to use the trackpad to traverse the build page. This PR adds always visible scrollbars for both vertical and horizontal scrolling.
=> Add always visible scrollbars to build page

app_dart/pubspec.yaml
So we'll no longer write into the legacy datastore.
=> Upgrade metrics_center

repo_dashboard/pubspec.yaml
`localstorage` depends on `path_provider`'s stable version, but due to breaking changes in FFI the stable version `path_provider_windows` (and thus `path_provider`) no longer work with the latest version of Dart. This overrides that transitive dependency with one that is compatible with with Dart ToT.
=> Override path_provider

cloud_build/app_flutter_build.sh, cloud_build/repo_dash_build.sh
Switch from `--dart-define` to `--web-renderer`. The latter is the officially supported option. Also added `--release` for explicitness.
=> switch from --dart-define to --web-renderer

repo_dashboard/pubspec.yaml
Reverts flutter/cocoon#1086
Not needed after the revert of the Dart SDK breaking change: https://dart-review.googlesource.com/c/sdk/+/185500
=> Revert "Override path_provider"

device_doctor/lib/src/android_device.dart, device_doctor/lib/src/utils.dart, device_doctor/pubspec.lock, device_doctor/test/src/android_device_test.dart
This adds adb power service health check for android device: make sure the power service is available before reserving/running tests.
Related: https://github.com/flutter/flutter/issues/76130
=> Add adb power service check to for Android device health check

app_dart/lib/src/request_handlers/refresh_github_commits.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/request_handlers/refresh_github_commits_test.dart, app_dart/test/service/scheduler_test.dart, licenses/check_licenses.dart
See the last commit for the diff between https://github.com/flutter/cocoon/pull/1087
The issue appears to have been the age was backwards in the scheduler. It was only looking to add older commits that did not exist in Datastore. Instead, it should add newer commits that do not exist in Datastore. Simply, larger timestamp commits should get added to datastore.
* Trigger adding tasks from github webhooks
* Remove the cron method
* Move retry logic into this service
=> [app_dart] Reland scheduler service

device_doctor/lib/src/android_device.dart, device_doctor/lib/src/utils.dart, device_doctor/pubspec.lock, device_doctor/test/src/android_device_test.dart
This add Android device developer mode health check: make sure it is on before reserving tests.
Related: https://github.com/flutter/flutter/issues/76165
=> Add developer mode health check for android device

device_doctor/lib/src/android_device.dart, device_doctor/lib/src/ios_device.dart, device_doctor/lib/src/mac.dart, device_doctor/lib/src/utils.dart, device_doctor/test/src/ios_device_test.dart, device_doctor/test/src/mac_test.dart
This adds health check for Mac bot swarming user auto login.
Though the check is on host level, we are adding it to device doctor tool to make it possible to quarantine bots when failing.
This is based on assumption that `swarming` user has been setup auto login for all Mac bots running devicelab tasks.
Related issue: https://github.com/flutter/flutter/issues/76091
=> Add swarming user auto login check for Mac bots

device_doctor/lib/src/android_device.dart
This is a post cleanup step following https://github.com/flutter/cocoon/pull/1064, which starts writing results to a local file.
Related issue: https://github.com/flutter/flutter/issues/74363
=> Stop device_doctor writing results to stdout

device_doctor/lib/src/ios_device.dart
This is to remove closeIosDialog functionality from device doctor cleanup for ios device.
Some context:
- close iOS dialog has been implemented in recipes
- if it fails to close IOS dialog from recipe, it will fail test rather than prevent picking up test. So we need to pre health check if iOS dialog is able to be closed before reserving a test to run. Namely quarantine the bot if the health check fails.
- Running closeIosDialog needs xcode available, but xcode is not ready when running device doctor health check
- device doctor clean up needs to be implemented from bot_config side to unblock issues (https://github.com/flutter/flutter/issues/76796#issuecomment-786425051).
Therefore here we are removing the closeIosDialog function from cleanup step to unblock the above issue.
A follow up …
=> Remove closeIosDialog from cleanup for ios device

device_doctor/lib/src/ios_device.dart, device_doctor/test/src/ios_device_test.dart
Uninstall applications when task fails for iOS device tasks.
This is to prevent application installation failure caused by using different signing certificate from previous installed application.
Related issue: https://github.com/flutter/flutter/issues/76896
=> Add uninstall appllcations to iOS device recovery

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
This is to avoid the githubbot from removing the waiting for tree to go
green label.
Bug: https://github.com/flutter/flutter/issues/77401
=> Add submit-queue check to the list of not related checks.

app_dart/pubspec.yaml
This is required for other Dart packages to pull Cocoon as a remote dependency. Which comes up when deploying a microservice dependent on it.
=> [app_dart] Add description to pubspec.yaml

app_flutter/test/utils/golden.dart
Needs https://github.com/flutter/flutter/pull/77825 to land first in flutter/flutter
This adds a custom file comparator that will allow for a tolerance to be set for golden file testing
Related issues:
https://github.com/flutter/flutter/issues/76337
https://github.com/flutter/flutter/issues/71437
=> Add custom golden comparator with diff tolerance

app_dart/lib/src/request_handlers/push_build_status_to_github.dart
Fix it so this message is shown on failure.
Skipped as there was no existing test for this, and it was a quick fix.
=> [app_dart] Show flutter-build description on failures

app_dart/lib/src/foundation/utils.dart, app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/lib/src/request_handlers/refresh_github_commits.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart
- Scheduler needs to pass httpClientProvider instead of httpClient due to timeout issues where the client is closed
- Use common remote file utility for devicelab manifest
- Update remote file utility to catch all possible places where an error can occur
- Set timeout of get request on the remote file utility
Fixes https://github.com/flutter/flutter/issues/78479
=> [app_dart] Switch scheduler to httpClientProvider + cleanup

app_dart/lib/src/foundation/github_checks_util.dart, app_dart/lib/src/request_handlers/luci_status.dart, app_dart/lib/src/service/github_checks_service.dart
This is to prevent errors when calling `/api/luci-status-handler` due to `GitHub Error` and `SocketException`.
Related issues: https://github.com/flutter/flutter/issues/78555, https://github.com/flutter/flutter/issues/78561
=> Add retries to the call of getCheckRun and updateCheckStatus

app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart
Forked from https://github.com/flutter/cocoon/pull/1111 into a smaller PR. Commits scheduled via webhook are truncating the repo.
`Commit.repo` expects `$org/$repo` as the format. This is causing failures to load commit diffs from the build dashboard.
=> [app_dart] Fix webhook scheduled commit repository field

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart
Only `flutter/flutter` has prod tasks that are supported by `Scheduler`. The GitHub webhooks are trying to schedule commits against unsupported repos (like `flutter/engine`) which is causing an increase in failures.
This doesn't affect presubmit tasks. When the scheduler is more fleshed out, this will include both types of builds.
=> [app_dart] Configurable supported repos for scheduler

app_dart/lib/src/datastore/cocoon_config.dart, app_dart/lib/src/foundation/utils.dart, app_dart/lib/src/model/appengine/commit.dart, app_dart/lib/src/service/luci.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/datastore/cocoon_config_test.dart, app_dart/test/src/datastore/fake_cocoon_config.dart
This updates `config.luciBuilders` to aggregate all the `LuciBuilders` from the `flutterBranches`. This supports showing luci builders from release branches in the build dashboard. Previously it only grabbed for master / tip of tree.
The release branches still require updating the builders.json to include the release channel name (e.g. `Linux Stable`).
https://github.com/flutter/flutter/issues/72466
=> [app_dart] luciBuilders aggregates from all branches

app_dart/lib/src/foundation/github_checks_util.dart
This is to enable presubmit LUCI `createCheckRun` retry on `SocketException`. The retry logic has been there when hitting Github Error, and this is appending the SocketException as well.
Related issue: https://github.com/flutter/flutter/issues/74611
=> [cocoon] Add createCheckRun retry on SocketException

app_dart/README.md, app_dart/bin/server.dart
Often we don't need to do an IO operation as these files rarely change (at most, once a weekday). Additionally, changes to the Flutter apps average once a week. This should speed up the overall load time of the dashboards.
=> [app_dart] Cache static files for 30 minutes

app_flutter/lib/main.dart, app_flutter/web/index.html
The favicon broke when we removed the Angular Dart dashboard as the Flutter app relied on the Angular Dart dashboard to link the favicon. Add the favicon links, similar to how the repository dashboard already does it.
I ran this locally to verify the links are working.
=> [app_flutter] Link favicon

app_dart/cron.yaml
Triaging the flutter-dashboard GCP logs shows all commits are being scheduled from the webhook trigger instead of this cron job. Reducing frequency to save some GitHub API quota.
=> Reduce cron for /api/refresh-github-commits

app_dart/README.md, app_dart/bin/server.dart
Reverts flutter/cocoon#1117
The MIME type isn't being saved, so everything is sent as plaintext. This is causing the dashboard to be unusable.
=> Revert "[app_dart] Cache static files for 30 minutes"

app_dart/lib/src/datastore/config.dart, app_dart/test/datastore/config_test.dart
1. refresh-chromebot-statuses was setting a null branch (https://github.com/flutter/flutter/issues/78889)
- I missed a null check
2. try builders pulled from HEAD of master instead of the PR sha (https://github.com/flutter/flutter/pull/78623#discussion_r599842246)
- My assumption was these configs came from HEAD and not the PR
Added a debug statement to make it easier to know what information this is getting for future changes.
=> [app_dart] Pull *_builders from commit sha on PRs prs use commitSha for *_builders configs

app_dart/bin/validate_scheduler_config.dart, app_dart/lib/cocoon_service.dart, app_dart/lib/src/model/proto/internal/scheduler.pb.dart, app_dart/lib/src/model/proto/internal/scheduler.pbjson.dart, app_dart/lib/src/model/proto/internal/scheduler.proto, app_dart/lib/src/model/proto/protos.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart, licenses/check_licenses.dart
Part of go/flutter-build-test-infra
This change is a no-op to Cocoon, and only adds models necessary for future changes.
* Create `SchedulerConfig` and `Target` protos
* Validate scheduler config from a yaml is valid
* Ensure all dependencies exist
* No duplicate targets
* No cycles (the config should only create a tree)
* Add `bin/validate_scheduler_config.dart` for running tests against external configs
=> [scheduler] Add SchedulerConfig and validation tests

app_flutter/pubspec.yaml, app_flutter/test/logic/qualified_task_test.dart, app_flutter/test/logic/task_grid_filter_test.dart, app_flutter/test/service/appengine_cocoon_test.dart, app_flutter/test/service/google_authentication_test.dart, repo_dashboard/pubspec.yaml, repo_dashboard/test/build_status_service_test.dart, repo_dashboard/test/build_status_test.dart, repo_dashboard/test/skia_autoroll_service_test.dart, repo_dashboard/test/status_page_status_service_test.dart
This makes it easier to version solve since flutter_test has fewer dependencies.
Blocking https://github.com/flutter/flutter/issues/77856
Should be safe as long as `flutter test` is being used to run unit tests, even if they are not flutter tests
=> use flutter_test instead of package:test

dev/provision_salt.sh
This is to avoid having to reboot the machine to pick up the changes to the path.
=> Update salt provisioning script.

app_dart/lib/src/service/luci.dart
When buildbucket API call returns empty builds, it fails `/api/refresh-chromebot-status` which refresh LUCI builds statuses to flutter dashboard.
This is to exclude the empty case.
https://github.com/flutter/flutter/issues/79380
=> [cocoon] Exclude null builds when calling buildbucket API

app_dart/cron.yaml
Disable the cron job as it is causing issues with the webhook scheduler.
For the next week I'll look at if any commits are being dropped via https://plx.corp.google.com/scripts2/script_60._49462f_0000_2e53_920f_089e0832f92c
This endpoint can still be manually queried if there are outages
https://github.com/flutter/flutter/issues/79408
=> [app_dart] Remove refresh github commits cron

app_dart/lib/src/model/proto/internal/scheduler.pb.dart, app_dart/lib/src/model/proto/internal/scheduler.pbjson.dart, app_dart/lib/src/model/proto/internal/scheduler.proto, app_dart/test/service/scheduler_test.dart
This config isn't being used yet. It's non-trivial to spawn a swarming task to run a recipe in Flutter LUCI infrastructure.
Instead, we'll start by triggering the existing builders from Cocoon.
=> [scheduler] Rename recipe field to builder

app_dart/lib/src/datastore/config.dart, app_dart/lib/src/request_handlers/push_engine_status_to_github.dart
Quick fix to unify the framework and engine tree failure status messages (they are identical)
=> [app_dart] Update engine build status to use config value

app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/request_handlers/github_webhook_test.dart
Applies a similar refactoring to the framework auto-labelling for files
as was done in #1140 for the engine. Also adds more test coverage for
framework labelling.
This also fixes a bug where PRs that included files with the word
'accessibility' in their path were missed due to a typo in the path
matching.
Moves the labelling tests into groups for framework and engine to
improve readability.
=> Extract and test framework auto-labelling

app_dart/lib/src/request_handlers/github_rate_limit_status.dart
The issue was the `resets` was being sent as a `DateTime`, when the table expected a timestamp int. This caused silent failures.
I rewrote the schema of the table to be with `DateTime`, and now seeing results using the `testchillers` version.
Fixes https://github.com/flutter/flutter/issues/79466
=> [app_dart] Fix writing GitHub quota rate limit json

device_doctor/lib/src/ios_device.dart, device_doctor/pubspec.lock, device_doctor/pubspec.yaml, device_doctor/test/src/ios_device_test.dart
Device recovery of device_doctor tool reboots the device. However ios32 phone needs manual intervention when rebooting.
This PR skips reboot for the 32 phone.
Related issue: https://github.com/flutter/flutter/issues/79316
=> Skip reboot for 32 bit phone when recovering device

app_dart/lib/src/model/proto/internal/scheduler.pb.dart, app_dart/lib/src/model/proto/internal/scheduler.pbenum.dart, app_dart/lib/src/model/proto/internal/scheduler.pbjson.dart, app_dart/lib/src/model/proto/internal/scheduler.proto, app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart
This allows for specifying a customer scheduler in the target. This will allow us to consolidate all the existing configs under `.ci.yaml` and make migrations simpler.
When this and https://github.com/flutter/cocoon/pull/1139 land, I'll follow up with a PR to download `.ci.yaml` and add the plumbing to add targets as tasks.
=> [scheduler] Add scheduler field to target

app_dart/bin/server.dart, app_dart/lib/cocoon_service.dart, app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/lib/src/request_handlers/refresh_github_commits.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/request_handlers/github_webhook_test.dart, app_dart/test/request_handlers/refresh_github_commits_test.dart, app_dart/test/service/scheduler_test.dart, app_dart/test/src/service/fake_scheduler.dart, app_dart/test/src/utilities/mocks.dart
This is to make it easier to write tests that depend on `Scheduler` but do not care about its implementation.
While implementing this, I noticed an issue where empty devicelab manifests would cause crashes, so I fixed it. Added a regression test.
Fixes https://github.com/flutter/flutter/issues/79679
=> [app_dart] Create FakeScheduler service + fix empty manifest crash

app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/request_handlers/github_webhook_test.dart
Avoid "It looks like this pull request may not have tests" message for framework PRs that only change dart files in `dev/devicelab/bin/tasks` or `dev/bots`.
Avoid adding the message on PRs like:
https://github.com/flutter/flutter/pull/71953
https://github.com/flutter/flutter/pull/75736
https://github.com/flutter/flutter/pull/76554
etc
=> [app_dart] Exclude framework dev/devicelab/bin/tasks and dev/bots from no tests warning

app_dart/lib/src/request_handling/authentication.dart, app_dart/test/request_handling/authentication_test.dart
There are several APIs that are called manually by gardeners. This
change allows to use gcloud auth to authenticate curl requests.
Bug: https://github.com/flutter/flutter/issues/43123
=> Allow request API requests from internal accounts.

app_dart/bin/server.dart, app_dart/bin/validate_scheduler_config.dart, app_dart/integration_test/validate_all_ci_configs_test.dart, app_dart/lib/src/datastore/config.dart, app_dart/lib/src/foundation/utils.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/foundation/utils_test.dart, app_dart/test/service/scheduler_test.dart, app_dart/test/src/service/fake_scheduler.dart
* Refactor `remoteFileContent` to `githubFileContent`
- Only return response content if file was a 200 response
- Throw NotFoundException on 404s
- Throw HttpException on remaining exceptions
- Allows for customized responses where it may be okay if a config file does not exist, otherwise it should be a hard failure
* If DeviceLab `manifest.yaml` 404s, return default response
* Retrieve `.ci.yaml` and store it in cache for future use
=> [app_dart] Differentiate 404s from other HTTP exceptions on GitHub files

app_dart/lib/src/request_handling/authentication.dart, app_dart/test/request_handling/authentication_test.dart
This path is frequently reached where the cookie is out of date due to the Flutter app rarely using cookies. Lowering this to a debug statement to reduce noise in the logs.
=> [app_dart] Lower log warning to debug in auth flow

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart, app_dart/test/src/datastore/fake_config.dart
Increases resilience and improves the waiting for tree to go green
workflows in the following ways:
* Process the label per repo independently of failures in other repos.
* Remove label and update PR if it does not have any checks and any
statuses.
* Do not raise an exception when graphql returns an empry list.
Bug: https://github.com/flutter/flutter/issues/79974
=> Prevent failures on empty status list.

app_dart/bin/server.dart, app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/lib/src/request_handlers/reset_try_task.dart, app_dart/lib/src/service/github_checks_service.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/request_handlers/github_webhook_test.dart, app_dart/test/request_handlers/reset_try_task_test.dart, app_dart/test/service/github_checks_service_test.dart, app_dart/test/service/scheduler_test.dart, app_dart/test/src/service/fake_buildbucket.dart, app_dart/test/src/service/fake_luci_build_service.dart, app_dart/test/src/service/fake_scheduler.dart
- Start of a refactor to internalize `LuciBuildService` and `BuildBucketClient` in `Scheduler` (i.e. request handlers should call `Scheduler` instead of these services)
- All references to the presubmit calls were switched to call scheduler directly
- Create fakes for the scheduler internal services (`FakeLuciBuildService` and `FakeBuildBucketClient`)
https://github.com/flutter/flutter/issues/77858
Since this is a refactor, I moved tests to the area under test. This deduplicated some of the mock calls
- Incorporate `.ci.yaml` targets into presubmit
- Refactor remaining `LuciBuildService` logic under `Scheduler` (postsubmit logic)
=> [app_dart] Refactor presubmit logic to scheduler

app_dart/lib/src/request_handlers/reset_prod_task.dart, app_dart/lib/src/request_handling/exceptions.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/test/request_handlers/reset_prod_task_test.dart, app_dart/test/service/luci_build_service_test.dart, app_flutter/lib/service/appengine_cocoon.dart
When a task has failed and the dashboard latency is high multiple people
can retry the same build multiple times wasting resources and preventing
tasks with lower priority from running.
Bug: https://github.com/flutter/flutter/issues/80918
=> Prevent retries on tasks already scheduled or running.

app_dart/lib/src/datastore/config.dart, app_dart/lib/src/foundation/github_checks_util.dart, app_dart/lib/src/model/appengine/commit.dart, app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/lib/src/request_handlers/github_rate_limit_status.dart, app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/lib/src/request_handlers/push_build_status_to_github.dart, app_dart/lib/src/request_handlers/push_engine_status_to_github.dart, app_dart/lib/src/request_handlers/push_gold_status_to_github.dart, app_dart/lib/src/request_handlers/refresh_chromebot_status.dart, app_dart/lib/src/request_handlers/reset_prod_task.dart, app_dart/lib/src/request_handlers/vacuum_github_commits.dart, app_dart/lib/src/service/github_checks_service.dart, app_dart/lib/src/service/github_status_service.dart, app_dart/lib/src/service/luci.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart, app_dart/test/request_handlers/github_webhook_test.dart, app_dart/test/request_handlers/push_engine_status_to_github_test.dart, app_dart/test/request_handlers/refresh_chromebot_status_test.dart, app_dart/test/request_handlers/reset_devicelab_task_test.dart, app_dart/test/request_handlers/reset_prod_task_test.dart, app_dart/test/request_handlers/reset_try_task_test.dart, app_dart/test/service/luci_test.dart, app_dart/test/src/datastore/fake_config.dart
This makes use of GitHub repositories consistent across Cocoon. Previously, some references were only the name of the repositories, others were `$owner/$name`, and lastly some were `RepositorySlug`. This switches everything to `RepositorySlug`.
Fixes https://github.com/flutter/flutter/issues/80531
=> [app_dart] Refactor repo references to RepositorySlug

app_dart/lib/src/request_handlers/reset_prod_task.dart, app_dart/test/request_handlers/reset_prod_task_test.dart
This is to allow the engine gardeners to re-trigger failed builds even
though they are not Flutter LUCI admins.
Bug: https://github.com/flutter/flutter/issues/81102
=> Add functionality to retry engine builds using curl commands.

app_dart/lib/src/request_handlers/vacuum_github_commits.dart, app_dart/test/request_handlers/vacuum_github_commits_test.dart
This is causing issues when there are no new github comits to refresh
=> [app_dart] Fix vacuum github commits on empty list

app_dart/cron.yaml
Agents have been deprecated and this job is generating errors, disable the cron job.
=> Remove agent health update cron job.

repo_dashboard/lib/repository.dart
Replaced Theme accentColor dependency with colorScheme.secondary because the accentColor theme properties are going to be deprecated. See https://github.com/flutter/flutter/pull/81336
=> Replaced accentColor with colorScheme.secondary

app_dart/lib/src/service/build_status_provider.dart, app_dart/test/service/build_status_provider_test.dart
If there are failures for a task in the consecutive latest commits, we will duplicate the task name in the list of failed tasks being returned.
Ensure that we only return a task name once in the list of failing tasks.
Bug:https://github.com/flutter/flutter/issues/81402
Test:app_dart/dart test
=> Fix duplicates tasknames get status list

app_dart/bin/server.dart, app_dart/lib/src/datastore/config.dart, app_dart/lib/src/foundation/github_checks_util.dart, app_dart/lib/src/foundation/utils.dart, app_dart/lib/src/model/proto/internal/scheduler.pb.dart, app_dart/lib/src/model/proto/internal/scheduler.pbenum.dart, app_dart/lib/src/model/proto/internal/scheduler.pbjson.dart, app_dart/lib/src/model/proto/internal/scheduler.proto, app_dart/lib/src/request_handlers/luci_status.dart, app_dart/lib/src/service/github_checks_service.dart, app_dart/lib/src/service/github_status_service.dart, app_dart/lib/src/service/luci.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/request_handlers/luci_status_test.dart, app_dart/test/request_handlers/reset_try_task_test.dart, app_dart/test/service/github_checks_service_test.dart, app_dart/test/service/github_status_service_test.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/service/scheduler_test.dart, app_dart/test/src/datastore/fake_config.dart, app_dart/test/src/service/fake_scheduler.dart, app_dart/test/src/utilities/mocks.dart
1. Add `run_if` to `Target` (maintain compatibility with try_builders.json)
2. Some refactoring to pass `List<LuciBuilder>` from scheduler to LuciBuildService for triggering presubmit runs
- The scheduler concats try_builders.json and .ci.yaml presubmit targets
Closes https://github.com/flutter/flutter/issues/77858 - Scheduler supports presubmit triggers
https://github.com/flutter/flutter/issues/76140 - Create Scheduler service
Fixes https://github.com/flutter/flutter/issues/80084 - prod_builders.json does not mark tasks flaky immediately
=> [scheduler] Add .ci.yaml presubmit scheduling

app_dart/lib/src/request_handlers/vacuum_github_commits.dart
This is causing some errors when we do want to add a commit from the cron method as the scheduler logger is null
=> [app_dart] Set logger in vacuum github commits

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart
This is done on pubsub notifications from the build, but during the scheduled -> started phase redirects to the build dashboard. We can minimize this to show users the queued time.
Update the `GrpcStatus` check to look for non-0 exit codes and log them
https://github.com/flutter/flutter/issues/80376
=> [scheduler] Set checkrun details page to LUCI build url when initially scheduled

app_dart/lib/src/service/config.dart, app_dart/pubspec.lock, app_dart/pubspec.yaml
Lower the dependency from a v2 to v1 is a quick fix until the package updates to the latest Dart
Without this, the Cocoon tree is broken. When this version of Dart rolls into the dev channel, deploys will also be broken.
=> [app_dart] fix graphql dependency on latest dart

app_dart/analysis_options.yaml, app_dart/lib/src/model/google/grpc.dart, app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/lib/src/request_handlers/get_build_status.dart, app_dart/lib/src/request_handlers/luci_status.dart, app_dart/lib/src/request_handlers/push_gold_status_to_github.dart, app_dart/lib/src/request_handlers/query_github_graphql.dart, app_dart/lib/src/request_handlers/reset_prod_task.dart, app_dart/lib/src/request_handlers/reset_try_task.dart, app_dart/lib/src/request_handling/authentication.dart, app_dart/lib/src/request_handling/static_file_handler.dart, app_dart/lib/src/request_handling/swarming_authentication.dart, app_dart/lib/src/service/github_status_service.dart, app_dart/lib/src/service/luci_build_service.dart, app_flutter/analysis_options.yaml, app_flutter/lib/service/appengine_cocoon.dart, app_flutter/lib/widgets/commit_author_avatar.dart
This is a recreation of https://github.com/flutter/cocoon/pull/1211 as I had a git hiccup
This lint is now supported, and we can add it to be enforced.
Added and updated `app_dart` and `app_flutter`.
=> Add lint: prefer relative imports

app_dart/lib/src/model/google/grpc.dart, app_dart/lib/src/model/luci/buildbucket.dart
Currently these show as `Response` or `Build` in the logs, and are not giving useful diagnostics. Update the `toString` to return information needed to debug scheduling failures.
https://github.com/flutter/flutter/issues/80376
=> [app_dart] Add more luci scheduling information to logs

app_dart/bin/server.dart, app_dart/lib/src/model/appengine/commit.dart, app_dart/lib/src/request_handlers/push_engine_status_to_github.dart, app_dart/lib/src/request_handlers/refresh_chromebot_status.dart, app_dart/lib/src/service/luci.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/request_handlers/push_engine_status_to_github_test.dart, app_dart/test/request_handlers/refresh_chromebot_status_test.dart, app_dart/test/service/luci_test.dart, app_dart/test/service/scheduler_test.dart, app_dart/test/src/datastore/fake_datastore.dart, app_dart/test/src/service/fake_scheduler.dart
Recreation of https://github.com/flutter/cocoon/pull/1210 due to some git hiccups
- Explicitly pass postsubmit builders in `LuciService.getRecentTasks`
- Update `/api/refresh-chromebot-status` to get postsubmit builders from `Scheduler`
- Update engine tree status to get postsubmit builders from `Scheduler`
Add test to refresh-chromebot-status to check builders in ci.yaml are used to update status
=> [scheduler] Update prod tasks listed in ci.yaml

app_dart/app.yaml, app_dart/bin/server.dart, app_dart/lib/cocoon_service.dart, app_dart/lib/src/request_handlers/readiness_check.dart
This is to ensure the dart server is ready to serve requests before
marking the VM as ready.
Bug: https://github.com/flutter/flutter/issues/79464
=> Add AppEngine readiness check.

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
This is will allow the waiting for tree to go green bot to submit commit
older than 10 mins.
Bug: https://github.com/flutter/flutter/issues/81072
=> Reduce injected latency for cocoon repo to 10 mins.

app_dart/lib/src/service/scheduler.dart, app_dart/test/request_handlers/github_webhook_test.dart, app_dart/test/service/scheduler_test.dart
This adds a check to all Cocoon scheduled presubmits that validates the ci.yaml + validates all builds were scheduled.
If `.ci.yaml` does not exist, it will pass as it uses an empty `SchedulerConfig`.
https://github.com/flutter/flutter/issues/82303
=> [scheduler] ci.yaml check run

scheduler/README.md
With the `.ci.yaml` migration complete, address some feedback on missing documentation in the linked README.
=> [scheduler] Document target fields in README

app_dart/lib/src/request_handlers/reset_prod_task.dart, app_dart/lib/src/service/config.dart, app_dart/test/request_handlers/reset_prod_task_test.dart
Related to https://github.com/flutter/flutter/issues/48987
This PR makes `reset_prod_task.dart` use the keyHelper defined in the cocoon config.
=> Refactor [reset_prod_task] cocoon config keyHelper reference

app_dart/lib/src/service/luci_build_service.dart
This is to be able to link to the LUCI task as soon as the build is
scheduled.
Bug: https://github.com/flutter/flutter/issues/82417
=> Update the details url as soon as we retrigger a task.

app_dart/dev/deploy.dart
Fixes https://github.com/flutter/flutter/issues/84139
Issue was the bash script exit code were being ignored by the local Dart script. This only impacted local uses, and not production uses.
=> [app_dart] Check bash script exit codes in local deploy script

app_dart/lib/src/service/github_checks_service.dart, app_dart/test/service/github_checks_service_test.dart
This adds the triaging [wiki page](https://github.com/flutter/flutter/wiki/Triaging-a-LUCI-build-failure) to the check run summary, to make it easy for people to reference. This should be more helpful for people new to the Flutter Infra/LUCI.
Related issue: https://github.com/flutter/flutter/issues/64208#issuecomment-841470687
=> Append triaging wiki link to Github check run summary

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
The status name was changed to make it consistent with the name used in
the engine and the the "waiting for tree to go green" was failing to
submit the PR instead of waiting for the tree to become green.
Bug: https://github.com/flutter/flutter/issues/84835
=> Update flutter status name.

app_dart/lib/src/service/luci_build_service.dart
Auto retry logic has been implemented for TOT failures, but there is no way to distinguish the auto-retried build from others. This PR adds auto trigger tags.
Issue: https://github.com/flutter/flutter/issues/85179
=> Add auto retry tag when build is auto triggered by cocoon

app_dart/lib/src/model/proto/internal/scheduler.pbenum.dart, app_dart/lib/src/model/proto/internal/scheduler.pbjson.dart, app_dart/lib/src/model/proto/internal/scheduler.proto, app_dart/lib/src/request_handlers/update_task_status.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/request_handlers/refresh_chromebot_status_test.dart, app_dart/test/service/scheduler_test.dart, app_dart/test/src/service/fake_scheduler.dart
Adds initial plumbing to ingest target from `.ci.yaml`
```yaml
- name: Google Internal Roll
bringup: true
presubmit: false
scheduler: google_internal
```
Using `/api/update-task-status` this target can be updated via FRoB
https://github.com/flutter/flutter/issues/79658
=> [app_dart] Add google_internal target support

app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/request_handlers/github_webhook_test.dart
This adds a `needs tests` label to any PR that doesn't appear to have tests. This allows us to more easily track PRs that were landed without tests.
=> Apply 'needs tests' label to any PR that needs tests

app_dart/dev/branches.txt
Removed Flutter 1.26 as it's an old branch
=> Add Flutter 2.4 to branches.txt

app_flutter/lib/widgets/app_bar.dart, app_flutter/lib/widgets/lattice.dart, app_flutter/pubspec.lock, device_doctor/pubspec.lock, device_doctor/pubspec.yaml
https://github.com/flutter/cocoon/pull/1270
`brightness` was deprecated, and layer handle API changed a bit. This unblocks Cocoon's presubmit.
=> [app_flutter] Fix brightness deprecation, cherrypick #1270

app_dart/bin/server.dart, app_dart/lib/cocoon_service.dart, app_dart/lib/src/request_handlers/check_flaky_tests_and_update_github.dart, app_dart/lib/src/request_handlers/check_flaky_tests_and_update_github_utils.dart, app_dart/lib/src/service/bigquery.dart, app_dart/lib/src/service/config.dart, app_dart/lib/src/service/github_service.dart, app_dart/test/request_handlers/check_flaky_test_and_update_github_test_data.dart, app_dart/test/request_handlers/check_flaky_tests_and_update_github_test.dart, app_dart/test/request_handlers/check_flaky_tests_and_update_github_test_data.dart, app_dart/test/service/bigquery_test.dart, app_dart/test/src/datastore/fake_config.dart, app_dart/test/src/service/fake_github_service.dart, app_dart/test/src/utilities/mocks.dart
Auto create issues if there is not already one or has closed one longer than 15 days.
create PR if the test is not already marked flaky and no existing pr to mark flaky
=> Auto flake part1

app_dart/lib/src/model/appengine/task.dart, app_dart/lib/src/model/appengine/task.g.dart, app_dart/lib/src/model/luci/buildbucket.g.dart
This is to mark test, which has rerun from test runner side, as flaky if any.
Existing logic counts a test as flaky if multiple runs exist for the whole build. With https://github.com/flutter/flutter/pull/86394, a test can be flaky even if there is only one build run but there are multiple reruns from the test runner. This PR adds a task property to hold that flaky flag.
One TODO is update this property when task finishes if any flake exists from test runner side.
Related: https://github.com/flutter/flutter/issues/86324
=> Add TestRunFlaky property for task

app_dart/lib/src/request_handlers/update_task_status.dart, app_dart/test/request_handlers/update_task_status_test.dart
This is a follow up of https://github.com/flutter/cocoon/pull/1280: updating TestFlaky property when updating the task status.
This PR also cleans up an obsolete test for retries.
Related: https://github.com/flutter/flutter/issues/86324
=> Update TestFlaky when updating task status

app_dart/lib/src/request_handlers/github_webhook.dart
Add a log line to help with debugging missing task scheduling for certain PRs (https://github.com/flutter/flutter/issues/86383)
=> Add a logging line to github webook scheduling tasks for mergeable PRs

app_dart/bin/generate_jspb.dart
This currently fails 100% of the time
=> [app_dart] Fix arg check

app_dart/lib/src/request_handlers/push_build_status_to_github.dart, app_dart/test/request_handlers/push_build_status_to_github_test.dart
While doing the beta release, I noticed we unnecessarily push tree status to the release branches.
I manually ran and verified querying base with master returns pull requests using the HTTP API.
=> [app_dart] Don't push tree status to release branches, fix LUCI console link

app_flutter/lib/service/dev_cocoon.dart, app_flutter/test/widgets/task_grid_test.dart
A recent change in scrolling has led to an assertion failure in our scrolling golden tests. Apparently you need to use pumpAndSettle() to avoid the assertion.
I've verified the above solution, but I'm starting this PR off with an empty commit to verify that the current tree cannot pass its own tests. When it fails, I'll push a second commit with the fixes to verify that it passes.
~Note that this points out another issue with the tests here - the tests that failed were attempting to see the "LOADING..." banner after a scroll (as per the comments on the tests themselves), and I'm guessing that is why they used pump() rather than pumpAndSettle() because they needed to get the screen capture before the new data came in. As far as I can tell, that never happened and the golden files for those …
=> Fix golden tests after change in scrolling

device_doctor/bin/main.dart, device_doctor/lib/src/android_device.dart, device_doctor/lib/src/device.dart, device_doctor/lib/src/ios_device.dart, device_doctor/test/src/android_device_test.dart
This PR adds a support for a new action `prepare`, which prepares the phone before running a task. One feature added here for android device is: clean up the top activity in android devices.
Related: https://github.com/flutter/flutter/issues/83938
=> [cocoon device doctor] Kill android process before running tasks

cloud_build/deploy.sh
This is to address the problems with the backend not being available
during the deployment process.
Bug: https://github.com/flutter/flutter/issues/87222
=> Redirect traffic only after the deployment is successful.

app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart
This is necessary for adding new presubmit targets in the .ci.yaml
The expectation is developers add a target that is in bringup, and wait for it to soak. Once prod is green, they can remove bringup to enable the presubmit.
Currently, this doesn't work as the ci.yaml change can't be landed as the builder doesn't exist yet.
=> [scheduler] Don't run bringup presubmit targets

CI_YAML.md
Fixes indentation of inline blocks and sublists, and replaces unsupported use of letters as list markers, so that the markdown will display correctly on GitHub.
=> Fix list formatting in ci.yaml docs

app_dart/lib/src/request_handlers/luci_status.dart
As the pubsub messages are coming from the same project as the appengine
instance there is no reason to use an additional service account. This
PR removes the dependency on the devicelab service account.
=> Prepare to remove devicelab service account.

app_dart/lib/src/model/luci/buildbucket.dart, app_dart/lib/src/request_handlers/push_build_status_to_github.dart, app_dart/lib/src/request_handlers/refresh_chromebot_status.dart, app_dart/lib/src/service/luci.dart, app_dart/test/service/luci_test.dart
The `staging` suffix was removed in https://flutter-review.googlesource.com/c/infra/+/17400 for staging builders, and same builder name exists in both staging and prod pools. This results in `realm` appended to `scheduler_job_id`:
Cocoon has been querying without specifying the `realm`, and miss those builds.
This PR adds the missing `realm` case.
=> Prepare search requests considering realm when calling builderbucket API

.github/workflows/mirror.yml
We will mirror master branch to main. This will enable us to start moving some processes to main branch in preparation to deprecate master.
=> Enable workflow to mirror master branch to main.

.github/workflows/mirror.yml
Flutter repositories allow readonly workflows by default. Workflows that
require write permissions need to explicitly request them in the
configuration file.
=> Grant explicit write permissions.

.github/workflows/mirror.yml
This is to be able to setup branch protection correctly.
=> Use githubbot token instead of the default one.

app_dart/lib/src/service/github_checks_service.dart, app_dart/test/service/github_checks_service_test.dart
Fixes https://github.com/flutter/flutter/issues/87507
=> [app_dart] Truncate luci build push messages before sending as check

app_dart/lib/src/service/luci_build_service.dart
This was caused by pubsub notification topic not being encoded as
base64.
Bug: https://github.com/flutter/flutter/issues/90914
=> Fixes build re-run failing with a 400 status code.

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
This will remove several 500 status code in the cocoon backend and it
will also improve the bot's throughput to submit PRs.
Bug: https://github.com/flutter/flutter/issues/90851
=> Do not try to submit if PR is not mergeable.

app_dart/lib/src/request_handlers/push_gold_status_to_github.dart, app_dart/test/request_handlers/push_gold_status_to_github_test.dart
We have a lot more web builds now, they are not indicative of golden file tests being run. 
For example, the flutter-gold check is currently broken on this change: https://github.com/flutter/flutter/pull/90413 This change does not execute golden file tests, so there are no results when it looks up Gold.
Fixes https://github.com/flutter/flutter/issues/90979
=> Remove `web` as an indicator of golden file test execution

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
We believe the mergeable check recently added is interfering with some PRs
Bug: https://github.com/flutter/flutter/issues/91035
=> Add additional logging to validate mergeable state.

device_doctor/lib/src/android_device.dart, device_doctor/lib/src/utils.dart, device_doctor/test/src/android_device_test.dart
This is to ensure devicelab android devices are running with screen on all the time.
https://github.com/flutter/flutter/issues/89260
=> Add screen on check for android devices

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
Reverts flutter/cocoon#1368
Fixes https://github.com/flutter/flutter/issues/91035
We need the bot to leave the "waiting for tree to go green" label on PRs that are green EXCEPT for the `luci-flutter` check
=> Revert "Do not try to submit if PR is not mergeable."

device_doctor/lib/src/android_device.dart, device_doctor/test/src/android_device_test.dart
This is a follow up of https://github.com/flutter/cocoon/pull/1370.
It turns out that `mHoldingWakeLockSuspendBlocker` is not reliable to decide if the screen is on.
For example: newly enabled test bed in staging `linux9` is with screen on and running test well, but 
```
mHoldingWakeLockSuspendBlocker=false
mHoldingDisplaySuspendBlocker=true
```
On the other hand, `mHoldingDisplaySuspendBlocker=false` always suggests screen is off. So we keep `mHoldingDisplaySuspendBlocker` only as a flag for screen on or off.
=> Remove unreliable mHoldingWakeLockSuspendBlocker check

app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/request_handlers/github_webhook_test.dart
Avoids the bot asking for tests on code that is test code.
See https://github.com/flutter/flutter/pull/91099 for example
=> Ignore devicelab lib tasks

app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/request_handlers/github_webhook_test.dart
I noticed during triage that the API docs are now in a directory that we can label for.
This accounts for `flutter/examples/api` now.
=> Add labeling for API docs

app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/request_handlers/github_webhook_test.dart
Engine uses things like shell_benchmarks.cc for benchmark related tests.
@xster fyi
Another attempt here, this time starting witht he right base.
=> Detect benchmarks as tests in engine repo

cloud_build/deploy.sh
GAE only allows 30 versions. The past 2 days had issues where it was failing to deploy due to the quota.
This will only keep the 10 most recent versions (gives some room for old versions to fallback to and dev versions).
I ran this command manually, and it takes ~1 minute per version to delete it. I did a bulk delete of 20 instances, so I only expect this to add 1-3 minutes to the cloudbuild workflow.
=> [cloud_build] Only keep 10 most recent versions

app_dart/pubspec.lock, app_dart/pubspec.yaml
This is to fix https://github.com/flutter/flutter/issues/90019
=> Push cocoon to use latest version of packages `googleapis` and `gcloud`

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
This will make the CheckRunConclusion take precedent over the status as that's what the GitHub UI does. There's a glitch where a check can be considered still running but it's marked with a green checkmark. To match expectations, that should be marked as a passing run.
Fixes https://github.com/flutter/flutter/issues/91908
https://github.com/flutter/flutter/issues/90970
=> [app_dart] Merged successful checks even if still running

app_dart/lib/src/model/luci/buildbucket.dart, app_dart/lib/src/request_handlers/luci_status.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/src/utilities/mocks.mocks.dart
There was an outage from yesterday's github model removal PR. It incorrectly set the repo_owner in the buildbucket rpc, which cannot be parsed (it passes `pullRequest.base.repo` instead of ` pullRequest.base.repo.owner`)
Fixes https://github.com/flutter/flutter/issues/92270
=> [app_dart] Fix presubmit builds setting incorrect repo_owner

device_doctor/lib/src/android_device.dart, device_doctor/lib/src/utils.dart, device_doctor/test/src/android_device_test.dart
Some Android tests do not work properly when the screen saver is
enabled.
Bug: https://github.com/flutter/flutter/issues/91826
=> Add device doctor check for screen saver on.

device_doctor/lib/src/android_device.dart
The functionality was added to the class but the method was not being
called.
Bug: https://github.com/flutter/flutter/issues/91826
=> Start using the screenSaver check.

release_dashboard/test/fake_process_manager.dart, release_dashboard/test/fake_process_manager_test.dart
The upstream FakeProcessManager is defined in test files, and thus not importable. Thus, this was copy pasted from https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/src/fake_process_manager.dart with some changes to satisfy the analyzer over null checks on non-nullable fields. I added an explicit test exercising it.
=> [release_dashboard] add fake_process_manager

release_dashboard/analysis_options.yaml, release_dashboard/lib/main.dart, release_dashboard/lib/services/conductor.dart, release_dashboard/lib/services/local_conductor.dart, release_dashboard/lib/widgets/conductor_status.dart, release_dashboard/lib/widgets/progression.dart, release_dashboard/pubspec.lock, release_dashboard/test/main_test.dart, release_dashboard/test/src/services/fake_conductor.dart, release_dashboard/test/widgets/conductor_status_test.dart, release_dashboard/test/widgets/stepper_test.dart
This refactors make it easy to use and test the conductor. It also makes it easier to propagate notifications with the state.
=> [release_dashboard] Create Conductor service

release_dashboard/test/widgets/conductor_status_test.dart
Fixed a few tests in `conductor_status_test.dart` from this [discussion](https://github.com/flutter/cocoon/pull/1427#discussion_r740377259).
=> removed path from conductor status test

release_dashboard/lib/main.dart, release_dashboard/lib/widgets/common/dialog_prompt.dart, release_dashboard/lib/widgets/conductor_status.dart, release_dashboard/pubspec.lock, release_dashboard/test/widgets/common/dialog_prompt_test.dart
*Added a Clean button to delete the release state file. It is currently not connected with `conductor clean` CLI command yet.*
Migrated from this [PR](https://github.com/flutter/flutter/pull/92505).
Here is a recording of the workflow:
https://user-images.githubusercontent.com/20194490/139136962-5fb9c82c-aa71-4984-a4ac-54182e3efb28.mov
*[Issue](https://github.com/flutter/flutter/issues/91119)*
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-rep …
=> [Conductor] Added clean confirmation prompt on conductor status

app_dart/lib/src/service/bigquery.dart, app_dart/test/service/bigquery_test.dart
This solves: https://github.com/flutter/flutter/issues/92999
changes:
1) switch query to staging runs instead of prod (with support of cl/407390665)
2) fix corner case when no rows are returned.
=> Use staging data when auto deflake tests

app_dart/lib/src/model/appengine/task.dart, app_dart/lib/src/model/ci_yaml/ci_yaml.dart, app_dart/lib/src/model/ci_yaml/target.dart, app_dart/lib/src/request_handlers/push_build_status_to_github.dart, app_dart/lib/src/request_handlers/refresh_chromebot_status.dart, app_dart/lib/src/request_handlers/reset_prod_task.dart, app_dart/lib/src/service/luci.dart, app_dart/lib/src/service/scheduler.dart, app_dart/test/request_handlers/push_build_status_to_github_test.dart, app_dart/test/request_handlers/refresh_chromebot_status_test.dart, app_dart/test/request_handlers/reset_prod_task_test.dart, app_dart/test/request_handlers/vacuum_github_commits_test.dart, app_dart/test/service/github_checks_service_test.dart, app_dart/test/src/service/fake_scheduler.dart, release_dashboard/pubspec.lock
This refactors to add a wrapper on top of the protobuf. This wrapper is where new functionality should be added instead of the increasing the service of the scheduler service. It's based on pain points i've found while developing the scheduler the past few months.
To start, I moved the postsubmitTargets and presubmitTargets logic to this wrapper.
https://github.com/flutter/flutter/issues/92301 - Requires a wrapper around the protobuf for parsing properties
https://github.com/flutter/flutter/issues/87954 - Requires scheduler validation logic to not contain any dart:mirrors related code
https://github.com/flutter/flutter/issues/92301 - Add getProperties() to `Target` that parses <String, String> to the correct data types (based on logic from flutter/infra)
=> [scheduler] ci.yaml models

app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/request_handlers/github_webhook_test.dart, app_dart/test/src/datastore/fake_config.dart
Enables the auto-comment bot for missing tests in flutter/packages and
flutter/plugins. The patterns are based on the standard pattern for Dart
tests, plus patterns specific to the various documented flutter/plugins
native test types; this should be essentially correct, but may require
fine-tuning later if there are special cases that weren't covered.
Fixes https://github.com/flutter/flutter/issues/83514 …
=> Enable test check for packages and plugins repos

app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart, app_dart/test/request_handlers/file_flaky_issue_and_pr_test.dart
This fixes: https://github.com/flutter/flutter/issues/92430
This PR skip deflake PR if there exists a flaky bug that is open or closed < 15 days.
(Tests need validation in https://github.com/flutter/flutter/issues/90139)
=> Skip PR creation when a flaky bug exists and is open or closed recently

release_dashboard/lib/main.dart, release_dashboard/lib/state/status_state.dart, release_dashboard/lib/widgets/conductor_status.dart, release_dashboard/lib/widgets/progression.dart, release_dashboard/pubspec.lock, release_dashboard/pubspec.yaml, release_dashboard/test/main_test.dart, release_dashboard/test/src/services/fake_conductor.dart, release_dashboard/test/widgets/conductor_status_test.dart, release_dashboard/test/widgets/stepper_test.dart
*Conductor status is in a global state now. Status can be read and modified in any widget now.*
*[Issue](https://github.com/flutter/flutter/issues/91119)*
Currently, the tests for status states are inside `conductor_status_test.dart` as well, since the global states are read in that widget. With the states being read correctly in that widget, it confirms the states are being set properly at the beginning of the app as well. …
=> [Conductor] status into state provider

release_dashboard/lib/widgets/common/url_button.dart, release_dashboard/lib/widgets/conductor_status.dart, release_dashboard/macos/Flutter/Flutter-Debug.xcconfig, release_dashboard/macos/Flutter/Flutter-Release.xcconfig, release_dashboard/macos/Flutter/GeneratedPluginRegistrant.swift, release_dashboard/macos/Podfile, release_dashboard/macos/Podfile.lock, release_dashboard/macos/Runner.xcodeproj/project.pbxproj, release_dashboard/macos/Runner.xcworkspace/contents.xcworkspacedata, release_dashboard/pubspec.lock, release_dashboard/pubspec.yaml, release_dashboard/test/widgets/common/url_button_test.dart, release_dashboard/test/widgets/conductor_status_test.dart
*The conductor status repo info section displays the LUCI dashboard link. Now, this link is clickable, and the URL is launched in a web browser. 3rd party package used: [url_launcher](https://pub.dev/packages/url_launcher)*
*[Issue](https://github.com/flutter/flutter/issues/91119)*
Screen recording:
https://user-images.githubusercontent.com/20194490/139513944-796b0853-cef5-4ebd-b1d3-1c47e2be6fba.mov
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutt …
=> [conductor] added URL launcher

app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/request_handlers/github_webhook_test.dart
Adds the ability to recognize PRs that only change single-line comments,
and exempts them from test requests.
- Currently only handles a specific set of languages that use `//`.
- Makes no attempt to handle multi-line (`/* */`) blocks, so tests will
still sometimes be requested for comment-only changes (e.g., to
Javadoc comments).
- Currently enabled only for flutter/plugins and flutter/packages in
order to evaluate it before rolling it out to other repositories.
[CLA]: …
=> Don't request tests for some commment-only changes

.github/workflows/mirror.yml
=> Revert "Remove cocoon mirroring from main to master."

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/lib/src/request_handlers/check_for_waiting_pull_requests_queries.dart, app_dart/lib/src/service/config.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
Google's CLA status was moved to a GitHub check. Instead, we should be checking iff the checks are empty.
Most repos still have a status (like WIP), but Cocoon only had the CLA bot. Now it's blocked on having PRs submitted by the bot.
Fixes https://github.com/flutter/flutter/issues/93418
=> [app_dart] Allow waiting for green to accept empty statuses

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests_queries.dart
Fixes https://github.com/flutter/flutter/issues/93418
I tested this with a dev version and was able to confirm it unblocked cocoon prs
https://github.com/flutter/cocoon/pull/1452#event-5606322592
=> [app_dart] Fix GraphQL parameters

device_doctor/lib/src/android_device.dart, device_doctor/lib/src/utils.dart, device_doctor/test/src/android_device_test.dart
Partly solves https://github.com/flutter/flutter/issues/92915.
This PR adds health checks for android device battery:
1) check battery level > 15 (100 scale)
2) check battery temperature < 34°C
=> [device doctor] Add android device battery health check

release_dashboard/test/main_test.dart
`CleanRelease` widget was created and tested correctly, but it was never called inside `main`. 
=> Conductor delete error msg

app_dart/lib/src/service/bigquery.dart, app_dart/test/src/utilities/mocks.mocks.dart
This fixes part of https://github.com/flutter/flutter/issues/92502.
Instead of querying build stats in past two weeks, this PR updates to query recent 100 (default value) builds for each builder.
=> Use a fixed number of commits when calculating flaky percentage

release_dashboard/lib/widgets/common/url_button.dart
`UrlButton` widget uses `TextButton` with a default leading and trailing padding. When displayed as a link in the UI, it has not aligned with the rest of the text as shown below:
This sets the padding of `TextButton` to zero and aligns with the rest of the text.
*[Issue](https://github.com/flutter/flutter/issues/91119)* …
=> [conductor] Removed URL padding

device_doctor/lib/src/ios_device.dart, device_doctor/test/src/ios_device_test.dart
Quarantine the testbed when the ios certificate was revoked.
https://github.com/flutter/flutter/issues/93610
=> [device doctor] Check ios revoked cert

app_dart/lib/src/request_handlers/flaky_handler_utils.dart, app_dart/lib/src/request_handlers/update_existing_flaky_issues.dart, app_dart/lib/src/service/bigquery.dart, app_dart/test/request_handlers/update_existing_flaky_issues_test.dart, app_dart/test/request_handlers/update_existing_flaky_issues_test_data.dart, app_dart/test/src/utilities/mocks.mocks.dart
This solves: https://github.com/flutter/flutter/issues/93678
This PR does
1) Update flaky bug body to reflect recent changes (https://github.com/flutter/flutter/issues/92502)
2) Update flaky bugs using staging stats for builders marked as `bringup: true`, which are expected to run in `staging` pool.
3) Update flaky bugs using prod stats for builders (such as shard builders) without `bringup: true`.
=> Use correct bucket stats when file/update flaky bugs

app_dart/lib/src/service/build_status_provider.dart
For engine repository main became the default branch and we need to
allow tree status calculations main.
[Discord]: …
=> Calculate tree status from both master and main.

dashboard/lib/widgets/app_bar.dart
This is to fix the analyzer error complaining about the deprecation of primaryBrightnessColor.
=> Remove use of primaryBrightnessColor.

app_dart/lib/src/request_handlers/push_build_status_to_github.dart
While other parts of the handler to push status to github where using
the correct branch the logic to update the status in github was still
using master.
Bug: https://github.com/flutter/flutter/issues/93872
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking …
=> Use main as default branch when pushing tree status.

device_doctor/tool/build.bat, device_doctor/tool/build.sh
The device_doctor build script relied on `dart2native`, which is deprecated: https://github.com/dart-lang/sdk/issues/46100
Updating to use `dart compile exe`.
Issue: https://github.com/flutter/flutter/issues/93942
=> Update device doctor build script to use dart compile exe

app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/request_handlers/github_webhook_test.dart
Fixes eager label bot tagging integration tests outside of the package with the package-specific label.
Fixes https://github.com/flutter/flutter/issues/92939
[Discord]: …
=> Adjust integration test labelling

release_dashboard/lib/widgets/clean_release_button.dart, release_dashboard/lib/widgets/codesign_engine_substeps.dart, release_dashboard/lib/widgets/common/url_button.dart, release_dashboard/lib/widgets/conductor_status.dart, release_dashboard/lib/widgets/create_release_substeps.dart, release_dashboard/lib/widgets/engine_cherrypicks_substeps.dart, release_dashboard/lib/widgets/progression.dart, release_dashboard/test/widgets/codesign_engine_substeps_test.dart
Made UI for the substeps of the step `Codesign Engine Binaries`. The CI dashboard link changes according to the release channel.
Main Issue: 
Screen Capture:
[Discord]: …
=> [release_dashboard] Add substeps for `Codesign Engine binaries` step

app_dart/lib/src/service/config.dart, app_dart/test/src/datastore/fake_config.dart
The `GitHubFlakyBotToken` was created for testing purpose, this PR cleans up related codes as we have switched to use `fluttergithubbot`.
=> Clean up github token for test flaky bot

CI_YAML.md, app_dart/integration_test/validate_all_ci_configs_test.dart, app_dart/lib/src/model/ci_yaml/ci_yaml.dart, app_dart/lib/src/service/scheduler.dart, app_dart/pubspec.lock, app_dart/pubspec.yaml, app_dart/test/model/ci_yaml/ci_yaml_test.dart, app_dart/test/service/scheduler_test.dart
This makes the release process easier. Instead of adding the candidate branch each time to the ci.yaml, we can insert the regex from this test and forget about the step.
Fixes https://github.com/flutter/flutter/issues/84356
=> [ci.yaml] Support branch regexes

release_dashboard/lib/widgets/clean_release_button.dart, release_dashboard/lib/widgets/common/dialog_prompt.dart, release_dashboard/lib/widgets/common/snackbar_prompt.dart, release_dashboard/test/widgets/clean_release_button_test.dart, release_dashboard/test/widgets/common/dialog_prompt_test.dart
User must input a confirmation string in order to clean a current release. This adds another layer of validation and security.
Main Issue:
Extras:
Screen recording:
https://user-images.githubusercontent.com/20194490/142506577-3493733a-b268-49b9-91a7-42fec82435c1.mov …
=> [release_conductor] add dialogue prompt with input confirmation

release_dashboard/lib/widgets/create_release_substeps.dart, release_dashboard/test/widgets/create_release_substeps_test.dart
Inputs and dropdowns disable when start initialization is being loaded. Also changed all keys that are hard-coded strings in `CreateReleaseSubsteps` to enums, which required a significant amount of refactoring.
Fore example, before, the release data are stored in `Map<String, String?>`, now they are in `Map<Enum, String?>`. 
Main Issue:
Side Issue:
Screen recording (inputs and dropdowns become disabled when loading):
https://user-images.githubusercontent.com/20194490/144473669-281b7971-b89e-4eda-b9fc-60cc79974e00.mov
[test-exempt]: …
=> [release_dashboard] Disabled inputs and dropdowns on loading

release_dashboard/lib/logic/cherrypick_state.dart, release_dashboard/pubspec.lock, release_dashboard/test/logic/cherrypick_state_test.dart
Previously the `cherrypickState` `toString` extension function does not have tests. This PR adds the missing tests.
Main Issue:
=> [release_dashboard] Add tests for cherrypickState

release_dashboard/android/local.properties, release_dashboard/lib/widgets/progression.dart, release_dashboard/lib/widgets/release_completed.dart, release_dashboard/test/widgets/framework_cherrypicks_substeps_test.dart, release_dashboard/test/widgets/release_completed_test.dart
UI for the last step: `Release is complete`
Main Issue:
Screen Capture:
=> [release_dashboard] Release Complete Step UI

release_dashboard/lib/widgets/progression.dart, release_dashboard/lib/widgets/push_release_substep.dart, release_dashboard/test/widgets/push_release_substep_test.dart
UI for `Push the release` step:
Main Issue:
UI:
=> [release_dashboard] Push release UI

app_dart/lib/src/request_handlers/deflake_flaky_builders.dart, app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart, app_dart/lib/src/request_handlers/get_build_status.dart, app_dart/lib/src/request_handlers/get_status.dart, app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/lib/src/request_handlers/push_build_status_to_github.dart, app_dart/lib/src/request_handlers/push_gold_status_to_github.dart, app_dart/lib/src/request_handlers/refresh_chromebot_status.dart, app_dart/lib/src/request_handlers/update_existing_flaky_issues.dart, app_dart/lib/src/request_handlers/vacuum_github_commits.dart, app_dart/lib/src/service/build_status_provider.dart, app_dart/lib/src/service/config.dart, app_dart/lib/src/service/datastore.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/test/request_handlers/deflake_flaky_builders_test.dart, app_dart/test/request_handlers/file_flaky_issue_and_pr_test.dart, app_dart/test/request_handlers/flaky_handler_utiles_test.dart, app_dart/test/request_handlers/get_status_test.dart, app_dart/test/request_handlers/github_webhook_test.dart, app_dart/test/request_handlers/push_build_status_to_github_test.dart, app_dart/test/request_handlers/refresh_chromebot_status_test.dart, app_dart/test/request_handlers/update_existing_flaky_issues_test.dart, app_dart/test/request_handlers/update_task_status_test.dart, app_dart/test/service/build_status_provider_test.dart, app_dart/test/service/datastore_test.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/src/datastore/fake_config.dart, app_dart/test/src/datastore/fake_datastore.dart, app_dart/test/src/service/fake_build_status_provider.dart
https://github.com/flutter/flutter/issues/94522
http://testchillers.flutter-dashboard.appspot.com/api/public/get-status?flushCache=true&repo=engine
1. Add other repos to supported scheduler repos (to start writing to datastore)
A. This should get a soak time of 30 commits for each repo to populate enough data for dashboards and tree status
2. Add refresh chromebot cron jobs for each repo (temporary measure until cocoon scheduler is available)
3. Revert tree status back to the datastore algorithm
3. Update frontend to allow for repo switching
=> [app_dart] Pass repo for Task and Commit

app_dart/lib/src/request_handlers/update_existing_flaky_issues.dart, app_dart/test/request_handlers/update_existing_flaky_issues_test.dart, app_dart/test/request_handlers/update_existing_flaky_issues_test_data.dart
https://github.com/flutter/cocoon/pull/1464/files updated the bot to comment on open flaky bugs based on different pool stats. But it missed a corner case when a builder was marked as unflaky but a flaky bug is still open. For this case, the bot logic updates the bug twice.
This PR skip the update from staging side, as the builder has been marked as unflaky.
Context: https://github.com/flutter/flutter/issues/93804#
=> Fix auto flake comment on open flaky bug for a recently deflaked builder

app_dart/lib/src/service/config.dart
https://github.com/flutter/flutter/issues/94790
Making this an explicit map so it's easier to review what the default branch is for each repo
This moves plugins and packages to use master as their default branch.
=> [scheduler] Move packages/plugins default branch back to master

release_dashboard/lib/main.dart, release_dashboard/test/main_test.dart
Added a message that remains the users to follow each step and substep in order.
Main Issue:
Screen capture:
=> [release_dashboard] Add follow each step and substeps in order

release_dashboard/lib/services/conductor.dart, release_dashboard/lib/services/local_conductor.dart, release_dashboard/lib/services/release_dashboard_next_context.dart, release_dashboard/lib/state/status_state.dart, release_dashboard/lib/widgets/cherrypicks_substeps.dart, release_dashboard/test/fakes/fake_next_context.dart, release_dashboard/test/fakes/services/fake_conductor.dart, release_dashboard/test/src/test_state_generator.dart, release_dashboard/test/widgets/engine_cherrypicks_substeps_test.dart, release_dashboard/test/widgets/framework_cherrypicks_substeps_test.dart
*Added `conductor next` implementation for `Apply engine cherrypicks` step*, and for `Apply framework cherrypicks` step.
Main Issue:
PR that needed to be landed before this:
[Discord]: …
=> [release_dashboard] nextContext Connect

release_dashboard/lib/widgets/cherrypicks_substeps.dart, release_dashboard/test/widgets/common/continue_button_test.dart
Made `continueButton` of each step a common widget so it could be used across any steps.
Main Issue:
PR needs to be rebased and updated after this has been merged:
https://github.com/flutter/cocoon/pull/1482
https://github.com/flutter/cocoon/pull/1483
https://github.com/flutter/cocoon/pull/1484
https://github.com/flutter/cocoon/pull/1487 …
=> [release_dashboard] continue button common widget

app_dart/lib/src/request_handlers/flaky_handler_utils.dart, app_dart/test/request_handlers/file_flaky_issue_and_pr_test_data.dart, app_dart/test/request_handlers/update_existing_flaky_issues_test_data.dart
Fixes https://github.com/flutter/flutter/issues/94319
When showing overviews of builders, the MILO pages can disappear. This should instead point to the build dashboard which can show the overview.
Since the flaky issue bot only directly links to builds, I replaced the successful builds section with a recent test runs pointing to the build dashboard.
=> [app_dart] Update flaky issue bot to link to build dashboard for overviews

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart
Quick fix. Cocoon's scheduler wasn't passing anything so it was using the starlark defaults (which for presubmit can be incorrect on release branches)
=> [scheduler] Pass git_branch

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
The new policy requires two member reviews for not member PRs and a
single member review for member PRs.
Bug: https://github.com/flutter/flutter/issues/81710
[Discord]: …
=> Update review policy used by auto-submit bot.

cloud_build/deploy.sh
The issue was the staging version running with prod keys.
Removing this logic to make rollbacks quicker.
=> [cloudbuild] Remove unnecessary stop logic

release_dashboard/lib/main.dart, release_dashboard/lib/services/conductor.dart, release_dashboard/lib/services/dev_local_conductor.dart, release_dashboard/lib/services/local_conductor.dart, release_dashboard/lib/services/release_dashboard_next_context.dart, release_dashboard/lib/services/release_dashboard_start_context.dart, release_dashboard/lib/state/status_state.dart, release_dashboard/lib/widgets/progression.dart, release_dashboard/test/fakes/fake_next_context.dart, release_dashboard/test/fakes/fake_start_context.dart, release_dashboard/test/widgets/progression_test.dart
Made a common `dialogPrompt` widget that would listen to the prompts returned by `StartContext` and `NextContext`. Whenever there is a prompt returned, the release dashboard displays a `dialogPrompt` with the prompt message as its content, and execute a completer to fulfill `StartContext` and `NextContext`'s prompts.
Main Issues:
Screen Recording:
https://user-images.githubusercontent.com/20194490/145631743-04ce05d2-c65d-436c-ba01-9511f769e54c.mov …
=> [release_dashboard] Add dialogPrompt to receive prompt from the core

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests_queries.dart
This is a follow up of https://github.com/flutter/cocoon/pull/1434, by adding the `authorAssociation` field.
https://github.com/flutter/flutter/issues/95023
=> Add authorAssociation field in github graph query for merge bot

app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/request_handlers/github_webhook_test.dart
These are ways that people create tests, particularly for things the analyzer can't currently cover or to add a new/update an existing test harness.
=> Accept dev/bots/test.dart and analyze.dart as tests

app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/request_handlers/github_webhook_test.dart
Enables the automatic test exception for changes that can easily be determined to be comment-only, which is currently enabled for flutter/plugins and flutter/packages, for flutter/flutter as well.
=> Enable the comment-only exemption for flutter/flutter

app_dart/lib/src/request_handlers/push_build_status_to_github.dart
If not specified, commit will use `master` by default. However, for engine repo, we need to use `main`.
This fixes: https://github.com/flutter/flutter/issues/94483
=> Specify commit branch explicitly in pushing build status to GitHub API

app_dart/lib/src/service/bigquery.dart
Flake bot should work on builders in master branch. This PR skips `dev` and `stable`.
Related: https://github.com/flutter/flutter/issues/96074
=> Skip release builders in flake bot

app_dart/lib/src/request_handlers/flaky_handler_utils.dart, app_dart/lib/src/service/bigquery.dart, app_dart/test/request_handlers/deflake_flaky_builders_test_data.dart
This fixes: https://github.com/flutter/flutter/issues/96303 to use only recent staging builds when deflaking a test.
This PR also updates the reference link to check the flake status of a test: instead of pointing to the prod builds, the staging builds should be used and are recently available. ([example](https://data.corp.google.com/sites/flutter_infra_metrics_datasite/flutter_check_test_flakiness_status_dashboard/?p=BUILDER_NAME:%22Mac%20module_test_ios%22))
=> Fix deflake query and reference builds link

app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/lib/src/service/config.dart, app_dart/test/request_handlers/github_webhook_test.dart
The message posted when a PR is automatically retargetted to the default
branch used a variable for the original target, but incorrectly still
hard-coded "master" as the default brach name. This means that the
message is wrong, and is particularly confusing for the (currently
common, as repos are being transitioned) case where the bot is switching
a PR from 'master' to 'main', as what it actually says is that the PR
wasn't opened against 'master' so is being switched to 'master', but if
that's not correct it can be switched back to 'master' again.
This fixes the message to get the actual default branch for the
repository, rather than assuming 'master'. …
=> Fix message when retargetting to default branch

app_dart/lib/src/service/config.dart
Using cloud service account allows easier impersonation and debugging.
=> Use cloud service account for FRoB.

dashboard/lib/service/appengine_cocoon.dart
This is processing ~200 KB of data every 30 seconds. It would speed up the app a bit to use an isolate for processing this data instead.
=> [dashboard] Process CommitStatus in isolate

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/lib/src/request_handlers/check_for_waiting_pull_requests_queries.dart, app_dart/pubspec.lock, app_dart/pubspec.yaml, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart, app_dart/test/src/utilities/mocks.mocks.dart
https://github.com/flutter/flutter/issues/94592
=> Merge a clean revert without waiting for checks

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
This fixes https://github.com/flutter/flutter/issues/96478.
Switching the order of base and head commit (ref: https://docs.github.com/en/rest/reference/commits#compare-two-commits)
=> Fix PR merge bot when checking if a clean revert happens

app_dart/lib/src/service/scheduler.dart, app_dart/test/service/scheduler_test.dart
https://github.com/flutter/flutter/issues/96501
This will make it easier to validate release branch PRs before submitting by running everything.
=> [scheduler] Ignore runIf on release branches

app_dart/cron.yaml, app_dart/lib/src/request_handlers/push_gold_status_to_github.dart, app_dart/lib/src/service/config.dart, app_dart/test/request_handlers/push_gold_status_to_github_test.dart, app_dart/test/service/config_test.dart, app_dart/test/src/datastore/fake_config.dart, app_dart/test/src/datastore/fake_datastore.dart
Relanding https://github.com/flutter/cocoon/pull/1505
Was reverted in https://github.com/flutter/cocoon/pull/1541
The entire original PR is in the first commit. All subsequent commits are the additional changes in the relanding.
The original PR was reverted because the GraphQL query was broken:
```
OperationException(
linkException: null,
graphqlErrors: [
GraphQLError(message: Variable $sRepoOwner is used by ChecksForPullRequest but not declared, locations: [ErrorLocation(line: 2, column: 21)], path: [query ChecksForPullRequest, repository, owner], extensions: {code: variableNotDefined, variableName: sRepoOwner}),
GraphQLError(message: Variable $sRepoName is used by ChecksForPullRequest but not declared, locations: [ErrorLocation(line: 2, column: 40)], path: [query ChecksForPullRequest, …
```
=> Reland "[web] Add the flutter-gold check in web engine PRs"

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/lib/src/request_handlers/check_for_waiting_pull_requests_queries.dart, app_dart/lib/src/request_handlers/query_github_graphql.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
- GitHub limits GraphQL queries to <10 seconds
- flutter/flutter has grown the number of contributors it receives, and the endpoint is timing out very frequently
- Simplify some of the operations in the GraphQL code to the bare minimum of what Cocoon needs
- Remove check runs and instead rely on the single checksuite conclusion (fixing a bug where we only checked the first 100 check runs)
https://github.com/flutter/flutter/issues/96503
Fixes https://github.com/flutter/flutter/issues/96540
- Remove cirrus graphql and rely on pulling all check suite conclusions
=> [app_dart] Speed up autosubmit bot graphql queries

app_dart/lib/src/foundation/utils.dart
- GitHub is taking longer to propagate to the CDN. Instead of doing 200ms, 400ms delays, we should do 3s, 6s to give the system more time to propagate
- Additionally, they're no longer reporting these issues as 500s, but as 404s
Fixes https://github.com/flutter/flutter/issues/96503
=> [app_dart] Extend backoff for github file content

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
This a quick fix to get deploys working again. I missed this in my production test as no PRs got submitted.
https://github.com/flutter/flutter/issues/96836
I want to switch these tests over to using the returned JSON to prevent issues like this from landing. I have a bit more work optimizing this query.
=> [app_dart] Fix cast expansion from dynamic

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests_queries.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
These are more realistic values, and are quick fixes to the timeouts.
According to GitHub, reducing page size from 100 to 20 on the PRs would result in a speed up of a factor of 5 (even when there isn't extra data).
https://github.com/flutter/flutter/issues/96836
If this doesn't fix timeout issues, we'll need to split this query into smaller parts.
=> [app_dart] Shrink auto submission graphql query pagination

app_dart/bin/server.dart, app_dart/lib/src/request_handlers/push_build_status_to_github.dart, app_dart/lib/src/service/build_status_provider.dart, app_dart/lib/src/service/datastore.dart, app_dart/test/request_handlers/push_build_status_to_github_test.dart, app_dart/test/src/service/fake_build_status_provider.dart
Fixes https://github.com/flutter/flutter/issues/90569
https://github.com/flutter/flutter/issues/94522 - Enabling this to unify more of the logic in Cocoon
https://github.com/flutter/flutter/issues/94483 - More state in Cocoon makes it easier to audit why issues happen in the tree state
Reverts https://github.com/flutter/cocoon/pull/1252
=> [app_dart] Move tree status check to be based on datastore algorithm

device_doctor/lib/src/ios_device.dart, device_doctor/lib/src/utils.dart, device_doctor/test/src/ios_device_test.dart
This adds the device provisioning profile health check for ios device. If the device on the test bed does not exist in the provisioning profile, the bot will be quarantined.
https://github.com/flutter/flutter/issues/95144
=> Add device provisioning profile health check for ios devices

app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart, app_dart/test/request_handlers/file_flaky_issue_and_pr_test.dart
The a builder is already `bringup: true`, it means there is a tracking issue (either open or recently closed). For either case, there is no need to create a new bug.
A deflake PR has been skipped for this case, and this PR skips issue creation as well.
https://github.com/flutter/flutter/issues/96799
=> Skip filing a new issue when the builder is bringup: true

app_dart/bin/server.dart, app_dart/lib/cocoon_service.dart, app_dart/lib/src/request_handlers/check_flaky_builders.dart, app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart, app_dart/lib/src/request_handlers/flaky_handler_utils.dart, app_dart/lib/src/service/bigquery.dart, app_dart/test/request_handlers/check_flaky_builders_test.dart, app_dart/test/request_handlers/check_flaky_builders_test_data.dart, app_dart/test/request_handlers/file_flaky_issue_and_pr_test.dart
Existing workflow is like:
1) flake bot file a flaky bug & deflake the builder
2) bug is closed due to a fix or decreased flake number
3) flake bot will file a new flaky bug still based on prod runs of this builder (INCORRECT)
This PR does:
1) file a new flaky bug based on staging runs (if there exists any flake)
2) create sharable function `fileFlakyIssue` in utils so different APIs can access
3) rename `deflake_flaky_builders` to `check_flaky_builders`.
https://github.com/flutter/flutter/issues/96799
=> File flaky bug for `bringup:true` builders if no open tracking bug

app_dart/lib/src/request_handlers/push_gold_status_to_github.dart, app_dart/test/request_handlers/push_gold_status_to_github_test.dart
The `flutter-gold` check in engine PRs is turning green before the author triages the new screenshots.
Example:
* **PR**: https://github.com/flutter/engine/pull/31024
* **Gold triage**: https://flutter-engine-gold.skia.org/cl/github/31024
The issue is that we are sending the request to the wrong host. This PR fixes it so that we send status requests to the appropriate host on each repo.
This PR also does few modifications to log messages for better readability.
=> Use the correct Gold host when checking status for engine PRs

device_doctor/lib/src/ios_device.dart, device_doctor/test/src/ios_device_test.dart
Adds ios battery health check. The allowed min battery level is 15 (100 scale).
Related issue: https://github.com/flutter/flutter/issues/97120, https://github.com/flutter/flutter/issues/96832
=> Add devicelab ios battery check

app_dart/lib/src/request_handlers/github_webhook.dart, app_dart/test/request_handlers/github_webhook_test.dart
https://github.com/flutter/flutter/pull/97175 isn't flagged as needing tests because hit_test.dart matches the test pattern. Add an exception.
=> ensure hit_test.dart needs tests

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart
Add additional fields to the user_data section when creating build
requests. This will allow us to process the pubsub messages generated to
apply updates to task status.
Fixes #97392.
[test-exempt]: …
=> Add branch, sha, and builder name to buildrequest.

app_dart/cron.yaml
The API has been recently updated, and this PR updates the cron job.
https://github.com/flutter/flutter/issues/96799
=> Update cron job for `check flaky builders`

app_dart/bin/server.dart, app_dart/lib/cocoon_service.dart, app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart, app_dart/lib/src/request_handlers/presubmit_luci_subscription.dart, app_dart/lib/src/request_handlers/scheduler/request_subscription.dart, app_dart/lib/src/request_handling/pubsub_authentication.dart, app_dart/lib/src/request_handling/subscription_handler.dart, app_dart/lib/src/service/config.dart, app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart, app_dart/test/request_handlers/presubmit_luci_subscription_test.dart, app_dart/test/request_handling/pubsub_authentication_test.dart
This is a quick fix to make writing subscriptions easier. I fell into this when I used the wrong auth for testing the scheduler batch request subscription.
- Default `SubscriptionHandler` to use the `PubsubAuthenticationProvider`
- Rename `LuciPubsubAuthenticationProvider` to `PubsubAuthenticationProvider` and fix related names and docs
https://github.com/flutter/flutter/issues/86948 - Enabling pubsub in Cocoon
=> [app_dart] Generalize pubsub authentication

app_dart/lib/src/request_handlers/flaky_handler_utils.dart, app_dart/test/request_handlers/check_flaky_builders_test.dart, app_dart/test/request_handlers/check_flaky_builders_test_data.dart, app_dart/test/request_handlers/file_flaky_issue_and_pr_test_data.dart
The current flake bot files flaky bugs for two scenarios:
1) Prod builders: if any one becomes flaky and there is no existing issue to track
2) Staging builders (bringup: true): if any one hit a flake and there is no open issue to track/ there is an obsolete closed issue
This PR fixes the logic for 2). By injecting the `bringup` property, corresponding bugs will be filed accordingly.
Fixes: https://github.com/flutter/flutter/issues/97731
=> Inject bringup to distinguish bugs between staging and prod pools

dashboard/lib/logic/qualified_task.dart, dashboard/test/widgets/task_grid_test.dart
Tasks with `scheduler:cocoon` and `scheduler:luci` are effectively the same. They are managed by the ci.yaml tooling, but change their triggering policy and results processing.
After starting the migration, there's a few issues that shouldn't show:
https://flutter-dashboard.appspot.com/#/build?repo=cocoon&branch=master
Instead, these duplicate columns shouldn't exist.
https://github.com/flutter/flutter/issues/92300 - Ensure a smooth migration (no disruption in the dashboard)
=> [dashboard] Merge columns for luci and cocoon tasks

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/lib/src/service/config.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
Dependabot uses the author association instead of login to identify the
author. This changes explicitly checks for dependabot PRs.
=> Add autosubmit bot support for dependabot.

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/lib/src/service/config.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
Turns out that author=dependabot is the correct check as
authorAssociation is "CONTRIBUTOR" for dependabot PRs.
=> Move dependabot validation to use author.

app_dart/lib/src/request_handlers/refresh_chromebot_status.dart, app_dart/lib/src/request_handlers/reset_prod_task.dart, app_dart/lib/src/service/config.dart, app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart, app_dart/test/src/utilities/entity_generators.dart
Engine/plugins/packages/cocoon repos are current supported in https://flutter-dashboard.appspot.com/#/build?repo=engine, however the auto retry logic when test fails is using default `flutter` repo and empty properties. 
This PR fixes the auto retry in other repos.
1) injects repo/properties when auto retry
2) moves `defaultProperties` to Config, and renames to `engineDefaultProperties`.
3) adds test to validate the logic
4) refactors other unit tests a bit to make it more clear.
Fixes: https://github.com/flutter/flutter/issues/98183
=> Fix auto retry in repositories other than `flutter/flutter

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/scheduler_test.dart, app_dart/test/src/service/fake_buildbucket.dart
This is required to preserve the cipdVersion across re-runs. When a try
run is first scheduled the cipdVersion is added as a tag. The rerun
collects the cipdVersion tag and pass it to the cipd_exe property.
Bug: https://github.com/flutter/flutter/issues/98472 …
=> Ensure retries with checkRunEvent include the cipdVersion.

app_dart/cron.yaml
Fixes: https://github.com/flutter/flutter/issues/98430 by shifting auto flake bot run from Mon. to Wed.
(will land this after Wed.)
=> Shift flake bot to run on Wed.

app_dart/lib/src/model/common/json_converters.dart, app_dart/lib/src/model/luci/push_message.dart, app_dart/lib/src/model/luci/push_message.g.dart, app_dart/test/model/push_message_test.dart, app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
Timestamp is expected to be in microseconds from LUCI.
This is affecting the plugins, cocoon, and packages build dashboards from showing an accurate time.
=> Fix push message not processing in microseconds

app_dart/lib/src/model/appengine/task.dart, app_dart/test/model/task_test.dart
Fixes https://github.com/flutter/flutter/issues/98759
Fixes https://github.com/flutter/flutter/issues/98758
Issue was `completed_ts` was omitted for in progress or scheduled build updates. Datastore won't allow null, so we need to default it to 0.
=> [app_dart] Default null timestamps to 0

app_dart/lib/src/request_handlers/reset_try_task.dart
This is a follow up of https://github.com/flutter/cocoon/pull/1617.
Updated to use `request.uri.queryParameters` instead of `json` data, as we are using `get` request to inject parameters.
cl/430741794 re doc update.
=> Update builders value when reset_try_task with specified list

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
Fixes: https://github.com/flutter/flutter/issues/99077
Based on https://github.com/flutter/flutter/issues/99077#issuecomment-1051314902, the first build of the cirrus GraphQL query will always reflect the latest CI status of the PR.
This PR skips the unnecessary branch check, and directly uses the first build to check cirrus runs.
=> Skip branch check for cirrus CI tests

release_dashboard/analysis_options.yaml, test_utilities/pubspec.yaml
With dart lint enabled, problems view would list all problems, including the 3k dependency and syntax errors under release dashboard folder, which is cluttering the actual problems of the opened project (e.g. app_dart, dashboard etc.). This commit suppresses lint in release dashboard, so we have a cleaner view of the actual problems.
=> [release dashboard] suppress 3k errors in release dashboard to manifest the real ones

dashboard/lib/widgets/lattice.dart
Might not be the best approach, I am suppressing the left and right and movement from inner vertical scrollbar to fix https://github.com/flutter/flutter/issues/99418. After flutter upgrade, the tot version is currently throwing
https://github.com/flutter/flutter/issues/99418 and blocking other PRs from landing.
=> [dashboard] suppress overscroll notifications elided from inner vertical scrollbar

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart, app_dart/lib/src/request_handlers/refresh_cirrus_status.dart, app_dart/test/request_handlers/refresh_cirrus_status_test.dart
Tentative fix for https://github.com/flutter/flutter/issues/99306.
The cirrus id and test results are mixed to cause flake when checking cirrus results. This PR returns the first build results right after obtaining the cirrus GraphQL results.
=> Returns first cirrus build directly instead of a list

app_dart/lib/src/request_handlers/refresh_cirrus_status.dart
PR https://github.com/flutter/cocoon/pull/1632 has fixed the problem, but from the log it shows:
```
Cirrus searchBuild id for flutter/null, commit: null: 4515354469728256
```
This PR is a nit fix to inject the repo name and sha for easy triage in the future.
=> Inject repo name and sha in cirrus log

app_dart/lib/src/request_handlers/flaky_handler_utils.dart, app_dart/lib/src/request_handlers/update_existing_flaky_issues.dart, app_dart/test/request_handlers/update_existing_flaky_issues_test.dart, app_dart/test/request_handlers/update_existing_flaky_issues_test_data.dart
Fixes: https://github.com/flutter/flutter/issues/99442
This PR does:
1) update flaky bugs with both prod and staging stats when the builder is `bringup: true`
2) skip build number check, it is useful to present any available test results even we have limited number
3) update tests
=> Update flaky bugs with both prod and staging stats when `bringup: true`

app_dart/lib/src/model/ci_yaml/target.dart, app_dart/test/model/ci_yaml/target_test.dart
Add entry into $flutter/osx_sdk dict, from runtime_versions value in
ci.yaml.
Bug:99698 …
=> Set $flutter/osx_sdk to include runtime_versions

cloud_build/deploy.sh
Cloud build has recently been failing as we added auto_submit service, and there can be versions stored there. This allows each service to have ~5 versions (we're allotted 30 total). Doubling the limit here to prevent the timeouts.
=> [cloudbuild] Allow for 20 versions

app_dart/lib/src/service/luci_build_service.dart, app_dart/test/service/luci_build_service_test.dart
This is to fix the attempts on Cocoon scheduled tasks.
https://github.com/flutter/flutter/issues/92300
=> [scheduler] Increment task attempts and reset status on reruns

app_dart/bin/server.dart, app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart, app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
https://github.com/flutter/flutter/issues/92300
This is dependent on https://github.com/flutter/cocoon/pull/1656 (the test will pass after it lands)
=> [scheduler] Add auto-retries on pubsub notifications

app_dart/lib/src/model/ci_yaml/target.dart, app_dart/test/model/ci_yaml/target_test.dart
The evaluation of properties is failing because int string are auto
converted to int.
Bug: https://github.com/flutter/flutter/issues/98529
=> Fix .ci.yaml properties evaluation.

device_doctor/lib/src/ios_device.dart, device_doctor/lib/src/utils.dart, device_doctor/test/src/ios_device_test.dart, device_doctor/test/src/utils_test.dart
M1 bots are installing some binaries to /opt/homebrew/bin, which is not visible to `swarming` by default. This PR checks that path to make sure binaries can run successfully, like `ideviceinstaller`.
Potentially solve: https://github.com/flutter/flutter/issues/98426#issuecomment-1063513050
=> [device doctor] Use homebrew bin
