app_flutter/android/app/src/main/AndroidManifest.xml
app_flutter/lib/main.dart
app_flutter/lib/service/appengine_cocoon.dart
app_flutter/lib/status_grid.dart
app_flutter/lib/task_box.dart
app_flutter/test/commit_box_test.dart
app_flutter/test/status_grid_test.dart
app_flutter/test/task_box_test.dart

Some extra work was done to make this app work in release mode to show live data. Overall, most of the work is getting StatusGrid to correctly display a `List<CommitStatus>`.
- Renamed ResultBox widget to TaskBox (Task is the proto it takes in)
- Added permission on Android to access the internet (to fetch production data)
- Learned more about `tester.takeException()` , so updated `commit_box_test` to take advantage of this newfound knowledge

StatusGrid using CocoonService

---

agent/bin/ci.sh
agent/bin/smoke_test.sh

* `ci.sh` starts the agent.
* `smoke_test.sh` validates the runtime environment setup.

[Agent] Add helper scripts

---

app_flutter/web/index.html

Copied over from https://github.com/flutter/cocoon/blob/master/app/web/build.html
Implements https://github.com/flutter/cocoon/pull/489 without breaking Android or iOS

index.html updates for Google Analytics and TV refresh

---

app_dart/lib/src/request_handling/authentication.dart

Looks like a new authentication method was added

Update authentication.dart overview documentation

---

agent/bin/ci.sh
agent/bin/smoke_test.sh

Also add `pub get` before a smoke test.

[Agent] Disown the agent process.

---

.cirrus.yml
app_flutter/lib/service/google_authentication.dart

I noticed some formatting issues make it into master and then get committed in follow up PRs. This will have cirrus fail if there's formatting issues.

Cirrus checks Flutter App formatting

---

devicelab/agent_manager.ps1

This is a script the will be running on a cron job every 5 minutes to
validate the agent is running on windows machines and restart it if
necessary. We will be implementing similar scripts for Linux and Mac
machines.

[devicelab][windows] agent manager for windows.

---

app_flutter/lib/service/appengine_cocoon.dart
app_flutter/lib/task_helper.dart
app_flutter/test/service/appengine_cocoon_test.dart

The `Task` key has been null for the flutter app. This makes it non null and uses it correctly in the places it needs to be.
- Updated test for building a CommitStatus to include the task key
- Fix authentication and v1 parity is met

Use Task Key

---

test_utilities/bin/dart_test_runner.sh
test_utilities/bin/flutter_test_runner.sh
test_utilities/bin/global_test_runner.dart
test_utilities/bin/prepare_environment.sh
test_utilities/pubspec.yaml
tests.yaml

We need new scripts that encapsulates the commands cirrus was running
for tests in this repo.
https://github.com/flutter/flutter/issues/43348

Runner scripts to run cocoon tests on luci.

---

agent/lib/src/adb.dart
agent/lib/src/health.dart
agent/lib/src/utils.dart

Adds a NoOp class for device discovery to bypass all the
device checks on VMs. This will be used to create several VMs and start
moving tests.
https://github.com/flutter/flutter/issues/27917

Add linux VM support to devicelab.

---

app_dart/dev/deploy.dart
app_flutter/lib/commit_box.dart
app_flutter/lib/status_grid.dart
app_flutter/test/commit_box_test.dart
app_flutter/test/status_grid_test.dart

CanvasKit achieves 60 fps for the build dashboard.
`deploy.dart` - Added profile mode flag, use skia
`app_flutter` - `CommitBox` shows author initial instead of image, `StatusGrid` reverted back to `GridView` implementation (reverting https://github.com/flutter/cocoon/pull/518)
- ~On HTTPS, an unsecured script (font) is loaded. This blocks running the rest of the Flutter app until it is allowed to load.~ - Fixed in https://github.com/flutter/engine/pull/14086
Demo: https://testchillers-dot-flutter-dashboard.appspot.com/build.html#/

app_flutter uses CanvasKit

---

app_dart/lib/src/request_handlers/push_build_status_to_github.dart
app_dart/lib/src/request_handlers/push_engine_status_to_github.dart
app_dart/lib/src/request_handlers/refresh_cirrus_status.dart
app_dart/lib/src/request_handlers/refresh_github_commits.dart
app_dart/pubspec.yaml
app_dart/test/request_handlers/github_webhook_test.dart
app_dart/test/request_handlers/luci_status_test.dart
app_dart/test/request_handlers/refresh_github_commits_test.dart

This is required to start running test on luci because the analyzer
returns non 0 exit code if there are info messages and/or warnings.

Fix analyzer warning for app_dart.

---

README.md
app_dart/dev/deploy.dart

Since there's still some CanvasKit issues to sort out, I am just going to add a use skia flag. This allows me to test CanvasKit while not blocking future updates.

Deploy script useSkia flag

---

app_dart/bin/server.dart
app_dart/lib/src/model/appengine/agent.dart

This PR solves https://github.com/flutter/flutter/issues/46239

Disable index for Agent HealthDetails property

---

agent/lib/src/commands/ci.dart
agent/lib/src/utils.dart

Dart Process do not expand environment variables. We need to pass the
value from the env variable to the command but do not log it.
https://github.com/flutter/flutter/issues/43125

Fix unlock command.

---

app_dart/lib/src/request_handlers/github_webhook.dart
app_dart/test/request_handlers/github_webhook_test.dart

Reverts flutter/cocoon#572 we are getting 500s for cocoon and engine tasks. Reverting while we check what the problem is.

Revert "Run presubmit tests for cocoon and engine automatically on luci."

---

agent/lib/src/health.dart
agent/pubspec.lock
agent/pubspec.yaml
agent/test/src/health_test.dart

Fix flutter/flutter#45760.
Fix flutter/flutter#45729.
Tested manually and with unit tests.

[agent] Remove Xcode derived data directory each time.

---

mobile/lib/src/service.dart

This is all I had to do to get the mobile app working. Figured I would share.

Update api root in mobile

---

.cirrus.yml

Takes this change for LUCI https://github.com/flutter/cocoon/pull/588 and puts it on Cirrus too

print file with format issues on cirrus

---

app_dart/lib/src/request_handlers/append_log.dart
app_dart/test/request_handlers/append_log_test.dart

Will look into this more after the winter break. This gets master in a safe place :)
Fixes https://github.com/flutter/flutter/issues/47453

Revert testable append log

---

app_dart/lib/src/model/appengine/benchmark_data.dart
app_dart/lib/src/request_handlers/append_log.dart
app_dart/lib/src/request_handlers/authorize_agent.dart
app_dart/lib/src/request_handlers/get_timeseries_history.dart
app_dart/lib/src/request_handling/authentication.dart
app_dart/lib/src/request_handling/static_file_handler.dart

This partly fixes https://github.com/flutter/flutter/issues/47544.

Fix ambiguous errors in app_dart Luci Test

---

app_dart/lib/src/request_handlers/github_webhook.dart
app_dart/test/request_handlers/github_webhook_test.dart

There is no goldens.version file anymore. Just cleaning up. :)

Removing old code related to goldens.version file

---

test_utilities/bin/flutter_test_runner.sh

With https://github.com/flutter/flutter/issues/45711 closed this should work.

LUCI run flutter analyze

---

app_dart/lib/src/datastore/cocoon_config.dart
app_dart/lib/src/request_handlers/github_webhook.dart

Updated the golden related messaging the Flutter Github Bot provides. Removed the out of date short link to the previous implementation's data store.

Updated golden-related comments

---

README.md
app_dart/dev/deploy.dart
app_flutter/lib/sign_in_button.dart
app_flutter/lib/task_box.dart

The issue was Angular Dart overriding the Flutter asset files.
Updates a few widgets to look better on CanvasKit, and removes option to choose CanvasKit in the deploy script.
https://testchillers1-dot-flutter-dashboard.appspot.com

Use CanvasKit

---

agent/lib/src/runner.dart

This PR fixes https://github.com/flutter/flutter/issues/44924

Save Agent ID in task log

---

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart

Fixes obervations in https://github.com/flutter/engine/pull/15935 
/cc @rmistry

fix pending

---

app_dart/lib/src/request_handlers/github_webhook.dart
app_dart/test/request_handlers/github_webhook_test.dart

A series of changes led to us:
- Scheduling PRs on every action to the PR, including actions that have no impact on source code
- Not scheduling PRs where source code changed
- Not cancelling builds when source code changed
Fixes that and updates tests.

fix PR scheduling

---

app_dart/dev/deploy.dart

Noticed this while trying to deploy today. This makes it more accurate for the logic it is using.

Change deploy script update Flutter message

---

app_dart/lib/src/request_handlers/reset_devicelab_task.dart
app_dart/test/request_handlers/reset_devicelab_task_test.dart

This PR fixes issue: https://github.com/flutter/flutter/issues/44780

Disable attempts increase when resetting devicelab task

---

app_dart/lib/src/datastore/cocoon_config.dart
app_dart/lib/src/request_handlers/refresh_cirrus_status.dart
app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
app_dart/test/request_handlers/refresh_cirrus_status_test.dart
app_dart/test/src/datastore/fake_cocoon_config.dart
app_dart/test/src/service/fake_graphql_client.dart

This PR solved issue https://github.com/flutter/flutter/issues/50293

Switch cirrus status calculation from Github check-runs to Cirrus API

---

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
app_dart/lib/src/request_handlers/check_for_waiting_pull_requests_queries.dart
app_dart/lib/src/request_handlers/refresh_cirrus_status.dart
app_dart/lib/src/request_handlers/refresh_cirrus_status_queries.dart
app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
app_dart/test/src/service/fake_cirrus_graphql_client.dart

Thus is a follow up PR solving issue: https://github.com/flutter/flutter/issues/50293

Use cirrus api in waiting for tree to go green logic

---

app_dart/lib/src/request_handlers/refresh_cirrus_status.dart

Update number of commits to check for cirrus status

---

agent/lib/src/utils.dart

If a subprocess fails quickly, an exception may be thrown before its output can be echoed to the logger. This PR drains the subprocess output before checking the exit code.

Drain subprocess stdout and stderr before throwing an exception

---

app_dart/lib/src/request_handlers/refresh_github_commits.dart
app_dart/lib/src/service/github_service.dart

This is a follow-up PR of https://github.com/flutter/cocoon/pull/658, to fix some remaining issues.

Fix timezone and dir for branch_regexps.txt - branching support

---

app_dart/lib/src/model/appengine/github_gold_status_update.dart
app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
app_dart/lib/src/service/datastore.dart
app_dart/test/request_handlers/push_gold_status_to_github_test.dart

#615 added a gold status check to framework PRs. The query to the datastore was expecting a `repository` property that was not included in the class. I have added this property to the class and tests. I also added additional logging.

Adjustment to Gold Check

---

app_dart/lib/src/model/appengine/github_gold_status_update.dart
app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
app_dart/test/request_handlers/push_gold_status_to_github_test.dart

Patches a few bugs found from deployment
- `in_progress` is not the correct status to push to GitHub, `pending` is.
- The cirrus status checks need to be cleared out in between pull requests
- There was an early return that should have bee an continue

Correcting GitHub Status for Gold check

---

app_flutter/lib/commit_box.dart
app_flutter/pubspec.lock
app_flutter/pubspec.yaml
app_flutter/test/commit_box_test.dart
app_flutter/test/status_grid_test.dart

https://github.com/flutter/flutter/issues/52147

Switch Image.network to CachedNetworkImage to fix tests on dev branch

---

app_dart/lib/src/request_handlers/get_build_status.dart
app_dart/lib/src/service/build_status_provider.dart
app_dart/test/service/build_status_provider_test.dart
app_dart/test/src/datastore/fake_datastore.dart
app_dart/test/src/service/fake_build_status_provider.dart

This is to calculate tree status based on branches.
Related issue:  https://github.com/flutter/flutter/issues/51807

Support branch for tree build status

---

app_dart/bin/server.dart
app_dart/lib/cocoon_service.dart
app_dart/lib/src/datastore/cocoon_config.dart
app_dart/lib/src/request_handlers/get_branches.dart
app_dart/lib/src/request_handlers/refresh_github_commits.dart
app_dart/lib/src/request_handlers/utils.dart
app_dart/test/request_handlers/get_branches_test.dart
app_dart/test/request_handlers/refresh_github_commits_test.dart
app_dart/test/request_handlers/utils_test.dart
app_dart/test/src/datastore/fake_cocoon_config.dart

This is to support dashboard to list branches by returning the available matched ones.
Part of https://github.com/flutter/flutter/issues/51807

Create /api/get-branches to support frontend listing branches

---

app_flutter/lib/index_page.dart
app_flutter/lib/navigation_drawer.dart
app_flutter/test/index_page_test.dart
app_flutter/test/navigation_drawer_test.dart

Fixes https://github.com/flutter/flutter/issues/52557

Add skia perf links to Cocoon home page and sidebar

---

app_dart/lib/src/request_handlers/get_timeseries_history.dart
app_dart/lib/src/service/datastore.dart

This fixes: https://github.com/flutter/flutter/issues/52692

Workaround fix for performance benchmarks  dashboard with limited data

---

app_dart/lib/src/request_handlers/refresh_github_commits.dart
app_dart/test/request_handlers/refresh_github_commits_test.dart

This solves https://github.com/flutter/flutter/issues/52443

Add branch to commit key

---

app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
app_dart/test/request_handlers/push_gold_status_to_github_test.dart

This PR changes the default branch name from `master` to `pull/${pr.name}`.

Update branch name for gold status

---

README.md
app_flutter/pubspec.lock

Update README to be clearer.

---

app_flutter/lib/agent_dashboard_page.dart
app_flutter/lib/build_dashboard_page.dart
app_flutter/lib/index_page.dart
app_flutter/lib/main.dart
app_flutter/lib/navigation_drawer.dart
app_flutter/lib/sign_in_button.dart
app_flutter/pubspec.lock
app_flutter/test/build_dashboard_page_test.dart
app_flutter/test/index_page_test.dart
app_flutter/test/navigation_drawer_test.dart
app_flutter/test/sign_in_button_test.dart

...and lots of random cleanup, including:
* Have the Drawer automatically figure out what page is up
* Test that the dashboard and the index page buttons match
* Prettier logo in drawer
* Show about/licenses

Bring the index page more in line with the Material spec.

---

app_flutter/lib/agent_dashboard_page.dart
app_flutter/lib/agent_health_details.dart
app_flutter/lib/agent_list.dart
app_flutter/lib/agent_tile.dart
app_flutter/lib/build_dashboard_page.dart
app_flutter/lib/canvaskit_widget.dart
app_flutter/lib/commit_box.dart
app_flutter/lib/index_page.dart
app_flutter/lib/navigation_drawer.dart
app_flutter/lib/task_attempt_summary.dart
app_flutter/lib/task_icon.dart

Just mechanically applying best practice here, nothing major.

Add key argumnts to every widget

---

app_flutter/lib/build_dashboard_page.dart

I believe after this, https://github.com/flutter/tests/pull/26 can run the tests.

const to fix flutter/tests analyze issue

---

test_utilities/bin/flutter_test_runner.bat
test_utilities/bin/flutter_test_runner.sh

This is for getting Cocoon added to flutter/tests
Manual run on Windows 10 showed this running all the commands and all tests passing

Add Windows version of flutter_runner_test_runner script

---

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart

This fixes https://github.com/flutter/flutter/issues/53124

Fix branch issue for API check_for_waiting_pull_requests

---

app_flutter/android/.gitignore
app_flutter/android/app/build.gradle
app_flutter/android/app/src/main/AndroidManifest.xml
app_flutter/android/app/src/main/kotlin/com/example/app_flutter/MainActivity.kt
app_flutter/android/app/src/main/res/values/styles.xml
app_flutter/android/build.gradle
app_flutter/android/gradle.properties
app_flutter/android/gradle/wrapper/gradle-wrapper.properties

I deleted the android directory and ran `flutter create .` to recreate it.

Update the Android files to support AndroidX.

---

app_dart/lib/src/request_handlers/refresh_chromebot_status.dart
app_dart/lib/src/service/luci.dart
app_dart/test/request_handlers/refresh_chromebot_status_test.dart

This is part of https://github.com/flutter/flutter/issues/51807

Support branching for refresh chromebot status

---

app_flutter/lib/agent_dashboard_page.dart
app_flutter/lib/app_bar.dart
app_flutter/lib/build_dashboard_page.dart
app_flutter/lib/index_page.dart

That way we don't need to keep setting the color on each page.

Factor out the AppBar widget

---

app_flutter/lib/header_text.dart
app_flutter/lib/index_page.dart

As requested in previous PR review.

HeaderText widget

---

app_flutter/lib/agent_dashboard_page.dart
app_flutter/lib/state/agent.dart
app_flutter/pubspec.lock
app_flutter/test/state/agent_test.dart
app_flutter/test/utils/fake_agent_state.dart

This means we don't have to explicitly tell it to start fetching.

Make AgentState automatically start fetching data when listened.

---

app_dart/lib/src/datastore/cocoon_config.dart
app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
app_dart/test/request_handlers/push_gold_status_to_github_test.dart
app_dart/test/src/datastore/fake_cocoon_config.dart

This change adds a gold status check to PRs on branches other than master.
It will also provide different messaging for these PRs if a change is found to explain why a divergence between the branch and master may have occurred across golden files.

Gold status updates for branching

---

app_flutter/lib/build_dashboard_page.dart
app_flutter/lib/state/agent.dart
app_flutter/lib/state/flutter_build.dart
app_flutter/test/state/flutter_build_test.dart
app_flutter/test/status_grid_test.dart
app_flutter/test/utils/fake_flutter_build.dart

...rather than having an explicit init step

Make FlutterBuildStatus autotrigger on listen

---

app_flutter/lib/service/dev_cocoon.dart
app_flutter/test/status_grid_test.dart

It introduces the risk of flakes.

Tests should not have randomness.

---

app_flutter/lib/agent_dashboard_page.dart
app_flutter/lib/commit_box.dart
app_flutter/lib/progress_button.dart
app_flutter/lib/task_attempt_summary.dart
app_flutter/lib/task_box.dart
app_flutter/pubspec.lock
app_flutter/pubspec.yaml
app_flutter/test/task_attempt_summary_test.dart
app_flutter/test/task_box_test.dart

Also, replace the ProgressButton widget with our own that knows how to
size correctly as a RaisedButton.

Clean up the TaskBox UI.

---

app_dart/bin/server.dart
app_dart/lib/src/request_handlers/get_build_status.dart
app_dart/lib/src/request_handlers/get_status.dart
app_dart/lib/src/request_handlers/push_build_status_to_github.dart
app_dart/lib/src/request_handlers/reserve_task.dart
app_dart/lib/src/service/access_token_provider.dart
app_dart/lib/src/service/build_status_provider.dart
app_dart/lib/src/service/buildbucket.dart
app_dart/lib/src/service/reservation_provider.dart
app_dart/lib/src/service/task_provider.dart
app_dart/test/request_handlers/get_status_test.dart
app_dart/test/request_handlers/push_build_status_to_github_test.dart
app_dart/test/request_handlers/reserve_task_test.dart
app_dart/test/service/build_status_provider_test.dart
app_dart/test/service/buildbucket_test.dart
app_dart/test/service/reservation_provider_test.dart
app_dart/test/service/task_provider_test.dart
app_dart/test/src/service/fake_build_status_provider.dart

Bugs:
flutter/flutter#42524
flutter/flutter#43112
flutter/flutter#49673
flutter/flutter#49672

Refactor reserve_task handler to use datastore service.

---

app_dart/lib/src/request_handlers/append_log.dart
app_dart/lib/src/request_handlers/authorize_agent.dart
app_dart/lib/src/request_handlers/create_agent.dart
app_dart/lib/src/request_handlers/get_benchmarks.dart
app_dart/lib/src/request_handlers/get_log.dart
app_dart/lib/src/request_handlers/get_timeseries_history.dart
app_dart/lib/src/request_handlers/push_engine_status_to_github.dart
app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
app_dart/lib/src/request_handlers/refresh_chromebot_status.dart
app_dart/lib/src/request_handlers/refresh_cirrus_status.dart
app_dart/lib/src/request_handlers/refresh_github_commits.dart
app_dart/lib/src/request_handlers/reset_devicelab_task.dart
app_dart/lib/src/request_handlers/update_agent_health.dart
app_dart/lib/src/request_handlers/update_agent_health_history.dart
app_dart/lib/src/request_handlers/update_benchmark_targets.dart
app_dart/lib/src/request_handlers/update_task_status.dart
app_dart/lib/src/request_handlers/update_timeseries.dart
app_dart/lib/src/request_handlers/vacuum-clean.dart

* Simplifies transactional code.
* Pass datastore parameters explicitly.
* Adds retries mechanism to all the handlers.
Bugs:
flutter/flutter#42524
flutter/flutter#43112
flutter/flutter#49673
flutter/flutter#49672

Refactor handlers to use service/datastore.

---

app_dart/lib/src/datastore/cocoon_config.dart
app_dart/lib/src/request_handlers/refresh_github_commits.dart
app_dart/lib/src/service/github_service.dart
app_dart/test/request_handlers/refresh_github_commits_test.dart
app_dart/test/src/datastore/fake_cocoon_config.dart
app_dart/test/src/service/fake_github_service.dart

This fixes: https://github.com/flutter/flutter/issues/53711

Refresh github commits of release branches

---

app_dart/lib/src/service/datastore.dart
app_dart/test/service/datastore_test.dart

https://github.com/flutter/flutter/issues/54298

Fix one off index calculation for datastore.

---

app_flutter/lib/agent_dashboard_page.dart
app_flutter/lib/build_dashboard_page.dart
app_flutter/lib/index_page.dart
app_flutter/lib/main.dart
app_flutter/lib/navigation_drawer.dart
app_flutter/lib/widgets/agent_health_details_bar.dart
app_flutter/lib/widgets/agent_list.dart
app_flutter/lib/widgets/agent_tile.dart
app_flutter/lib/widgets/app_bar.dart
app_flutter/lib/widgets/commit_box.dart

This is required to roll the latest Dart SDK which contains fixes for the prefer_const_constructors lint

[lint] fix prefer_const_constructors lint

---

app_flutter/lib/service/dev_cocoon.dart
app_flutter/test/service/dev_cocoon_test.dart

I got the maths wrong when writing this.

Tweak the names of the fake agents to avoid duplicates

---

app_dart/lib/src/datastore/cocoon_config.dart
app_dart/lib/src/foundation/utils.dart
app_dart/lib/src/request_handlers/github_webhook.dart
app_dart/lib/src/request_handlers/luci_status.dart
app_dart/lib/src/request_handlers/push_build_status_to_github.dart
app_dart/lib/src/request_handlers/push_engine_status_to_github.dart
app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
app_dart/lib/src/request_handlers/refresh_github_commits.dart
app_dart/lib/src/service/datastore.dart
app_dart/lib/src/service/github_service.dart
app_dart/pubspec.lock
app_dart/pubspec.yaml
app_dart/test/foundation/utils_test.dart
app_dart/test/request_handlers/github_webhook_test.dart
app_dart/test/request_handlers/luci_status_test.dart
app_dart/test/request_handlers/push_build_status_to_github_test.dart
app_dart/test/request_handlers/push_gold_status_to_github_test.dart
app_dart/test/request_handlers/refresh_cirrus_status_test.dart
app_dart/test/request_handlers/refresh_github_commits_test.dart
app_dart/test/src/datastore/fake_cocoon_config.dart
app_dart/test/src/service/fake_github_service.dart

This PR upgrades the github package to prepare the integration with https://github.com/liyuqian/metrics_center.
The github_webhook.dart is the most affected file in by this change, as the github package no longer exports PullRequestEvent. See https://github.com/SpinlockLabs/github.dart/issues/220
Bug: https://github.com/flutter/flutter/issues/51607

[app_dart] Upgrade the github package to 6.1.3

---

app_dart/lib/src/request_handling/static_file_handler.dart
app_dart/test/request_handling/static_file_handler_test.dart

Bug:
https://github.com/flutter/flutter/issues/54865

Fix related with null mimetype for .map files.

---

app_dart/lib/src/request_handlers/get_timeseries_history.dart
app_dart/lib/src/request_handlers/github_webhook.dart
app_dart/lib/src/request_handlers/push_build_status_to_github.dart
app_dart/lib/src/request_handlers/refresh_github_commits.dart
app_dart/lib/src/request_handlers/update_agent_health_history.dart
app_dart/lib/src/request_handlers/update_task_status.dart
app_dart/pubspec.lock
app_dart/pubspec.yaml

Bug:
https://github.com/flutter/flutter/issues/57256

Fix test failures caused by new version of flutter in beta channel.

---

app_dart/lib/src/datastore/cocoon_config.dart
app_dart/lib/src/request_handlers/github_webhook.dart

Bug: https://github.com/flutter/flutter/issues/56138

[app_dart] Adds a trigger for fuchsia_ctl builder

---

app_dart/lib/src/request_handlers/github_webhook.dart

Bug:
https://github.com/flutter/flutter/issues/57256

Remove todos and ignores from github webhook.

---

app/lib/benchmark/benchmark_card.html
app/lib/benchmark/benchmark_grid.html
app/lib/benchmark/benchmark_history.html
app/web/benchmarks.html
app/web/repository.html
app_flutter/web/index.html
licenses/check_licenses.dart

This PR removed html header check to fix html malformed issue on benchmark page.

[cocoon] Remove html header check

---

app_dart/lib/src/model/github/checks.dart
app_dart/lib/src/model/github/checks.g.dart
app_dart/test/model/github/checks_test.dart
app_dart/test/model/github/checks_test_data.dart

This model class will be required to retry individual tasks from github.
Bug:

Add CheckRunEvent model class.

---

app_dart/dev/branch_regexps.txt

fixes issue: https://github.com/flutter/flutter/issues/53706
/cc @jmagman

Remove unused branch v1.12.13-hotfixes

---

app_dart/lib/src/model/appengine/github_build_status_update.dart
app_dart/lib/src/request_handlers/push_build_status_to_github.dart
app_dart/lib/src/request_handlers/push_engine_status_to_github.dart
app_dart/lib/src/service/datastore.dart
app_dart/test/request_handlers/push_build_status_to_github_test.dart
app_dart/test/request_handlers/push_engine_status_to_github_test.dart
app_dart/test/src/datastore/fake_datastore.dart

This is to fix issue: https://github.com/flutter/flutter/issues/55377

[cocoon] Add timestamp for entity GithubBuildStatusUpdate

---

app_dart/lib/src/datastore/cocoon_config.dart
app_dart/test/datastore/cocoon_config_test.dart

Bug:
https://github.com/flutter/flutter/issues/59270

Fix return type for getRepoForBuilder and add tests.

---

app_dart/lib/src/service/github_status_service.dart
app_dart/test/service/github_status_service_test.dart

This is to prevent adding drone checks and have PRs waiting forever.
Bug:
https://github.com/flutter/flutter/issues/59526

Only add github status if builders exist in the configurations.

---

app_dart/README.md
app_dart/lib/src/request_handlers/luci_status.dart
app_dart/test/request_handlers/luci_status_test.dart
app_dart/test/src/utilities/push_message.dart

Bug:
https://github.com/flutter/flutter/issues/60304

Skip status updates that do not have a buildset tag.

---

app_dart/README.md
app_dart/lib/src/datastore/cocoon_config.dart
app_dart/lib/src/request_handlers/github_webhook.dart
app_dart/lib/src/request_handlers/push_build_status_to_github.dart
app_dart/lib/src/request_handlers/push_engine_status_to_github.dart
app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
app_dart/lib/src/request_handlers/refresh_github_commits.dart
app_dart/lib/src/service/github_status_service.dart
app_dart/pubspec.yaml
app_dart/test/datastore/cocoon_config_test.dart
app_dart/test/request_handlers/github_webhook_test.dart
app_dart/test/src/datastore/fake_cocoon_config.dart

This only applies to repositories already using cocoon as a github app.
Bug:

Add functionality to support github app auth workflows.

---

test_utilities/bin/flutter_test_runner.sh

This is to fix: https://github.com/flutter/flutter/issues/58833

Fix app_flutter flaky tests by updating test golden images

---

app_dart/lib/src/model/proto/internal/task.pb.dart
app_dart/lib/src/model/proto/internal/task.proto
app_flutter/lib/logic/qualified_task.dart
app_flutter/lib/widgets/luci_task_attempt_summary.dart
app_flutter/lib/widgets/task_overlay.dart
app_flutter/test/widgets/luci_task_attempt_summary_test.dart
app_flutter/test/widgets/task_overlay_test.dart

This PR is part of https://github.com/flutter/flutter/issues/56048

Add flutter dashboard link to luci tasks

---

app_dart/lib/src/foundation/github_checks_util.dart

Add github checks utility as a wrapper to simplify tests.

---

app_dart/lib/src/model/appengine/task.dart
app_dart/lib/src/model/appengine/task.g.dart
app_dart/lib/src/model/proto/internal/task.pb.dart
app_dart/lib/src/model/proto/internal/task.proto
app_dart/lib/src/request_handlers/refresh_chromebot_status.dart
app_dart/pubspec.lock
app_flutter/lib/service/appengine_cocoon.dart
app_flutter/lib/service/dev_cocoon.dart
app_flutter/test/service/appengine_cocoon_test.dart
app_flutter/test/utils/appengine_cocoon_test_data.dart

This is a follow-up pr of https://github.com/flutter/cocoon/pull/820
In addition to adding properties to Task in app_dart, we also need to add those in app_flutter for frontend usage.

Add new properties to Task in app flutter appengine

---

app/pubspec.lock
app/pubspec.yaml

Hit issue again https://github.com/flutter/flutter/issues/52362
This is to solve it.

Fix cocoon app build by updating dependency version

---

app_dart/lib/src/model/proto/internal/commit.pb.dart
app_dart/lib/src/model/proto/internal/commit.proto
app_flutter/lib/logic/qualified_task.dart
app_flutter/lib/service/appengine_cocoon.dart
app_flutter/lib/service/dev_cocoon.dart
app_flutter/test/logic/qualified_task_test.dart
app_flutter/test/service/appengine_cocoon_test.dart
app_flutter/test/widgets/task_overlay_test.dart

This is to fix: https://github.com/flutter/flutter/issues/53943

Add branch to cirrus log url

---

app_dart/lib/src/datastore/cocoon_config.dart
app_dart/lib/src/foundation/github_checks_util.dart
app_dart/lib/src/model/luci/buildbucket.dart
app_dart/lib/src/model/luci/buildbucket.g.dart
app_dart/lib/src/request_handlers/github_webhook.dart
app_dart/lib/src/service/luci_build_service.dart
app_dart/test/request_handlers/github_webhook_test.dart
app_dart/test/service/luci_build_service_test.dart
app_dart/test/src/datastore/fake_cocoon_config.dart

PR information is not populated on the CheckSuiteEvents and PR
information is needed to trigger the build bucket builds.
Bug:

Use pull request to trigger builds instead of CheckSuiteEvent.

---

app_dart/lib/src/datastore/cocoon_config.dart

This will add failed builds retry functionality.
Bug:

Add support checks api for the engine.

---

app_dart/lib/src/service/luci.dart
app_dart/test/request_handlers/refresh_chromebot_status_test.dart

This PR fixes: https://github.com/flutter/flutter/issues/61873

Address ref NULL issue which fails API refresh-chromebot-status

---

app_dart/bin/server.dart
app_dart/lib/src/request_handlers/reset_try_task.dart
app_dart/test/request_handlers/reset_try_task_test.dart

This API is required to trigger builds for rollers where is not possible
to upload a new commit and for some reason the checks API failed to
update the status.
Bug:
https://github.com/flutter/flutter/issues/61904

Add an api to retrigger all the builds for a commit.

---

app_dart/dev/luci_prod_builders.json
app_dart/dev/luci_try_builders.json

This pr is part of https://github.com/flutter/flutter/issues/61769

Add luci builders for both prod and try

---

app_dart/lib/src/service/github_checks_service.dart

This fixes issue: https://github.com/flutter/flutter/issues/62056

Solve corner case that summaryMarkdown is null when `updateCheckRun` in Github

---

agent/lib/src/runner.dart
agent/lib/src/utils.dart

Related issue: https://github.com/flutter/flutter/issues/62206#issuecomment-663736708

Add --disable-dart-dev to dart in cocoon agent

---

app_dart/lib/src/datastore/cocoon_config.dart
app_dart/lib/src/foundation/utils.dart
app_dart/lib/src/request_handlers/luci_status.dart
app_dart/lib/src/service/github_status_service.dart
app_dart/lib/src/service/luci.dart
app_dart/lib/src/service/luci_build_service.dart
app_dart/test/foundation/utils_test.dart
app_dart/test/request_handlers/push_engine_status_to_github_test.dart
app_dart/test/request_handlers/refresh_chromebot_status_test.dart
app_dart/test/src/datastore/fake_cocoon_config.dart

This is to finish https://github.com/flutter/flutter/issues/61769.

Access Luci builders via http access

---

app_flutter/pubspec.lock
test_utilities/bin/flutter_test_runner.sh

The formatter was broken on CI: https://ci.chromium.org/p/flutter/builders/try/Cocoon/1113

Fix dart formatter

---

app_dart/lib/src/model/appengine/commit.dart
app_dart/lib/src/model/proto/internal/commit.pb.dart
app_dart/lib/src/model/proto/internal/commit.proto
app_dart/lib/src/request_handlers/refresh_github_commits.dart
app_dart/test/request_handlers/get_status_test.dart

This will allow us to show the commit message in the overlay
card of the build dashboard that pops up when the user clicks
on the commit.
https://github.com/flutter/flutter/issues/43107

Store commit message in the `Checklist` Datastore & BigQuery

---

app_dart/lib/src/request_handlers/github_webhook.dart
app_dart/lib/src/request_handlers/reset_try_task.dart
app_dart/lib/src/service/luci_build_service.dart
app_dart/test/request_handlers/github_webhook_test.dart

This is to detect why the skia auto rollers are not running all the
tests.
Bug:
https://github.com/flutter/flutter/issues/62233

Add logging to trigger try builds.

---

app_dart/lib/src/service/github_service.dart
app_dart/test/request_handlers/refresh_github_commits_test.dart
app_dart/test/service/github_service_test.dart

https://github.com/flutter/flutter/issues/43107

Fix bug whereby we weren't capturing the commit message

---

app_dart/lib/src/datastore/cocoon_config.dart

This is to be able to retry luci tasks from github ui.

Enable checks api in flutter repository.

---

app_dart/pubspec.lock
dev/validate_json.dart
tests.yaml

This PR is a follow up of https://github.com/flutter/cocoon/pull/886. 
Dev json validation has been implemented, and this PR is to enable it in luci pre tasks.

Enable dev json check in presubmit tasks

---

app_dart/lib/src/datastore/cocoon_config.dart
app_dart/lib/src/model/appengine/github_gold_status_update.dart
app_dart/lib/src/request_handlers/github_webhook.dart
app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
app_dart/test/request_handlers/github_webhook_test.dart
app_dart/test/request_handlers/push_gold_status_to_github_test.dart
app_dart/test/src/datastore/fake_cocoon_config.dart

Reverts flutter/cocoon#892
The graphQL query is failing in looking up the Luci builds.

Revert "Refactor and Update flutter-gold check"

---

app_dart/dev/luci_try_builders.json

Bug:
https://github.com/flutter/flutter/issues/63241
https://github.com/flutter/flutter/issues/63242

Add new sdk presubmit tests.

---

app_dart/lib/src/service/github_status_service.dart
app_dart/test/service/github_status_service_test.dart

This is part of https://github.com/flutter/flutter/issues/62429

Update github_status_service to query luci builders by using bucket and repo

---

app_dart/lib/src/service/luci_build_service.dart
app_dart/test/request_handlers/github_webhook_test.dart
app_dart/test/service/luci_build_service_test.dart
app_dart/test/src/datastore/fake_cocoon_config.dart

This is part of flutter/flutter#62429

Update github_webhook to query luci builders by using bucket and repo

---

app_dart/lib/src/request_handlers/refresh_github_commits.dart
app_dart/lib/src/service/luci.dart
app_dart/lib/src/service/luci.g.dart
app_dart/test/request_handlers/refresh_github_commits_test.dart
app_dart/test/src/datastore/fake_cocoon_config.dart

Prod configuration values were hardcoded in different places. This PR
reads those configs from a single place.
Bug:
https://github.com/flutter/flutter/issues/63256

Read prod configurations from config file.

---

app_dart/lib/src/foundation/utils.dart
app_dart/test/foundation/utils_test.dart

This is part of https://github.com/flutter/flutter/issues/63437

Add logic to check if luci try builders are enabled

---

dev/README.md
dev/try_builders.json

This is part of flutter/flutter#63437.

Add enabled flag for try builders

---

app_dart/lib/src/datastore/cocoon_config.dart
app_dart/lib/src/model/appengine/github_gold_status_update.dart
app_dart/lib/src/request_handlers/github_webhook.dart
app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
app_dart/test/request_handlers/github_webhook_test.dart
app_dart/test/request_handlers/push_gold_status_to_github_test.dart
app_dart/test/src/datastore/fake_cocoon_config.dart

The flutter-gold refactor was reverted due to there being `int!` instead of `Int!` in the query string.

Reland flutter-gold refactor

---

app_dart/dev/branches.txt

+ flutter-1.21-candidate.9
-1.18 and 1.19
part of https://github.com/flutter/flutter/issues/64078

Add 1.21 branch and remove older 1.18 and 1.19 beta branches

---

app_dart/lib/src/model/appengine/task.dart
app_dart/lib/src/request_handlers/refresh_github_commits.dart
app_dart/test/model/task_test.dart

Prevents isFlaky and other required fields be null in datastore.
Bug: https://github.com/flutter/flutter/issues/64114

[app_dart] Ensure chromebot tasks have valid format in datastore

---

app_dart/lib/src/foundation/utils.dart
app_dart/lib/src/service/github_service.dart
app_dart/lib/src/service/github_status_service.dart
app_dart/lib/src/service/luci_build_service.dart
app_dart/test/foundation/utils_test.dart
app_dart/test/request_handlers/github_webhook_test.dart
app_dart/test/request_handlers/push_engine_status_to_github_test.dart
app_dart/test/service/github_status_service_test.dart
app_dart/test/service/luci_build_service_test.dart
app_dart/test/src/service/fake_github_service.dart

This is to solve https://github.com/flutter/flutter/issues/62841

Enable filtering builders based on changed files in PRs

---

agent/lib/src/adb.dart

Bug:
https://github.com/flutter/flutter/issues/64753

This is to ensure slow devices are being discovered.

---

app_dart/lib/src/request_handlers/reserve_task.dart
app_dart/lib/src/service/task_provider.dart
app_dart/test/request_handlers/reserve_task_test.dart
app_dart/test/service/reservation_provider_test.dart
app_dart/test/service/task_provider_test.dart

This PR fixes: https://github.com/flutter/flutter/issues/64108

Let devicelab run release branch tests first

---

app_flutter/lib/service/google_authentication.dart
app_flutter/pubspec.lock
app_flutter/pubspec.yaml
app_flutter/test/service/google_authentication_test.dart

Catch issues in the Google Sign in plugin so they do not crash the app's sign in functionality.
Re-enable silent sign in.
Update dependencies to ensure latest sign in plugin is used.
https://github.com/flutter/flutter/issues/65912

[app_flutter] Catch google sign in platform exceptions

---

Dockerfile
cloudbuild.yaml

These are copied over from https://github.com/keyonghan/cloud-builder-flutter with some merging done on `cloudbuild.yaml` to do both the Dockerfile building and the project building.

[cloudbuild] Move config and dockerfile into cocoon

---

app_dart/dev/branches.txt

I think we need a cherry pick on the dev branch to fix a devicelab regression, so this will let us run devicelab tests on it.

add dev branch to branches.txt

---

app_dart/lib/src/datastore/cocoon_config.dart
app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
app_dart/test/request_handlers/push_gold_status_to_github_test.dart
app_flutter/lib/widgets/task_overlay.dart

This changes the scope of PRs that the bot will alert for stale Gold results.
It also buffs up the message a bit to be clearer and more helpful. 
Fixes https://github.com/flutter/flutter/issues/66478

Fix scope for stale PR alert

---

app/pubspec.lock
app/pubspec.yaml

This is to fix: https://github.com/flutter/flutter/issues/67319

update build_web_compilers to a higher version

---

app_flutter/README.md
app_flutter/USER_GUIDE.md

Imported from flutter/flutter to be closer to the code. I'll send a follow up PR there to link here.
Added some common questions about the frontend I have seen over the past month.
https://github.com/flutter/flutter/issues/68336

[Doc Fixit 2020] Create frontend user guide

---

app_dart/README.md

This is to address: https://github.com/flutter/flutter/issues/68337

Update cocoon backend doc

---

app_dart/lib/src/service/luci_build_service.dart

Reverts flutter/cocoon#990
Causing this error:
Converting object to an encodable object failed: Instance of 'NotificationConfig'
#0      _JsonStringifier.writeObject (dart:convert/json.dart:687:7)
#1      _JsonStringifier.writeMap (dart:convert/json.dart:768:7)
#2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:723:21)
#3      _JsonStringifier.writeObject (dart:convert/json.dart:678:9)
#4      _JsonStringStringifier.printOn (dart:convert/json.dart:876:17)
#5      _JsonStringStringifier.stringify (dart:convert/json.dart:861:5)
#6      JsonEncoder.convert (dart:convert/json.dart:261:30)
#7      JsonCodec.encode (dart:convert/json.dart:171:45)
#8      BuildBucketClient._postRequest (package:cocoon_service/src/service/buildbucket.dart:78:28)
<asynchronous suspension>
#9 …

Revert "Specify pubsub topic use when rescheduling prod builds."

---

agent/lib/src/utils.dart

Clean up some of the output in the devicelab logs.
fxb/64761

[agent] Clean log args

---

agent/lib/src/utils.dart

Follow up from https://github.com/flutter/cocoon/pull/1008

[agent] Null check before checking for excluded keyword

---

app/web/benchmarks.dart

Fixes https://github.com/flutter/flutter/issues/71427
http://testchillers.flutter-dashboard.appspot.com/benchmarks.html

[app_dart] Fix benchmark page empty provider issue

---

device_doctor/tool/infra-dialog/.gitignore
device_doctor/tool/infra-dialog/infra-dialog.xcodeproj/project.pbxproj
device_doctor/tool/infra-dialog/infra-dialog.xcodeproj/project.xcworkspace/contents.xcworkspacedata
device_doctor/tool/infra-dialog/infra-dialog.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
device_doctor/tool/infra-dialog/infra-dialog.xcodeproj/xcshareddata/xcschemes/infra-dialog.xcscheme
device_doctor/tool/infra-dialog/infra-dialogUITests/Info.plist
device_doctor/tool/infra-dialog/infra-dialogUITests/infra_dialogUITests.swift

This is a direct copy of the `infra-dialog` tool to `device_doctor/tool` from `agent/tool`. It will be used to dismiss pop-up windows on iOS devices.
Related issue: https://github.com/flutter/flutter/issues/66193

Copy the infra-dialog tool to device_doctor/tool from agent/tool

---

app_dart/lib/src/request_handlers/update_task_status.dart
app_dart/test/request_handlers/update_task_status_test.dart

This will return a more descriptive error on LUCI devicelab runs instead of a general check in the test runner.
https://github.com/flutter/flutter/issues/71749
Added check for bad request on a branch that does not exist in cocoon config

[app_dart] Check git branch on LUCI update-task-status

---

app_dart/lib/src/request_handlers/update_task_status.dart
app_dart/test/request_handlers/update_task_status_test.dart

https://github.com/flutter/flutter/issues/71749

[app_dart] Pull commit key from Datastore for task lookup

---

app_dart/lib/src/service/luci_build_service.dart

Fixes https://github.com/flutter/flutter/issues/72007

[app_dart] Pass branch when rescheduling prod builds

---

app_dart/lib/src/request_handlers/update_task_status.dart
app_dart/test/request_handlers/update_task_status_test.dart

The backend is receiving string input with one byte difference from what's in datastore. This cleans the hidden whitespace to match what's in datastore.
Reverts back to the key lookup instead of the brute force scan.
Fixes https://github.com/flutter/flutter/issues/71749
Added unit test with hidden whitespace from the prod example
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_benchmarks_canvaskit/76/overview

[app_dart] Sanitize update task status input

---

app_dart/dev/branches.txt

this will be our next beta branch

update branches.txt for 1.25.x

---

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart

This is to support the auto-merger (wait for tree to go green) for the plugins repo.

Update `CheckForWaitingPullRequests` to supports flutter/plugins

---

dev/salt.minion.plist

That comment was causing the xml validation to fail.

Remove comment from plist file.

---

device_doctor/LICENSE
device_doctor/README.md
device_doctor/bin/main.dart

This adds LICENSE and README to device_doctor tool.
Related issue: https://github.com/flutter/flutter/issues/72835

Add device doctor license and readme

---

licenses/pubspec.yaml

This is part of a wider audit of pubspec.yaml files

Remove obsolete comment

---

app_dart/lib/src/datastore/cocoon_config.dart
app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
app_dart/test/src/datastore/fake_cocoon_config.dart

Reverts flutter/cocoon#1049
This broke the engine autoroller.

Revert "Check autoroller author by ID instead of name"

---

app_dart/lib/src/request_handlers/push_engine_status_to_github.dart
app_dart/pubspec.lock
app_dart/test/request_handlers/push_engine_status_to_github_test.dart

This solves https://github.com/flutter/flutter/issues/73810

Treat infra failure as fail to close engine tree

---

app_flutter/lib/build_dashboard_page.dart
app_flutter/lib/state/build.dart

Fixed the status string so that it is calculated inside of the animated builder instead of outside of it.

Fix update of failed tasks list

---

app_dart/dev/metrics_transfer.dart
app_dart/pubspec.lock
app_dart/pubspec.yaml
app_dart/test/dev/metrics_transfer_test.dart

Some part of this PR's code is from https://github.com/flutter/cocoon/pull/788.
Related issue: https://github.com/flutter/flutter/issues/73872

Add a script to manually transfer Cocoon metrics

---

app_dart/lib/src/service/luci.dart
app_dart/test/service/luci_test.dart

The results extraction process runs a single query to retrieve 40 builds
for +200 builders making the grpc service to fail with 500 errors. This
pr changes the logic to send several requests for <50 builders and
aggregates the data at the end.
Bug: https://github.com/flutter/flutter/issues/74536

Fix buildbucket grpc errors.

---

app_dart/lib/src/datastore/cocoon_config.dart
app_dart/lib/src/request_handlers/push_engine_status_to_github.dart
app_dart/lib/src/service/luci_build_service.dart
app_dart/test/request_handlers/luci_status_test.dart
app_dart/test/request_handlers/push_build_status_to_github_test.dart
app_dart/test/service/luci_build_service_test.dart
app_dart/test/src/datastore/fake_cocoon_config.dart

This is a follow up of https://github.com/flutter/cocoon/pull/1072
Also increased the retry limit to 2.
Related issue: https://github.com/flutter/flutter/issues/68322

Fix engine luci auto rerun by setting logger

---

device_doctor/lib/src/android_device.dart
device_doctor/lib/src/device.dart
device_doctor/lib/src/ios_device.dart
device_doctor/lib/src/utils.dart
device_doctor/test/src/android_device_test.dart
device_doctor/test/src/ios_device_test.dart

This adds `unlock keychain healthcheck` for ios device.
Related issue: https://github.com/flutter/flutter/issues/74960

Add unlock keychain healthcheck for device doctor ios device

---

app_dart/lib/src/request_handlers/refresh_github_commits.dart
app_dart/lib/src/service/scheduler.dart
app_dart/test/request_handlers/refresh_github_commits_test.dart
app_dart/test/service/scheduler_test.dart
licenses/check_licenses.dart

Refactors logic in `refresh_github_commits` into a service
* Trigger adding tasks from github webhooks
* Remove the cron method
* Move retry logic into this service

[app_dart] Create scheduler service

---

app_dart/lib/src/service/scheduler.dart
app_dart/test/service/scheduler_test.dart

https://github.com/flutter/cocoon/pull/1087 moved the datastore commits to be in separate transactions. This moves them back together and adds a regression test.
When a failure occurs, the next scheduler attempt will try to "reschedule" the tasks. That is expected to be successful.
Fixes https://github.com/flutter/flutter/issues/76716

[app_dart] Fix scheduler failing to create tasks

---

app_dart/lib/src/service/luci.dart
app_dart/test/service/luci_test.dart

This fixes: https://github.com/flutter/flutter/issues/76889

[app_dart] Fix sublist index when dividing builders for buildbucket query

---

app_dart/bin/server.dart
app_dart/lib/src/request_handlers/github_webhook.dart
app_dart/lib/src/request_handlers/refresh_github_commits.dart
app_dart/lib/src/service/scheduler.dart
app_dart/test/request_handlers/github_webhook_test.dart
app_dart/test/service/scheduler_test.dart
app_dart/test/src/utilities/mocks.dart

Given [PullRequest], add it to Cocoon so tasks can be scheduled against it.
https://github.com/flutter/flutter/issues/76140 - Move from cron method to webhooks
https://github.com/flutter/flutter/issues/77385 - Webhook method will no longer have this issue. The GitHub refresh cron doesn't dynamically add commits

[app_dart] Schedule prod tasks from GitHub webhooks

---

app_dart/lib/src/datastore/config.dart
app_dart/test/datastore/cocoon_config_test.dart

Revert "[app_dart] Pull *_builders from commit sha on PRs prs use commitSha for *_builders configs"

---

app_dart/lib/src/datastore/config.dart
app_dart/lib/src/foundation/utils.dart
app_dart/lib/src/model/appengine/commit.dart
app_dart/lib/src/service/luci.dart
app_dart/lib/src/service/scheduler.dart
app_dart/test/datastore/cocoon_config_test.dart
app_dart/test/src/datastore/fake_config.dart

This reverts commit f6165832e6236d6c16b57f2745f8e596a0b67936.
Revert done locally as github ui was not able to resolve it (issues with imports)

Revert "[app_dart] luciBuilders supports release branches (#1111)"

---

app_dart/lib/src/foundation/utils.dart

The logs show `Failed to add build status to BigQuery: ApiRequestError `
This moves from try/on to try/catch to log the error message

[app_dart] Log BigQuery errors

---

app_dart/lib/src/request_handlers/github_rate_limit_status.dart

API is tracked to the flutter-dashboard app, so all supported repos share the same quota.
Remove the for loop and create a GitHub client against flutter/flutter to check the current rate limit.

[app_dart] Remove repo logic from GitHub API tracking

---

test_utilities/bin/config_test_runner.sh

This script will be called by the builder to validate a given config file.
https://github.com/flutter/flutter/issues/79579 - Bringup builder for validating scheduler configs

[test_utilities] Create config test runner

---

app_dart/lib/src/request_handlers/github_webhook.dart
app_dart/test/request_handlers/github_webhook_test.dart

This adds additional engine auto-labelling for the following labels:
* embedder
* platform-fuchsia
* platform-linux
* platform-macos
* platform-web
* platform-windows

Add additional engine auto-labelling

---

test_utilities/bin/config_test_runner.sh
test_utilities/bin/dart_test_runner.sh
test_utilities/bin/flutter_test_runner.sh

for reference: https://tldp.org/LDP/abs/html/quotingvar.html

wrap vars in double quotes to safeguard strings with spaces

---

app_flutter/lib/widgets/progress_button.dart
app_flutter/lib/widgets/task_overlay.dart

to unblock engine roll https://github.com/flutter/flutter/pull/79953, that contains dart_style change https://github.com/dart-lang/sdk/commit/f0ccceab4d16dc0ddfc535733c30d36dcbf75699 that breaks cocoon formatting.

fix dartfmt

---

app_dart/lib/src/service/scheduler.dart

Fixes https://github.com/flutter/flutter/issues/80128

[app_dart] Fix null http provider in scheduler

---

app_dart/index.yaml

Adding a composite index on Checklist entity for FlutterRepositoryPath and CreationDate, as a precursor to enabling display of different repo data on flutter dashboard.

Add a composite index for flutter repo and creation date on Checklist.

---

app_flutter/lib/widgets/progress_button.dart
app_flutter/lib/widgets/task_overlay.dart

Revert "fix dartfmt"

---

app_dart/dev/branches.txt

TODO get these branches from the flutter/infra repo

add 2.2.x branch to build dashboard

---

app_dart/pubspec.lock
app_dart/pubspec.yaml

This speeds up `dart test` in app_dart by ~50% on my workstation. This is probably useful for everyone

[app_dart] Upgrade dart test to a recent version

---

app_dart/bin/server.dart
app_dart/lib/cocoon_service.dart
app_dart/lib/src/request_handlers/query_github_graphql.dart
app_dart/test/request_handlers/query_github_graphql_test.dart

This is required to validate github graphql queries that require
authentication.

Adds a graphql query service.

---

app_dart/app.yaml

This should reduce issues in the daily promotion

[app_dart] Update readiness check to match Dart

---

app_dart/lib/src/model/appengine/allowed_account.dart
app_dart/lib/src/request_handling/authentication.dart
app_dart/lib/src/request_handling/swarming_authentication.dart
app_dart/test/request_handling/api_request_handler_test.dart
app_dart/test/request_handling/authentication_test.dart
app_dart/test/request_handling/swarming_authentication_test.dart
app_dart/test/src/request_handling/fake_authentication.dart

Removing agent references from authentication code in app_dart

---

app_dart/bin/validate_scheduler_config.dart
app_dart/integration_test/validate_all_ci_configs_test.dart
app_dart/lib/src/service/datastore.dart
app_dart/test/foundation/utils_test.dart
app_dart/test/model/buildbucket_test.dart
app_dart/test/model/google/token_info_test.dart
app_dart/test/request_handlers/flush_cache_test.dart
app_dart/test/request_handlers/luci_status_test.dart
app_dart/test/request_handlers/push_engine_status_to_github_test.dart
app_dart/test/request_handlers/refresh_chromebot_status_test.dart
app_dart/test/request_handlers/vacuum_github_commits_test.dart
app_dart/test/request_handling/cache_request_handler_test.dart
app_dart/test/request_handling/static_file_handler_test.dart
app_dart/test/service/cache_service_test.dart
app_dart/test/service/config_test.dart
app_dart/test/service/datastore_test.dart
app_dart/test/service/luci_build_service_test.dart
app_dart/test/service/scheduler_test.dart
app_dart/test/src/datastore/fake_config.dart
app_dart/test/src/request_handling/fake_authentication.dart
app_dart/test/src/service/fake_luci_build_service.dart
app_dart/test/src/service/fake_scheduler.dart

This broke as customer tests only tests the Flutter apps. Now that it's available on ToT of Flutter CQ is failing.

[app_dart] Fix directive ordering

---

app_dart/pubspec.lock
app_dart/pubspec.yaml
scheduler/LICENSE
scheduler/pubspec.yaml

Fixes https://github.com/flutter/flutter/issues/82548
```sh
$ cd app_dart
$ dart dev/deploy.dart --project flutter-dashboard --version testchillers
```
https://testchillers-dot-flutter-dashboard.appspot.com/

[scheduler] Publish package to fix gcloud deploys

---

test_utilities/bin/dart_test_runner.sh
test_utilities/bin/flutter_test_runner.sh
test_utilities/bin/prepare_environment.sh

This is only for the backend project until the project can migrate to NNBD packages
https://github.com/flutter/flutter/issues/82705

[app_dart] Use Dart stable in CQ

---

app_dart/integration_test/validate_all_ci_configs_test.dart

https://github.com/flutter/flutter/issues/82303

[scheduler] Add all repos with ci.yaml to integration test

---

test_utilities/bin/flutter_test_runner.sh

CQ is currently broken due to using Dart 2.14.
https://github.com/flutter/flutter/issues/82705

Move cocoon to Flutter stable (match Dart stable)

---

app_dart/lib/src/model/luci/buildbucket.dart
app_dart/lib/src/request_handlers/reset_prod_task.dart
app_dart/lib/src/service/luci_build_service.dart
app_dart/test/request_handlers/reset_prod_task_test.dart

This is allow retry builds that override properties.
Bug: https://github.com/flutter/flutter/issues/81102

Add support for properties in the reset_prod_task.

---

app_dart/lib/src/request_handlers/reset_prod_task.dart
app_dart/lib/src/service/luci_build_service.dart
app_dart/test/request_handlers/reset_prod_task_test.dart

Bug: https://github.com/flutter/flutter/issues/83823

Print build url when triggering a retry with curl.

---

app_flutter/lib/build_dashboard_page.dart
app_flutter/lib/main.dart
format.sh

Fixes https://github.com/flutter/flutter/issues/62459

[app_flutter] Fix branch text in light theme

---

app_dart/lib/src/request_handlers/reset_prod_task.dart
app_dart/lib/src/request_handling/api_request_handler.dart
app_dart/lib/src/request_handling/authentication.dart
app_dart/lib/src/service/luci_build_service.dart
app_dart/test/request_handlers/reset_prod_task_test.dart
app_dart/test/request_handling/authentication_test.dart
app_dart/test/src/request_handling/fake_authentication.dart

This is to be able to identify manually triggered tasks and who is triggering them.

Adds trigger_type and triggered_by tags.

---

app_dart/lib/src/service/github_checks_service.dart

Triaging a LUCI build failure -> Understanding a LUCI build failure
https://github.com/flutter/flutter/issues/64208#issuecomment-857938079

Update Github check run wiki link title

---

scheduler/CHANGELOG.md
scheduler/pubspec.yaml

https://github.com/flutter/flutter/issues/82705

[scheduler] Migrate package to null safety

---

app_dart/lib/src/request_handlers/push_gold_status_to_github.dart

The link has changed per the gold team. :)

Updated Gold triage link

---

app_dart/lib/src/request_handlers/push_engine_status_to_github.dart
app_dart/lib/src/request_handlers/refresh_chromebot_status.dart
app_dart/lib/src/service/luci_build_service.dart
app_dart/test/request_handlers/refresh_chromebot_status_test.dart
app_dart/test/service/luci_build_service_test.dart

This adds auto retry for framework TOT failures. 
Issues: https://github.com/flutter/flutter/issues/84004, https://github.com/flutter/flutter/issues/84818

Adds auto retry for framework TOT failures

---

.ci.yaml
scheduler/bin/generate_jspb.dart
scheduler/bin/validate_scheduler_config.dart
scheduler/lib/models/scheduler.pb.dart
scheduler/lib/models/scheduler.pbenum.dart
scheduler/lib/models/scheduler.pbjson.dart
scheduler/lib/models/scheduler.proto
scheduler/lib/scheduler.dart
scheduler/pubspec.lock
scheduler/test/scheduler_test.dart

generate_jspb will take a given yaml, and make it into a format that luci's starlark files can read.

[scheduler] Add recipe field and generate_jspb script

---

.ci.yaml

[scheduler] Add recipes to ci.yaml

---

CI_YAML.md

https://github.com/flutter/flutter/issues/79658

Document external tests in .ci.yaml

---

app_dart/lib/src/foundation/github_checks_util.dart
app_dart/lib/src/service/scheduler.dart
app_dart/test/service/scheduler_test.dart

https://github.com/flutter/flutter/issues/85483

[scheduler] Add description on pending ci.yaml check to push empty commit

---

app_dart/lib/src/model/proto/internal/build_status_response.pb.dart
app_dart/lib/src/model/proto/internal/build_status_response.pbenum.dart
app_dart/lib/src/model/proto/internal/key.pb.dart
app_dart/lib/src/model/proto/internal/scheduler.pb.dart
app_dart/lib/src/model/proto/internal/scheduler.pbenum.dart
app_dart/lib/src/model/proto/internal/scheduler.pbjson.dart
app_dart/lib/src/model/proto/internal/scheduler.pbserver.dart
app_dart/lib/src/model/proto/internal/scheduler.proto

This allows us to move platform arg logic from flutter/infra into the respective .ci.yaml

[scheduler] Add platform properties to .ci.yaml

---

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
app_dart/lib/src/request_handlers/check_for_waiting_pull_requests_queries.dart
app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart

Fixes https://github.com/flutter/flutter/issues/85657

Add link(s) to failure page when a PR has failing checks/statuses

---

.ci.yaml

Related infra CL: https://flutter-review.googlesource.com/c/infra/+/15360

[ci.yaml] Add platform_properties, add_recipe_cq

---

app_dart/bin/yaml_converter.dart

This is a boiler plate script that allows you to easily make LSC to ci.yaml. It includes logic on how to write the file in yaml.
The useful part of this is the `writeYaml`. This functionality could probably be generalized and upstreamed into `package:yaml`, but  there's a lot of edge cases it doesn't handle.

[ci.yaml] LSC boiler plate script

---

app_dart/bin/generate_jspb.dart

Uploading this as it's a useful script I use when debugging the feasibility of ci.yaml features in flutter/infra (doesn't require me to constantly upload new commits)

[ci_yaml] Local jspb generator

---

app_dart/lib/src/request_handlers/check_flaky_tests_and_update_github.dart
app_dart/lib/src/request_handlers/check_flaky_tests_and_update_github_utils.dart
app_dart/test/request_handlers/check_flaky_tests_and_update_github_test.dart
app_dart/test/request_handlers/check_flaky_tests_and_update_github_test_data.dart

ci.yaml format has changed, This pr updates the script to be in sync.
This pr also change the way we detect existing issue and pr. It now write a hidden meta tags to the issue/pr body and use them to detect which builders they belong to

Update the script to match the ci.yaml

---

Dockerfile

https://github.com/flutter/flutter/issues/86450
I'm not sure if this will fix it, but it's worth a try

[cloudbuild] Update to use flutter master

---

app_dart/lib/src/request_handlers/push_build_status_to_github.dart
app_dart/test/request_handlers/push_build_status_to_github_test.dart

https://github.com/flutter/flutter/issues/86509

[app_dart] Ignore flaky builders in tree status

---

app_dart/lib/src/request_handlers/check_flaky_tests_and_update_github.dart
app_dart/lib/src/request_handlers/check_flaky_tests_and_update_github_utils.dart
app_dart/test/request_handlers/check_flaky_tests_and_update_github_test.dart

Also fixes an issue where github may use a different line break

Switch to use github bot for check flaky handler

---

.ci.yaml

[ci.yaml] Enable CI and add ci.yaml roller

---

app_dart/lib/src/request_handlers/github_webhook.dart
app_dart/lib/src/request_handlers/push_build_status_to_github.dart

https://github.com/flutter/flutter/issues/86383
The current stack trace being thrown is not showing any Cocoon lines. This is making it hard to debug where the issue is popping up. Adding some more here to see if we can find it.

[app_dart] Add more logs to github webhook handler

---

CI_YAML.md
app_dart/bin/yaml_converter.dart
app_dart/lib/src/model/proto/internal/scheduler.pb.dart
app_dart/lib/src/model/proto/internal/scheduler.pbenum.dart
app_dart/lib/src/model/proto/internal/scheduler.pbjson.dart
app_dart/lib/src/model/proto/internal/scheduler.proto

[ci.yaml] Deprecate tags field

---

.ci.yaml

Reverts flutter/cocoon#1299 to test out the auto-roll CL again

Revert "[test] Trigger auto-roll CL"

---

app_dart/lib/src/request_handlers/push_build_status_to_github.dart
app_dart/lib/src/service/build_status_provider.dart

Related: https://github.com/flutter/flutter/issues/87512

Add more logs when pushing build status to github

---

app_dart/lib/src/request_handlers/deflake_flaky_builders.dart
app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart
app_dart/lib/src/request_handlers/flaky_handler_utils.dart
app_dart/test/request_handlers/deflake_flaky_builders_test_data.dart
app_dart/test/request_handlers/file_flaky_issue_and_pr_test_data.dart
app_dart/test/request_handlers/update_existing_flaky_issues_test_data.dart

To support https://github.com/flutter/flutter/pull/87522

Change to use name instead of builder defined in .ci.yaml

---

app_dart/lib/src/service/luci.dart

Context: https://github.com/flutter/flutter/issues/87512

Use tags when search builds via buildbucket API 

---

app_dart/lib/src/service/luci_build_service.dart

Issue: https://github.com/flutter/flutter/issues/87599

Add scheduler_job_id tag when reset a prod task from build dashboard

---

app_dart/lib/src/request_handlers/deflake_flaky_builders.dart
app_dart/test/request_handlers/deflake_flaky_builders_test.dart
app_dart/test/request_handlers/deflake_flaky_builders_test_data.dart

fixes https://github.com/flutter/flutter/issues/87520

Do not deflake test if not enough builds

---

cloudbuild.yaml

This is for https://github.com/flutter/flutter/issues/87749.

Skip cocoon backend cloud build if no new commits

---

app_dart/lib/src/foundation/utils.dart
app_dart/lib/src/request_handlers/deflake_flaky_builders.dart
app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart
app_dart/lib/src/request_handlers/flaky_handler_utils.dart
app_dart/lib/src/request_handlers/update_existing_flaky_issues.dart
app_dart/test/request_handlers/deflake_flaky_builders_test_data.dart
app_dart/test/request_handlers/file_flaky_issue_and_pr_test.dart
app_dart/test/request_handlers/file_flaky_issue_and_pr_test_data.dart
app_dart/test/request_handlers/flaky_handler_utiles_test.dart

fixes https://github.com/flutter/flutter/issues/87500
script will now add team label
Skip filing the pr if no entry in ci.yaml
updated ignored list for deflake script

Fixes flaky script

---

CI_YAML.md

This is to support easier bringup of new dependencies like https://github.com/flutter/flutter/issues/87649

Document upgrading dependencies via ci.yaml

---

device_doctor/lib/src/utils.dart
device_doctor/test/src/android_device_test.dart
device_doctor/test/src/host_utils_test.dart
device_doctor/test/src/ios_device_test.dart
device_doctor/test/src/utils_test.dart

Fixes https://github.com/flutter/flutter/issues/88008

[device_doctor] Fix flake and old formats

---

app_dart/lib/src/request_handlers/push_build_status_to_github.dart
device_doctor/test/src/android_device_test.dart

This is to fix: https://github.com/flutter/flutter/issues/88361

Tree build status fix - wait async operations to finish before referencing result

---

app_dart/lib/src/request_handlers/deflake_flaky_builders.dart
app_dart/test/request_handlers/deflake_flaky_builders_test_data.dart

fixes https://github.com/flutter/flutter/issues/88321

deflake handler uses name instead of builder

---

app_dart/lib/src/request_handlers/update_task_status.dart
app_dart/lib/src/service/config.dart
app_dart/pubspec.lock
app_dart/pubspec.yaml
app_dart/test/request_handlers/update_task_status_test.dart
app_dart/test/src/datastore/fake_config.dart

This is last part of https://github.com/flutter/flutter/issues/88484

Skip uploading metrics to metrics center in cocoon

---

app_dart/bin/server.dart
app_dart/lib/src/request_handlers/update_task_status.dart
app_dart/lib/src/request_handling/swarming_authentication.dart
app_dart/lib/src/service/access_client_provider.dart
app_dart/lib/src/service/access_token_provider.dart
app_dart/lib/src/service/buildbucket.dart
app_dart/lib/src/service/config.dart
app_dart/lib/src/service/luci_build_service.dart
app_dart/test/request_handlers/github_webhook_test.dart
app_dart/test/service/buildbucket_test.dart
app_dart/test/service/luci_build_service_test.dart
app_dart/test/src/datastore/fake_config.dart
app_dart/test/src/service/fake_luci_build_service.dart
app_dart/test/src/utilities/mocks.dart
device_doctor/test/src/utils.dart

This is to use the application default account for everything in the
backend.

Remove the use of devicelab service account.

---

app_dart/lib/src/model/luci/buildbucket.dart
app_dart/lib/src/model/proto/internal/scheduler.pb.dart
app_dart/lib/src/request_handlers/push_build_status_to_github.dart
app_dart/lib/src/request_handlers/refresh_chromebot_status.dart
app_dart/lib/src/service/luci.dart
app_dart/test/service/luci_test.dart

Reverts flutter/cocoon#1344 (follow up of the config change: https://flutter-review.googlesource.com/c/infra/+/17941)

Revert "Prepare search requests considering realm when calling builderbucket API"

---

app_dart/lib/src/model/proto/internal/scheduler.pb.dart
app_dart/lib/src/request_handlers/vacuum_github_commits.dart

The vacuum handler was raising an exception trying to call a method in a
null.
Bug: https://github.com/flutter/flutter/issues/89622

Fix vacuum handler.

---

app_dart/lib/src/request_handlers/push_build_status_to_github.dart
app_dart/lib/src/request_handlers/query_github_graphql.dart
app_dart/lib/src/request_handlers/reset_prod_task.dart
app_dart/lib/src/request_handlers/reset_try_task.dart
app_dart/lib/src/service/config.dart
app_dart/lib/src/service/github_checks_service.dart
app_dart/lib/src/service/github_service.dart
app_dart/lib/src/service/luci.dart
app_dart/lib/src/service/luci_build_service.dart
app_dart/lib/src/service/scheduler.dart
app_dart/test/request_handlers/github_webhook_test.dart
app_dart/test/request_handlers/luci_status_test.dart
app_dart/test/request_handling/static_file_handler_test.dart
app_dart/test/service/luci_build_service_test.dart
app_dart/test/service/scheduler_test.dart
app_dart/test/src/datastore/fake_config.dart
app_dart/test/src/service/fake_github_service.dart
app_dart/test/src/service/fake_graphql_client.dart

This is to prevent the task timing out before the builds are scheduled.

Create checks and batch build requests asynchronously.

---

.github/workflows/mirror.yml

Reorder branch replication to replicate from main to master.

---

app_dart/lib/src/model/luci/buildbucket.dart
app_dart/lib/src/model/luci/buildbucket.g.dart
app_dart/lib/src/service/luci_build_service.dart
app_dart/test/service/buildbucket_test.dart
app_dart/test/service/luci_build_service_test.dart
app_dart/test/src/utilities/mocks.mocks.dart

Scheduling is working correctly but the github checks were not updated
as the request objects were not returning the tags.

Fix scheduling problems.

---

app_dart/cron.yaml
app_dart/pubspec.lock

Fixes https://github.com/flutter/flutter/issues/90475

[app_dart] Re-enable github endpoint

---

app_dart/lib/src/service/logging.dart

https://github.com/flutter/flutter/issues/90979 - Fix logs so they show on non-error logs
Follow up from https://github.com/flutter/cocoon/pull/1362

[app_dart] Log all writes

---

app_dart/lib/src/request_handlers/flaky_handler_utils.dart
app_dart/test/request_handlers/flaky_handler_utiles_test.dart

https://github.com/flutter/flutter/issues/90019

Makes the get existing pr until function throw more descriptive error

---

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart

PR reverting the original change: https://github.com/flutter/cocoon/pull/1372
Bugs:
flutter/flutter#91035
flutter/flutter#90851

Relands fix for mergeable state.

---

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart

Bug: https://github.com/flutter/flutter/issues/91035

Add logs indicating when a PR is in conflicting state.

---

dashboard/USER_GUIDE.md

Performance dashboard has been deprecated for a long time, this removes obsolete doc about that.

Remove obsolete doc about performance dashboard

---

app_dart/lib/src/service/scheduler.dart

This is to help identify the cases where we failed to schedule all the
builds.

Add more logging to the scheduler.

---

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart

This is to identify why sometimes landing a new commit takes a very long
time.

Add more logging to auto-submit bot.

---

app_dart/bin/generate_jspb.dart
app_dart/bin/validate_task_ownership.dart
app_dart/integration_test/common.dart
app_dart/integration_test/validate_all_ci_configs_test.dart
app_dart/integration_test/validate_test_ownership_test.dart
app_dart/lib/src/foundation/utils.dart
app_dart/lib/src/service/scheduler.dart
app_dart/test/foundation/utils_test.dart

~This is blocked on https://github.com/flutter/flutter/issues/91505 (and waiting for all repos to have a fallback)~
Fixes https://github.com/flutter/flutter/issues/89614
- Added tests for the gob fallbacks (both branch and ref specific)
- Did manual tests to validate if github was down, the integration tests would work (commented out the github requests)

[app_dart] Fallback to git-on-borg for source files

---

app_dart/lib/src/request_handlers/flaky_handler_utils.dart
app_dart/test/request_handlers/file_flaky_issue_and_pr_test.dart
app_dart/test/request_handlers/file_flaky_issue_and_pr_test_data.dart

This solves: https://github.com/flutter/flutter/issues/93000.
Added a test for the proposed change, but test validation is blocked on https://github.com/flutter/flutter/issues/90139.
Landing the change to unblock the auto bot, and the test needs validation when migrating NNBD.

File flaky issue with limited number of successful builds

---

app_dart/lib/src/foundation/github_checks_util.dart
app_dart/lib/src/model/github/checks.dart
app_dart/lib/src/model/github/checks.g.dart
app_dart/lib/src/model/luci/buildbucket.g.dart
app_dart/lib/src/model/luci/push_message.g.dart
app_dart/lib/src/request_handlers/github_webhook.dart
app_dart/lib/src/service/github_checks_service.dart
app_dart/lib/src/service/luci_build_service.dart
app_dart/lib/src/service/scheduler.dart
app_dart/pubspec.lock
app_dart/pubspec.yaml
app_dart/test/request_handlers/github_webhook_test.dart
app_dart/test/request_handlers/reset_try_task_test.dart
app_dart/test/service/github_checks_service_test.dart
app_dart/test/service/luci_build_service_test.dart
app_dart/test/service/scheduler_test.dart
app_dart/test/src/utilities/mocks.mocks.dart

This is a revert done of https://github.com/flutter/cocoon/pull/1407 relating to the 'rerequested' changes. Changes are required in `package:github` to fix, but that tree is currently blocked.
Fixes https://github.com/flutter/flutter/issues/92611

[app_dart] Fix GitHub check retries

---

release_dashboard/lib/widgets/conductor_status.dart
release_dashboard/lib/widgets/create_release_substeps.dart
release_dashboard/test/widgets/create_release_substeps_test.dart

Enums in substep files are named simply `substepEnum`. They are changed to more meaningful namees.

[conductor] Fixed enums naming

---

device_doctor/lib/src/android_device.dart
device_doctor/lib/src/utils.dart
device_doctor/test/src/android_device_test.dart

This fixes: https://github.com/flutter/flutter/issues/93075

Kill adb server before running any device healthcheck

---

CI_YAML.md
app_dart/lib/src/model/proto/internal/scheduler.proto

Fixes https://github.com/flutter/flutter/issues/87675

[ci.yaml] Add postsubmit_properties, update dependency docs

---

app_dart/lib/src/request_handlers/push_build_status_to_github.dart

This is part of the engine migration from master to main.

Calculate engine tree status using commits from main.

---

release_dashboard/analysis_options.yaml
release_dashboard/lib/main.dart
release_dashboard/lib/services/conductor.dart
release_dashboard/lib/services/local_conductor.dart
release_dashboard/lib/state/status_state.dart
release_dashboard/lib/widgets/clean_release_button.dart
release_dashboard/lib/widgets/common/checkbox_substep.dart
release_dashboard/lib/widgets/conductor_status.dart
release_dashboard/lib/widgets/create_release_substeps.dart
release_dashboard/lib/widgets/engine_cherrypicks_substeps.dart
release_dashboard/lib/widgets/progression.dart
release_dashboard/test/fake_process_manager.dart
release_dashboard/test/fake_process_manager_test.dart
release_dashboard/test/src/services/fake_conductor.dart
release_dashboard/test/src/test_state_generator.dart
release_dashboard/test/widgets/conductor_status_test.dart
release_dashboard/test/widgets/engine_cherrypicks_substeps_test.dart

UI for step 2: apply engine cherrypicks
Main Issue: 
Side issue addressed: 
PRs that needed to be landed before this:
The UI when there are engine cherrypicks conflicts (second version):
When there are no conflicts (second version):
The UI when there are engine cherrypicks conflicts (first version):
When there are no conflicts (first version): …

[release_dashboard] Add substeps for engine cherrypicks step

---

cloud_build/deploy.sh

To avoid unexpected behaviour when updating logic running on cronjobs we
will stop all the previous versions after a new one is released.
Bug: https://github.com/flutter/flutter/issues/93872
Bug: https://github.com/flutter/flutter/issues/93418 …

Keep only one backend version in serving state.

---

app_dart/lib/src/service/scheduler.dart
app_dart/test/service/scheduler_test.dart

Fixes https://github.com/flutter/flutter/issues/93923
Fixes https://github.com/flutter/flutter/issues/87965

[scheduler] Retry ci.yaml checks

---

app_dart/pubspec.lock
app_dart/pubspec.yaml

[app_dart] Roll pubspec versions

---

dev/provision_salt.sh

This update is required for pkg install issues we are seeing with lower minion versions. …

Updating salt minion to 3002.7 for macs

---

app_dart/dev/branches.txt

This is causing a few errors in the backend related to vacuum github commits not having access to these branches

Remove old branches from branches.txt

---

release_dashboard/lib/widgets/progression.dart
release_dashboard/lib/widgets/publish_channel_substeps.dart
release_dashboard/lib/widgets/publish_tag_substeps.dart
release_dashboard/test/widgets/publish_tag_substeps_test.dart

UI for the last two steps:
Main Issue:
UI:

[release_dashboard] push tag step UI

---

app_dart/lib/src/service/config.dart

https://github.com/flutter/flutter/issues/94635
This code is randomly failing, so to debug I'm adding some logs and more explicit failures where I think the issue is.

[app_dart] Add logging to generateGithubToken

---

app_dart/cron.yaml

https://github.com/flutter/flutter/issues/94522

[app_dart] Add cron to refresh every repos luci data

---

app_dart/lib/src/request_handlers/refresh_chromebot_status.dart
app_dart/lib/src/service/datastore.dart
app_dart/lib/src/service/luci.dart
app_dart/lib/src/service/scheduler.dart
app_dart/test/service/datastore_test.dart
app_dart/test/service/luci_test.dart
app_dart/test/src/utilities/mocks.mocks.dart

This fixes the chromebot statuses on other repos as (1) it'll get the correct default branch and (2) fixes incorrectly filtering builders
https://github.com/flutter/flutter/issues/94522

[app_dart] Remove repo logic from luci build service

---

app_dart/lib/src/request_handlers/flaky_handler_utils.dart
app_dart/lib/src/service/bigquery.dart
app_dart/test/request_handlers/file_flaky_issue_and_pr_test_data.dart
app_dart/test/request_handlers/update_existing_flaky_issues_test_data.dart

https://github.com/flutter/flutter/issues/94873

Update flake auto bot comment on existing flaky bugs

---

app_dart/lib/src/service/config.dart

This is part of the migration of packages repo to main.

Update default branch of packages to main.

---

app_dart/pubspec.lock
app_dart/pubspec.yaml
app_dart/test/request_handlers/vacuum_github_commits_test.dart
device_doctor/pubspec.lock
device_doctor/pubspec.yaml
release_dashboard/pubspec.lock
release_dashboard/pubspec.yaml
tests.yaml

Fixes https://github.com/flutter/flutter/issues/95212
The issue was the test was not clearing the datastore between runs, so previous data filled the datastore

Fix vacuum github test

---

app_dart/lib/src/service/config.dart
app_dart/test/service/config_test.dart

See https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits
Fixes https://github.com/flutter/flutter/issues/94635

[app_dart] Cache github tokens

---

device_doctor/bin/main.dart
device_doctor/lib/src/android_device.dart
device_doctor/lib/src/device.dart
device_doctor/lib/src/ios_device.dart
device_doctor/lib/src/utils.dart
device_doctor/test/src/android_device_test.dart
device_doctor/test/src/fake_ios_device.dart
device_doctor/test/src/ios_device_test.dart

The screen rotation is expected to be disabled for a healthy device.
https://github.com/flutter/flutter/issues/95145

Add screen rotation health check for android devices

---

app_dart/lib/src/service/config.dart
app_dart/test/request_handlers/vacuum_github_commits_test.dart

This is to make progress in standardizing the default branch of flutter
repositories to main.
[Discord]: …

Move plugins repo default branch to main.

---

app_dart/lib/src/model/luci/buildbucket.dart
app_dart/lib/src/model/luci/buildbucket.g.dart
app_dart/lib/src/service/config.dart
app_dart/lib/src/service/gerrit_service.dart
app_dart/lib/src/service/luci_build_service.dart
app_dart/test/service/gerrit_service_test.dart
app_dart/test/service/luci_build_service_test.dart
app_dart/test/service/scheduler_test.dart
app_dart/test/src/datastore/fake_config.dart
app_dart/test/src/service/fake_luci_build_service.dart
app_dart/test/src/utilities/mocks.dart
app_dart/test/src/utilities/mocks.mocks.dart

Instead of forking the recipes any time we are creating a new release
branch we will branch the recipes repository along with flutter/flutter
and use the recipes version that corresponds to the PR base ref on
presubmit.
Bug: https://github.com/flutter/flutter/issues/53371 …

Use branched recipes.

---

app_dart/lib/src/model/ci_yaml/target.dart
app_dart/test/model/ci_yaml/target_test.dart
app_dart/test/src/utilities/entity_generators.dart

https://github.com/flutter/flutter/issues/95429
This was an issue with platform specific xcode not being applied to the properties

[scheduler] Fix xcode not being forwarded to recipe module

---

app_dart/cron.yaml
app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
app_dart/lib/src/service/config.dart
app_dart/test/request_handlers/push_gold_status_to_github_test.dart
app_dart/test/service/config_test.dart
app_dart/test/src/datastore/fake_config.dart
app_dart/test/src/datastore/fake_datastore.dart

Reverts flutter/cocoon#1505
This PR is suspected of breaking the flutter-gold check in the flutter/flutter repo.

Revert "[web] Add the flutter-gold check in web engine PRs"

---

app_dart/bin/server.dart
app_dart/lib/cocoon_service.dart
app_dart/lib/src/model/appengine/task.dart
app_dart/lib/src/model/luci/push_message.dart
app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
app_dart/lib/src/request_handlers/reset_prod_task.dart
app_dart/lib/src/request_handlers/update_task_status.dart
app_dart/lib/src/service/datastore.dart
app_dart/lib/src/service/github_checks_service.dart
app_dart/test/request_handlers/get_status_test.dart
app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
app_dart/test/request_handlers/reset_prod_task_test.dart
app_dart/test/request_handlers/update_task_status_test.dart
app_dart/test/src/datastore/fake_datastore.dart
app_dart/test/src/request_handling/fake_authentication.dart
app_dart/test/src/utilities/entity_generators.dart
app_dart/test/src/utilities/push_message.dart

https://github.com/flutter/flutter/issues/81795

[scheduler] Add postsubmit subscription

---

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
app_dart/lib/src/request_handlers/scheduler/request.dart
app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart

Fixes https://github.com/flutter/flutter/issues/96780

[app_dart] Fix autosubmit graphql to use json list

---

app_dart/lib/src/model/luci/push_message.g.dart
app_dart/lib/src/service/github_service.dart
app_dart/lib/src/service/scheduler.dart
app_dart/pubspec.lock
app_dart/test/service/github_checks_service_test.dart
app_dart/test/service/scheduler_test.dart
app_dart/test/src/utilities/mocks.mocks.dart

Instead of failing, this should run all targets.
Fixes https://github.com/flutter/flutter/issues/97152

[scheduler] Gracefully fail runIf

---

cloud_build/dashboard_build.sh

Fixes https://github.com/flutter/flutter/issues/97402

[cloudbuild] Use ToT for dashboard builds

---

app_dart/lib/src/request_handlers/push_build_status_to_github.dart
app_dart/test/request_handlers/push_build_status_to_github_test.dart

Closes https://github.com/flutter/flutter/issues/93872

[app_dart] Add test for push_build_status using default branch

---

app_dart/test/request_handlers/check_flaky_builders_test.dart
app_dart/test/request_handlers/file_flaky_issue_and_pr_test.dart
app_dart/test/request_handlers/file_flaky_issue_and_pr_test_data.dart

fixes https://github.com/flutter/flutter/issues/90139

Adds additional mock to test to unskip flaky bot tests

---

dashboard/lib/service/cocoon.dart

Fixes: https://github.com/flutter/flutter/issues/97546

[dashboard] Fix plugins branch

---

app_dart/lib/src/request_handlers/scheduler/request_subscription.dart
app_dart/test/request_handlers/scheduler/request_subscription_test.dart

I filed https://github.com/flutter/flutter/issues/97828 as the tech-debt clean up to make this API easier to use in the future.

[app_dart] Quick fix to base64 decode messages in scheduler requests

---

dashboard/USER_GUIDE.md

Refresh this doc with the latest information

[dashboard] Update USER_GUIDE.md

---

app_dart/lib/src/model/ci_yaml/target.dart
app_dart/lib/src/service/config.dart
app_dart/lib/src/service/luci_build_service.dart
app_dart/test/model/ci_yaml/target_test.dart
app_dart/test/service/luci_build_service_test.dart
app_dart/test/service/scheduler_test.dart
app_dart/test/src/datastore/fake_config.dart

This is a follow PR of https://github.com/flutter/cocoon/pull/1597 to move `getDimensions` function to Target.

Test dimensions followup

---

app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
app_dart/test/service/luci_build_service_test.dart
app_dart/test/src/utilities/push_message.dart

This is to help with debugging why the Cocoon build dashboard isn't updating.
https://flutter-dashboard.appspot.com/#/build?repo=cocoon&branch=main

[app_dart] Add logs for postsubmit build results

---

app_dart/lib/src/model/appengine/task.dart
app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
app_dart/test/model/task_test.dart
app_dart/test/src/utilities/entity_generators.dart

Fixes https://github.com/flutter/flutter/issues/98288
Fixes https://github.com/flutter/flutter/issues/98287

[scheduler] Update task from push message

---

auto_submit/Dockerfile
auto_submit/pubspec.lock
auto_submit/pubspec.yaml
cloud_build/autosubmit_deploy.sh
cloud_build/deploy.sh
cloudbuild.yaml

Info is available in https://pantheon.corp.google.com/run/detail/us-west2/auto-submit/revisions?project=flutter-dashboard

[cloudbuild] Add auto_submit to cloud build

---

app_dart/test/service/luci_build_service_test.dart

Fixes https://github.com/flutter/flutter/issues/97602
I ran this test on a random shuffle 100 times and was not able to reproduce

[app_dart] Fix gerrit service stub flake

---

app_dart/lib/src/model/luci/buildbucket.dart
app_dart/lib/src/request_handlers/scheduler/request_subscription.dart
app_dart/lib/src/service/config.dart
app_dart/test/request_handlers/scheduler/request_subscription_test.dart
app_dart/test/src/datastore/fake_config.dart

https://github.com/flutter/flutter/issues/86948
https://github.com/flutter/flutter/issues/84450

[scheduler] Add retries to requests

---

app_dart/lib/src/request_handlers/reset_try_task.dart
app_dart/lib/src/service/scheduler.dart
app_dart/test/request_handlers/reset_try_task_test.dart
app_dart/test/service/scheduler_test.dart

https://github.com/flutter/flutter/issues/98776

Retry subset of presubmit builds

---

app_dart/lib/src/model/appengine/task.dart
app_dart/test/model/task_test.dart

Fixes https://github.com/flutter/flutter/issues/98939

[app_dart] Fix duplicate build numbers

---

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
app_dart/lib/src/request_handlers/check_for_waiting_pull_requests_queries.dart

This change is also adding logs when the codereview check fails to help
diagnoze auto-submit bot issues.
Bug: https://github.com/flutter/flutter/issues/99033
[Discord]: …

Increase the inspected code reviews from 5 to 30.

---

app_dart/lib/src/service/config.dart
app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart

This is to support auto-updating github actions dependencies.

Add autosubmit bot support to impeller.

---

app_dart/lib/src/request_handlers/github_webhook.dart
app_dart/test/request_handlers/github_webhook_test.dart

I updated https://github.com/flutter/flutter/wiki/Tree-hygiene#tests to not require tests for .cirrus.yml

[app_dart] do not request tests for changes to cirrus.yml

---

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
app_dart/lib/src/request_handlers/refresh_cirrus_status.dart

This is to help triage: https://github.com/flutter/flutter/issues/99306

Add cirrus logs to help triage

---

.github/dependabot.yml
.github/workflows/scorecards-analysis.yml

We are adding these two tools to most of the repositories in the flutter
org to identify any potential security problems.

Add dependabot and scorecards to cocoon repository.

---

app_dart/lib/src/service/luci_build_service.dart
app_dart/lib/src/service/scheduler.dart
app_dart/test/service/scheduler_test.dart

Fixes https://github.com/flutter/flutter/issues/99523
https://github.com/flutter/flutter/issues/97687

[scheduler] Use same scheduleTryBuild when retrying failures

---

app_dart/lib/src/request_handling/swarming_authentication.dart
app_dart/lib/src/service/config.dart
app_dart/test/request_handling/swarming_authentication_test.dart
app_dart/test/src/datastore/fake_config.dart

Some debugging and cleanup for getting FRoB updates logged.
https://github.com/flutter/flutter/issues/79658

[app_dart] Add log and make service accounts static

---

dashboard/web/index.html

Fixes http://b/215905909
Ran a local run and verified the wasm request was to my localhost

[dashboard] Change canvaskit source to source from build

---

app_dart/lib/src/model/ci_yaml/target.dart
test_utilities/bin/licenses.sh

This is required to validate changes to the cores dimension in
presubmit.
Bug: https://github.com/flutter/flutter/issues/98529

Process cores as dimensions.

---

.github/workflows/mirror.yml

This is to fix the security alerts related to missing top level workflow
permissions.

Declare default permissions as read.

---

Dockerfile
app_dart/Dockerfile
auto_submit/Dockerfile

This is to address the security alerts complaining about dependencies
not being pinned.

Pin docker file dependencies.

---

auto_submit/lib/requests/check_pull_request.dart
auto_submit/lib/requests/github_webhook.dart
auto_submit/lib/service/config.dart
auto_submit/lib/service/github_service.dart
auto_submit/pubspec.lock
auto_submit/pubspec.yaml
auto_submit/test/requests/check_pull_request_test.dart
auto_submit/test/requests/github_webhook_test.dart
auto_submit/test/requests/github_webhook_test_data.dart
auto_submit/test/src/service/fake_config.dart
auto_submit/test/src/service/fake_github_service.dart
auto_submit/test/utilities/mocks.dart
auto_submit/test/utilities/mocks.mocks.dart

This pull request solves three issue:
1. After check the PR should be merged, we merge this PR;
2. After check this PR shouldn't merge, we remove the 'autosubmit' label. Solved the https://github.com/flutter/flutter/issues/99877 issues.
3. Added the logic to validate check runs statuses. Solved the https://github.com/flutter/flutter/issues/99873 issue.
If the pull request have tests that haven't been run, push this PR to pubsub again to be checked later after it finish all its tests. To solve https://github.com/flutter/flutter/issues/100076.

[autosubmit] Implement remove label

---

cloud_build/deploy.sh

This is to bisect which app is failing to deploy.

Temporarily remove auto-submit deployment.

---

Dockerfile
app_dart/Dockerfile
auto_submit/Dockerfile

Reverts flutter/cocoon#1668
https://github.com/flutter/flutter/issues/100185

Revert "Pin docker file dependencies."

---

app_dart/lib/src/request_handlers/github_webhook.dart
app_dart/lib/src/service/config.dart
app_dart/test/request_handlers/github_webhook_test.dart

being lazy and directing context to issue https://github.com/flutter/flutter/issues/100923 , welp, if you click on this link it will direct you to another context link :)

[release] Test exemption bot should not run on release branch PRs

---

cloud_build/deploy_app_dart.sh
cloud_build/deploy_auto_submit.sh

Fixes https://github.com/flutter/flutter/issues/100925

[cloud_build] Delete versions per service

---

app_dart/lib/src/model/appengine/task.dart
app_dart/test/model/task_test.dart
dashboard/lib/widgets/task_box.dart

Fixes https://github.com/flutter/flutter/issues/101072

Add cancelled to task status

---

Dockerfile

This is part of the effort to pin all versions for all the docker files.

Pin cocoon main docker file version.

---

auto_submit/lib/requests/check_pull_request.dart
auto_submit/lib/requests/check_pull_request_queries.dart
auto_submit/lib/service/config.dart
auto_submit/test/requests/check_pull_request_test.dart

This PR solves the issue we encountered when creating graphQL client and query pull request.

[autosubmit] Fix graphQL Client

---

.github/workflows/mirror.yml
.github/workflows/scorecards-analysis.yml

Bug: https://github.com/flutter/flutter/issues/97599

Do not run scorecards on forks.

---

app_dart/lib/src/request_handlers/get_green_commits.dart
app_dart/test/request_handlers/get_green_commits_test.dart

This is so I can set a bash script to ping me when to create the Flutter PR that rolls an Engine CP.
Long term, this will be used by rapid

[app_dart] Add branch support to get green commits

---

app_dart/lib/src/request_handlers/github_webhook.dart
app_dart/lib/src/service/config.dart
app_dart/test/request_handlers/github_webhook_test.dart
app_dart/test/src/datastore/fake_config.dart
app_dart/test/src/utilities/webhook_generators.dart

Fixes https://github.com/flutter/flutter/issues/101397

[app_dart] Approve release PRs

---

auto_submit/bin/server.dart
auto_submit/lib/server/authenticated_request_handler.dart
auto_submit/lib/server/request_handler.dart
auto_submit/lib/service/config.dart
auto_submit/test/requests/check_pull_request_test.dart

This PR is to fix the authentication error encountered during test.

[autosubmit] Fix authentication

---

auto_submit/lib/requests/check_pull_request.dart
auto_submit/lib/service/github_service.dart
auto_submit/test/requests/check_pull_request_test.dart
auto_submit/test/requests/github_webhook_test_data.dart
auto_submit/test/src/service/fake_github_service.dart

This PR solves the https://github.com/flutter/flutter/issues/100088 issue, will merge a pull request if this pull request is checked to merge.

[autosubmit] Add merge pull request

---

auto_submit/lib/requests/check_pull_request.dart

Add a log to show author association to help triage the mergePR error.

[autosubmit] Add author association log

---

auto_submit/lib/requests/check_pull_request.dart

Add a log to track shouldMerge logic to help triage the mergePR error.

[autosubmit] Add shouldmerge log

---

auto_submit/lib/requests/check_pull_request.dart

Use this Pr to test merge PR rest api

[auto-submit] test merge pr permission

---

auto_submit/lib/requests/check_pull_request.dart

Add a log for acknowledging pubsub to help triage the mergePR error.

[autosubmit] Add ack pubsub log

---

.github/dependabot.yml

This will update pub dependencies automatically.

Add dependabot for pub ecosystem.

---

auto_submit/lib/requests/check_pull_request.dart

[autosubmit] Add merge counts log

---

auto_submit/lib/requests/check_pull_request.dart

Added a log before process merge PR.

[autosubmit] Add merge log

---

dashboard/lib/main.dart

This lets me use vimium to navigate the dashboard (granted I can't open tasks which seems like a bug with `Lattice`)

[dashboard] Enable semantics

---

app_dart/lib/src/request_handlers/github_webhook.dart
app_dart/test/request_handlers/github_webhook_test.dart

Fixes https://github.com/flutter/flutter/issues/101948

make devicelab tests count as tests

---

app_dart/lib/src/request_handlers/flaky_handler_utils.dart

Fixes: https://github.com/flutter/flutter/issues/102258

Update modify mode when creating PRs via auto flake bot

---

.github/dependabot.yml

Pub ecosystem requires a configuration per directory containing pubspec
files.

Update dependabot pub configurations.

---

auto_submit/lib/requests/check_pull_request.dart
auto_submit/lib/requests/check_pull_request_queries.dart
auto_submit/test/requests/check_pull_request_test.dart

This PR switched author to [author][login] from graphQL.
Issue: https://github.com/flutter/flutter/issues/102417

[autosubmit] Use PR author from graphQL query

---

auto_submit/test/utilities/mocks.dart
dashboard/pubspec.lock
device_doctor/bin/main.dart
device_doctor/lib/src/android_device.dart
device_doctor/lib/src/device.dart
device_doctor/lib/src/health.dart
device_doctor/lib/src/host_utils.dart
device_doctor/lib/src/ios_device.dart
device_doctor/lib/src/mac.dart
device_doctor/lib/src/utils.dart
device_doctor/pubspec.lock
device_doctor/pubspec.yaml
device_doctor/test/src/android_device_test.dart
device_doctor/test/src/fake_ios_device.dart
device_doctor/test/src/health_test.dart
device_doctor/test/src/host_utils_test.dart
device_doctor/test/src/ios_device_test.dart
device_doctor/test/src/mac_test.dart
device_doctor/test/src/utils.dart
device_doctor/test/src/utils_test.dart
device_doctor/tool/build.bat

https://github.com/flutter/flutter/issues/102350

[device doctor] Migrate to null safety

---

auto_submit/analysis_options.yaml
auto_submit/bin/server.dart
auto_submit/lib/requests/check_pull_request.dart
auto_submit/lib/requests/github_webhook.dart
auto_submit/lib/server/request_handler.dart
auto_submit/lib/service/config.dart
auto_submit/pubspec.lock
auto_submit/pubspec.yaml
auto_submit/test/request_handling/authentication_test.dart
auto_submit/test/requests/github_webhook_test.dart
auto_submit/test/requests/github_webhook_test_data.dart
auto_submit/test/service/config_test.dart
auto_submit/test/src/request_handling/fake_pubsub.dart
auto_submit/test/src/service/fake_github_service.dart

Yep auto submit wasn't using lint packages. geez i thought this was going to be fast, turned out there were quite many lint errors to fix.

[auto submit]fix errors, pass tests

---

app_dart/lib/src/foundation/utils.dart
app_dart/test/foundation/utils_test.dart

Fixes https://github.com/flutter/flutter/issues/102825

Use cocoon default branch when fetching GOB file

---

app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart

Fixes: https://github.com/flutter/flutter/issues/100232
/cc @zanderso

[app_dart] Ignore latency check for TOT revert

---

app_dart/Dockerfile
auto_submit/Dockerfile

This PR pins the hash for the Dockerfile dependency to ensure a trusted source for the dependency.
Fixes issues:
- https://github.com/flutter/cocoon/security/code-scanning/3
- https://github.com/flutter/cocoon/security/code-scanning/4 …

Pin Dockerfile Dependencies

---

auto_submit/.dockerignore
auto_submit/Dockerfile
auto_submit/app.yaml
auto_submit/bin/server.dart
auto_submit/lib/requests/readiness_check.dart
auto_submit/lib/service/config.dart

The google/dart images have been deprecated and already 3 months old. We
are updating our apps to the official images to keep getting updates.
Bug: https://github.com/flutter/flutter/issues/102945 …

Move auto-submit to dart official images.

---

app_dart/.gitignore
app_dart/Dockerfile

The google/dart-runtime are now deprecated and 3+ months old.
Bug: https://github.com/flutter/flutter/issues/102945

Migrate app_dart application to dart official docker images.

---

app_dart/pubspec.lock
app_dart/pubspec.yaml
app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
app_dart/test/request_handlers/push_gold_status_to_github_test.dart
app_dart/test/request_handlers/query_github_graphql_test.dart
app_dart/test/src/service/fake_graphql_client.dart
app_dart/test/src/utilities/mocks.mocks.dart
auto_submit/pubspec.lock
auto_submit/pubspec.yaml
auto_submit/test/requests/check_pull_request_test.dart
auto_submit/test/src/service/fake_graphql_client.dart

Fixes https://github.com/flutter/cocoon/pull/1769
Fixes https://github.com/flutter/cocoon/pull/1768
Most of this is auto-generated code. The only thing I did was refactor some of the logic to have a `createFakeQueryResult` to remove some of the boiler plate.

Update package:graphql to 5.1.1

---

dashboard/lib/build_dashboard_page.dart

fixes https://github.com/flutter/flutter/issues/103082

checkboxes for stages were being ignored when set to default again

---

auto_submit/lib/requests/check_pull_request.dart
auto_submit/test/requests/check_pull_request_test.dart

closes https://github.com/flutter/flutter/issues/102317
Added try catch around the github merge graphql call, so the process goes on and finishes other PRs

adding try catch to processMerge function

---

app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
app_dart/lib/src/service/scheduler.dart
app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
app_dart/test/src/utilities/push_message.dart

Reverts flutter/cocoon#1816
This functioality is still needed

Reland "[scheduler] Process build messages with null task key (#1698)"

---

dashboard/lib/service/appengine_cocoon.dart
dashboard/lib/state/build.dart
dashboard/test/utils/appengine_cocoon_test_data.dart

fixes https://github.com/flutter/flutter/issues/103362.
The issue was cause by an obsolete version of json returned from the request handler. The correct json format should be a list of maps.

[dashboard] change json return type from map to array

---

app_dart/lib/src/service/branch_service.dart
app_dart/test/service/branch_service_test.dart
app_dart/test/src/utilities/webhook_generators.dart

fixes https://github.com/flutter/flutter/issues/103363.
We will not store branches that are created in a forked flutter repository.

[release] exclude forks for branch datastore

---

app_dart/lib/src/request_handlers/check_flaky_builders.dart
app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart
app_dart/lib/src/request_handlers/flaky_handler_utils.dart
app_dart/lib/src/request_handlers/update_existing_flaky_issues.dart
app_dart/test/request_handlers/check_flaky_builders_test_data.dart
app_dart/test/request_handlers/file_flaky_issue_and_pr_test_data.dart
app_dart/test/request_handlers/update_existing_flaky_issues_test_data.dart

If the builder in .ci.yaml has ignore_flakiness = true specified, then
we ignore those when performing flakiness related actions.
Bug:91913
[test-exempt]: …

Ignoring builds in flakiness checks when ignore_flakiness is specified.

---

app_dart/README.md
app_dart/dev/branches.txt

Revert "[app_dart] Remove branches.txt"

---

app_dart/lib/src/model/ci_yaml/target.dart
app_dart/test/model/ci_yaml/target_test.dart

Adding ignoreFlakiness() to target.dart

---

auto_submit/lib/model/auto_submit_query_result.dart
auto_submit/lib/model/auto_submit_query_result.g.dart
auto_submit/pubspec.lock
auto_submit/pubspec.yaml
auto_submit/test/model/auto_submit_query_result_test.dart

This is the first step to refactoring the application to use models
instead of json to make it more extensible.

Add models for auto-submit bot.

---

app_dart/bin/server.dart
app_dart/lib/src/model/ci_yaml/target.dart
app_dart/lib/src/request_handlers/check_flaky_builders.dart
app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart
app_dart/lib/src/request_handlers/update_existing_flaky_issues.dart
app_dart/test/model/ci_yaml/target_test.dart
app_dart/test/request_handlers/file_flaky_issue_and_pr_test.dart

Convert to using ciYaml.postsubmitTargets and Target.ignoreFlakiness().
Bug:87529 …

Convert to using ciYaml.postsubmitTargets and Target.ignoreFlakiness()

---

device_doctor/lib/src/ios_device.dart
device_doctor/test/src/ios_device_test.dart

https://github.com/flutter/flutter/issues/103237

[device doctor] Fix idevicediagnostics binary path for M1 bots

---

app_dart/lib/src/service/luci_build_service.dart
app_dart/test/src/service/fake_buildbucket.dart

If somebody clicks the re-run button on the github ui the build was not
copying additional properties making PRs updating CI.yaml to fail.
Bug: https://github.com/flutter/flutter/issues/101715 …

Pass properties on re-runs using the checkrun.

---

app_dart/lib/src/request_handlers/check_flaky_builders.dart
app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart
app_dart/test/request_handlers/check_flaky_builders_test.dart
app_dart/test/request_handlers/file_flaky_issue_and_pr_test.dart

Fix null value in flakey test search.

---

auto_submit/lib/requests/check_pull_request.dart

It also prevents processing messages from forks.

Prevent exceptions when the PR doesn't have any tests.

---

dashboard/lib/build_dashboard_page.dart
dashboard/linux/flutter/generated_plugins.cmake
dashboard/pubspec.lock
dashboard/pubspec.yaml
dashboard/web/index.html

@CaseyHillers I've started writing the plugin. favicon was easy, android is a bit more complicated... 2 tests will fail, but have no idea why. Let me know what you think.

[dashboard] Migrate to flutter_app_icon

---

auto_submit/test/requests/check_pull_request_test.dart
dashboard/lib/logic/task_grid_filter.dart
dashboard/lib/widgets/lattice.dart

Update deprecated hash calls.

---

app_dart/lib/src/service/config.dart
auto_submit/lib/service/validation_service.dart

https://github.com/flutter/flutter/issues/106138

Skip engine PRs auto merge

---

app_dart/lib/src/service/config.dart
auto_submit/lib/service/validation_service.dart

Reverts flutter/cocoon#1920
Tryjobs not getting scheduled.

Revert "Skip engine PRs auto merge"

---

auto_submit/lib/service/validation_service.dart
auto_submit/test/requests/check_pull_request_test.dart
auto_submit/test/service/validation_service_test.dart
auto_submit/test/src/service/fake_github_service.dart
auto_submit/test/utilities/utils.dart
dashboard/pubspec.lock

Fixes: https://github.com/flutter/flutter/issues/106487

Remove autosubmit label when validation fails

---

app_dart/lib/src/foundation/github_checks_util.dart
app_dart/lib/src/service/luci_build_service.dart

Help triage: https://github.com/flutter/flutter/issues/102402

Add triaging logs for github secondary rate limit error

---

app_dart/lib/src/service/config.dart

Fixes https://github.com/flutter/flutter/issues/106712
@zanderso

Drop cirrus from engine checks

---

dashboard/lib/build_dashboard_page.dart
dashboard/lib/logic/links.dart
dashboard/lib/widgets/commit_box.dart
dashboard/lib/widgets/luci_task_attempt_summary.dart
dashboard/lib/widgets/task_icon.dart
dashboard/lib/widgets/task_overlay.dart
dashboard/pubspec.lock
dashboard/pubspec.yaml

Manually lands https://github.com/flutter/cocoon/pull/1942 together with fixes.
Fixes: https://github.com/flutter/flutter/issues/107506

[dashboard] url_launcher version bump

---

dashboard/lib/build_dashboard_page.dart
dashboard/lib/index_page.dart
dashboard/lib/service/google_authentication.dart
dashboard/lib/state/build.dart
dashboard/lib/widgets/commit_box.dart
dashboard/lib/widgets/filter_property_sheet.dart
dashboard/lib/widgets/progress_button.dart
dashboard/lib/widgets/sign_in_button.dart
dashboard/lib/widgets/task_overlay.dart
dashboard/pubspec.lock
dashboard/pubspec.yaml
dashboard/test/index_page_test.dart
dashboard/test/state/build_test.dart
dashboard/test/widgets/task_overlay_test.dart

Manually lands https://github.com/flutter/cocoon/pull/1945 together with lint fixes.
Fixes: https://github.com/flutter/flutter/issues/107503

[dashboard] lint version bump

---

auto_submit/lib/requests/check_pull_request.dart
auto_submit/lib/service/validation_service.dart

For triage: https://github.com/flutter/flutter/issues/107788

Add logs for autosubmit triage

---

dev/provision_salt.sh

updates the salt package to an available package but not the latest one.

[salt] update salt pkg name

---

cron.yaml

Context:  https://github.com/flutter/flutter/issues/107788#issuecomment-1189315465

Run auto-submit cronjob every 1 min

---

auto_submit/lib/validations/ci_successful.dart
auto_submit/test/requests/check_pull_request_test.dart
auto_submit/test/validations/ci_successful_test.dart

Fixes: https://github.com/flutter/flutter/issues/108300

Wait for tree status instead of posting a check failure

---

app_dart/lib/src/model/ci_yaml/target.dart
app_dart/test/model/ci_yaml/target_test.dart

Fixes: https://github.com/flutter/flutter/issues/108317

Batch schedule samsung and Mac host only targets

---

dashboard/lib/widgets/sign_in_button.dart

Switch to using the avatar widget provided by google_sign_in instead of a raw image in the top right of the app bar.
Fixes [this TODO](https://github.com/flutter/cocoon/blob/6ec0130b56ef2256427509dea61235d14ad11fc0/dashboard/lib/widgets/sign_in_button.dart#L52)
```
child: WebImage(
// TODO(chillers): Switch to use avatar widget provided by google_sign_in plugin
imageUrl: authService.user?.photoUrl,
placeholder: Padding(
padding: const EdgeInsets.only(right: 10.0, top: 20.0),
child: Text(authService.user!.email),
),
),
```
Note: values were not provided for [GoogleUserCircleAvatar](https://pub.dev/documentation/google_sign_in/latest/widgets/GoogleUserCircleAvatar-class.html)'s `foregroundColor`, `backgroundColor`, and `placeholderPhotoUrl` as the defaults were reasonable for the …

Switch to use avatar widget provided by google_sign_in plugin

---

app_dart/lib/src/service/gerrit_service.dart

Follow up to the request from GoB team in b/240600670

[app_dart] Add gerrit trace to create branch requests

---

dashboard/analysis_options.yaml
dashboard/lib/build_dashboard_page.dart
dashboard/lib/index_page.dart
dashboard/lib/logic/brooks.dart
dashboard/lib/logic/links.dart
dashboard/lib/logic/task_grid_filter.dart
dashboard/lib/main.dart
dashboard/lib/service/appengine_cocoon.dart
dashboard/lib/service/dev_cocoon.dart
dashboard/lib/widgets/lattice.dart
dashboard/lib/widgets/luci_task_attempt_summary.dart
dashboard/lib/widgets/sign_in_button.dart
dashboard/lib/widgets/task_grid.dart
dashboard/lib/widgets/task_overlay.dart
dashboard/pubspec.lock
dashboard/test/build_dashboard_page_test.dart
dashboard/test/index_page_test.dart
dashboard/test/logic/qualified_task_test.dart
dashboard/test/logic/task_grid_filter_test.dart
dashboard/test/service/appengine_cocoon_test.dart
dashboard/test/service/google_authentication_test.dart
dashboard/test/state/build_test.dart
dashboard/test/utils/fake_build.dart
dashboard/test/utils/golden.dart
dashboard/test/widgets/accessibility_test.dart

Add trailing comma requirement to analysis file.
[Discord]: …

Trailing comma analysis

---

app_dart/lib/src/request_handlers/github_webhook.dart
app_dart/test/request_handlers/github_webhook_test.dart

https://github.com/flutter/flutter/issues/102325

[app_dart] Only create recipe branches on flutter/flutter branches

---

CI_YAML.md

An overview of the features supported by the Cocoon scheduler

Add Cocoon scheduler docs

---

cron.yaml

Part of https://github.com/flutter/flutter/issues/107431

Remove check waiting pull request API

---

auto_submit/lib/requests/check_pull_request.dart
auto_submit/lib/service/config.dart
auto_submit/test/requests/check_pull_request_test.dart
auto_submit/test/src/request_handling/fake_pubsub.dart
auto_submit/test/src/service/fake_config.dart

Fixes: https://github.com/flutter/flutter/issues/108767

Call pub/sub pull API multiple times to return more messages

---

auto_submit/lib/requests/check_pull_request.dart
auto_submit/test/requests/check_pull_request_test.dart
auto_submit/test/src/request_handling/fake_pubsub.dart

Fixes: https://github.com/flutter/flutter/issues/109409
(This is basically the initial logic here: https://github.com/flutter/cocoon/pull/2035/commits/5a22258bcdbe7977bb16bd9b2bcb87683b31cd8a)

Consolidate pubsub messages to avoid duplicate processing

---

app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
app_dart/lib/src/service/scheduler/policy.dart
app_dart/test/request_handlers/scheduler/batch_backfiller_test.dart
app_dart/test/service/scheduler/policy_test.dart

Fixes: https://github.com/flutter/flutter/issues/109359

Inject a higher priority for failed builds when scheduling

---

README.md

Adds flutter logo and scorecards badge.

Update README to include scorecards badge

---

CI_YAML.md

Fixes: https://github.com/flutter/flutter/issues/109712

Remove luci scheduler in CI_YAML doc

---

app_dart/lib/src/model/ci_yaml/target.dart
app_dart/lib/src/service/scheduler/policy.dart
app_dart/test/model/ci_yaml/target_test.dart
app_dart/test/service/scheduler/policy_test.dart

Fixes: https://github.com/flutter/flutter/issues/109711

Increase cocoon scheduling batch of size 6

---

dashboard/lib/build_dashboard_page.dart
dashboard/lib/main.dart
dashboard/lib/widgets/commit_box.dart
dashboard/lib/widgets/header_text.dart
dashboard/lib/widgets/task_overlay.dart
dashboard/pubspec.lock

Most PRs on Cocoon are failing due to this. Quick fix that `dart fix` was able to solve.

[dashboard] Update text themes to latest material 3 spec

---

app_dart/lib/src/service/scheduler/policy.dart
app_dart/test/service/scheduler/policy_test.dart

Fixes: https://github.com/flutter/flutter/issues/110059

Fix boundary issue when back filling queued tasks

---

device_doctor/pubspec.lock

Fixes https://github.com/flutter/flutter/issues/110265

update package:file in device_doctor

---

.github/dependabot.yml
analyze/pubspec.lock
app_dart/pubspec.lock
auto_submit/pubspec.lock
codesign/pubspec.lock
licenses/pubspec.lock

This is failing on tip of tree 
See https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8804842406213514465/+/u/analyze/stdout

[analyze] Update pubspec for file fix and add dependabot

---

app_dart/lib/src/foundation/utils.dart
app_dart/lib/src/model/appengine/branch.dart
app_dart/lib/src/model/appengine/key_helper.dart
app_dart/lib/src/request_handlers/reset_prod_task.dart
app_dart/lib/src/request_handlers/scheduler/batch_backfiller.dart
app_dart/lib/src/request_handlers/update_task_status.dart
app_dart/lib/src/request_handlers/vacuum_github_commits.dart
app_dart/lib/src/service/config.dart
app_dart/test/foundation/utils_test.dart
app_dart/test/request_handlers/reset_prod_task_test.dart
app_dart/test/request_handlers/update_task_status_test.dart
app_dart/test/request_handlers/vacuum_github_commits_test.dart
app_dart/test/service/branch_service_test.dart
app_dart/test/service/config_test.dart
app_dart/test/service/scheduler_test.dart
app_dart/test/src/datastore/fake_config.dart

Cleans up a TODO related to how Cocoon has several ways of getting branches.

[app_dart] Get branches only from datastore

---

auto_submit/test/validations/testfile.txt

Simple revert functionality test. …

Adding a fake file to test revert in the autosubmit bot.

---

app_dart/lib/src/request_handlers/reset_try_task.dart
app_dart/test/request_handlers/reset_try_task_test.dart

Fixes: https://github.com/flutter/flutter/issues/109626

Handle empty builders case for /api/reset-try-task

---

auto_submit/lib/model/auto_submit_query_result.g.dart
auto_submit/lib/requests/check_pull_request.dart
auto_submit/lib/service/approver_service.dart
auto_submit/lib/service/validation_service.dart
auto_submit/pubspec.yaml
auto_submit/test/service/approver_service_test.dart
auto_submit/test/utilities/mocks.mocks.dart

Forgot to add auto-approval of the request. Since right now it will be validated correctly but we cannot merge due to the repository approval rules.
[CLA]: …

Adding approval of the revert request

---

auto_submit/lib/service/approver_service.dart
auto_submit/lib/service/validation_service.dart

Added more fine grained logging around approval of revert requests.
[breaking change …

Add more logging around revert approval.

---

app_dart/lib/src/request_handlers/github/webhook_subscription.dart
app_dart/test/request_handlers/github/webhook_subscription_test.dart

Fixes https://github.com/flutter/flutter/issues/110518

allow no tests on .gitignore files

---

auto_submit/lib/service/approver_service.dart
auto_submit/lib/service/validation_service.dart
auto_submit/test/service/approver_service_test.dart
auto_submit/test/utilities/mocks.mocks.dart
dashboard/pubspec.lock

The github.PullRequest object did not have the correct authorAssociation, instead we needed to use the QueryResult that we fetch from github which has the correct authorAssociation. …

Revert timing fix

---

auto_submit/test/validations/testfile.txt

Revert "Adding a fake file to test revert in the autosubmit bot."
